### ISSUE TITLE
client.get(torrentId) not doing anything?

### ISSUE THREAD

**Issue by davidgatti** [feross/webtorrent#1002]
The documentation states:

> Returns the torrent with the given torrentId. Convenience method. Easier than searching through the client.torrents array. Returns null if no matching torrent found.

But when I write the following:

```Javascript
	//
	//	Get torrent info from the client
	//
	client.get(magnet, function (torrent) {

		//
		//	Content of the Magnet URL
		//
		let files = [];

		//
		//	Extract all the files form the Magnet URL
		//
		torrent.files.forEach(function(data) {

			files.push({
				name: data.name,
				length: data.length
			});

		});

		//
		//	->	Just say it is ok.
		//
		res.status(200)
		res.json(files);

	});
```

Nothing happens, no `null` no nothing. Where for example `.add()` works no problem. Am I doing something wrong?

* WebTorrent version: 0.98.0
* Node.js version: v6.4.0
* Browser name/version (if using WebTorrent in the browser): Using NodeJS module.

**Comment by jo-san** [comment]
Am also facing the same problem. In debugger i can get array of torrents from `client.torrents` but `client.get(torrentId)` returning `null`

Thanks,

**Comment by feross** [comment]
@davidgatti `client.get(magnet)` doesn't take a callback. It *returns* the given torrent.

This is what you want:

```js
var torrent = client.get(magnet)
torrent.files.forEach(function () {})
```
