### ISSUE TITLE
How to stop/resume torrent ?

### ISSUE THREAD

**Issue by FrancoisMentec** [feross/webtorrent#1004]
I'm using webtorrent server side
npm : 3.10.5
webtorrent : 0.98.0

torrent.pause() only stop connecting to new peers so it doesn't stop torrent, I used : `client.remove(mytorrent.infoHash)`
and later :
```
client.add(mytorrent.magnerURI, function(torrent){
  //This callback is never triggered
});
```

Can't add torrent again, the torrent exists in the client but it never start, there is no metadata. I need to stop my nodejs app and restart it to add it again.

Is there an efficient way to stop/resume torrent ?

Not sure if it's the right place to ask this.

**EDIT**
I found a solution : 
stop : 
```
torrent.pause()
torrent.wires = [];
```

resume : 
```
for(var p in torrent._peers){
  torrent.wires.push(torrent._peers[p].wire);
}
torrent.resume();
```

Probably not the best but it's the only way I found, what do you think about it ? is there a better way ?

**Comment by feross** [comment]
- Can you post the full code that you used to initially add the torrent?
- Are you waiting until the `client.add()` callback is called or `torrent.on('infoHash') event is fired before calling `client.remove()`?

I would be very surprised if `client.remove()` was not working.

**Comment by FrancoisMentec** [comment]
My function to add a torrent : 
     
```
TorrentAPI.addTorrentFromMagnet = function(magnetURI){
   if(TorrentAPI.client.get(magnetURI)===null){
	    TorrentAPI.client.add(magnetURI, { path: TorrentAPI.downloadsPath }, function (torrent) {
				if(typeof torrent.infoHash == "undefined"){
					torrent.on('infoHash', function(){
						TorrentAPI.torrentsData[torrent.infoHash] = new TorrentData(torrent);
					});
				}else{
					TorrentAPI.torrentsData[torrent.infoHash] = new TorrentData(torrent);
				}
	    });
		}else{
			console.log("Torrent already added, can't duplicate it");
		}
  }
```
It work the first time I add the torrent but if I remove it I can't add it again. Remove work, but the callback for `client.add()` is only fired the first time I use it. I wait `torrent.on('infoHash')` to remove the torrent and use the infoHash to do it.

**Comment by feross** [comment]
It looks like you're not actually removing the torrent.

The callback to `client.add()` is called AFTER the 'infohash' event has already fired. You need to listen to it like this:

```js
var torrent = client.add(...)
torrent.on('infohash', onInfoHash)
torrent.on('ready,' onReady)
```

Note: The callback to `client.add()` is just a shorthand for listening to the 'ready' event.
