### ISSUE TITLE
Is there a way to make the web client to seed the stream he's currently downloading ?

### ISSUE THREAD

**Issue by vanilla38** [feross/webtorrent#1008]
Is there a way to make the web client to seed the stream he's currently downloading ?
For example: X download test.mp4 from a seedbox and he also seed it, while Y download it from 2 peers (seedbox + X) ?

**Comment by DiegoRBaquero** [comment]
This is the default behavior

**Comment by feross** [comment]
Yes, all torrent clients seed while they download. Cheers.
