### ISSUE TITLE
How to pass custom/new information to current peers?

### ISSUE THREAD

**Issue by fultonm** [feross/webtorrent#1010]
For example, I want to inform current peers of a new infohash for an updated file. Is there a way to send extra data to the peers currently connected?

**Comment by DiegoRBaquero** [comment]
There's no way of currently doing that in WebTorrent, but could be done with protocol extensions I suppose.

**Comment by fultonm** [comment]
I found this conversation which talks about sending messages using a protocol extension: https://github.com/feross/webtorrent/issues/368 Time to do some homework on extensions
