### ISSUE TITLE
How to specify custom announce urls?

### ISSUE THREAD

**Issue by am1stad** [feross/webtorrent#1011]
This doesn't work for me...I'm probably not specifying the announce urls properly but I don't really know what they should be.

        const client = new window.WebTorrent()

        client.add(this.torrent.magnet, {
          announce: [
            'http://router.bittorrent.com:6881',
            'http://dht.transmissionbt.com:6881'
          ]
        }, (torrent) => {
          console.log(torrent)
          const file = torrent.files[0]
          console.log(file)
          file.appendTo('body')
        })

Using browser version from CDN.

**Comment by DiegoRBaquero** [comment]
Why do you say it doesn't work?

Is this in the browser or Node?

Do you get any errors?

**Comment by chovy** [comment]
I'm doing it in browser, via cdn js

callback never fires even when using example torrent from http://webtorrent.io

        const magnet = 'magnet:?xt=urn:btih:6a9759bffd5c0af65319979fb7832189f4f3c35d&dn=sintel.mp4'
        console.log('play!', magnet)
        const client = new window.WebTorrent()

        client.add(magnet, {
          announce: [
            'wss://tracker.openwebtorrent.com',
            'wss://tracker.btorrent.xyz'
          ]
        }, function (torrent) {
          console.log(torrent)
          torrent.on('download', () => {
            console.log('downloadSpeed', torrent.downloadSpeed)
            console.log('timeRemaining', torrent.timeRemaining)
          })

          torrent.on('upload', () => {
            console.log('uploadSpeed', torrent.uploadSpeed)
          })

          console.log(torrent)
          const file = torrent.files[0]
          console.log(file)
          file.appendTo('main')
        })

**Comment by am1stad** [comment]
const magnet = 'magnet:?xt=urn:btih:6a9759bffd5c0af65319979fb7832189f4f3c35d&dn=sintel.mp4'
        console.log('play!', magnet)
        const client = new window.WebTorrent()

        client.add(magnet, {
          announce: [
            'wss://tracker.openwebtorrent.com',
            'wss://tracker.btorrent.xyz'
          ]
        }, function (torrent) {
          // this never fires
          console.log(torrent)
          torrent.on('download', () => {
            console.log('downloadSpeed', torrent.downloadSpeed)
            console.log('timeRemaining', torrent.timeRemaining)
          })

          torrent.on('upload', () => {
            console.log('uploadSpeed', torrent.uploadSpeed)
          })

          console.log(torrent)
          const file = torrent.files[0]
          console.log(file)
          file.appendTo('main')
        })

**Comment by feross** [comment]
If you find out any info about why it took so long, please share.

**Comment by am1stad** [comment]
The only difference I can see is I'm using vue.js -- perhaps that is causing severe slowdown?

I'm using the same bootstrap socket servers you are. So its very odd. I will do a simple test w/o vue.js and see if that's the issue.

**Comment by feross** [comment]
It could be because webtorrent.io is using a web seed as a fallback. Try adding this to your magnet link:

```
&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fsintel-1024-surround.mp4
```

**Comment by am1stad** [comment]
I don't know. I just tried again and it still never loads although it does start to download but does not play right away. I'm guessing it has to wait for the entire file to download for some reason.


```
<!doctype html>
<html>
<head>
<script src="https://cdn.jsdelivr.net/webtorrent/latest/webtorrent.min.js"></script>
<script>

function play(){
	// var magnet = 'magnet:?xt=urn:btih:6a9759bffd5c0af65319979fb7832189f4f3c35d&dn=sintel.mp4'
	var magnet = document.getElementById('magnet').value;
	console.log('play!', magnet)
	var client = new window.WebTorrent()

	client.add(magnet, {
	  announce: [
		'wss://tracker.openwebtorrent.com',
		'wss://tracker.btorrent.xyz',
		'wss://tracker.fastcast.nz'
	  ]
	}, function (torrent) {
	  // this never fires <--------------
	  console.log(torrent)
	  torrent.on('download', () => {
	    console.log('downloadSpeed', torrent.downloadSpeed)
	    console.log('timeRemaining', torrent.timeRemaining)
	  })

	  torrent.on('upload', () => {
	    console.log('uploadSpeed', torrent.uploadSpeed)
	  })

	  console.log(torrent)
	  var file = torrent.files[0]
	  console.log(file)
	  file.appendTo('body')
	})	
}
</script>
</head>
<body>
<h1>Play</h1>
<p>
	<label for=magnet>Magnet URL:</label>
	<input type=text id=magnet name=magnet>
	<button onclick=play()>play</button>
</p>
<p>
magnet:?xt=urn:btih:6c1fe48331262be9e257a5998e7b9c1e558abc98<br><br>
magnet:?xt=urn:btih:6a9759bffd5c0af65319979fb7832189f4f3c35d&dn=sintel.mp4<br><br>
magnet:?xt=urn:btih:6a9759bffd5c0af65319979fb7832189f4f3c35d&dn=sintel.mp4&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fsintel-1024-surround.mp4<br><br>
</p>

</body>
```


Above is a simple test which rules out vue.js being my problem. I tried the 3rd url (with ws fallback) and it still seems to not play until the entire file is downloaded (i did not wait that long).

If I do `webtorrent 'magnet:?xt=urn:btih:6a9759bffd5c0af65319979fb7832189f4f3c35d&dn=sintel.mp4' --vlc` it starts playing in VLC immediately and it plays on webtorrent.io immediately.

The above test.html seems to be missing some options perhaps? I could not tell by looking at webtorrent.io source what options (if any) you are passing to `client.add()`

**Comment by am1stad** [comment]
I did not see this error with `console all` showing. but when I clicked on `errors` tab I can see there are some errors:

```
Not allowed to load local resource: blob:null/7f22f81e-4a71-49b1-ae03-17520713fa35
webtorrent.min.js:6 Uncaught (in promise) DOMException: The element has no supported sources.
a @ webtorrent.min.js:6
webtorrent.min.js:6 Uncaught (in promise) DOMException: The element has no supported sources.
```

**Comment by feross** [comment]
Ahh, are you running this page with a `file://` url? That will block Blob URLs for security reasons (which I do not understand). That prevents Mediasource streaming from working.

**Comment by am1stad** [comment]
Yeah. I realized that right away. I am using `http-server` from npm and it does load the movie (sometimes). It is really inconsistent, flaky and slow. After around 10 tries it loaded.

Like i said cli interface starts playing right away in VLC. I even cloned the repo and built the debug version to make sure I have the latest.

I'm curious if you want that test and paste in the magnet does it work consistently for you?

The webtorrent.io site works fine and so does instant.io but not when web server is running locally.

**Comment by am1stad** [comment]
Only diff i could find is that you're adding this tracker option with ice servers. What is that?

	var client = window.client = new WebTorrent({
      tracker: {
        rtcConfig: rtcConfig
      }
    })
    client.on('warning', onWarning)
    client.on('error', onError)

    torrent = client.add(TORRENT, onTorrent)
    graph.add({ id: 'You', name: 'You', me: true })


rtcConfig (ice servers)

    {
        "iceServers": [{
            "urls": "stun:23.21.150.121"
        }, {
            "username": "xxx",
            "credential": "xxx",
            "urls": "turn:global.turn.twilio.com:3478?transport=udp"
        }, {
            "username": "xxx",
            "credential": "xxx",
            "urls": "turn:global.turn.twilio.com:3478?transport=tcp"
        }, {
            "username": "xxxx",
            "credential": "xxx",
            "urls": "turn:global.turn.twilio.com:443?transport=tcp"
        }]
    }


When I tried adding this your demo movie plays right away for me. But other magnet urls I try still suffer from same problem where downloading never starts.

What are these ice servers used for and where can I read more about setting one up?

**Comment by feross** [comment]
Sounds like you're on a network with a restrictive firewall or NAT. This makes it harder for peers to connect to you. Those "ice servers" are also known as TURN servers and they're a way to help WebRTC connections succeed even when there's a firewall or NAT that is preventing the direct P2P connection from working.

You can make an account with Twilio and sign up for this service (https://www.twilio.com/stun-turn) and they'll run the server for you. That's what I currently do. You can also try to install a TURN server yourself, but I hear it's tricky. If you include these in the rtcConfig option, then webtorrent will include them in the RTCPeerConnection (webrtc constructor) option, so the WebRTC connections are more likely to succeed.

TURN servers are only used as a fallback, when P2P connections fail. TURN is essentially a central server.
