### ISSUE TITLE
Use WebTorrent URLs in HTML

### ISSUE THREAD

**Issue by srt5y6ty** [feross/webtorrent#1015]
Instead of this

    var WebTorrent = require('webtorrent')
    
    var client = new WebTorrent()
    var magnetURI = '...'
    
    client.add(magnetURI, function (torrent) {
      // Got torrent metadata!
      console.log('Client is downloading:', torrent.infoHash)
    
      torrent.files.forEach(function (file) {
        // Display the file by appending it to the DOM. Supports video, audio, images, and
        // more. Specify a container element (CSS selector or reference to DOM node).
        file.appendTo('body')
      })
    })

would it be possible to support URLs directly like this

    <img src="magnet-url" />

**Comment by DiegoRBaquero** [comment]
Repeated issue.

See this: https://github.com/feross/webtorrent/issues/879
