### ISSUE TITLE
Question about handling magnets

### ISSUE THREAD

**Issue by CraigglesO** [feross/webtorrent#1020]
Do you request torrent metadata from all the peers you initially connect to?

Or do you 
1) Connect to 1 peer,
2) ask for torrent metadata
2.5) Failure -> move to next peer, put this peer on hold
3) Success -> connect to everyone and start asking for data

I could see asking everyone initially until you set a flag to true and then send cancels and move on.
But then I feel like this overcomplicates the process.

**Comment by xuset** [comment]
It looks like if the client does not have the metadata then it is requested from all peers it connects to until the metadata is received.

If you want to look it over, it's in [lib/torrent.js](https://github.com/feross/webtorrent/blob/beda5162c573adbecf5d6777b6821ec451b46639/lib/torrent.js#L976-L982)

**Comment by CraigglesO** [comment]
Thank you so much!
