### ISSUE TITLE
Cannot read property 'complete' of null

### ISSUE THREAD

**Issue by Tonkungs** [feross/webtorrent#1022]
I found that after download complete.

> DEBUG INFO: webtorrent-cli 1.9.0, webtorrent 0.98.2, node v7.2.1, win32 x64, exit 1
> C:\Users\username\AppData\Roaming\npm\node_modules\webtorrent-hybrid\node_modules\webtorrent\lib\torrent.js:1535
>         if (self._checkDone()) self.discovery.complete()
>                                              ^
> 
> TypeError: Cannot read property 'complete' of null
>     at C:\Users\username\AppData\Roaming\npm\node_modules\webtorrent-hybrid\node_modules\webtorrent\lib\torrent.js:1535:46
>     at C:\Users\username\AppData\Roaming\npm\node_modules\webtorrent-hybrid\node_modules\simple-sha1\index.js:6:5
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
>

**Comment by bdevore17** [comment]
Having the same issue

**Comment by feross** [comment]
Fixed in 0.98.4
