### ISSUE TITLE
Question concerning WS (not issue)

### ISSUE THREAD

**Issue by CraigglesO** [feross/webtorrent#1024]
I've been looking over the code and I realized that you just reused the bittorent protocol (wire) with ws.

However, I can't seem to understand how you implemented the ws server and client?

Did you use websocket-stream package? If you could point me to the code that explicitly preps the conditions (as I don't see it inside Peer or webconn) that would really help! Or just a quick paragraph explanation.

Also seems like you follow BEP 19 for website based DL. So It's all rather confusing as how to understand where to start.

**Comment by DiegoRBaquero** [comment]
The ws is not used for the bittorrent protocol, webrtc is. It is used only for the tracking.

**Comment by CraigglesO** [comment]
I thought ws was built on webrtc.... I have a lot to learn about this...

**Comment by feross** [comment]
The `bittorrent-tracker` package connects to tracker servers. There are 3 types: http, udp, and ws (websocket). The websocket trackers are the only kind that can introduce you to webrtc peers.

You can look at this file to see how the webrtc connections are created during communication with the tracker: https://github.com/feross/bittorrent-tracker/blob/master/lib/client/websocket-tracker.js
