### ISSUE TITLE
Stream torrent without downloading the file

### ISSUE THREAD

**Issue by ritz078** [feross/webtorrent#1027]
Is there a way to stream the torrent directly. Currently it saves the file which is being streamed.

**Comment by feross** [comment]
No, torrent clients need to be able to share files with others while they download, so the data needs to be stored somewhere. When using webtorrent in node, by default that place is the file system.

If you're willing to write code, you can store data in-memory by passing a custom  `store` option as documented here: https://github.com/feross/webtorrent/blob/master/docs/api.md#clientaddtorrentid-opts-function-ontorrent-torrent- 

You can set that option to use this package: https://www.npmjs.com/package/memory-chunk-store
