### ISSUE TITLE
List all torrents api

### ISSUE THREAD

**Issue by atmoner** [feross/webtorrent#1028]
**What version of WebTorrent?**
WebTorrent 1.9.0 (0.98.3)

**What operating system and Node.js version?**
Ubuntu 16.04 & Node v7.4.0

**What browser and version? (if using WebTorrent in the browser)**
No browser, in electron 

**What did you expect to happen?**
1) I would like to know if it is possible to access the list of torrents?
For now, I try the function [client.torrents](https://github.com/feross/webtorrent/blob/master/docs/api.md#clienttorrents) but it returns me only the name of the torrent currently in action
2) Why does the client.torrents function only work in [client.add](https://github.com/feross/webtorrent/blob/master/docs/api.md#clientaddtorrentid-opts-function-ontorrent-torrent-)?

```
      client.add(torrentId, function (torrent) {
  		log(util.inspect(client.torrents)) // Work, get 1 torrent
      }
```
```
      log(util.inspect(client.torrents)) // Not Work, get 'undefinied'
      client.add(torrentId, function (torrent) {
  		
      }
```

**Comment by DiegoRBaquero** [comment]
You should be getting an empty list. Do you really get undefined???

See [index.js#L86](https://github.com/feross/webtorrent/blob/e7fb21ec72b3d5b6ed1612f8a6f452e10de46d11/index.js#L86)

**Comment by feross** [comment]
@atmoner Can you share your complete code? Without that we can't really help you.

**Comment by atmoner** [comment]
@feross of course! 

### The context
I code from electron  
When I do my tests, I run a torrent with webtorrent-cli and a torrent from my software (which runs with webtorrent too)

The code is very basic:  

```
<script src="https://cdn.jsdelivr.net/webtorrent/latest/webtorrent.min.js"></script>
<script>
	 var torrentId = 'https://webtorrent.io/torrents/sintel.torrent'
	 var client = new WebTorrent()
	 var util = require('util')
	
	client.add(torrentId, function (torrent) {
	    console.log(Array.isArray(client.torrents)); // return true
	    client.torrents.forEach(function(element) {
	    console.log(element.name); // Return only sintel.mp4
	});		 		      
})
</script>
```  

 Webtorrent + my soft so 2 torrents runing but out of log give just one  

![1](https://cloud.githubusercontent.com/assets/1071490/22324030/e1f7f70c-e3a6-11e6-8ada-fa4a4214a58e.png)

**Comment by feross** [comment]
I believe you're using the wrong terminology. You are trying to print the number of **peers**, but what you are actually printing is the number of **torrents**.

A **torrent** is a set of files that are shared via the BitTorrent protocol.
A **peer** is a computer that your BitTorrent client connects to, in order to retrieve files

Try this:

```js
var client = new WebTorrent()
var torrentId = 'https://webtorrent.io/torrents/sintel.torrent'
var torrent = client.add(torrentId)

torrent.on('wire', function (wire) {
  console.log('Now connected to ' + torrent.numPeers + ' peers')
  if (wire.remoteAddress) {
    console.log(wire.remoteAddress + ':' + wire.remotePort)
  }
})
```

**Comment by atmoner** [comment]
> I believe you're using the wrong terminology. You are trying to print the number of peers, but what you are actually printing is the number of torrents.

No no ^^ I am really trying to display the list of torrents active in webtorrent (if it is possible obviously) ...

> A torrent is a set of files that are shared via the BitTorrent protocol.
> A peer is a computer that your BitTorrent client connects to, in order to retrieve files

For the connect peers it's ok, Webtorrent does very well this spot on a torrent but my final goal would be to create a mini torrent client with the simple functionality of webtorrent.

- Adding torrent (s)
- List the torrents
- Edit / delete
- ....

I almost do everything except the list of torrents! 
Thanks for your snip, It will be useful to me later ;)

**Comment by feross** [comment]
I don't understand why you expect your snippet to return more than 1 torrent. You're only adding 1 torrent to the client.

```js
	 var torrentId = 'https://webtorrent.io/torrents/sintel.torrent'
	 var client = new WebTorrent()
	 var util = require('util')
	
	client.add(torrentId, function (torrent) {
	    console.log(Array.isArray(client.torrents)); // return true
	    client.torrents.forEach(function(element) {
	    console.log(element.name); // Return only sintel.mp4
	});	
```

**Comment by atmoner** [comment]
On my screen I add a torrent from my software and a torrent with webtorrent-cli. But return only 1 torrent

> You're only adding 1 torrent to the client.

Ah! it's my another question, Can I add several torrent at once?

**Comment by atmoner** [comment]
Done for me! You had pointed out The right mistake, It was enough to add a second torrent as a result
Thank you very much for your work !! :+1: 

Code work:
```
var client = new WebTorrent()
var torrentId = 'https://webtorrent.io/torrents/sintel.torrent'
var torrent = client.add(torrentId)
var torrentId2 = 'https://website.io/another.torrent'
var torrent2 = client.add(torrentId2)
	
// Note: we refer to "peers" as "wires" in the WebTorrent codebase sometimes
torrent.on('wire', function (wire) {
	 // console.log('Now connected to ' + torrent.numPeers + ' peers')
	client.torrents.forEach(function(element) {
			console.log(element.name); // Return only sintel.mp4
	});
```
})

![2](https://cloud.githubusercontent.com/assets/1071490/22344911/3e3ae130-e3fe-11e6-8211-25c2bedda9ef.png)
