### ISSUE TITLE
Urgent: Hosted version is slow/broke

### ISSUE THREAD

**Issue by DiegoRBaquero** [feross/webtorrent#1033]
Latest version in jsDelivr & webtorrent.io take a lot of time to send first message to trackers & find first peers.

simple-peer creation take 9 seconds in generating 1 of the 10 initial offers:
![](https://www.dropbox.com/s/f0onp2avkbrmefy/Screenshot%202017-02-01%2017.30.46.jpg?dl=1)

Tested with a brand new browserified bundle version of my app and it works as it should.

Many dependencies have been update. We should try to create a build on each dep update.

@feross

**Comment by DiegoRBaquero** [comment]
Documenting:

Using clean standalone browserified version has the same problem.

Browserifying a small app that uses webtorrent has no problem.

**Comment by DiegoRBaquero** [comment]
Compare:

index.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<script src="bundle.js"></script>
</body>
</html>
```

app.js which bundles to bundle.js
```js
const WebTorrent = require('webtorrent')
const client = new WebTorrent()

client.add('6a9759bffd5c0af65319979fb7832189f4f3c35d', {announce: ['wss://tracker.btorrent.xyz']}, (torrent) => {
  console.debug('woot')
  torrent.files[0].appendTo('body')
})
```

with:
index2.html using latest hosted/browserified-standalone-version from latest git
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<script src="webtorrent.js"></script>
<script src="app2.js"></script>
</body>
</html>
```

app2.js
```js
const client = new WebTorrent()

client.add('6a9759bffd5c0af65319979fb7832189f4f3c35d', {announce: ['wss://tracker.btorrent.xyz']}, (torrent) => {
  console.debug('woot')
  torrent.files[0].appendTo('body')
})
```

For some reason the bundle is fast, the standalone, hosted or not, is slow.

**Comment by DiegoRBaquero** [comment]
Works perfectly when manually browserifying standalone version of webtorrent or bundling an app that requires it.

**Comment by DiegoRBaquero** [comment]
More findings: the issue happens with clean browserified version if online. localhost version is fast.

**Comment by DiegoRBaquero** [comment]
127.0.0.1:8080 version is slow, localhost:xxxxx is fast.

**Comment by DiegoRBaquero** [comment]
Found the real issue: Having STUN servers in the rtcConfig is what creates the delay.

**Comment by feross** [comment]
I just confirmed that the STUN server in `webtorrent.min.js` is "stun:stun.l.google.com:19302" so I don't think there's anything we need to do here.
