### ISSUE TITLE
torrent.pause is not working

### ISSUE THREAD

**Issue by jo-san** [feross/webtorrent#1035]
Hi,

I know it could be a false issue. But i have tried all the ways possible. Am building a node application which will allow my users to downloading torrents from my website. Downloading working fine. But when trying to implement pause/resume its just not happening. 

code snippet for reference
`var torrent = client.get(torrentId);`
`// torrent.pause();`
`torrent.swarm.pause();`

tried both. 

My webtorrent version: 0.98.0
On Windows7 with node v6.9.1

**Comment by feross** [comment]
From the docs for `torrent.pause()`:

> Temporarily stop connecting to new peers. Note that this does not pause new incoming connections, nor does it pause the streams of existing connections or their wires.

If you want to stop downloading, use `torrent.remove()`, then `torrent.add()` with the same `path` argument to get the download started again.
