### ISSUE TITLE
how to get the date of torrent.files directly

### ISSUE THREAD

**Issue by bluefchen** [feross/webtorrent#1036]
hi, does there is a way to get the date of torrent.files  ? it seems that the api file.appendTo can not get the hole file date to a local variable
torrent.on('done', function(){
torrent.files.forEach(function(file){
// do something with file
var tempDate = file //the file is a object which can not get the file content directly
// i want to get the text format file content
})
})

**Comment by DiegoRBaquero** [comment]
You mean like date of creation, modification, etc?

I don't think there such metadata available for the files accessible from the API.

**Comment by feross** [comment]
You can get the torrent creation date with `torrent.created`, but torrents do not contain information about when individual files were created because a torrent is single unit. There is one date for the whole torrent.
