### ISSUE TITLE
webtorrent-hybrid can't pass through the EC2(AWS) firewall

### ISSUE THREAD

**Issue by ijiboom** [feross/webtorrent#1038]
Hello, I'm trying to use webtorrent-hybrid in AWS EC2 and have some problem

I just copy/paste examples(webtorrent-hybrid/examples/) and Actually it works. but when seeding, To make it works, I manually check node's port (netstat -tnlp) and edit my AWS inbound rule. I don't want to repeat this

is there any solution?

**Comment by DiegoRBaquero** [comment]
Isn't there a way to open all ports?

**Comment by feross** [comment]
You can tell webtorrent what port to use on the command line by using the `--port` flag:

```
webtorrent-hybrid --port 6991
```

Then it will be consistent across runs of the program and you can open a single port.
