### ISSUE TITLE
Which ip address will be visible? (Paradox of egg and chicken)

### ISSUE THREAD

**Issue by atmoner** [feross/webtorrent#1046]
Just a question!
If I install webtorrent on an external server and add a web interface (with express js for example), what I call this page to stream a torrent, what IP address will be injected in the list of peers?

- The ip address of the server (where to install webtorrent)
or
- The ip address of the web browser that streamed the torrent?

In all logic, it is the browser that leech so it is him who shows his ip. no?

**Comment by DiegoRBaquero** [comment]
Depends where you run the WebTorrent client. If you run it in the browser, the browser's IP, else the server's IP.
