### ISSUE TITLE
is it possible to select all downloaded torrents files and delete them at ones ?! <!--- Version 0.18.0 (0.98.5) --->

### ISSUE THREAD

**Issue by Mohsenqaysi** [feross/webtorrent#1052]
**What version of WebTorrent?**

**What operating system and Node.js version?**

**What browser and version? (if using WebTorrent in the browser)**

**What did you expect to happen?**

**What actually happened?**

**Comment by feross** [comment]
Issues that do not follow the issue template cannot be answered, sorry. If you open a new issue that follows the template, the team can take a look.
