### ISSUE TITLE
Not downloading when using private tracker

### ISSUE THREAD

**Issue by zephrax** [feross/webtorrent#1054]
Hi,

I've started the simple private tracker with torrent-tracker:

``╰─○ ./node_modules/bittorrent-tracker/bin/cmd.js
HTTP tracker: http://localhost:8000/announce
UDP tracker: udp://0.0.0.0:8000
UDP6 tracker: udp://localhost:8000
WebSocket tracker: ws://localhost:8000
Tracker stats: http://localhost:8000/stats``

Also started another process to seed the file:

``var WebTorrent = require('webtorrent');
var client = new WebTorrent();
var file = '/home/zephrax/Vuze Downloads/Test.mp4';
var options = { 
  announce : [ 'http://localhost:8000/announce', 'udp://127.0.0.1:8000', 'ws://localhost:8000' ]
};
client.seed(file, options, function(torrent) {
  console.log('Client is seeding:', torrent.infoHash)
});``

And finally, I wrote a little html to be loaded by the browser, with the following code:
``             var client = new WebTorrent();
              var magnetURI = 'magnet:?xt=urn:btih:11d68fffe54198b07093e3bac796d4adcf15bfd6&dn=Test.mp4&tr=ws%3A%2F%2Flocalhost%3A8000&tr=http%3A%2F%2Flocalhost%3A8000%2Fannounce&tr=udp%3A%2F%2Flocalhost%3A8000';
              
              client.on('error', function (err) {
                  console.error('ERROR: ' + err.message);
              }); 
              
              client.on('torrent', function (data) {
                  console.log(data);
              }); 
              
              client.add(magnetURI, function (torrent) {
                console.log('Client is downloading:', torrent.infoHash);
                
                torrent.files.forEach(function (file) {
                  file.appendTo('body');
                })
              });``

I can see the WebSocket comminicating, but it never starts downloading the file:
![selection_371](https://cloud.githubusercontent.com/assets/688426/23142224/8d7f2aa4-f799-11e6-81c3-f5439c049871.jpg)
![selection_372](https://cloud.githubusercontent.com/assets/688426/23142225/90285802-f799-11e6-8ac0-150f8e717cf2.jpg)

Am I doing something wrong? or this could be an issue?

**Comment by DiegoRBaquero** [comment]
Are you using webtorrent-hybrid to seed? Because it won't work with plain webtorrent in nodejs

**Comment by zephrax** [comment]
Nice tip, with webtorrent-hybrid it worked perfectly. Thanks!
