### ISSUE TITLE
Any way to log what's happening after webtorrent.add(id) ?? 

### ISSUE THREAD

**Issue by jackey** [feross/webtorrent#1057]
i'm beginner to use webtorrent. not lucky to use it. :( 

```
    var client = new WebTorrent();
    var id = "magnet:?xt=urn:btih:81b15febb76e289928ff9ba93b1062ce7bf068d7&dn=Marvels.Agents.of.S.H.I.E.L.D.S04E06.1080p.WEB-DL.DD5.1.H264-RARBG&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710";
    client.on('error', function (err) {
      console.log(['err', err]);
    });
    client.on('torrent', function (torrent) {
      console.log(['torrent', torrent]);
    });
    client.add(id, function(torrent) {
      console.log(torrent);
    });
```
i got nothing from these code. how to check the log during webtorrent runing ?

**Comment by bertofer** [comment]
WebTorrent uses the [debug](https://www.npmjs.com/package/debug) module for logs. If you put localStorage.debug = '*' you will see all the logs happening. 'webtorrent:*' will filter the webtorrent specific ones. Although webtorrent uses other internal modules (like bittorrent-protocol, ...), consider just '*' if you want to go deeper en your debug.

**Comment by jackey** [comment]
@bertofer  i saw there's log output in console.  thank u .

**Comment by feross** [comment]
Thanks for helping out @bertofer :)
