### ISSUE TITLE
MIME Type not supported for mkv files

### ISSUE THREAD

**Issue by silverblade7** [feross/webtorrent#1058]
Hi,

I was experimenting with webrtc and not able to solve how to stream MKV files. All I see is MIME Type not supported.

The last time I was working on media encoding I came to know that MKV should be explicitly defined as DOM type.

Thanks in advance.

**Comment by DiegoRBaquero** [comment]
Next time please search before opening a new issue: https://github.com/feross/webtorrent/issues?q=is%3Aissue+mkv+is%3Aclosed

See: https://github.com/jhiesey/videostream/issues/29
