### ISSUE TITLE
Video and subtitles

### ISSUE THREAD

**Issue by jsilvaneto** [feross/webtorrent#1064]
**What version of WebTorrent?**

**What operating system and Node.js version?**

**What browser and version? (if using WebTorrent in the browser)**

**What did you expect to happen?**

**What actually happened?**

**Comment by jsilvaneto** [comment]
Hello, I am new to the webtorrent and I am using webtorrent plugin in wordpress but I am in difficulty to change the autoplay to false and I am also not able to put the subtitles file the videos and I would like to know if the quality of the videos is automatic?

**Comment by DiegoRBaquero** [comment]
There's no option to either right now. If you'd like to request the features, do so here: https://github.com/feross/webtorrent-wordpress

The quality of the video is whatever the video's quality at time of torrent creation was.
