### ISSUE TITLE
Slow down when adding multiple torrents

### ISSUE THREAD

**Issue by 6f7262** [feross/webtorrent#1065]
**What version of WebTorrent?**
master (0.98.8) and below

**What operating system and Node.js version?**
Windows 10 & Mac OSX Sierra

**What browser and version? (if using WebTorrent in the browser)**
Tried with the latest build of Chrome. Canary and Firefox

**What did you expect to happen?**
Not slow down and crash webpages.

**What actually happened?**
Pages slow down significantly when adding multiple torrents at a time. Even with a 100ms delay between adding torrents the page becomes unusable. Adding 50~ torrents with a 100ms between addition, this is the CPU profile 
![image](https://cloud.githubusercontent.com/assets/9749173/23445897/d724637e-fe36-11e6-8ca9-d4398d263cc8.png)

This behavior can be seen when going to [instant.io](http://instant.io) and adding maybe 10~ torrents.

**Comment by feross** [comment]
Thanks for posting this issue. I plan to do something about the CPU issue when I get some more time. This is a known issue.

Also, btw, it's probably not a good idea to add 50 torrents to the client (if they are all downloading) at the same time, even once we fix this issue. Most torrent clients limit to 5 active at any given time.
