### ISSUE TITLE
Completed downloads Not Making Blob URLs

### ISSUE THREAD

**Issue by Edward-Stryfe** [feross/webtorrent#1067]
I am seeding the torrent and a few others and this is a reoccuring problem where random files (all of which are completed and seeding) are completed but are not highlighted and does not link to the blob of the file. This happens on instant.io btorrent.xyz and my personal scripts so I know it's not a problem with the individual scripts/servers. It seems web torrent must not be emitting the event on finished. 

Example torrent https://btorrent.xyz/#76437ff7ec0ca8014c199a59e63be4dd2a3da0cf

**Comment by feross** [comment]
Your link is dead for me. If you can provide a reproducible example or a PR, that would be appreciated.
