### ISSUE TITLE
wordpress post reposition

### ISSUE THREAD

**Issue by NinjaAtWork** [feross/webtorrent#1069]
hi
really glad to see this happens to WordPress!
I'm going to use this at my post there :)
two request
1-sintel example will appear at the start of page no matter where the [webtorrent] is inserted and this is annoying,what to do? i saw the plain text of the article and the sort is what i need but after reloading the page, movie canvas will be on top also i tested [webtorrent] in 3 place and still they all go in top of article
2-is there any way to download the movie by the "download link" some where?

**Comment by DiegoRBaquero** [comment]
Refer to: https://github.com/feross/webtorrent-wordpress
