### ISSUE TITLE
Option 'port' is required

### ISSUE THREAD

**Issue by dpxcc** [feross/webtorrent#1071]
I'm using webtorrent on react native, with the help of rn-nodeify. But I got an error: Option 'port' is required at index.js:20:44

**What version of WebTorrent?**
0.98.9
**What operating system and Node.js version?**
OSX, 6.3.1
**What browser and version? (if using WebTorrent in the browser)**
In Iphone 6 iOS 10.2 simulator
**What did you expect to happen?**
```
const client = new WebTorrent()
client.add(magnet, torrent =>
  console.log(torrent)
)
```
**What actually happened?**
Option 'port' is required at index.js:20:44

**Comment by dpxcc** [comment]
I fixed this by using a random torrentPort. However, the callback is never called.

**Comment by feross** [comment]
Sorry, I don't use React Native and it's unclear from your bug report what the issue could be. If you have a PR that fixes your issue, feel free to submit it.

**Comment by dpxcc** [comment]
I was able to use webtorrent with react-native. If I remember correctly, you have to update some nodes libraries. The current rn-nodify are using old shimed libraries and they are not compatible with others.

https://github.com/urbien/tradle/issues/3
