### ISSUE TITLE
Simple questiones 

### ISSUE THREAD

**Issue by jackey** [feross/webtorrent#1072]
I'm new beginer to p2p network and got free questions.

1. Does the webtorrent-hybird need to keep opening after generate magnet URI ?

2. When browser plays the video with webtorrent, does it join the p2p network and share the video file ? If so that, is this means more user play video, more faster the network ??

**Comment by feross** [comment]
1. Yes.

2. Yes. Yes.

**Comment by jackey** [comment]
@feross, great. 

i got new question,

does webtorrent-hybird that in difference network generates same magnet URI if the shared file is same name. if yes, is this means more user share file with same name, so more faster download speed ?

**Comment by feross** [comment]
Yes. If the files and filenames are the same, then the generated magnet uri should be the same.

**Comment by jackey** [comment]
@feross , this's so exciting ! thank you for confirm :+1:
