### ISSUE TITLE
file.renderTo('div#player') fails

### ISSUE THREAD

**Issue by chovy** [feross/webtorrent#1073]
Calling `file.renderTo('div#player')` fails when file is an mp4

`Uncaught Error: Cannot render ".mp4" inside a "div" element, expected "video"`

using `file.appendTo('div#player')` works but then I get multiple video objects each time I play a file.

**Comment by feross** [comment]
`renderTo` is intended to be used with a `<video>` dom node. You can't use it with a `<div>`.

You can make a `<video id="player">` element and then use `renderTo` with it.

**Comment by chovy** [comment]
I tried that too, it seems to show up but nothing is visible.

**Comment by chovy** [comment]
https://github.com/feross/webtorrent/pull/1074/files
