### ISSUE TITLE
electron-eval error: Electron process exited with code 2

### ISSUE THREAD

**Issue by chovy** [feross/webtorrent#1075]
```

UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/feross/webtorrent/issues

DEBUG INFO: webtorrent-cli 1.9.0, webtorrent 0.98.10, node v7.7.1, linux x64, exit 1
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: electron-eval error: Electron process exited with code 2
    at ChildProcess.<anonymous> (/home/example/.nvm/versions/node/v7.7.1/lib/node_modules/webtorrent-hybrid/node_modules/electron-eval/lib/index.js:174:22)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:504:12)

```

This happens when I seed more than one file. One usually seems to work ok, but if i have 2-3 it crashes frequently. Probably a memory/resource issues -- its on a $5 vps.

**Comment by feross** [comment]
If you have to seed many files, I recommend using http web seeds instead of `webtorrent-hybrid`. They will be much more reliable.

**Comment by chovy** [comment]
I am confused. isn't webtorrent a cli torrent client? It can only seed one file at a time?

**Comment by feross** [comment]
WebTorrent isn't a CLI torrent client. It's a JavaScript torrent client that has many different frontends. It can be used via an official CLI, a desktop app, or a `<script>` tag in a browser.

The CLI only supports one torrent at a time. Use the desktop app if you want to seed multiple torrents.

**Comment by chovy** [comment]
gotcha. i thought cli was a full blown torrent client?

**Comment by feross** [comment]
Yes, sorry. If someone else wants to build a full-featured CLI torrent client on top of the webtorrent engine, they should feel free. It's not something I want to do. Since most users want a GUI, I'd rather put my effort there.

**Comment by chovy** [comment]
Makes sense. Dont' mean to bombard you with all these questions -- but this project looks very promising and I'm sure others will have same questions, so at least there is a record.
