### ISSUE TITLE
Files under 16Kb are not downloaded correctly

### ISSUE THREAD

**Issue by Angelmmiguel** [feross/webtorrent#1077]
**What version of WebTorrent?**
0.98.10

**What browser and version? (if using WebTorrent in the browser)**
Google Chrome v56.0.2924.87 (64-bit)

**What did you expect to happen?**
I seeded several files. The size of every of them didn't exceed 16Kb. After that, I got the magnet URI and tried to download from other window of the same browser. It seems the files was dowloaded but I couldn't get the content of those files.

To double check it, I uploaded the same file to [instant.io](instant.io) and the result was the same.

However, If I use a file > 16Kb it works fine in my implementation and [instant.io](instant.io). You can use the following image to check the problem:

![small image](https://cloud.githubusercontent.com/assets/4056725/23846417/a5e601f0-07cd-11e7-80be-a8e377ca9eb0.png)

**What actually happened?**
The file was downloaded but I couldn't get the content of the image or text. I tried with the method `appendTo` and I got an empty box without any content.

**Investigation**
I investigate a bit the error and the `_notify` method of `file-stream.js` is only called once. The method returns on [file-stream.js#L53](https://github.com/feross/webtorrent/blob/master/lib/file-stream.js#L53) and never execute the `get` method in [file-stream.js#L60](https://github.com/feross/webtorrent/blob/master/lib/file-stream.js#L60).

**Comment by feross** [comment]
Confirmed this is an issue. Found the bug this was introduced in, using `git bisect`: https://github.com/feross/webtorrent/commit/6ef2785e4bbed07f2429725ed2b05bd91fc36233

**Comment by feross** [comment]
Fixed in 0.98.12. Thanks for reporting!

**Comment by Angelmmiguel** [comment]
That's great! Thank you.
