### ISSUE TITLE
Videos doesn't work

### ISSUE THREAD

**Issue by andreapaiola** [feross/webtorrent#1080]
**What version of WebTorrent?**
v0.98.14

**What browser and version? (if using WebTorrent in the browser)**
Chrome and Firefox, maybe all?

**What did you expect to happen?**
Images and videos load and render...

**What actually happened?**
Images work
Video doesn't work

Example:
https://andreapaiola.name/php-p2p-webtorrent-cdn/

Only a video
https://andreapaiola.name/php-p2p-webtorrent-cdn/video.php

The .torrent files are generated by php, but in a BitTorrent client like Transmission all works...

**Comment by andreapaiola** [comment]
Added audio test, it works.

**Comment by feross** [comment]
Your server is misbehaving. It claims to support Range requests but it's not handling them correctly.

Look at the network tab in Chrome, at the request for `sintel.mp4`. The request contains the header:

```
Range: bytes=start-end
```

So, a valid server response is either:

1) HTTP 200, indicating that the server did not understand the range request (and it will return the whole file)

2) HTTP 206, indicating the server understood the range request (and it will return ONLY the requested range)

In case 2, the server will include the following headers:

```
Accept-Ranges: bytes
Content-Range: bytes {start}-{end}/{total}
```

The first indicates that it supports Range requests, and the second confirms the range that is being returned.

Your server is doing a mix of these things which is incorrect:

1) Returning HTTP 200 and returning the full file
2) Including the header `Accept-Ranges: bytes` indicates it supports Range requests, but it's missing `Content-Range`.

If you replace the web seed URL with https://webtorrent.io/torrents/sintel-1024-surround.mp4 you can see how a well-behaved server works.

**Comment by andreapaiola** [comment]
But I see Content-Range...

https://andreapaiola.name/php-p2p-webtorrent-cdn/sintel.mp4

![schermata 2017-03-20 alle 13 28 26](https://cloud.githubusercontent.com/assets/16450997/24099809/7c28fbac-0d71-11e7-9c27-967099e27e1a.png)

**Comment by andreapaiola** [comment]
https://andreapaiola.name/php-p2p-webtorrent-cdn/test.mp4

![schermata 2017-03-20 alle 13 30 16](https://cloud.githubusercontent.com/assets/16450997/24099870/c010a892-0d71-11e7-96f6-34292096d284.png)

**Comment by andreapaiola** [comment]
And it seems to me that it downloads the videos...


![schermata 2017-03-20 alle 13 38 04](https://cloud.githubusercontent.com/assets/16450997/24100076/bbcd87e0-0d72-11e7-8ef2-ae1c0015b952.png)

**Comment by feross** [comment]
Content-Range isn't being set when the XHR request is made from the page. Look in the Network tab on your page: https://andreapaiola.name/php-p2p-webtorrent-cdn/video.php

These are the response headers:

```
HTTP/1.1 200 OK
Date: Mon, 20 Mar 2017 23:47:23 GMT
Server: Apache
Last-Modified: Sat, 18 Mar 2017 21:42:21 GMT
Accept-Ranges: bytes
Cache-Control: max-age=2592000
Expires: Wed, 19 Apr 2017 23:47:23 GMT
Vary: Accept-Encoding,User-Agent
Content-Encoding: gzip
X-Powered-By: PleskLin
P3P: policyref="/w3c/p3p.xml", CP="IDC DSP COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
Keep-Alive: timeout=15, max=9996
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: video/mp4
```

It's definitely odd that the correct headers are set when you visit the URL directly. I would look at the headers that are being sent with each request and see if there's a difference that's causing your server to misbehave.

**Comment by andreapaiola** [comment]
Yeah I made a simple XHR request and I can confirm that

https://andreapaiola.name/php-p2p-webtorrent-cdn/video-test.php

I disabled gzip compression for .mp4 files with

`SetOutputFilter DEFLATE
SetEnvIfNoCase Request_URI \.mp4$ no-gzip dont-vary`

and now it works
