### ISSUE TITLE
Chrome will crash on big file with ws feature (firefox won't)

### ISSUE THREAD

**Issue by kocoten1992** [feross/webtorrent#1081]
**What version of WebTorrent?**
0.98.14

**What operating system and Node.js version?**
Ubuntu 17.04

**What browser and version? (if using WebTorrent in the browser)**
Chrome 57 (Firefox seem fine)

**What did you expect to happen?**
Nothing should happen

**What actually happened?**
Chrome crashed when I'm testing the ws feature

// Sintel, a free, Creative Commons movie
var torrentId = 'magnet:?xt=urn:btih:6a9759bffd5c0af65319979fb7832189f4f3c35d&dn=sintel.mp4&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&**ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fsintel-1024-surround.mp4**'

If movie size are big (like 2GB) it will crash chrome (Firefox seem fine).

**Comment by feross** [comment]
Sorry, can't reproduce this with the torrent you shared. If you have a public domain, creative commons torrent that exhibits this issue, please share.

**Comment by kocoten1992** [comment]
related issue, https://github.com/feross/webtorrent/issues/319
