### ISSUE TITLE
Check for duplicate torrent

### ISSUE THREAD

**Issue by andreapaiola** [feross/webtorrent#1082]
Duplicate torrent

https://andreapaiola.name/php-p2p-webtorrent-cdn/multi.php

Uncaught Error: Cannot add duplicate torrent 858155eb96db0008d9e0e720eb20d4db7dd18c77

How can I check if a torrent exists and use it to insert the content in the page? I think that could be useful to insert these in the documentation... thank you!

**Comment by feross** [comment]
Use `client.get(torrentId)` to see if the torrent is already part of the client.

https://github.com/feross/webtorrent/blob/master/docs/api.md#clientgettorrentid

**Comment by andreapaiola** [comment]
yeah, I use it... line 44... it doesn't work...

**Comment by feross** [comment]
If you add a torrent type that is async, like an http torrent file, then it's not possible for the client to know what the infohash of the torrent is until it has fetched the torrent file. So if you call `client.add` twice with two torrent files that both have the same infohash, you'll get this error.

There's not an easy way for the webtorrent library to fix this issue.

**Comment by andreapaiola** [comment]
ummm maybe I can check the url of the .torrent file... I'll think about it
