### ISSUE TITLE
How to intregrate in php

### ISSUE THREAD

**Issue by sagar3506** [feross/webtorrent#1088]
hey i found its very useful for my project but i don`t know how to intregrate  webtorrent.io  api with php

or its possible to stream direct link videos on webtorrent.io

ex :  i have  link of mp4 video like www.ex.com/sp/sp.mp4  
its possible to streeam this link video using webtorrent.io

**Comment by DiegoRBaquero** [comment]
You can use the minified version on the client. You need to create a torrent from the video first (And hopefully add a webseed).
