### ISSUE TITLE
Storage and seed information

### ISSUE THREAD

**Issue by Smallkan** [feross/webtorrent#1089]
I apologize for my ignorance and bad English.

Next, I'll try to explain what I want to do.

I have a site where I want to add the player to the user watching through the streaming torrent.

I have a dedicated server with Windows Server.

Then go the questions:

Which torrent client do I use to leave "sowing" the torrent whenever someone watches?
Where do I send the .mp4 file? Btorrent.xyz? Instant.
Ok, I sent the .mp4 file, received an infohash, magnet uri and a torrent file generated, can I close the browser? Or shall I leave it open?

Are doubts that I have, because I accessed btorrent.xyz, I sent a file and it was playing normal, but after I give an F5, the transmission STOPED.

So I want to know where I'm sending it and it stays permanent, just like on piratebay for example.

It is a good use of WebTorrent Desktop, but after many files, it hangs and gets very heavy, so it would have to have a smaller torrent client, such as utorrent.

I would be grateful if anyone would help me.

**Comment by DiegoRBaquero** [comment]
You can only use Vuze and WebTorrent Desktop. The others don't support WebRTC peers yet.

**Comment by Smallkan** [comment]
I used Vuze, but it's a protocol.
I created a torrent in Vuze and added the trackers of the webtorrent, but it does not work.
So I had to send it to the btorrent, download the file to my pc, then download it to Vuze so he could sow.

**Comment by feross** [comment]
If you want to seed something so it's always available to web users, I recommend adding an http web seed to your torrent.
