### ISSUE TITLE
tracker

### ISSUE THREAD

**Issue by Smallkan** [feross/webtorrent#1092]
Is there a way to create a client torrent to send multiple files? About 200?

You can not use uTorrent I know, you can not use Vuzer, it buga very much. Using WebTorrent, once it has a list of over 100 files, starts getting heavy and crashes alone, it really is tricky.

**Comment by feross** [comment]
For seeding lots of torrents you're better off using HTTP Web Seeds. http://www.bittorrent.org/beps/bep_0019.html
