### ISSUE TITLE
Video starts playing late

### ISSUE THREAD

**Issue by davidupx** [feross/webtorrent#1097]
**What version of WebTorrent?**
v0.98.16
**What operating system and Node.js version?**
CentOS 6.8 - node 6.10
**What browser and version? (if using WebTorrent in the browser)**
Chrome 57 - Firefox 52
**What did you expect to happen?**
Video starts playing as soon as first frame is downloaded
**What actually happened?**
The video size is 500MB, 2 webseeds are being used and are fetched from torrent file (urlList parameter), the chunk size is 512KB.
The video starts playing after downloading about 15MB which is kind of late compared to classic streaming.
Where should I be looking in order to make the video start playing sooner?

**Comment by DiegoRBaquero** [comment]
Which file format is the video?

**Comment by davidupx** [comment]
MP4 for sure

**Comment by DiegoRBaquero** [comment]
MP4 videos are handled by this library: https://github.com/jhiesey/videostream

@jhiesey has 100x my experience in the subject, he might be able to help with this issue.

**Comment by yciabaud** [comment]
Mp4 is good but you need to encode the video with some flags at the begining in order to be able to stream it.

Try a basic player with a webseed to see if it is webtorrent related.

The flags are called moov if you need reference.

**Comment by davidupx** [comment]
@yciabaud  We tried the -movflags faststart ffmpeg option but no luck, their is still the same delay before the player starts the video.
Any more idea about it?
Thanks

**Comment by yciabaud** [comment]
Can you provide the torrent with the webseeds in order to have a look?

**Comment by davidupx** [comment]
http://179.43.145.194/sintel.html
As you can see, the video starts playing only after downloading about >10MB,
knowing that for users who have a medium-speed connection, 10MB means a few minutes of patience to see the first frame...

**Comment by DiegoRBaquero** [comment]
Loads for me after 2 seconds at 4 MB downloaded

**Comment by feross** [comment]
Loads for me at 7MB.

Multiple pieces are being downloaded concurrently but a piece can't be used until it's completely downloaded, so some of those extra MBs are probably devoted to future pieces that aren't needed to play the first frame. But if there are enough peers available in the network, we'll try to connect and get data from them anyway. Maybe this can be improved but then we'd need to have an idea of how much bandwidth is available to the client... This all sounds really hard and I haven't taken a close look at the download strategy code in a long time.

I'm -1 on changing anything to address this.

**Comment by jhiesey** [comment]
I'm a bit late to this issue, but I'll take a look this weekend to see if there's anything that can be improved on the videostream side.

@yciabaud @davidupx I'm not surprised the faststart option doesn't make much difference. In either case videostream will request the beginning of the file first and then almost immediately seek to the correct moov offset (either still near the beginning with the option passed or near the end without it). Different chunks would be downloaded but not much else changes.

**Comment by davidupx** [comment]
@jhiesey Thanks for your reply, I hope you can improve the situation.
I look forward to hearing from you, if there is a solution or suggestions.

**Comment by jhiesey** [comment]
Alright, didn't get to it this weekend. Hopefully early this week.
