### ISSUE TITLE
How can i  know the torrent file created time ?

### ISSUE THREAD

**Issue by catchstar** [feross/webtorrent#1099]
How can i  know the torrent file created time?  i can't find the created time information in torrent.

client.add(magnetURI, function (torrent) {
    console.log(torrent) // none of created time information
});

**Comment by DiegoRBaquero** [comment]
a magnet URI won't ever show the torrent's created time.

A torrent file will have `.created` property if the file contained the `creation date`, else it won't.

**Comment by catchstar** [comment]
got it. Thanks.
