### ISSUE TITLE
timeout setting and error callback question

### ISSUE THREAD

**Issue by catchstar** [feross/webtorrent#1100]
I have two question about webtorrent api.

i want to get file's information from magnet uri. so my code is :
```js
let client = new WebTorrent();
let magnet = 'magnet:?xt=urn:btih:08BC48D2EF4887EAEBE759CA31736B6A7C6CABFB';

client.add(magnet, function (torrent) {
      // get information about torrent's files
      console.log(torrent.files);

      // stop download because just want file's information
      torrent.destroy();

});
client.on('error', function (err) {
      console.log(err)
});
```

--------------------
i run the code on two vps.  the first one is located in Japan, the second is located in US.

Japan vps result is:
no callback for a long time. And i can't find the timeout option from webtorrent api.

US vps result is:
**args[0] = '[' + this.client._debugId + '] [' + this._debugId + '] ' + args[0]
TypeError: Cannot read property '_debugId' of null**

this error is not occur on client.on('error') and stop my nodejs process. what is so bad.

nodejs version : v7.6.0
webtorrent version: 0.98.16

Maybe my question is how can i deal with the  unavailable or poor quality magnet uri.
please help me solve the problems. Thank you.

**Comment by feross** [comment]
Fixed by: https://github.com/feross/webtorrent/pull/1103
