### ISSUE TITLE
How to remove a torrent for the client?

### ISSUE THREAD

**Issue by catchstar** [feross/webtorrent#1101]
My code:
```js
const WebTorrent = require('webtorrent')
let client = new WebTorrent();
let torrentId = 'magnet:?xt=urn:btih:1E717B83DFDC69339F260E7BAB85E8C9D87B835A';

client.add(torrentId);

client.on('torrent', function (torrent) {
    console.log(torrent)
    
   // occur an error: No torrent with id magnet
    client.remove(torrentId);
});
```
but if change below like that, it will be ok:
```js
client.on('torrent', function (torrent) {
    console.log(torrent)
    
   // remove right
   setTimeout(() => {
       client.remove(torrentId);
   }, 0)
});
```

i'm confused by this problem.
please help me to solve the problem.Thanks a lot.

**Comment by DiegoRBaquero** [comment]
Weird because the torrent is being added before the torrent callback is emitted: https://github.com/feross/webtorrent/blob/master/index.js#L261

**Comment by feross** [comment]
@catchstar I ran your code and could not reproduce the issue with the latest version of WebTorrent.
 
What version of `webtorrent` do you have installed? Are you possibly calling `client.remove()` or `torrent.destroy()` anywhere else in your program? Since that could cause this issue.

**Comment by catchstar** [comment]
@feross my vps could reproduce the issue but i can't login in right now.Because i receive a shutdown ticket from lindode support which say my program has a copyright-infringing question.
When i solve the linode problem, i will check the webtorrent version. orz..:(

**Comment by catchstar** [comment]
@feross @DiegoRBaquero Hello, i reproduce the problem.  Here my code:
```js
const WebTorrent = require('webtorrent')
let client = new WebTorrent();

// the torrentId is different with above
let torrentId = '08BC48D2EF4887EAEBE759CA31736B6A7C6CABFB';
client.add(torrentId);

client.on('torrent', function (torrent) {
    console.log(torrent)

   // occur an TypeError: Cannot read property '_debugId' of null
   client.remove(torrentId);
});
```
-------------
webtorrent version : 0.98.16
NodeJS version: v6.10.2

i try this code on two vps and occur error either.

**Comment by catchstar** [comment]
@feross @DiegoRBaquero  
i debug the program and found after destory the torrent and reset the self.client = null
https://github.com/feross/webtorrent/blob/master/lib/torrent.js#L708

and program will still run by the wire.request callback function
https://github.com/feross/webtorrent/blob/master/lib/torrent.js#L1500

it makes me feel so weird.
