### ISSUE TITLE
Support downloading torrents larger than available memory without swapping

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#112]
<a href="https://github.com/feross"><img src="https://avatars.githubusercontent.com/u/121766?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [feross](https://github.com/feross)**
_Sunday May 18, 2014 at 07:09 GMT_
_Originally opened as https://github.com/feross/bittorrent-client/issues/16_

----

We'll need to come up with an eviction solution so you can download torrents which are larger than the available memory on the system without thrashing to disk!

**Comment by sammuel86** [comment]
bump. issue still present and huge problem for older computers.

**Comment by feross** [comment]
Duplicate of https://github.com/feross/webtorrent/issues/248

**Comment by carlopires** [comment]
Any improvements on this? I would like to implement IndexedDB for my browser clients if this is an option supported by the official interface.
