### ISSUE TITLE
Add test for ut_pex

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#119]
<a href="https://github.com/feross"><img src="https://avatars.githubusercontent.com/u/121766?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [feross](https://github.com/feross)**
_Friday Jun 06, 2014 at 06:52 GMT_
_Originally opened as https://github.com/feross/bittorrent-client/issues/23_

----

**Comment by nkittsteiner** [comment]
Is this still required? Can you provide more feedback of what is needed for this issue?
