### ISSUE TITLE
Add test of different strategies

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#121]
<a href="https://github.com/feross"><img src="https://avatars.githubusercontent.com/u/121766?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [feross](https://github.com/feross)**
_Friday Jun 06, 2014 at 06:57 GMT_
_Originally opened as https://github.com/feross/bittorrent-client/issues/25_

----

I deleted the old strategy test (see https://github.com/feross/bittorrent-client/commit/864fc3b71defd8983bd5e3638ebd54645bb5b9a8) because it wasn't actually verifying that the right pieces are requested based on the strategy.

**Comment by nkittsteiner** [comment]
The link provided is broken, so it's not possible to see the strategy test.
