### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#146]
Specifically, these modules need better docs:

- https://github.com/feross/bittorrent-swarm
- https://github.com/feross/bittorrent-tracker
- https://github.com/feross/webtorrent-tracker
- https://github.com/feross/webtorrent-swarm

**Comment by vpontis** [comment]
I might try and tackle this soon because I can add documentation as I go through trying to understand each module...

**Comment by feross** [comment]
@vpontis awesome, that would be a huge help.
