### ISSUE TITLE
Need to periodically announce to the DHT

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#147]
Need to periodically announce to the DHT, otherwise we'll get removed from people's routing tables after a while. This is important for long-running torrents.

For someone interested in tackling this issue, the modules to look at are `torrent-discovery` and `bittorrent-dht`.

**Comment by oleiba** [comment]
Hi, wasn't this handled with feross/torrent-discovery#11 ?
Thanks!

**Comment by feross** [comment]
@oleiba Yes, this bug is fixed now, thanks to my PR https://github.com/feross/torrent-discovery/pull/12 Thanks for pointing that out!
