### ISSUE TITLE
Compress SDP messages

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#148]
SDP message compression can significantly lighten the load on the webtorrent tracker and dht by making the signaling messages much smaller. This could be done by giving each peer a common dictionary of frequently-occurring strings that can be referenced to compose a complete SDP message.

**Comment by feross** [comment]
The unnecessary audio lines have been eliminated from the SDP.

Regarding SDP compression, after some investigation, I decided to punt on SDP compression. It's actually quite tricky to get right with all the variations of SDP and the evolving spec. It's also premature optimization. I'll re-open this when/if the webtorrent tracker starts to experience significant load.

**Comment by feross** [comment]
For anyone interested, @fippo got this working!

https://twitter.com/HCornflower/status/580623559019638784
http://code.gar.zone/?gist=c85814f9a1ffec5340e8

**Comment by fippo** [comment]
note that delivering the answer in near-realtime (<10s) is pretty critical. Updated version soon probably, found a couple of issues.

**Comment by feross** [comment]
Why is it necessary to deliver the answer in near-realtime?

**Comment by fippo** [comment]
for crazy complicated annoying reasons :-)

there is a 30s timeout on ice checks from the answerer. And since TURN is involved, there are additional complications and round-trips involved. Still debating whether there is a bug, too...

**Comment by feross** [comment]
More info here: https://webrtchacks.com/the-minimum-viable-sdp/

**Comment by substack** [comment]
and soon: an npm package https://github.com/fippo/minimal-webrtc/pull/2

**Comment by gauravsaini** [comment]
This is exciting :+1:

**Comment by feross** [comment]
Published as sdp-minimizer https://www.npmjs.com/package/sdp-minimizer

**Comment by piranna** [comment]
Awesome! :-D

**Comment by feross** [comment]
Now that there's a nice module for this, let's try using it for WebTorrent.
