### ISSUE TITLE
firefox os torrent app

### ISSUE THREAD

**Issue by gotwig** [feross/webtorrent#149]
An app for firefox os to handle torrents would be nice

**Comment by hferee** [comment]
Idem. Note that firefox os devices would make a perfect hybrid client.
Also, such a client might be android compatible, which would greatly increase the number of possible hybrid clients.

**Comment by feross** [comment]
This is a cool idea, but this isn't a goal for anytime soon, so I'm going to close it so we can focus. If someone wants to tackle building a WebTorrent client for Firefox OS, you're more than welcome to :-). We can come back to this once more pressing issues are fixed. Closing
