### ISSUE TITLE
Save to api

### ISSUE THREAD

**Issue by sammuel86** [feross/webtorrent#156]
Would be awsome to have a save to api for node webkit apps!

eg: { path: 'C:/superamazing.avi' }

**Comment by feross** [comment]
This is officially supported in webtorrent 0.30.0. Just do this:

```js
var WebTorrent = require('webtorrent')
var client = new WebTorrent()
client.add('magnet: ...', { path: '/download/folder' }, function (torrent) {
})
```

**Comment by sammuel86** [comment]
Awesome thanks so much!
