### ISSUE TITLE
Raspberry PI support

### ISSUE THREAD

**Issue by ghost** [feross/webtorrent#171]
Has anyone had luck using this module with their Raspberry PI and omxplayer? I tried executing the following:

#### $ webtorrent --omx hdmi "magnet link"

It seems to start finding peers then terminates, however if I don't supply an output player it works as intended. Could it be a memory issue? I'm using Raspbian.

**Comment by corelgott** [comment]
Hi,

i've tried it with the R-Pi. Unfortunately the R-Pi[1,B,+] don't seem to have enough cpu-power to download the torrent and to stream it at the same time. I've also tried to split the streaming from the torrent download it self with no luck. I solved the problem by buying a R-Pi  v2. The new (March 2015) Quad-Code of the Pi is power full enough that even streaming 1080p and 3D is possible.

**Comment by feross** [comment]
Nice!

**Comment by zoudf** [comment]
@corelgott 
Hi Corelgott,
Did you success seed or download on R-Pi v2 ?  
You mention that you can use webtorrent to download via command line.
So you don't need WebRTC ? 

I tried install webtorrent-hybrid before, but meet the problem:
https://github.com/feross/webtorrent-hybrid/issues/2

**Comment by feross** [comment]
[`webtorrent-cli`](https://www.npmjs.com/package/webtorrent-cli) works fine on the raspberry pi!
