### ISSUE TITLE
Does webtorrent have any protection from greedy peers?

### ISSUE THREAD

**Issue by arestov** [feross/webtorrent#178]
consumes 50% of poccessor in tasks manager (wich means 100% of one core)
and here is why
![2014-11-09 11_46_56-developer tools - file____d___documents_seesu_index html](https://cloud.githubusercontent.com/assets/69734/4966924/4237f4ec-67ed-11e4-9004-6a1e272910e6.png)

**Comment by feross** [comment]
Closing out old issues. Feel free to comment or open a new issue if this still affects you.
