### ISSUE TITLE
Decentralized search

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#186]
I used this slide in my JSConf Asia 2014 talk today:

![screen shot 2014-11-21 at 11 52 00 am](https://cloud.githubusercontent.com/assets/121766/5137464/d971ec4c-7174-11e4-8298-fb5b0fba3f6b.png)

It would be awesome if we could crack the decentralized search problem.

cc @missinglink

**Comment by feross** [comment]
From the p2p-hackers mailing list:

> There's a really neat solution to this problem called Hyperspace Hashing which has you model your data in a set of different dimensions (i.e. a euclidian hyperspace), and locate a point within the hyperspace based on the hashes of the inputs. You then break the hyperspace down into a finite number of subspaces, and partition those among the available servers. The familiar hash ring can be seen as the one dimensional version of this concept.

> It doesn't quite fit the full text search scenario you described, but it does help expressing more powerful queries than just k/v lookup:

> http://www.cs.cornell.edu/people/egs/papers/hyperdex-sigcomm.pdf
> http://www.slideshare.net/DECK36/c36-hyperdexmeetupdec2013v2nogfx

> - Tony Arcieri

**Comment by urbien** [comment]
perhaps if we relax one requirement for a de-centralized search, like immediacy of answers, then we can solve the problem. Here is a sketch for an algorithm:

Take a look at the [decentralized search idea by Bill Gross (Idealab)](https://www.youtube.com/watch?v=9LMtyKU3G5Y). The essence of it is:
- index data on each machine/node, and keep index there
- broadcast a search query
- have users manually confirm the return of search results
Broadcast can be done using Ethereum's Whisper or equivalent DHT-based mechanism and can be optimized by each node publishing the topics that it allows searches for.
Manual confirmation for searches can be saved with user's permissions and can be used later without bring it to user's attention.

**Comment by niczy** [comment]
I was trying to build a chrome app to browse content with webtorrent (Each file is some content, with a collection of magnet links). So the user can navigate from one file to another.

But seems DHT is not supported in browser? which makes it not much different than traditional content serving from a server.

Any plan to support DHT in the browser?

Thanks!

**Comment by eklem** [comment]
What if Webtorrent had a built in version of [Norch](https://github.com/fergiemcdowall/norch/issues/51) ? Part of it is already browserified [search-index](https://github.com/fergiemcdowall/search-index).

**Comment by feross** [comment]
@niczy Even without DHT support in the browser, the content still gets delivered P2P which is very different than serving the content from a server.

**Comment by feross** [comment]
This is a cool topic, but out-of-scope for WebTorrent. Closing issue, but feel free to continue discussion.

**Comment by lmatteis** [comment]
Also, Tribler seems to have tackled this issue: http://dl.acm.org/citation.cfm?id=2072433

**Comment by lmatteis** [comment]
Another approach seems to use the blockchain to store magnet links: http://mercbay.com/#faq

**Comment by rom1504** [comment]
http://btdigg.org/about/ seems interesting on that topic, sadly it doesn't seem to be opensource

**Comment by anexit1** [comment]
This is off the wall but you could create a flowing side bar.  If we can stream video we could centrally snag info.  Basically a scrolling window where if someone see's something they like it will display the hash and the file name.  The webtorrent will come and go depending if the browser(s) are open or not.  Could certainly dump this info to a small text file and make hash's search able.

**Comment by mskogly** [comment]
A local index sounds good, but letting a user choose cwhich categories to "host", i.e to limit the local index to contenttypes of interrest.
