### ISSUE TITLE
WebTorrent (node & command line) should be a "hybrid client"

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#202]
From the readme:

> To make BitTorrent work over WebRTC (which is the only p2p transport that works on the web) we made some protocol changes. Therefore, a browser-based WebTorrent client can only connect to other clients that support WebTorrent (and WebRTC).

The `webtorrent` npm module should support WebRTC so when people use the command line `webtorrent` program or `require('webtorrent')` and torrent something, they will also swarm with web peers (i.e. web browsers).

**Comment by prodigel** [comment]
Hey there,

I've been testing the library and got encouraging results, but I've stumbled on this missing feature when trying to create a browser-independent seeder.

Saw your 'hope' in #239, was wondering if there's any news on it?

PS: Congrats on the project, really cool idea/implementation.

**Comment by sashahilton00** [comment]
Bumping this for TehShrike, as he is too polite to do so himself ;)

**Comment by feross** [comment]
I'm working on this right now.

There's actually quite a bit of code that needs to be refactored, since we were relying on browserify's ["browser" field](https://gist.github.com/defunctzombie/4339901) to replace TCP with WebRTC in the browser. Getting the node version of the app to support multiple types of peers is harder than it sounds, and will require changes to multiple webtorrent modules.

**Comment by fbodz** [comment]
Is there any way I can be of assistance @feross. "More hands the merrier"

**Comment by feross** [comment]
Good news everyone! As of v0.32.0, the `webtorrent` node client is a hybrid client! It can talk to normal BitTorrent peers, as well as web peers!

Please give it a shot!

First, seed a file from the the node command line (`webtorrent seed file.txt`), then go to https://instant.io and paste in the info hash. That's it!

Seeding to web peers works while you're downloading too (`webtorrent download magnet_uri`), as long as the magnet uri or .torrent file specifies a webtorrent tracker (`wss://tracker.webtorrent.io`).

The next step is to fix the remaining bugs that cause the streaming to stall, as well as fix the memory leaks preventing the browser from handling files over ~500MB. Please file bugs – or better yet, send PRs. I can't do this alone!

**Comment by iadj** [comment]
AWESOME @feross !!!!

**Comment by feross** [comment]
Thanks :-)

**Comment by fbodz** [comment]
@feross Great Work. But when i attempt to seed the file. I get Missing WebRTC support - was `wrtc` dependency installed?. Where am i supposed to install the module. Thanks

**Comment by iadj** [comment]
Same issue here, and when trying to install wrtc I get flooded with errors (most likely because I'm on Windows, and it appears wrtc has no Windows support).

**Comment by fbodz** [comment]
@ladj. To use wrtc on any other operating system you can just install it globally. Wrtc is under active development may be a while before windows support though.

**Comment by feross** [comment]
`wrtc` is an optional dependency. If it fails to install on your platform, the rest of the installation should continue just fine. In node, WebTorrent will function as a normal bittorrent client that **cannot** talk to web peers if the `wrtc` module is missing.
