### ISSUE TITLE
Memory leak through event listeners

### ISSUE THREAD

**Issue by arestov** [feross/webtorrent#207]
![2014-11-15 12_28_56-developer tools - file____d___documents_seesu_index html](https://cloud.githubusercontent.com/assets/69734/5448999/74155c90-8505-11e4-9dd4-afbf7cb99ce6.png)

After removing torrents it stay (relative objects) in memory.

To fix this we need to unsubscribe objects from events on destroying. Reemit module should provide a way to unsubscribe too.

**Comment by feross** [comment]
This is super old, closing.
