### ISSUE TITLE
Support http .torrent urls in browser

### ISSUE THREAD

**Issue by phambanhan** [feross/webtorrent#208]
I got error "Uncaught Error: invalid torrent id" with webtorrent in the browser (use webtorrent.min.js). This is my simple code:

var client = new WebTorrent();
var magnet_uri = '<redacted>';
client.download(magnet_uri, function (torrent) {
  console.log('Torrent info hash:', torrent.infoHash)
});

Please help me fix the error

Thanks

**Comment by Wingman4l7** [comment]
Unless I'm misunderstanding, CORS shouldn't be an issue if you're trying to make an XHR request to load a .torrent from the current domain, which you might be doing if you were using webtorrent as part of a browser extension.

**Comment by feross** [comment]
@Wingman4l7 You're right. Is this an important feature to you?

**Comment by Wingman4l7** [comment]
Definitely!  It's a crucial feature in using webtorrent as part of a browser extension.  Of course, so is webtorrent using TCP / UDP within the browser, which is currently only does in nodejs... but that's another problem.  :P

**Comment by feross** [comment]
Okay, PR welcome!
