### ISSUE TITLE
Automatic codec detection

### ISSUE THREAD

**Issue by jakefb** [feross/webtorrent#222]
Hi, I'm having a few issues streaming video in the browser with WebTorrent.

I encoded a MP4 video to MPEG-Dash with the command: MP4Box -dash 5000 -frag 5000 -rap video.mp4. I uploaded the video_dashinit.mp4 file to [instant.io](https://instant.io/) in Chrome. The torrent was created and an HTML5 <video> element appeared, but the video doesn't buffer.

It would be great to have a wiki page with instructions for streaming video with WebTorrent in the browser, as well as how to seed the video while it buffers if it's possible.

**Comment by jakefb** [comment]
If anyone finds it helpful, this is how I encoded the mp4 files before converting them to MPEG-DASH. Set the bitrate to what you want depending on the video resolution, or you can use -crf 18 (visually lossless) instead if -b:v 8000k. ./ffmpeg -i video.mp4 -c:v h264 -preset slow -c:a aac -strict -2 -b:v 8000k -b:a 384k fcvideos/yosemite.mp4

**Comment by feross** [comment]
@jakefb Thanks for sharing the command.

**Comment by feross** [comment]
Good news! @jhiesey has gotten automatic MP4 repackaging working! He's published it as a module: [`videostream`](https://npmjs.com/package/videostream) (highly work-in-progress).

It's currently being used on https://instant.io, which you'll be able to test when I get the site working again (sorry, broke it then went on a three-day sailing adventure with @dominictarr). Will try to get https://instant.io working again sometime today so you all can test it out!

cc @mafintosh @maxogden

**Comment by feross** [comment]
https://instant.io is working again.

**Comment by feross** [comment]
Automatic MP4 and M4A repackaging for playback in the `<video>` and `<audio>` tag has been working for a while, so I'm going to close this issue.

Take a look at https://instant.io to see it in action, and the source code is [here](https://github.com/feross/instant.io/blob/4513e0eb98ab31a2e8ae969bb0708cce5dbaff54/client/index.js#L155-L241).
