### ISSUE TITLE
command line: add `seed` command

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#231]
start seeding a file like this:

```bash
webtorrent seed /path/to/file.txt
```

**Comment by jakefb** [comment]
This would be great! Is there another way of seeding at the moment with cli?

**Comment by feross** [comment]
Currently there's no way to seed with the `webtorrent` command line program. That's what this issue is for :)

You can always use the `client.seed` API directly from a node.js script. Docs for it are here: https://github.com/feross/webtorrent#clientseedinput-opts-function-onseed-torrent-

**Comment by feross** [comment]
Okay, this is done now. Still only seeds to bittorrent nodes. I'll add seeding to web peers soon.

Released as 0.25.0.
