### ISSUE TITLE
Use native browser sha1 implementation when possible

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#234]
Most of the the browser's time is spent in `git-sha1` when creating a torrent. This is unsurprising, since the file must be split into pieces and hashed. But, this currently locks the entire browser for seconds.

Is the browser's native sha1 implementation faster? It's already shipped in Chrome and Firefox. See: http://caniuse.com/#feat=cryptography

- [x] Test that `crypto.subtle` is actually faster
- [x] Compare `Rusha` and current `git-sha` as fallback for insecure origins and older browsers
- [ ] File bug on Chrome and the spec to complain that `crypto.subtle` is only available on `https:` sites (https://instant.io is https, but other sites that use webtorrent might not be). Comment on this issue: https://code.google.com/p/chromium/issues/detail?id=373032

Related issue: https://github.com/feross/create-torrent/issues/4

**Comment by astro** [comment]
It looks like [simple-sha1](https://github.com/michaelrhodes/simple-sha1) has the right aims: to provide the fastest implementation available. crypto.subtle support should be implemented there.

**Comment by feross** [comment]
This is done now. Released as 0.22.0.

- `crypto.subtle` is actually faster
- `Rusha` is faster than `git-sha1`
- Will file bugs on chrome later
