### ISSUE TITLE
CLI doesn’t display any information

### ISSUE THREAD

**Issue by niksy** [feross/webtorrent#238]
When using WebTorrent as CLI app and specifying arguments in format `webtorrrent [magnet-uri] --mpv`, WebTorrent doesn’t display any useful information (peers, download status, download folder and such). Only when you exit the process via Ctrl+C you get the message "webtorrent is exiting...". File has started to download, so it seems like WebTorrent does it’s job, but you don’t have any sign of that other than visiting default `/tmp/webtorrent` directory.

Does this have something to do with `DEBUG` environment variable? Using [peerflix](https://github.com/mafintosh/peerflix) you get useful information by default which is useful when used inside command line.

**Comment by rom1504** [comment]
It works fine here. Maybe it has something to do with your os/terminal ?

**Comment by niksy** [comment]
Hm, nothing unsusal here, default Terminal app on OS X 10.10.1. My `DEBUG` variable has only one entry, `iectrl:*` so it could be that?

**Comment by astro** [comment]
`unset DEBUG` if you want the console interface: https://github.com/feross/webtorrent/blob/master/bin/cmd.js#L104
