### ISSUE TITLE
HTTP server for streaming video

### ISSUE THREAD

**Issue by jakefb** [feross/webtorrent#239]
Hi,

I'm trying to write a streaming HTTP server for node that integrates as a peer, with WebTorrent. I have got this far. I'm new to node.js by the way. Is it possible to use http as a web seed, without WebRTC? This would be great as a fallback.

```javascript
var http = require('http');
var fs = require('fs');
var createTorrent = require('create-torrent')
var WebTorrent = require('webtorrent')

client = new WebTorrent()

var files = 'video.mp4'

createTorrent(files, function (err, torrent) {
  if (!err) {
    // `torrent` is a Buffer with the contents of the new .torrent file
    fs.writeFile('video.torrent', torrent)

    client.add('video.torrent', function (torrent) {
			// Got torrent metadata!
			console.log('Torrent info hash:', torrent.infoHash)
		})
	}
})

http.createServer(function (req, res) {
	fs.createReadStream(files).pipe(res)
}).listen(1337, '127.0.0.1')
console.log('Server running at http://127.0.0.1:1337/')
```

**Comment by feross** [comment]
Hey @jakefb, both **web seeding** and **node.js support for web peers** are planned, but unimplemented:

- https://github.com/feross/webtorrent/issues/67 (web seeding)
- https://github.com/feross/webtorrent/issues/202 (node & command line should be a "hybrid client")

I'm hoping to get both done this month. You can follow the individual issues.
