### ISSUE TITLE
Reach out to libtorrent, libtransmission, Vuze, Deluge projects

### ISSUE THREAD

**Issue by iShift** [feross/webtorrent#241]
Webtorrent - cool project, but now project have Chicken and egg problem - people don't use them because traditional torrent clients don't support WebRTC torrent protocol. 

I think, that to solve that problem we need to add new protocol to libtorrent, after that - all main torrent client start work with webtorrent. 

(I talk about issue in libtorrent/tranmission/another_torrent_client_or_lib tracker) also we can help them with bounty program. 

What do you think about that?

**Comment by feross** [comment]
Yeah, I would love for `libtorrent` to support web peers. That would be huge! Then lots of other clients could really easily swarm with web peers.

Once the webtorrent hybrid client is in a bit better shape and the BEP is written up, the demo will be much more compelling and we should ask them about it.

**Comment by feross** [comment]
Now tracking this in https://github.com/feross/webtorrent/issues/241
