### ISSUE TITLE
npm fails to install

### ISSUE THREAD

**Issue by tienthanh8490** [feross/webtorrent#242]
Hi, i got error installing using npm. This is the npm debug log:

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@2.1.18
3 info using node@v0.10.32
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
6 info prebuild webtorrent@0.14.0
7 info build webtorrent@0.14.0
8 verbose unsafe-perm in lifecycle true
9 info webtorrent@0.14.0 Failed to exec build script
10 verbose stack Error: webtorrent@0.14.0 build: `browserify -s WebTorrent -e ./ | uglifyjs -c warnings=false -m > webtorrent.min.js`
10 verbose stack Exit status 127
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:212:16)
10 verbose stack     at EventEmitter.emit (events.js:98:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:98:17)
10 verbose stack     at maybeClose (child_process.js:756:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
11 verbose pkgid webtorrent@0.14.0
12 verbose cwd /Users/tnguyen/webtorrent
13 error Darwin 14.0.0
14 error argv "node" "/usr/local/bin/npm" "run" "build"
15 error node v0.10.32
16 error npm  v2.1.18
17 error code ELIFECYCLE
18 error webtorrent@0.14.0 build: `browserify -s WebTorrent -e ./ | uglifyjs -c warnings=false -m > webtorrent.min.js`
18 error Exit status 127
19 error Failed at the webtorrent@0.14.0 build script 'browserify -s WebTorrent -e ./ | uglifyjs -c warnings=false -m > webtorrent.min.js'.
19 error This is most likely a problem with the webtorrent package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     browserify -s WebTorrent -e ./ | uglifyjs -c warnings=false -m > webtorrent.min.js
19 error You can get their info via:
19 error     npm owner ls webtorrent
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by feross** [comment]
What npm command are you using to install webtorrent? It looks like a very old version (0.14.0) is getting installed. 0.25.0 is the latest release.

**Comment by tienthanh8490** [comment]
npm install webtorrent
How can i update the version to install then ?

**Comment by feross** [comment]
It looks like you're installing webtorrent locally, since you omitted `-g` (global). Try checking your `package.json` and see what version is specified there. You can install the latest and overwrite `package.json` with this:

```
webtorrent install@latest --save
```

**Comment by tienthanh8490** [comment]
Ok that command worked. Thanks for the prompt reply. Meanwhile maybe you can update README, since the installing section still say npm install webtorrent (without -g)
