### ISSUE TITLE
Streaming live video

### ISSUE THREAD

**Issue by Charuru** [feross/webtorrent#243]
Will live video from webcams be possible? Webrtc examples are already full of live video streaming, but I want to do broadcasting with webtorrent.

**Comment by Svenskunganka** [comment]
WebTorrent is an implementation of the BitTorrent protocol for Node and the browser, not a video streaming module. As BitTorrent isn't built to allow file changes to a file within a torrent after it has been created, this is not possible. You can't write a live video feed to a torrent.

You can probably achieve your goal by using parts of the WebRTC code behind WebTorrent, but you won't be able to do this using WebTorrent alone.

**Comment by Charuru** [comment]
The official bittorrent company had a streaming video site. It should just be a question of changing the protocol to support streaming needs, eg low latency, sending things in order, editing torrents. But that sounds like it's out of the scope of this project?

**Comment by astro** [comment]
You could try implementing http://datatracker.ietf.org/doc/draft-ietf-ppsp-peer-protocol/ -- I'd review and help!

**Comment by bradisbell** [comment]
I've often wondered if HLS-style segmenting of streams would allow for streaming over the existing BitTorrent client.  Is it possible to create a torrent with segment, followed by a pointer to the next torrent, even if that next torrent hasn't been created yet?  I don't know much about the BitTorrent protocol itself.  If there was some way to reference the next torrent in the stream, then the same segmentation that allows for HLS could enable BitTorrent streaming to work, complete with multiple bitrate streams.

**Comment by feross** [comment]
Live streaming video is a cool idea, but out-of-scope for this module. Could be built on top of it though :P

**Comment by ernado** [comment]
Webrtc DataChannels + Media Source Extensions can make it possible. 
But not serverless, because we need to convert Webrtc video stream to chunks that MSE can consume.

**Comment by feross** [comment]
Actually - have you seen https://github.com/gpac/mp4box.js/ ? You can do the conversion for MSE in the browser! That's what https://instant.io currently does.

**Comment by alamcordeiro** [comment]
See this project http://bem.tv/

**Comment by hbakhtiyor** [comment]
also checkout the project https://livepeer.org/

**Comment by voronoipotato** [comment]
those projects are interesting but aren't free. More interestingly is something like nile.js which is actually using webtorrent to achieve the aforementioned goal by cutting up the video into segments as was described earlier in the thread.
