### ISSUE TITLE
Peer coming from DHT for specific torrent?

### ISSUE THREAD

**Issue by FLYBYME** [feross/webtorrent#256]
How do  you know if the torrent that is coming from DHT is for the right torrent?

dht emits peers for any infoHash but torrent.js is not looking if the peer is for this torrent.
https://github.com/feross/webtorrent/blob/master/lib/torrent.js#L190

**Comment by feross** [comment]
You are correct. This was a bug! I just patched `torrent-discovery` to only emit peers for the `infoHash` that is passed to `discovery.setTorrent`. See: https://github.com/feross/torrent-discovery/commit/bb9e379efc7d5857e1dbb42a602fa3eef944afd6

Thanks for reporting!

**Comment by feross** [comment]
And a matching test case: https://github.com/feross/torrent-discovery/commit/18bfda36019d5f750f38faa36574a7ac0a86016a
