### ISSUE TITLE
Error when browserify

### ISSUE THREAD

**Issue by nezzard** [feross/webtorrent#258]
Good evening, I'm sorry for my english. After executing the commands "browserify app2.js -o bundler.js" I get the error "C: \ Users \ Yura \ node_modules \ webtorrent \ node_modules \ browserify-versionify \ node_modules \ find-root \ index.js: 13
     throw new Error ('package.json not found in path') "

**Comment by fbodz** [comment]
Go into the directory containing the app and run npm init.

**Comment by feross** [comment]
@nezzard Can you share your project folder structure?

**Comment by feross** [comment]
Closing because of lack of new info.
