### ISSUE TITLE
Webtorrent extention for Libtorrent with python

### ISSUE THREAD

**Issue by vkefallinos** [feross/webtorrent#259]
I want to add webtorrent extention to rasterbar libtorrent. I couldn't find any instructions to create a generic webtorrent  extention. 
I am thinking something like proxying and modifying webrtc requests to fool libtorrent and treat them as normal connections. This way it could interoperate. Node is not good for really low end hardware like raspberry pi 1. 
Can you help? Or resources would help too..
Great Work by the way...!!
Thanks

**Comment by feross** [comment]
@vkefallinos Thanks for opening this issue. As soon as I have the time, I'll write up a BEP to explain the changes needed to support WebTorrent. There aren't many. You can have a look at the [`bittorrent-tracker`](https://npmjs.com/package/bittorrent-tracker) module in the meantime to see how websocket trackers work.

See: https://github.com/feross/webtorrent/issues/168

**Comment by onny** [comment]
Sorry for posting in this old and closed issue @feross but I have a small question regarding webtorrent and python.
I have this small test python script here https://git.project-insanity.org/snippets/22 which should connect to a websocket tracker and ask for peers. I always get the response, that my infohash is wrong.
I'm not sure how to do this hex to binary encoding etc., especially in Python. Do you have any clue?
Thank you,
Jonas

**Comment by Zer0C001** [comment]
@onny : You need to use unhexlify and json: 
import json,binascii
.....
after pl = '{"numwant":10 ... : 

pl=json.loads(pl)
pl['info_hash']=binascii.unhexlify(infohash).decode('unicode-escape')
pl=json.dumps(pl)


result: 
$ python3 pywbt2.py 
> {"numwant": 10, "uploaded": 0, "downloaded": 0, "left": "null", "event": "started", "action": "announce", "info_hash": "\b\u00ad\u00a5\u00a7\u00a6\u0018:\u00ae\u001e\t\u00d81\u00dfgH\u00d5f\tZ\u0010", "peer_id": "-WW0098-CR5i5FXgxCXl"}
< {"complete":13,"incomplete":1,"action":"announce","interval":120,"info_hash":"\b­¥§¦\u0018:®\u001e\tØ1ßgHÕf\tZ\u0010"}

Without the double json conversion you get "Unexpected token" errors.
