### ISSUE TITLE
Streaming video

### ISSUE THREAD

**Issue by fbodz** [feross/webtorrent#261]
I get the following error on instant.io and in my own code when i attempt to stream video: Uncaught InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source. Thanks.

**Comment by nextgenthemes** [comment]
is this a tut on how not to write a bug report?

**Comment by achernar** [comment]
use a diferent video container/codec

**Comment by jakefb** [comment]
You might find this related issue helpful: https://github.com/feross/webtorrent/issues/222

**Comment by fbodz** [comment]
Yes it is a tutorial. On how to write the best bug report ever

**Comment by feross** [comment]
As @jakefb stated, see issue https://github.com/feross/webtorrent/issues/222. :)
