### ISSUE TITLE
Explain what the bars mean in the CLI interface

### ISSUE THREAD

**Issue by adammw** [feross/webtorrent#264]
I'm trying to understand what the bars mean in the CLI interface, but there's nothing in the README. A screenshot and explanation in the README would help a lot here.

**Comment by feross** [comment]
The bars show which pieces and blocks the client is requesting.

Each bar is labeled with the piece number. Each piece is made up of 16KB blocks, labeled red for missing, blue for requested, and green for received.

The bars should probably be disabled by default (I just made an issue for that: https://github.com/feross/webtorrent/issues/296). They're a bit overkill for most casual users, but useful when trying to debug issues.
