### ISSUE TITLE
File more than 15MB  seems not downloading o working

### ISSUE THREAD

**Issue by samihaq** [feross/webtorrent#265]
First of all "webtorrent " is amazing and believe it's a feature of torrent and P2P streaming
I was testing by using your website instant.io , I found that if file size is 15MB or more it wont create a P2P, means it won't work.
Is there a limitation of file-size and same with video , it shows it create the hash but nothing after that nothing?
I'm using Windows 7 with FF 35.01 and Chrome 40.0.2214.111m
Thank you

**Comment by feross** [comment]
I can't reproduce this, sorry. I just tested and a P2P connection is always established for me. File size doesn't matter until you start to get into the ~500MB range and then the browser sometimes crashes, but that's a different issue.
