### ISSUE TITLE
Specify tracker at seeding

### ISSUE THREAD

**Issue by zxvfbg** [feross/webtorrent#268]
Is it possible to specify specific tracker when we use seed method ?

Thank you

**Comment by feross** [comment]
Yep, you can pass in any valid [`create-torrent`](https://github.com/feross/create-torrent) options, as it says in the [readme](https://github.com/feross/webtorrent#clientseedinput-opts-function-onseed-torrent-).

Just use the `announce` option.

```js
client.seed(files, {
  announce: [ 'udp://tracker.publicbt.com:80', 'udp://tracker.openbittorrent.com:80' ]
}, onTorrent)
```

Or, you can prioritize the trackers in "tiers" with the `announceList` option. See [the spec](http://www.bittorrent.org/beps/bep_0012.html) for more details.

```js
client.seed(files, {
  announceList: [
    [ 'udp://tracker.publicbt.com:80', 'udp://tracker.openbittorrent.com:80' ],
    [ 'tier2' ],
    [ 'tier3 first', 'tier3 second' ]
  ]
}, onTorrent)
```

If you omit this option entirely, then some default trackers will be selected, as specified, in the `create-torrent` readme.

**Comment by zxvfbg** [comment]
And how we can seed to wss tracker ?

**Comment by feross** [comment]
That's not supported yet, sorry. See: https://github.com/feross/webtorrent/issues/202
