### ISSUE TITLE
dragdrop/buffer

### ISSUE THREAD

**Issue by jman6495** [feross/webtorrent#269]
Hey,

I'm having an issue wirh browserify'ing my project.
It's just a demo, I reused the demo code for seeding a torrent.
Browserify refuses to create my bundle citing that drag-drop/buffer does not exist, it cannot be installed by npm. Am I really misunderstanding something here ?

Thanks for any help

-jman6495

**Comment by raptats** [comment]
based on feross's other project -- https://github.com/feross/drag-drop..installation should be npm install drag-drop..

**Comment by jman6495** [comment]
Cheers ! That's fixed it :)

**Comment by feross** [comment]
Thanks for helping @raptats :)
