### ISSUE TITLE
Blank bundle.js

### ISSUE THREAD

**Issue by raptats** [feross/webtorrent#270]
I tried to compile the demos on the source code but when I go to cmd to browserify the js file, it returns with an error saying that a module is missing but completes the bundling with a blank bundle.js.. Could someone help me with resolving this matter? Thanks!

**Comment by feross** [comment]
Which module does it say is missing? Please paste the error message you're getting, the browserify command you're running, and your code.

**Comment by raptats** [comment]
I apologise for the long post in advance. I included all I input in the cmd just in case I overlooked something.


C:\Users\>cd Downloads\webtorrent-master\webtorrent-master\examples

C:\Users\\Downloads\webtorrent-master\webtorrent-master\examples>npm install -g browserify
C:\Users\\AppData\Roaming\npm\browserify -> C:\Users\\AppData\Roaming\npm\node_modules\browserify\bin\cmd.js
browserify@8.1.3 C:\Users\\AppData\Roaming\npm\node_modules\browserify
├── https-browserify@0.0.0
├── os-browserify@0.1.2
├── tty-browserify@0.0.0
├── inherits@2.0.1
├── builtins@0.0.7
├── constants-browserify@0.0.1
├── commondir@0.0.1
├── process@0.10.0
├── path-browserify@0.0.0
├── string_decoder@0.10.31
├── isarray@0.0.1
├── stream-browserify@1.0.0
├── defined@0.0.0
├── shell-quote@0.0.1
├── domain-browser@1.1.4
├── shallow-copy@0.0.1
├── xtend@3.0.0
├── deep-equal@0.2.2
├── querystring-es3@0.2.1
├── assert@1.3.0
├── timers-browserify@1.3.0
├── punycode@1.2.4
├── util@0.10.3
├── parents@1.0.1 (path-platform@0.11.15)
├── events@1.0.2
├── vm-browserify@0.0.4 (indexof@0.0.1)
├── console-browserify@1.1.0 (date-now@0.1.4)
├── url@0.10.2 (punycode@1.3.2)
├── subarg@1.0.0 (minimist@1.1.0)
├── deps-sort@1.3.5 (through2@0.5.1, minimist@0.2.0)
├── http-browserify@1.7.0 (Base64@0.2.1)
├── readable-stream@1.0.33 (core-util-is@1.0.1)
├── shasum@1.0.1 (sha.js@2.3.6, json-stable-stringify@0.0.1)
├── through2@1.1.1 (xtend@4.0.0, readable-stream@1.1.13)
├── duplexer2@0.0.2 (readable-stream@1.1.13)
├── resolve@0.7.4
├── concat-stream@1.4.7 (typedarray@0.0.6, readable-stream@1.1.13)
├── buffer@3.0.2 (ieee754@1.1.4, is-array@1.0.1, base64-js@0.0.8)
├── labeled-stream-splicer@1.0.2 (stream-splicer@1.3.1)
├── glob@4.4.0 (once@1.3.1, inflight@1.0.4, minimatch@2.0.1)
├── JSONStream@0.8.4 (through@2.3.6, jsonparse@0.0.5)
├── browser-resolve@1.7.0 (resolve@1.1.0)
├── browser-pack@3.2.0 (through2@0.5.1, combine-source-map@0.3.0)
├── crypto-browserify@3.9.12 (randombytes@2.0.1, create-hmac@1.1.3, pbkdf2-compa
t@3.0.2, create-hash@1.1.0, diffie-hellman@3.0.1, browserify-aes@1.0.0, create-e
cdh@1.0.3, browserify-sign@2.8.0, public-encrypt@1.1.2)
├── umd@2.1.0 (through@2.3.6, rfile@1.0.0, uglify-js@2.4.16, ruglify@1.0.0)
├── syntax-error@1.1.2 (acorn@0.9.0)
├── insert-module-globals@6.2.0 (process@0.6.0, through@2.3.6, JSONStream@0.7.4,
 combine-source-map@0.3.0, lexical-scope@1.1.0)
├── browserify-zlib@0.1.4 (pako@0.2.5)
└── module-deps@3.7.1 (minimist@0.2.0, stream-combiner2@1.0.2, subarg@0.0.1, res
olve@1.1.3, through2@0.4.2, JSONStream@0.7.4, detective@4.0.0)

C:\Users\\Downloads\webtorrent-master\webtorrent-master\examples>npm install drag-drop
drag-drop@2.0.0 ..\node_modules\drag-drop
├── run-parallel@1.0.0
├── blob-to-buffer@1.2.0 (typedarray-to-buffer@3.0.1)
└── lodash.throttle@2.4.1 (lodash.isfunction@2.4.1, lodash.isobject@2.4.1, lodas
h.debounce@2.4.1)

C:\Users\\Downloads\webtorrent-master\webtorrent-master\examples>npm install webtorrent
npm WARN install Refusing to install webtorrent as a dependency of itself

C:\Users\\Downloads\webtorrent-master\webtorrent-master\examples>browserify
 browser-seed.js -o bundle.js
**Error: Cannot find module 'browserify-versionify' from 'C:\Users\\Downloads
\webtorrent-master\webtorrent-master'**
    at C:\Users\\AppData\Roaming\npm\node_modules\browserify\node_modules\m
odule-deps\node_modules\resolve\lib\async.js:46:17
    at process (C:\Users\\AppData\Roaming\npm\node_modules\browserify\node_
modules\module-deps\node_modules\resolve\lib\async.js:171:43)
    at C:\Users\\AppData\Roaming\npm\node_modules\browserify\node_modules\m
odule-deps\node_modules\resolve\lib\async.js:180:21
    at load (C:\Users\\AppData\Roaming\npm\node_modules\browserify\node_mod
ules\module-deps\node_modules\resolve\lib\async.js:69:43)
    at C:\Users\\AppData\Roaming\npm\node_modules\browserify\node_modules\m
odule-deps\node_modules\resolve\lib\async.js:74:33
    at C:\Users\\AppData\Roaming\npm\node_modules\browserify\node_modules\m
odule-deps\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:99:15)

I browserified the example *browser-seed.js* so then I can include it to my html file but the bundle.js is empty. I am under the impression that bundle.js should contain the require calls for the project. Thanks for your help

**Comment by raptats** [comment]
I have just resolved this error with having **npm init** and installing *browserify-versionify* on npm. Thanks for looking into it. Cheers!
