### ISSUE TITLE
Respect the "private" flag in .torrent files

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#271]
When torrents are marked "private", they should not announce to any source but the tracker (i.e. no DHT, no peer exchange).

**Comment by rom1504** [comment]
What about https://github.com/feross/webtorrent-app/blob/c176e3897ac70d55acd099a4f15464fb85e79ed7/renderer/index.js#L34 and https://github.com/feross/instant.io/blob/c8924fe4cea665c938911edf5b7efaa2c4b1e9ab/client/index.js#L15 @feross ?
It sounds like it makes all torrent (even ones which are private) use the default tracker list in instant.io and webtorrent-app.

**Comment by rom1504** [comment]
Maybe webtorrent-app and instant.io should check for the private flag before adding these trackers.

**Comment by feross** [comment]
@rom1504 You're correct. Fixed this directly in `webtorrent`. Released as 0.84.0.
