### ISSUE TITLE
Can't run video streaming example with standalone webtorrent.min.js

### ISSUE THREAD

**Issue by ddctd143** [feross/webtorrent#275]
Trying to run example from main page

```
        <script src="webtorrent.min.js"></script>
        <script>
            var client = new WebTorrent();
            var magnetUri = 'magnet:?......';

            client.add(magnetUri, function (torrent) {
                var file = torrent.files[0];
                var video = document.createElement('video');
                video.controls = true;
                document.body.appendChild(video);
                file.createReadStream().pipe(video);
            });

            console.log(client);
            console.log(client.torrents[0].infoHash);
            console.log(client.torrents[0].files);
      </script>
```

Tried different magnet uri's but console.log(client.torrents[0].files);  always returns empty array.
```
files []
```
I can get info hash from console.log and it shows all data, but files array is always empty and because of that video element isn't created

But i can open magnet uri and stream to vlc player from console using webtorrent download "magnet:?......" --vlc 

Why browser code with webtorrent.min.js does not see any files in torrent files to stream ?

**Comment by feross** [comment]
You can't just paste in any random magnet uri or .torrent file!

In the browser, WebTorrent can only download torrents that are explicitly seeded to the WebTorrent network. Desktop torrent clients need to support WebRTC to peer with web browsers. Currently, no clients support it but you can use http://instant.io/ to seed torrents to the WebTorrent network.

**Comment by feross** [comment]
This question has been asked about a dozen times already, so I'm starting an FAQ: https://github.com/feross/webtorrent/wiki/FAQ
