### ISSUE TITLE
Resumable downloads (using partial files)

### ISSUE THREAD

**Issue by corysimmons** [feross/webtorrent#276]
For instance, if I'm torrenting something and close my terminal, can I reopen it and resume a download?

Didn't grep it in README.

**Comment by feross** [comment]
No way to do this right now. PR welcome!

**Comment by corysimmons** [comment]
Aww...

Is there even a way to perform any events right before someone exits a program in Node?

**Comment by corysimmons** [comment]
Without actually reading any of this or knowing what any of it does...

http://stackoverflow.com/a/14032965/175825 > https://nodejs.org/api/stream.html#stream_readable_pause

On WebTorrent open: https://nodejs.org/api/stream.html#stream_readable_resume

**Comment by feross** [comment]
Duplicate of #320
