### ISSUE TITLE
avoid using node.js

### ISSUE THREAD

**Issue by charlsagente** [feross/webtorrent#279]
Hi guys i apologize for the previous issue. 
Im trying to use only webtorrent without using node.js. I installed your webtorrent.min.js in my apache server and used in the following example. 

But the next code does nothing. What am i doing wrong?
node.js is necessary? or just the browser? 
```
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
      <script src="webtorrent.min.js"></script>
</head>
<body>
 <script>
 var client = new WebTorrent()
var magnetUri = '...'  //copied directly from a torrent

client.add(magnetUri, { tmp: 'C:\Users\lenovo\Downloads' },function (torrent) {
  // Got torrent metadata!
  console.log('Torrent info hash:', torrent.infoHash)

  torrent.files.forEach(function (file) {
    // Get a url for each file
    file.getBlobURL(function (err, url) {
      if (err) throw err

      // Add a link to the page
      var a = document.createElement('a')
      a.download = file.name
      a.href = url
      a.textContent = 'Download ' + file.name
      document.body.appendChild(a)
    })
  })
})
 </script>
 
 
</body>
</html>
```

**Comment by feross** [comment]
WebTorrent work in the browser without node.js! But you can't just paste in any random magnet uri or .torrent file.

In the browser, WebTorrent can only download torrents that are explicitly seeded to the WebTorrent network. Desktop torrent clients need to support WebRTC to peer with web browsers. Currently, no clients support it but you can use http://instant.io/ to seed torrents to the WebTorrent network.
