### ISSUE TITLE
Uglify compression causes "invalid asm.js warning"

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#281]
WebTorrent uses [`simple-sha1`](https://www.npmjs.com/package/simple-sha1) to create SHA1 hashes. `simple-sha1` prefers the WebCrypto API but falls back to [`rusha`](https://www.npmjs.com/package/rusha) (an asm.js SHA1 implementation) when WebCrypto is unavailable.

When building `webtorrent.min.js`, we compress and minify the code to save bytes, but the compression changes the rusha code in a way that makes it invalid asm.js.

https://github.com/srijs/rusha/issues/27#issuecomment-79708384
https://github.com/mishoo/UglifyJS2/issues/167

Until the issue is fixed in uglify, we need to disable compression (i.e. change `uglifyjs -c warnings=false -m` to `uglifyjs -m`), increasing the gzipped file size from 45.7 kb to 46.5 kb - which is actually pretty negligible.

**Comment by norzak** [comment]
I am getting following warning on Chrome using latest webtorrent in an iframe.

Invalid asm.js: Expected function name

Is this related to this?

**Comment by norzak** [comment]
Firefox gives a similar error

TypeError: asm.js type error: initializer of exported object literal must be name of function
