### ISSUE TITLE
let Client.remove use magnet url 

### ISSUE THREAD

**Issue by sammuel86** [feross/webtorrent#287]
Client.remove only seems to work with a infohash at the moment would be great to be able to just throw a magnet url and have it remove it aswell.

**Comment by feross** [comment]
What makes you think that `client.remove` is not working? What behavior are you seeing?

I just added tests for `client.remove` (including with a magnet uri) in https://github.com/feross/webtorrent/commit/020ffa3c70244684a45ae7386c52447ae237b8ca and it appears to work correctly.

**Comment by feross** [comment]
Closing because I think this is working as expected.

@sammuel86 if you think this is still broken, just comment with more info and I'll reopen.
