### ISSUE TITLE
Crazy RAM usage when downloading

### ISSUE THREAD

**Issue by sammuel86** [feross/webtorrent#289]
when downloading a 2.2 gig file and using webtorrents torrent.server() api RAM usage goes from 24mb to over 500 after a few minutes.

I'm not sure whats causing this or if a buffer can be implemented to help reduce the ram usage?

My code looks like this:

    client.add(magnetURL, {
                verify: true
            }, function(torrent) {
                var server = torrent.createServer();
                server.listen(2710);
    });

**Comment by sammuel86** [comment]
https://github.com/feross/webtorrent/issues/248
https://github.com/feross/webtorrent/issues/207

**Comment by feross** [comment]
Duplicate of #248. This is high priority - will look at this soon.
