### ISSUE TITLE
Build a website (webtorrent.io)

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#29]
WebTorrent needs a website. Something simple and clean like the [NodeOS](http://node-os.com) site.

- What is webtorrent
- What are we building
- How to try it out, getting started
- Subscribe for updates (email list)
- Blog (for project updates)
- Documentation for all the webtorrent node modules

**Comment by feross** [comment]
We'll track progress for this here: https://github.com/feross/webtorrent-website

**Comment by feross** [comment]
A basic website is live at https://webtorrent.io now. It was designed by @sashahilton00 - thanks!

Help needed! If you're looking a way to get involved with WebTorrent, please help improve the website.

**Comment by feross** [comment]
Folks who send good PRs to the website will get commit access! The site automatically deploys whenever there are new commits.

The repo is here: https://github.com/feross/webtorrent-www

**Comment by sashahilton00** [comment]
@feross, sorry I didn't manage to get any further, life got busy. i will try to add some more to it in the future, but for now the framework to easily add content is there :)

**Comment by feross** [comment]
@sashahilton00 No problem! It's a great design and I really appreciate the work you put into it. I'm going to add a few new pages to it, but still looking for PRs to make it even better!

This will really help with WebTorrent adoption!

**Comment by feross** [comment]
@sashahilton00 I just gave you the commit bit on the webtorrent-www repo!
