### ISSUE TITLE
browser-download.js example not working / Can't start download in browser

### ISSUE THREAD

**Issue by fpinzn** [feross/webtorrent#292]
When used as is, the following warning is thrown:

```
Warning: must specify a tracker server to discover peers (required in browser because DHT is not implemented yet) (you can use wss://tracker.webtorrent.io)
```

When the tracker is appended to the url like `magnet:?xt=urn:btih:d2474e86c95b19b8bcfdb92bc12c9d44667cfa36&tr=wss://tracker.webtorrent.io` the execution never reaches the add callback.

Here's a plunkr: http://plnkr.co/ey0bp4

Neither does it work in node.

I guess the magnet uri used not longer works. When its changed for a torrent file uri works like a charm in node. In the browser throws an `Invalid torrent Identifier` error

Like in here: http://plnkr.co/edit/6Jr7qH?

**Comment by fbodz** [comment]
You must be explicitly seeding the file using webrtc. You are able to seed a file on http://instant.io and then download using your provided script with the correct infohash.

**Comment by fpinzn** [comment]
Even when seeding explicitly, the code doesn't reach the torrent metadata callback. This doesn't happen when running in node.

**Comment by feross** [comment]
I'm in the middle of refactoring `bittorrent-tracker` to support discovery of WebTorrent peers, and deployed to `tracker.webtorrent.io` and accidentally broke things. Working on fixing that today :)

**Comment by fpinzn** [comment]
:ok_hand:

**Comment by feross** [comment]
Okay, https://instant.io is working again!
