### ISSUE TITLE
Error when torrentId is http/https url or filesystem path to a torrent file

### ISSUE THREAD

**Issue by green13** [feross/webtorrent#295]
Parse-torrent throws error "Invalid torrent identifier" when torrentId is http/https url or filesystem path to a torrent file (string). 

webtorrent version 0.30.0

```
var client = new WebTorrent();
var torrent = client.add(torrentId); // error
```

**Comment by feross** [comment]
I cannot reproduce this. We also have tests that verify this is working, so this sounds like a bug . Can you post the http url you are trying to use? (Note: please do not share links to copyrighted content.)

Are you running this in node or the browser? Both http/https and filesystem urls are only supported in node.

**Comment by green13** [comment]
I mistaked, client.get throws error, not client.add. client.get has parameter [torrentid](https://github.com/feross/webtorrent#clientgettorrentid) and returns null earlier. This confused me.
I'm running in node.
