### ISSUE TITLE
'webtorrent seed' doesn't work on Windows ('wrtc' dependency doesn't support Windows)

### ISSUE THREAD

**Issue by iadj** [feross/webtorrent#297]
With the 'wrtc' dependency, there's no longer support for running 'webtorrent seed' on Windows as wrtc doesn't have Windows support: https://github.com/js-platform/node-webrtc/issues/42

**Comment by feross** [comment]
@iadj Thanks for reporting. What's the behavior that you're seeing? Does webtorrent throw an error or just fail to seed to web peers?

**Comment by feross** [comment]
I just released a change in `bittorrent-tracker` 3.4.3 that prevents crashing when the `wrtc` optional dependency is missing.

@iadj Can you confirm that `webtorrent seed` now works on Windows?

**Comment by iadj** [comment]
Yes, it's working fine now! Good job @feross.

**Comment by iadj** [comment]
@feross, is the wrtc dependency currently active for any certain Webtorrent feature? In case I find other issues while testing on Windows.

**Comment by feross** [comment]
`wrtc` is needed to connect to web peers. It's used by `webtorrent seed` and `webtorrent download`.
