### ISSUE TITLE
What's wrong? Add torrent with hash.

### ISSUE THREAD

**Issue by brunocascio** [feross/webtorrent#299]
Hi guys!

I try to add a torrent using hash:

```
var torrentHash = "...";

 client.add(torrentHash, function(torrent){
      console.log(torrent)
});
```

But console.log don't execute nothing. 

I see on the net the petition is pending but does nothing more.

![captura de pantalla de 2015-04-19 19 55 01](https://cloud.githubusercontent.com/assets/2397875/7221727/fd6e2678-e6cd-11e4-9f23-f2aebb86fc01.png)

help?

**Comment by fbodz** [comment]
The torrent must be explicitly seeded either using the hybrid client or online using HTTPS://instant.io. This issue has been raised multiple times and is discussed in the readme.

**Comment by brunocascio** [comment]
Well... My code:

```
client.add("magnet:?xt=urn:btih:390C83FC95B05A4259C0BF1DB95DBFCB4E08D85E", 
		function(torrent){
		    // Got torrent metadata!
		    console.log('Torrent info hash:', torrent.infoHash)
		}
	);
```

But callback never execute. 

With localStorage.debug = '*'

Print this output:

![captura de pantalla de 2015-04-20 20 09 50](https://cloud.githubusercontent.com/assets/2397875/7242490/51251c38-e799-11e4-87bb-f4e35b588452.png)
![captura de pantalla de 2015-04-20 20 10 07](https://cloud.githubusercontent.com/assets/2397875/7242491/512e6a36-e799-11e4-9994-1548dcfe47ec.png)
![captura de pantalla de 2015-04-20 20 10 21](https://cloud.githubusercontent.com/assets/2397875/7242492/512faa72-e799-11e4-9727-17f7ba8f67e7.png)
