### ISSUE TITLE
Seeding a file from the local filesystem using Atom Electron (Including Windows)

### ISSUE THREAD

**Issue by iadj** [feross/webtorrent#305]
I read @feross is working on optimizing Webtorrent's Atom Electron support, so I've been playing around with some features to see to what points I can use the features until I run into issues.

An important concept for WebTorrent that becomes available with Electron, is node's file system. The ability to seed a file directly from the file system.

I've been trying to access a file from the local filesystem by entering the file's path as a string into the client.seed function.
Example:
```
client.seed('L:/image.jpg', function onTorrent (torrent) {
      // Client is seeding the file!
      console.log('Torrent info hash: ' + torrent.infoHash)
 })
```
On Windows it appears the Torrent hash appears after some time, but the hash remains unable to seed it to a WebRTC client (probably because there's no wrtc package support for Windows. I haven't tested this on Linux yet).

I also tried to browserify the code, which results in filesystem functions not being recognized as functions (ie: 'fs.readdir is not a function').

Possible solutions to get Webtorrent + Electron + filesystem working cross-platform would be:
Node WebRTC support for Windows (Seems to be the best solution. This also appears to be under active development: https://github.com/js-platform/node-webrtc/issues/42)
Get filesystem to work in browserify bundle.js files when ran in Electron (I feel like this may already be possible with something like brfs, but haven't been able to figure this out yet).

**Comment by rom1504** [comment]
same as https://github.com/feross/webtorrent/issues/304#issuecomment-198750669 (also see https://github.com/feross/webtorrent-hybrid which now uses electron)

This can probably be closed.

**Comment by feross** [comment]
Yep, this can be closed. WebTorrent works in Electron just fine. See: https://github.com/feross/webtorrent-app
