### ISSUE TITLE
Make a logo

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#308]
WebTorrent needs a logo! Here's a logo that @dcposch and I brainstormed a while ago:

![screen shot 2015-05-07 at 4 04 14 pm](https://cloud.githubusercontent.com/assets/121766/7527663/c42086d2-f4d2-11e4-8507-79604504edb1.png)

But this is just one idea. I wanted to open the logo design up to the whole community! If you have an idea for a logo design, or just have awesome editing skills, please take a shot and coming up with a logo for the project!

After a while, we can pick one (or multiple!) to use on the website and stickers (https://github.com/feross/webtorrent/issues/309)!

**Comment by feross** [comment]
Of course, there's also the bubble letters we've been using in the readme:

![wordmark](https://raw.githubusercontent.com/feross/webtorrent/master/img/wordmark.png)

And this image in the readme that came from the noun project:

![network](https://raw.githubusercontent.com/feross/webtorrent/master/img/logo.png)

**Comment by pieper** [comment]
I've always liked that one - I'd like a sticker  : )

**Comment by feross** [comment]
@pieper Which one have you always liked?

**Comment by pieper** [comment]
The one that's labeled as coming from the noun project.  Is it an option just to keep that as the logo?

**Comment by feross** [comment]
Maybe, but I think we can probably come up with something even better!

**Comment by EgyptionBoy** [comment]
I like this idea , may be someone do some enhancement
![Image of Spider](http://th02.deviantart.net/fs8/200H/i/2005/312/f/0/Web_winged_Heart_by_Flesh_Etched_Heart.jpg)

**Comment by feross** [comment]
@EgyptionBoy Nice! Reminds me of the art style of [Kingdom Hearts](https://www.google.com/search?q=kingdom+hearts&es_sm=91&source=lnms&tbm=isch&sa=X&ei=N8dTVY6aD5ProAS22YGIBA&ved=0CAgQ_AUoAg&biw=1436&bih=805&dpr=2), one of my favorite childhood video games.

**Comment by cadesalaberry** [comment]
Ahah, thanks for the link @feross, good memories :smile:                                                                                                                                                                                                                                                                                                                                                     From: Feross AboukhadijehSent: mercredi 13 mai 2015 17:51To: feross/webtorrentReply To: feross/webtorrentSubject: Re: [webtorrent] Make a logo (#308)@EgyptionBoy Nice! Reminds me of the art style of Kingdom Hearts, one of my favorite childhood video games.

—Reply to this email directly or view it on GitHub.

**Comment by EgyptionBoy** [comment]
I will try at weekend play with some ideas and share with you,

**Comment by eliooses** [comment]
I will make a proposal brand in a few days in appreciation of this excellent project.

**Comment by rom1504** [comment]
isn't this done ?

**Comment by DiegoRBaquero** [comment]
I think is done. Can be closed

**Comment by dcposch** [comment]
![webtorrent](https://cloud.githubusercontent.com/assets/169280/14481008/73c4d74c-00e3-11e6-9315-6d2e8a6304ac.png)
