### ISSUE TITLE
Make WebTorrent stickers

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#309]
@maxogden said this is a good site to order stickers: https://www.stickermule.com/products/die-cut-stickers

Once we have a WebTorrent logo (https://github.com/feross/webtorrent/issues/308), I'm happy to order a batch and send a bunch out to whoever wants them!

**Comment by maxogden** [comment]
i can also recommend https://hexi.pics/

**Comment by feross** [comment]
Moved to a fresh new issue: https://github.com/feross/webtorrent/issues/586
