### ISSUE TITLE
Send "stop" to trackers during shutdown

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#313]
The tracker protocol (and [bittorrent-tracker](https://github.com/feross/bittorrent-tracker)) has a method to tell the tracker that a client is leaving the swarm, so the tracker can remove it's "ip:port" from the list of clients.

From the bittorrent-tracker API:

```
// stop getting peers from the tracker, gracefully leave the swarm
client.stop()
```

Let's do this.

**Comment by sudoaza** [comment]
Is this as simple as calling client.stop() from WebTorrent.prototype.destroy ? or am i missing something?

**Comment by feross** [comment]
Probably :smile: You want to try your hand at a PR?

**Comment by sudoaza** [comment]
i will!

**Comment by janza** [comment]
This seems to already be the case, it's called when [torrent is removed](https://github.com/feross/webtorrent/blob/master/lib/torrent.js#L365)

**Comment by feross** [comment]
@janza @sudoaza You guys are right. There may be a timing issue where the server doesn't get the 'stop' event if the client shuts down too quickly because we don't wait for confirmation. See [here](https://github.com/feross/torrent-discovery/blob/master/index.js#L67). There's no callback to wait for the response. 

But I think this is okay. We don't want to delay the process exiting to wait for some slow, overloaded tracker on the other side of the world to respond to us.
