### ISSUE TITLE
Can't download via .torrent file

### ISSUE THREAD

**Issue by jaybekster** [feross/webtorrent#315]
When i add torrent file in http://instant.io/ it doesn't start it although CLI is working perfectly. What is the problem?

**Comment by feross** [comment]
Is the torrent being seeded by a webrtc-capable client, i.e. [webtorrent-hybrid](https://github.com/feross/webtorrent-hybrid) or [instant.io](https://instant.io/)?

In the browser, WebTorrent can only download torrents that are explicitly seeded to the WebTorrent network. Desktop torrent clients need to support WebRTC to peer with web browsers.
