### ISSUE TITLE
Memory doesn't get freed after removing torrent from client

### ISSUE THREAD

**Issue by baranbaygan** [feross/webtorrent#317]
Memory goes up and never goes down even after client.remove is called and nothing is downloading. Any feedback on this?

**Comment by DiegoRBaquero** [comment]
With the peer destroying this improved. @baranbaygan Any input?

**Comment by feross** [comment]
@baranbaygan Can you share more information?

**Comment by feross** [comment]
This should be fixed now. PR coming in a second.
