### ISSUE TITLE
Resumable downloads / seed existing downloads

### ISSUE THREAD

**Issue by misterhat** [feross/webtorrent#320]
It should be possible to start seeding as soon as a torrent is "downloaded" if the contents are found in the output directory. This is how Transmission works on the CLI. The functionality would be especially useful for *webtorrent-hybrid*.

**Comment by feross** [comment]
Yeah, this makes sense to me. I would accept a PR for this. :) Busy with other issues right now, but I agree this is important.

**Comment by jaybekster** [comment]
But would it be the soulton to create client.seed in the callbak when downloading is finiehed?

**Comment by devTristan** [comment]
Trying to figure out how to do this, but having a pretty tough time getting started. @feross, could you point me in the right direction?

**Comment by feross** [comment]
@devTristan Have you taken a look at lib/storage.js?

**Comment by devTristan** [comment]
@feross Yeah, I am right now. I saw that a torrent is seeded by loading all of the data into torrent.storage and then... (???)

Maybe I'm wrong about a basic assumption. After `client.add`, are all files selected or deselected?

**Comment by sharedmit** [comment]
+1 for this feature!

**Comment by MiracleBlue** [comment]
+2 for this, I desperately need pause functionality.  I'm currently working on just the UI part of my new client, but will probably start the actual data transfer stuff fairly soon.  Any takers?  Or should I give it a go?

**Comment by feross** [comment]
You should give it a go!

**Comment by MiracleBlue** [comment]
@feross Gonna give it a go tonight and see where I get to :) here's hoping!

**Comment by feross** [comment]
@MiracleBlue How'd it go?

**Comment by MiracleBlue** [comment]
I struggled with trying to figure out what it takes to actually resume a
partial torrent download (I'm not particularly knowledgible in the Torrent
spec), but I discovered that most clients will do a re-check of the hashes
(or something like that) of the downloaded pieces and determine which
partials are missing, but I was mostly focussed on getting a few of the
last UI bits in to my blue-torrent.

Next weekend I will continue!

**Comment by MiracleBlue** [comment]
I haven't forgotten about this.  Just finding it hard to find the time.  Unfortunately I'm not terribly knowledgable with the Torrent spec, so this is certainly a tricky thing for me :) I'm still working away slowly on my little torrent client which is gonna need this functionality.

**Comment by DiegoRBaquero** [comment]
+1 to seed existing downloads!

**Comment by eliooses** [comment]
+1

**Comment by whitef0x0** [comment]
I just made a PR that fixes this. https://github.com/feross/webtorrent/pull/515

**Comment by JacopoDaeli** [comment]
Hello @feross any news about this feature? How would you suggest to do it, I may try my chance and open a PR.

**Comment by skibulk** [comment]
Is this possible in a web browser? Can file pieces persist across sessions and still be accessible? Wouldn't there be file size limitations?

**Comment by skibulk** [comment]
I found this which could be useful: http://stackoverflow.com/questions/21015771/what-causes-the-chrome-wants-to-permanently-store-large-data-message

**Comment by whitef0x0** [comment]
I already did this. Look at my fork for inspiration

**Comment by singpolyma** [comment]
Does this not work now?  If I run with `--keep-seeding` it certainly does not seem to re-download... but maybe it's not really seeding?

**Comment by feross** [comment]
I'm pretty sure this issue can be closed.

It's possible to resume a torrent by calling `client.add()` with the option `{ path: '/path/to/torrent/folder' }`. If files exist there with the same names as what is in the torrent, then WebTorrent will verify them and check their contents. Whichever pieces are valid, will be preserved and not re-downloaded.

On the command line, you can do the same with `webtorrent "magnet_uri" --out /path/to/torrent/folder`.

**Comment by JacopoDaeli** [comment]
@feross is webtorrent start seeding as soon as it gets the first piece of data?

**Comment by feross** [comment]
@JacopoDaeli Yes.

**Comment by RationalCoding** [comment]
How can this be done in the browser?

**Comment by feross** [comment]
@RationalCoding Sorry for the delayed response. There's not a simple API to get this working in the browser yet, but you can call `torrent.add()`, then later manually call the undocumented [`torrent.load()`](https://github.com/webtorrent/webtorrent/blob/225b6150a9f2bde2519e28d4163ab41adf30e4b6/lib/torrent.js#L1605) with the partial or completely downloaded torrent contents and that will re-populate the storage.

Alternatively, you can use the documented `store` argument to specify a custom factory function that returns an [`abstract-chunk-store`](https://github.com/mafintosh/abstract-chunk-store) compliant storage object that you initialize with the needed data. You can see how this is invoked here: https://github.com/webtorrent/webtorrent/blob/225b6150a9f2bde2519e28d4163ab41adf30e4b6/lib/torrent.js#L1605
