### ISSUE TITLE
Option to add trackers to a certain torrent in WebTorrent

### ISSUE THREAD

**Issue by Qqwy** [feross/webtorrent#323]
I'm testing out WebTorrent, switching over from torrent-stream.
One thing I noticed is that WebTorrent does not seem to have a clear way to add trackers (beside the DHT-network of course) to a certain torrent. Is there a built-in mechanism for this?
If not, I think it would be a very useful feature that might very well speed up many of the torrent requests (at least the ones not needing WebRTC, for now).

**Comment by Svenskunganka** [comment]
WebTorrent parses the magnet link (which contains the trackers) and adds the trackers to the torrent. See [parse-torrent](https://github.com/feross/parse-torrent)

**Comment by Qqwy** [comment]
So basically, if I want to add more trackers, I add them as '&tr=http://some.url.com&tr=http://some_other.url.com' to the end of the magnet string?

**Comment by feross** [comment]
@Qqwy Correct - adding the additional trackers in the magnet uri would work.

You can also do:

```js
var parseTorrent = require('parse-torrent')
var torrent = parseTorrent('magnet:...')

torrent.announce.push('another tracker')
client.add(torrent, function () { ... })
```

**Comment by feross** [comment]
And, as of v0.43, you can also pass in an `announce` option to `client.add`, like this:

```js
var WebTorrent = require('webtorrent')

var client = new WebTorrent()
client.add(torrentId, { announce: [] }, function () { ... })
```

This adds to the tracker list already specified in the `torrentId`. Cheers!
