### ISSUE TITLE
not working inside a LAN

### ISSUE THREAD

**Issue by enorrmann** [feross/webtorrent#326]
Hi ! I'm trying instant.io behind a proxy, my local ip is something like 10.4.8.20.
I get to instant.io and start seeding a txt file, then I click on "Share link", so it opens a new tab and it says "Downloading torrent from infohash blahblahblah..." but the download never starts.
Is this supposed to work this way or am I missing something ?
thx !

**Comment by feross** [comment]
@enorrmann Yeah, that should definitely work. My guess is that your proxy is confusing Chrome/Firefox and it can't hole punch with that active. I don't think there's anything that we can do about that.

Consider filing a bug here: https://code.google.com/p/webrtc/issues/list

**Comment by enorrmann** [comment]
Just to clarify.. does this require some special ports to be open ? perhaps my proxy is allowing just 80 and 443

**Comment by feross** [comment]
WebRTC is supposed to figure out how to connect despite whatever ports your NAT allows. If your proxy is super restrictive, however, it might not be possible to find a path to the other peer.
