### ISSUE TITLE
Seeding folder in browser

### ISSUE THREAD

**Issue by fbodz** [feross/webtorrent#327]
Thanks for the awesome project once again. I was just wondering if it was possible to seed a folder in the browser. When I drag and drop a folder it says "1 file seeding" and then appears to be inactive. Thanks for your time.

**Comment by rom1504** [comment]
related to https://github.com/feross/instant.io/issues/30

**Comment by feross** [comment]
This is more of an https://instant.io issue than a WebTorrent one.

It looks like we can support seeding folders (both via drag-and-drop and the file upload input) in Chrome. The non-standard FileSystem API makes this possible. Other browsers don't have any mechanism to do this, as far as I can tell.

I'm working on this right now.

**Comment by feross** [comment]
In other browsers, you can still upload multiple files and they'll be bundled into the same torrent. You just can't include any folders.

**Comment by feross** [comment]
This is done now.
