### ISSUE TITLE
Add WebTorrent support to Playback

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#329]
Once [this issue](https://github.com/feross/webtorrent/issues/310) is fixed, let's add WebTorrent support to @mafintosh's excellent Playback app :)

https://github.com/mafintosh/playback

**Comment by feross** [comment]
In progress diff here: https://github.com/mafintosh/playback/compare/master...feross:master

**Comment by jakefb** [comment]
This will be awesome!

**Comment by feross** [comment]
This is now being tracked here: https://github.com/feross/webtorrent/issues/369
