### ISSUE TITLE
Download torrent team crashes 

### ISSUE THREAD

**Issue by KrasCYBORG** [feross/webtorrent#332]
Example:

OS windows, centos
download torrent by infohash in command line:

webtorrent download hash <a 3d86eaaef6ce444da7761f39b16859c1f8b4f99b>

the file is downloaded and a while crashes:

ERROR: If you think this is a bug in webtorrent, report it!
=====>                                               <=====
=====>  https://github.com/feross/webtorrent/issues  <=====
=====>                                               <=====

**Comment by KrasCYBORG** [comment]
In previous versions 0.3- it was all good

**Comment by feross** [comment]
@KrasCYBORG Can you share the full stack trace when you see the error? I can't debug with such limited information.

**Comment by feross** [comment]
I'm going to close this since there's not enough info for me to understand the problem. @KrasCYBORG If you're reading this, feel free to comment with more info or open a new issue.
