### ISSUE TITLE
WebTorrent.Seed should return an error if it cannot connect to the tracker

### ISSUE THREAD

**Issue by gmbuell** [feross/webtorrent#333]
There is currently no way to tell if connecting to the tracker was successful.

Example:

```javascript
var client = new WebTorrent()
client.seed(input, { announceList: [["invalid://definitely-not-valid"]]})
```

Seed should support an error callback with debug information.

**Comment by feross** [comment]
This is fixed in webtorrent 0.48.0. You can check for warnings like this:

```js
  var torrent = client.seed(buf, { announce: ['invalid://definitely-not-valid'] })
  torrent.on('warning', function (err) {
    console.log('torrent warning', err.message)
  })
```

You should probably always be attaching a 'warning' handler and logging warnings since they contain useful information. There's also the 'error' event which is even more important to listen for.
