### ISSUE TITLE
Improve webrtc peer connection handling

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#338]
- [x] need to cleanup closed/errored webrtc peers from the swarm
- [x] need to cleanup unused peers when tracker doesn't respond any answers (add a timeout)
- [ ] ~~need to increase number of offers (maybe to 25?)~~
- [x] need to re-announce to tracker every 5 minutes (instead of 15 minutes) since peers are probably shorter-lived

**Comment by feross** [comment]
I just pushed an improvement to the tracker module, so we now try to look for new peers every 30 seconds on the already-established WebSocket connection to the tracker.

**Comment by DiegoRBaquero** [comment]
@feross The first two, I think they can be checked with the recent peer destroy update.

**Comment by feross** [comment]
@DiegoRBaquero Yep, thanks. Going to close this now.
