### ISSUE TITLE
listen EADDRINUSE

### ISSUE THREAD

**Issue by kevinsimper** [feross/webtorrent#339]
I know that this is because the port is used, but I think we should give it a better error message.

Also could not find anything about in the issues before.

**Comment by feross** [comment]
I agree the message isn't very friendly. But this is a node.js error message, not something WebTorrent generates. We're just passing it along. iojs and future versions of node.js actually have much friendlier messages for most of these errors, so this problem will actually just fix itself over time as people upgrade. :-)

**Comment by feross** [comment]
Here's the exact message iojs shows: "EADDRINUSE: Address already in use"

More info here: https://iojs.org/api/errors.html#errors_eaddrinuse_address_already_in_use

**Comment by kevinsimper** [comment]
@feross Yes, but i did not do anything, it crashed for me which kept it in this state, therefore the issue, it not like I was running anything else.
