### ISSUE TITLE
cli drawing takes up too much screen

### ISSUE THREAD

**Issue by kevinsimper** [feross/webtorrent#340]
Not doing anything while it moves.
![cli](https://cloud.githubusercontent.com/assets/1126497/7944286/030316de-096a-11e5-8447-c1588d358728.gif)

**Comment by KrasCYBORG** [comment]
+1

**Comment by feross** [comment]
The problem is the magnet uri is too long. I've just removed that bit of info for now. Released as 0.49.1.

What we really should do is add a prompt that shows the magnet uri and gives the user a chance to copy it to clipboard before starting seeding and showing the full UI.

**Comment by kevinsimper** [comment]
:+1:
