### ISSUE TITLE
webtorrent drop when downloading a file

### ISSUE THREAD

**Issue by KrasCYBORG** [feross/webtorrent#341]
[root@krs ~]# webtorrent -v
0.48.5

[root@krs ~]# node -v
v0.12.4

OS: Centos 6.0 x64

when downloading a file after a certain time an error
Example:
webtorrent download xxxxxxxxxxxxxxxxxxxxxxxxx

downloading: xxxxxxxxxxxxxxxxxxxxxxxxx.mkv
speed: 104.86 kB / s downloaded: 97.67 MB / 1.64 GB uploaded: 2.39 MB peers: 0/0 hotswaps: 0
time remaining: 4 hours remaining total time: 164s queued peers: 1322 blocked: 0

ERROR: If you think this is a bug in webtorrent, report it!
=====>                                               <=====
=====>  https://github.com/feross/webtorrent/issues  <=====
=====>                                               <=====
/usr/local/lib/node_modules/webtorrent/node_modules/bittorrent-swarm/lib/peer.js:202
  self.swarm.wires.splice(self.swarm.wires.indexOf(self.wire), 1)
            ^
TypeError: Cannot read property 'wires' of null
    at Peer.destroy (/usr/local/lib/node_modules/webtorrent/node_modules/bittorrent-swarm/lib/peer.js:202:13)
    at Wire.<anonymous> (/usr/local/lib/node_modules/webtorrent/node_modules/bittorrent-swarm/lib/peer.js:109:10)
    at Wire.g (events.js:199:16)
    at Wire.emit (events.js:129:20)
    at finishMaybe (_stream_writable.js:484:14)
    at afterWrite (_stream_writable.js:362:3)
    at _stream_writable.js:349:9
    at process._tickCallback (node.js:355:11)

Download speed is constantly changing all the time

**Comment by rom1504** [comment]
You shouldn't put the copyrighted torrent/file name here (see https://github.com/feross/webtorrent/issues/307) ;)

**Comment by feross** [comment]
Fixed in `bittorrent-swarm` 5.0.3. `webtorrent` should inherit the fix if you're running the latest version and you run `npm update`.
