### ISSUE TITLE
seeding a file using nodejs

### ISSUE THREAD

**Issue by afshinm** [feross/webtorrent#342]
I'm trying to seed an html file using WebTorrent in Nodejs. I get callback from WebTorrent which indicates that the client is started seeding but when I copy-paste the hash on the client-side to download the file, nothings happened.

Here is my code on the server-side:
```
  client.seed(file, function (torrent) {
    debug('started seeding %s - %s', torrent.infoHash, torrent.files[0].name);
  });
```

What is the problem and how can I debug to see what is going on?

**Comment by afshinm** [comment]
resolved https://github.com/feross/webtorrent/issues/343#issuecomment-108903368

**Comment by feross** [comment]
Nice - glad you got it figured out :+1:
