### ISSUE TITLE
cannot download the torrent using uTorrent client

### ISSUE THREAD

**Issue by afshinm** [feross/webtorrent#343]
I'm seeding a file using https://instant.io/ and I want to download that file using a torrent client (e.g. uTorrent). When I copy the magnet uri in the torrent client, it doesn't understand the file and does not start the downloading.

Is this the problem of my torrent client or instant.io? Please note that I can download the same file using another window of instant.io.

**Comment by rom1504** [comment]
uTorrent doesn't implement WebTorrent.

**Comment by Wingman4l7** [comment]
What rom1504 means is that the browser-based implementation of WebTorrent only uses the WebRTC protocol to communicate; the BitTorrent protocol uses TCP / UDP.  Since the torrent client uTorrent doesn't yet support WebRTC, it won't see any browser-based WebTorrent peers.

**Comment by afshinm** [comment]
Thank you guys, that makes sense. Is that somehow related to this? https://github.com/feross/webtorrent/issues/342

I'm trying to seed a file using nodejs and download it from web browser but nothing is happened. But when I see it using web browser, it works.

**Comment by rom1504** [comment]
if you want to seed a file from nodejs and download it from the web browser, you need to use webtorrent-hybrid https://github.com/feross/webtorrent-hybrid

**Comment by afshinm** [comment]
@rom1504 cool! thanks. it works.
