### ISSUE TITLE
Mac OS X issue

### ISSUE THREAD

**Issue by gyzerok** [feross/webtorrent#344]
I'm trying to use webtorrent cli in following way:
```
webtorrent ~/Downloads/1.torrent
```
After this it shows me some interface and nothing happening. All the peers appears just for a few seconds. So download doesnt start. No errors.

P.S. Same with programmatic usage.

For cli: node 0.12.2.
For programmatic: iojs 1.2.0.

**Comment by gyzerok** [comment]
https://github.com/feross/webtorrent/issues/310

**Comment by feross** [comment]
Yeah, sorry about this. Still haven't had time to sit down and debug this. Help appreciated!

Closing as duplicate of #310
