### ISSUE TITLE
Node.js memory leak

### ISSUE THREAD

**Issue by afshinm** [feross/webtorrent#346]
When I try to seed two or three files, more than 30 processes created and the server just stop working.

Here is a screenshot of my server and processes:
![screen shot 2015-06-05 at 12 22 17 am](https://cloud.githubusercontent.com/assets/314326/7993099/1123f4b2-0b19-11e5-8da0-a3aefc043c5c.png)

Also I got `max EventListener` error.

**Comment by feross** [comment]
Those are almost certainly threads, not processes. WebTorrent doesn't ever spawn processes but node.js will spawn new threads for IO tasks.

The problem where everything stops working is the real problem here. How large are the torrents you're seeding? How many are you seeding?

**Comment by feross** [comment]
Pro-tip: You can configure `htop` to show only processes, instead of the default of threads.

**Comment by afshinm** [comment]
Hey @feross 

I'm seeding 4 `html` files, less than 1kb. I figured out that when I start seeding even a 1kb file, nodejs creates about 20 threads. I don't know which module is creating this threads btw.

**Comment by rom1504** [comment]
Why is it a problem that node create these threads ?

**Comment by afshinm** [comment]
@rom1504 after seeding 3 html files, you will have more than 100 threads and no memory left.

**Comment by rom1504** [comment]
How are you seeding these files ? I don't think starting several webtorrent instances is an efficient way to do it.
Are you using webtorrent or webtorrent-hybrid ? There are some performance problems with webtorrent-hybrid currently.

**Comment by afshinm** [comment]
@rom1504 I'm using webtorrent-hybrid. I don't create several WebTorrent instances but I call `add` function three times to seed three different files (which makes sense I think)

**Comment by feross** [comment]
Threads don't necessarily take a notable amount memory.

`webtorrent-hybrid` has memory issues because of the `wrtc` module. We should investigate using Electron instead of `wrtc`. Looking for a volunteer to work on this! https://github.com/feross/webtorrent-hybrid/issues/5

**Comment by feross** [comment]
Closing because the original issue was invalid (node.js creates lots of threads - not a WebTorrent issue).
