### ISSUE TITLE
Clientside can't find seeder from webtorrent-hybrid

### ISSUE THREAD

**Issue by afshinm** [feross/webtorrent#356]
Recently I've developed http://www.peopledrivenweb.com/ which is a cms based on torrent. Here is the Github repo: https://github.com/peopledrivenweb/pwjs

The issue is, sometimes it takes too long to find a seeder from webtorrent-hybrid but sometimes it works really fast. I monitored resource on the server-side but I didn't find anything special. 

What is the problem? Is this related to browser or serverside codes?

**Comment by feross** [comment]
Cool site! Not sure what the issue could be, based on your description. If you learn anything new, please share.

**Comment by DiegoRBaquero** [comment]
@afshinm Any updates?

**Comment by feross** [comment]
Looks like his site is down now. Also, I expect that `webtorrent-hybrid` will undergo some big changes soon once we switch the webrtc implementation that's used, so this issue will be irrelevant.
