### ISSUE TITLE
When seeding a file/folder from disk, don't perform extra copy to /tmp

### ISSUE THREAD

**Issue by Chocobozzz** [feross/webtorrent#357]
Hi !

If I want to seed a file from (just an example) */home/me/videos/awesome.webm* I see that webtorrent copy it as */tmp/webtorrent/xxx/xxx.webm*. I wanted to know if this was really needed, since the file is already on the disk. 

This could be annoying with big videos (1Go), disk space would rapidly decrease and the seeding would take much time since the disk should copy 1Go before it.

Thanks :)

**Comment by ericwooley** [comment]
I'm sure feross can enlighten us, but I'll take a stab at the question. From my limited work with the file api, it's not easy to access data from the outside of the web sandbox (by that I mean not possible). So the options would be too keep the data in memory (hope you have a lot!) or write it to disk somewhere you can access.

**Comment by Chocobozzz** [comment]
Oh sorry, I forgot an important thing. It's with webtorrent in a node server (*webtorrent-hybrid*).

Of course in a browser I agree there is no many options.

**Comment by feross** [comment]
@Chocobozzz You're right, copying to /tmp is not really needed if you're seeding a file that you alreadu have on disk. This is a bug!

PR welcome!

**Comment by feross** [comment]
Released as 0.50.1, thanks to a PR from @janza :+1:

**Comment by Chocobozzz** [comment]
Thanks guys !
