### ISSUE TITLE
Move SHA1 to web worker pool

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#36]
The UI currently lags (it's affecting the CSS animations) and I think it's due to SHA1 hashing happening on the main thread. Stick it in a web worker pool.

**Comment by piedshag** [comment]
@feross would this be useful now, considering this is probably the biggest consumer of the cpu? Substack has a great module for [web workers](https://github.com/substack/webworkify). I am not an expert on web workers but would this perhaps speed up the seeding process? Once support is added for data channels in web workers we could just use webtorrent in a worker, but at the moment this seems like the only process you could offload to the worker. What are your thoughts on this?

**Comment by feross** [comment]
@piedshag Yeah, this would indeed be useful. The issue is that this module needs to work in node.js and Electron environments too, so there's a bit of complexity involved in supporting Node.js which lacks Web Workers. But we can (and should) do it.

**Comment by josephfrazier** [comment]
Should we close this in favor of https://github.com/feross/webtorrent/issues/235? It looks like there's more discussion/information there.

**Comment by feross** [comment]
Thansk
