### ISSUE TITLE
Proposal: EmerCoin NVS as magnet link storage

### ISSUE THREAD

**Issue by maxihatop** [feross/webtorrent#362]
Hi,
I would like to make your attention into Emercoin Name-Value storage, NVS:
http://emercoin.com/DNS_and_Name-Value_Storage
This decentralized storage has feature to store and distribute magnet links, see "Magnet" in the document, and table 2. In opposite to another technologies, this is truthfully distributed system,
and cannot be blocked/censored/alerted, etc. Anyone able load and manage his magnet link, but nobody else. I think, decentralized link storage is very suitable for your decentralized system.
For cooperate, contact EmerCoin team: team(well known symbol)emercoin.com.
We will happy to assist you, and provide initial funds for experiments.

Also, this is possible to add another feature: copy from NVS-record, contains magnet link, EMC-address of link owner.  Thereafter, send direct tips/donation to that address by EMC-wallet.

See analogous request for Tribbler: https://github.com/Tribler/tribler/issues/1455

**Comment by devTristan** [comment]
Why build a module that can connect to an emercoin daemon and then bundle it inside another, unrelated module?

**Comment by maxihatop** [comment]
Excuse me, I did not understand your question, about build module inside another module. As I understand, Tribbler and Webtorrent - completwly differrent products. Or I missed something, and Webtorrent uses Tribbler as module? If so - then of course, no sense to duplicate functionality.

**Comment by devTristan** [comment]
I'm not talking about tribler. If your proposed use case is that people look up magnet links via emercoin and then download them with webtorrent, that would involve connecting two unrelated modules. One, WebTorrent, is for downloading files over bittorrent. The other is for looking things up using emercoin. I'm not a significant contributor to this project so I obviously have no say in this, but it seems to me that you're proposing the addition of emercoin lookup functionality to **this** module, which makes no sense to me. Why not just make an emercoin module and use it with webtorrent?

**Comment by maxihatop** [comment]
I think, WebTorrent can just send http json requests to EMC-wallet, and extract magnet links from here. So, there is not needed some special module. Just config line for wallet URL, and interface ability. 
Unfortunately, EMC-wallet cannot perform fuzzy search (it can perform exact search in bdb), and for search something - webtorrent must request for dump whole NVS db, and filter out interesting lines. Fortunately, NVS stored in the local wallet, and download+parsing is quick for millions records.

**Comment by rom1504** [comment]
Related with https://github.com/feross/webtorrent/issues/186
I think this integration with emercoin would probably go into an other module that would use webtorrent yeah, but it's a bit related to webtorrent anyway.

**Comment by packetlost** [comment]
the concept of a blockchain tracker does sound interesting at first glance.

**Comment by feross** [comment]
This is interesting, but as @devTristan says, it doesn't belong in WebTorrent. If someone wants to bundle EmerCoin and WebTorrent into a new module that does EmerCoin lookup and downloads with WebTorrent that would be cool.

As @rom1504 said, related discussion is here: https://github.com/feross/webtorrent/issues/186
