### ISSUE TITLE
How to use the file tranfer part only 

### ISSUE THREAD

**Issue by aliraza0337** [feross/webtorrent#365]
Hi I want to use the file transfer part only from the webtorrent, can you please guide me how to do that ?

**Comment by feross** [comment]
I don't understand what you mean by "only the file transfer part". Can you elaborate?

What are you trying to do?

**Comment by aliraza0337** [comment]
Hi Thanks for your response,
I have a seprate mechanism[I have already implimented this] through which I know who is hosting the files I want, Lets say H[some machine or and ip address to which I can connect] is hosting a file F. How I can download F using this torrent protocol.

**Comment by feross** [comment]
It's not enough that you know *who* has the file. They have to be *seeding* the file using a torrent client. If you can do that, then you're good.

You'll want to disable the normal peer finding via trackers and the DHT.

```js
var client = new WebTorrent({ dht: false, tracker: false })
client.seed('/path/to/file', function (torrent) {
  console.log(torrent.infoHash) // get info hash
  console.log(client.torrentPort) // get torrent port
})
```

Then from the downloader's end:

```js
var client = new WebTorrent({ dht: false, tracker: false })
var torrent = client.add(infoHash)
torrent.addPeer('ip:port') // use ip and port of remote machine
```

Hope this helps!

**Comment by aliraza0337** [comment]
Yes I can run the client for seeding the file as well, Thanks Alot, I will test and update here if it works.

**Comment by aliraza0337** [comment]
if multiple machies are hosting the same file is there any way I can pass the ip addresses of all so that it can download faster [the usuall chunk based downloading]?

**Comment by feross** [comment]
Just call `torrent.addPeer('ip:port')` multiple times if you have multiple peers to download from.

You can specify download location with the `path` option to `client.add`. Read [the documentation](https://github.com/feross/webtorrent#clientaddtorrentid-opts-function-ontorrent-torrent-) to learn how it works.

**Comment by aliraza0337** [comment]
I tried to run both instances on one machine, 
I got the port number from one and put 'localhost:portnumber' in the downloader here is the error

/Users/aliraza/node_modules/webtorrent/lib/torrent.js:385
    self.swarm.addPeer(peer)
              ^
TypeError: Cannot read property 'addPeer' of undefined
    at Torrent.addPeer (/Users/aliraza/node_modules/webtorrent/lib/torrent.js:385:15)
    at Object.<anonymous> (/Users/aliraza/Desktop/receiver.js:5:9)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by feross** [comment]
localhost is not a valid IP address.

**Comment by aliraza0337** [comment]
I tried 127.0.0.1 as well it didn't work.

**Comment by feross** [comment]
Ah, the downloader needs to wait until the 'infoHash' or 'listening' event before `self.swarm` is defined, and before you can call `torrent.addPeer(peer)`.

I just published a new version of WebTorrent that fixes this. So update to that and try this:

#### Seeder
```js
var WebTorrent = require('webtorrent')
var client = new WebTorrent({ dht: false, tracker: false })
client.seed('README.md', function (torrent) {
  console.log(torrent.infoHash) // get info hash
  console.log(client.torrentPort) // get torrent port
})
```

#### Downloader
```js
var WebTorrent = require('webtorrent')
var client = new WebTorrent({ dht: false, tracker: false })
var torrent = client.add('037596f40092d714b57a919f5628c6d3930debd0') // replace with your infohash
torrent.addPeer('127.0.0.1:52472') // replace with your port
torrent.on('done', function () {
  console.log('all done!')
})
```
