### ISSUE TITLE
A new bittorent extension (like ut_pex, ut_metadata) to send plain chat message to peer

### ISSUE THREAD

**Issue by vairabagni** [feross/webtorrent#368]
How can I use this extension or [ut_metadata](https://github.com/feross/ut_metadata) or by creating a new one to be able to send messages to other peer (chat message) ?

I just started by creating a new extension which i am thinking of integrating that into webtorrent. So I modified torrent.js (inside webtorrent, ln 463) - _onWire callback - this block is same as that of ut_pex.

```Javascript
if (typeof ut_message === 'function') {
    wire.use(ut_message())

    //wire.ut_message.start() // TODO two-way communication
    wire.ut_message.on('peer', function (peer) {
      debug('ut_message: got peer: %s (from %s)', peer, addr)
      self.addPeer(peer)
    })

    wire.ut_message.on('dropped', function (peer) {
      // the remote peer believes a given peer has been dropped from the swarm.
      // if we're not currently connected to it, then remove it from the swarm's queue.
      debug('ut_message: dropped peer: %s (from %s)', peer, addr)
      var peerObj = self.swarm._peers[peer]
      if (!peerObj || !peerObj.conn) self.swarm.removePeer(peer)
    })
  }

```

Is it required? Or i can just use any extension (ut_metadata, ut_pex or mine - ut_message) as:

```Javascript
torrent.swarm.on("wire", function(wire) {
	console.log("onwire - " + wire.peerId + " - " + wire.remoteAddress + ':' + wire.remotePort);
		
	wire.on('extended', function (ext, obj) {
		console.log('extended', ext, obj.toString());
	});
	wire.use(ut_message()); 
        //or
        wire.use(ut_metadata());
        //or
	wire.use(ut_pex()); 
		
	wire.extended(3, 'hello'); //first param will be either 1, 2 or 3
});
```

**Comment by devTristan** [comment]
```javascript
torrent.on('wire', function (wire) {})
```

https://github.com/feross/webtorrent#torrentonwire-function-wire-

**Comment by vairabagni** [comment]
My Seeder looks like:
```Javascript
var client = new WebTorrent({
	dht: {
		announce: ['http://127.0.0.1:6881/announce']
	}
});

client.seed('something.mp4', {
  announce: ['http://127.0.0.1:6881/announce'],
  private: false
}, function onTorrent (torrent) {
        // Client is seeding the file!
	console.log('MargnetURI:', torrent.magnetURI);
	console.log('Info hash:', torrent.infoHash);
});

client.on('torrent', function (torrent) {
       torrent.on("wire", function(wire) {
		console.log("onwire - " + wire.peerId + " - " + wire.remoteAddress + ':' + wire.remotePort);
		
		wire.on('extended', function (ext, obj) {
			console.log('extended', ext, obj.toString());
		});
		
		wire.ut_pex.on('warning', function (err) {
			console.log('warning', err.message)
		})
		
		wire.extended(2, 'hello');
	});
});
```

-- The callback onwire will be called if i specify 
```Javascript
torrent.swarm.on("wire", function(wire) {
```
instead of
```Javascript
torrent.on("wire", function(wire) {
```

Which one I should use ?


-- When i restart the local tracker then the litcher is getting the message 'hello'. Is there anything wrong I am doing?

**Comment by devTristan** [comment]
If I were you, I'd get started using the test.

https://github.com/feross/webtorrent/blob/master/test/extensions.js

Provided your extension is properly named, you can then send messages like this:

```javascript
wire.extended('my_extension', 'ayyyy lmao')
```

**Comment by feross** [comment]
What @devTristan said – thanks for helping out!

**Comment by vairabagni** [comment]
I was using webtorrent@0.49.2, that may be the reason why "torrent.on("wire", function(wire) {" was not triggering. When i updated to webtorrent@0.51.1 it starts working.

Yes, @devTristan I have created a new extension for message communication and I will be using the way you suggested.

Thanks both you.

**Comment by fultonm** [comment]
How is your extension working @vairabagni? You can add extensions to the list of known extensions by making a pull request here https://github.com/feross/bittorrent-protocol#extension-api

I'm interested in something like this 👍

**Comment by norzak** [comment]
@devtristan would you care to share the working piece of your messaging extension?
