### ISSUE TITLE
Does webtorrent "auto-seed" torrents after add?

### ISSUE THREAD

**Issue by Stiveknx** [feross/webtorrent#371]
When I start download a torrent, using: ```client.add```, it automatically starts seed that files (or better, the pieces), automatically?
If doesn't is that possible?

While we still don't have the support of another torrent clients #369, what it can be done is seed the file from who already downloaded or is downloading the torrent ...

**Comment by feross** [comment]
Yes, WebTorrent seeds files as you download, and continues to seed once the download is complete. :+1:
