### ISSUE TITLE
Standardize hash variable names

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#374]
Right now, in most of the webtorrent modules, we use `self.infoHash` to store a buffer and `self.infoHashHex` to store a hex string. But there are a few places like `lib/torrent.js` where it's actually a hex string.

Same with `self.peerId` and `self.peerIdHex`.

We've already standardized on using hex strings at the edges of the various modules, i.e. events that emit infoHashes or peerIds always use hex strings. Functions that take an hash input always accept a hex string OR a buffer.

Let's go hex strings all the way, and make it so the `self.infoHash` property is always a hex string as well. And we can use `self.infoHashBuffer` for the buffer version. This will require changes to almost every module.

**Comment by imsnif** [comment]
Please let me know if I missed anything.
