### ISSUE TITLE
Abnormal quit during streaming to VLC

### ISSUE THREAD

**Issue by solderzzc** [feross/webtorrent#377]
It happens on Mac OS X, node version is v0.12.7. Both happens on webtorrent and webtorrent-hybrid 0.53.0.
Following is the console log:
webtorrent-hybrid "magnet:?xt=urn:btih:c49f565a15c41563404e161862751218c4fa9e10&dn=American+Heist+2014+720p+BrRip+2CH+x265+HEVC-CHALA&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969" -q  --vlc
ERROR: stderr maxBuffer exceeded.
ERROR 1: If you think this is a bug in WebTorrent, report it!
=====>                                                 <=====
=====>   https://github.com/feross/webtorrent/issues   <=====
=====>                                                 <=====
SYSTEM INFO: node v0.12.7 darwin x64 WebTorrent 0.53.0

Let me know if you need more information

**Comment by solderzzc** [comment]
Also tested on Linux, following is the log:

ERROR 1: If you think this is a bug in WebTorrent, report it!
=====>                                                 <=====
=====>   https://github.com/feross/webtorrent/issues   <=====
=====>                                                 <=====
SYSTEM INFO: node v0.10.25 linux x64 WebTorrent 0.53.0


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)

**Comment by feross** [comment]
Don't post magnet links or torrent files that link to copyrighted content. It's against [the rules](https://github.com/feross/webtorrent/blob/master/CONTRIBUTING.md). Don't use WebTorrent for copyright infringement.
