### ISSUE TITLE
Abnormal quit during streaming to VLC

### ISSUE THREAD

**Issue by solderzzc** [feross/webtorrent#380]
It happens on Mac OS X, node version is v0.12.7. Both happens on webtorrent and webtorrent-hybrid 0.53.0.
Following is the console log:
webtorrent-hybrid -q --vlc
ERROR: stderr maxBuffer exceeded.
ERROR 1: If you think this is a bug in WebTorrent, report it!
=====> <=====
=====> https://github.com/feross/webtorrent/issues <=====
=====> <=====
SYSTEM INFO: node v0.12.7 darwin x64 WebTorrent 0.53.0

Also tested on Linux, following is the log:

ERROR 1: If you think this is a bug in WebTorrent, report it!
=====> <=====
=====> https://github.com/feross/webtorrent/issues <=====
=====> <=====
SYSTEM INFO: node v0.10.25 linux x64 WebTorrent 0.53.0

events.js:72
throw er; // Unhandled 'error' event
^
Error: write EPIPE
at errnoException (net.js:901:11)
at Object.afterWrite (net.js:718:19)

Let me know if you need more information

**Comment by feross** [comment]
This is fixed in webtorrent 0.53.1.

**Comment by solderzzc** [comment]
Verified, it's fixed in 0.53.1. Thanks a lot for your amazing work.

**Comment by solderzzc** [comment]
But not on Linux, there's still issue:

ERROR: If you think this is a bug in WebTorrent, report it!

=====>                                               <=====
=====>  https://github.com/feross/webtorrent/issues  <=====
=====>                                               <=====
DEBUG INFO: node v0.10.25, linux x64, webtorrent 0.53.1, exit 1
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)

**Comment by solderzzc** [comment]
Upgraded to node v0.10.40/webtorrent 0.53.2 on linux x64, no such issue.

**Comment by feross** [comment]
Great to hear!
