### ISSUE TITLE
How to get progress of a download

### ISSUE THREAD

**Issue by webchaz** [feross/webtorrent#381]
I started with the example provided here for node: https://github.com/feross/webtorrent/blob/master/examples/browser-download.js

I can't see a way to get the download progress (speed, percent left, etc.).   Is there an event for this?

**Comment by webchaz** [comment]
In addition, running node v0.10.38, I get a ton of:

`(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.`

and then finally:

`RangeError: Maximum call stack size exceeded`

This is using the same example.

**Comment by ericwooley** [comment]
We worked on a webtorrent based project over the weekend, and here is the file where we calculated speed and progress.

https://github.com/ericwooley/ship-it-wt/blob/master/app/src/js/src/ui/download-stats/download-stats.js

It's also really helpful to look through the instant.io source code to find a lot of these things.

**Comment by feross** [comment]
@webchaz The node warning you're seeing is a node 0.10 bug. If you upgrade to node 0.12 or iojs, the warning should go away. See: https://github.com/joyent/node/issues/6065

@ericwooley's advice is right. For now, it's really useful to look at the code for https://instant.io to learn how to do various things. Please send PRs to improve the docs, if you find things that aren't documented.

Specifically, here's how to get download progress: https://github.com/feross/instant.io/blob/0bfc78b401ae39bcd3352c8c7cb6f5d5c1bc5e0b/client/index.js#L144

**Comment by ericwooley** [comment]
@feross Are you open to a PR on torrent-swarm to implement a getProgress type method?

**Comment by webchaz** [comment]
@feross @ericwooley Thanks for the links and info, this was exactly what I was looking for.

**Comment by feross** [comment]
@ericwooley 

I'd accept a PR to add `torrent.downloadSpeed()` and `torrent.uploadSpeed()` which would just call `torrent.swarm.downloadSpeed()` and `torrent.swarm.uploadSpeed()`.

`torrent.progress` is already implemented: https://github.com/feross/webtorrent/blob/master/lib/torrent.js#L99-L103

**Comment by ericwooley** [comment]
@feross I didn't notice the swarm speeds were implemented. That makes things easy!
