### ISSUE TITLE
Implement strategy to detect non seeded torrents

### ISSUE THREAD

**Issue by ericwooley** [feross/webtorrent#384]
As @feross suggested in gitter, one possible solution is to emmit event 'no-peers' when there are no peers available on a torrent.

**Comment by Stiveknx** [comment]
+1

**Comment by eliooses** [comment]
+1

**Comment by harperj** [comment]
#775 Adds this 'noPeers' event whenever an announce occurs, but the resulting swarm contains no peers.  I think this doesn't quite solve the problem of detecting "non seeded torrents" though.  We might also look at all of our peers and see if the set of desired pieces is available before emitting a "notSeeded" event.

Thoughts?

**Comment by feross** [comment]
Done in https://github.com/feross/webtorrent/pull/775
