### ISSUE TITLE
No compatible version found mp4box.js when trying to install npm webtorrent with meteor

### ISSUE THREAD

**Issue by zakaria340** [feross/webtorrent#393]
Hi,
Im trying to use webtorrent with meteorhack:npm.
packages.json : 
{
    "webtorrent":"0.55.0"
}

server.js
if (Meteor.isServer) {
  Meteor.startup(function () {
    var Webtorrent = Meteor.require('webtorrent');
  });
}

![npmerror](https://cloud.githubusercontent.com/assets/4690805/9026017/ce0b898e-3916-11e5-9f1a-c7bd64f299c0.jpg)

**Comment by feross** [comment]
I believe that Windows can't handle `git+ssh://` urls in npm dependencies. I fixed this in `videostream` (see https://github.com/jhiesey/videostream/pull/14).

@zakaria340 Can you try installing again and let me know if it works now?
