### ISSUE TITLE
Transfers die

### ISSUE THREAD

**Issue by acidhax** [feross/webtorrent#394]
Transfers just stop randomly. Is there a way to force it to continue?

**Comment by feross** [comment]
Please provide more information.

What were you were doing when you saw this happen?
Were you using WebTorrent in the browser?
Was node or the browser seeding?
How far did it make it before it stalled?
What version of WebTorrent are you using? (run `webtorrent --version`)

**Comment by acidhax** [comment]
Basically, it was running on node.js, and I would do createReadStream(start, end). It would eventually just stop calling back.

**Comment by feross** [comment]
This issue is probably fixed now. There was an issue with connections getting killed due to a bug in `bittorrent-protocol`. If this is still a problem for you, please open a new issue.
