### ISSUE TITLE
maxPeers not working (and not inherited to maxConns in Swarm)

### ISSUE THREAD

**Issue by alexradostin** [feross/webtorrent#395]
Is maxPeers option really working now? I’ve searched the sources and the only place it’s mentioned is the documentation. However this is another maxConns setting of the Swarm which seems not inherited from maxPeers in any way.

**Comment by feross** [comment]
This option works now, thanks to @imsnif's PR #548, but the option is now called `maxConns`.

Released as 0.66.0.
