### ISSUE TITLE
Streaming - Status Code:101 Switching Protocols

### ISSUE THREAD

**Issue by MrTibbles** [feross/webtorrent#396]
Firstly, love th project!

Basically I am trying to simply stream a torrent into an audio player, however i am getting:
Status Code:101 Switching Protocols
Any ideas as to why this would be occuring?

Thank you in advance :)

**Comment by feross** [comment]
This is expected. It's what Chrome shows when a WebSocket connection is active. WebSockets are used to communicate with a tracker server for finding peers.

If you switch to the "Frames" tab (to the left of "Headers") you should see that data is sent to/from the tracker.

**Comment by MrTibbles** [comment]
Ok thanks for the speedy response! I can confirm there are readings in the frames panel, however the function is not being triggered. I waited for at least 10 mins and still nothing, which is why i thought it to be an issue. Please advise

Thank you once again :)

**Comment by MrTibbles** [comment]
{
  "complete": 0,
  "incomplete": 1,
  "action": 1,
  "interval": 600000,
  "info_hash": "\u0013è4ü-ÊÛ\u000eP/B¶\\\u0012½¨ÆÆá¶"
}

**Comment by feross** [comment]
You can't just paste in any random magnet uri or .torrent file. Is the torrent being seeded by a webrtc-capable client, i.e. webtorrent-hybrid or instant.io?

In the browser, WebTorrent can only download torrents that are explicitly seeded to web peers via a WebTorrent capable client. Desktop torrent clients need to support WebRTC to peer with web browsers.

**Comment by MrTibbles** [comment]
I was simply trying to test with a, yes random, torrent. I didnt realise that was th case. :/

Where would i get hold of an example torrent that works?

**Comment by feross** [comment]
You can seed any file by drag-and-dropping it onto https://instant.io

**Comment by MrTibbles** [comment]
ok cool, currently at my full time job, so can’t attempt to do so just yet. But thank you once again for the incredible service :)

**Comment by MrTibbles** [comment]
ok cool, im now successfully getting the torrent, however now webtorrent is throwing an error when trying to pipe the file into the audio tag. Is this also expected?

Uncaught TypeError: e.on is not a function56.c.pipe @ webtorrent.min.js:2(anonymous function) @ web-torrent-view.js:25o @ webtorrent.min.js:13(anonymous function) @ webtorrent.min.js:13187.i.emit @ webtorrent.min.js:8(anonymous function) @ webtorrent.min.js:5195.u.run @ webtorrent.min.js:8l @ webtorrent.min.js:8

**Comment by feross** [comment]
What code are you using?

**Comment by MrTibbles** [comment]
I am using the example for streaming audio to player

https://github.com/feross/webtorrent/blob/master/examples/browser-stream-to-audio.js <https://github.com/feross/webtorrent/blob/master/examples/browser-stream-to-audio.js>

**Comment by feross** [comment]
Ah, this example is out of date. I just updated it:

https://github.com/feross/webtorrent/blob/master/examples/browser-stream-to-video-or-audio.js

**Comment by MrTibbles** [comment]
Thanks, thats working now. Thank you once again Feross, your a dude :)
