### ISSUE TITLE
Error: listen EADDRINUSE

### ISSUE THREAD

**Issue by Stiveknx** [feross/webtorrent#403]
It's been very a common error.
Checkout some debugs:

http://pastebin.com/raw.php?i=0NReWmLt

**Comment by Stiveknx** [comment]
Nevermind, webtorrent was runing in another tab, that's why the error was throwing ...

But, here's a question: Why I can't run two proccess at the same time?

**Comment by feross** [comment]
@Stiveknx 

This error means that the port WebTorrent wants to use (port 8000) is already in use. This could be from an other instance of WebTorrent, or any another program.

You can run WebTorrent on a different port by using the `--port` argument:

```
webtorrent --port 8001
```

This way you can run two instances of WebTorrent on different ports.

Related: https://github.com/feross/webtorrent/issues/411
