### ISSUE TITLE
concurrency and possible memory leak?

### ISSUE THREAD

**Issue by btmdave** [feross/webtorrent#407]
When running in node, it seems that there's some memory leaks.  I've setup 10 clients to download and it just climes up to 1.7g and cuts off.  Even with only a couple simultaneous downloads the memory just slow climes up over time, is this a known issue or are there any stats for running a higher level of concurrency?

**Comment by feross** [comment]
What version of WebTorrent are you using?

**Comment by btmdave** [comment]
0.60.0 with node 0.12.7.    Is there maybe a limit on the size of torrent? I saw some issues about buffer limits, not sure if that still holds true.

**Comment by feross** [comment]
Can you share the code that triggers this? I'll take a look.

**Comment by btmdave** [comment]
Cool thanks, here it is: https://gist.github.com/btmdave/1ea4b14b1754b8d7bffe

It's not actually doing it now for me as it's no longer downloading (re: #408)

**Comment by feross** [comment]
@btmdave 

Can you give it a try with webtorrent 0.57.0. We made significant code changes in 0.58.0 and I'm curious if that may be the cause.

```
npm install webtorrent@0.57.0
```

**Comment by shavyg2** [comment]
kk this version works alot better. I was getting memory of 1,800 MB but now it's under 400mb.
Torrent.pieceLength is missing tho.

**Comment by Stiveknx** [comment]
I'm facing some memory leaks too.
After 0.58.0.

I command line, I'm getting this error:

```terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

I'm trying to find what change is causing this leak, but there's a lot to look for.
That error may indicate something?

**Comment by antonheryanto** [comment]
got similar problem here webtorrent
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```
run on webtorrent 0.71.1 node v0.10.36 on nas (low cpu and memory) 128MB 
but peerflix running ok

**Comment by feross** [comment]
Running on node 4.x and WebTorrent 0.71.4, I have no memory issues.

RAM usage hovers around 130mb. But it occasionally rises to 200mb before going back down. I think there's a baseline of RAM usage that can't go away because it's all source code that is `require`'d by node.js. 

Try using a system with at least 500mb of RAM to avoid issues.

**Comment by feross** [comment]
Going to close this issue as I can't think of an easy solution to get RAM usage consistently below 128mb. If someone has any ideas, feel free to leave a comment.
