### ISSUE TITLE
Previous downloads cached?

### ISSUE THREAD

**Issue by btmdave** [feross/webtorrent#408]
Is there a cache for previous downloads? I downloaded a torrent, killed node, removed the directory from disk, but when i re-download the same one, it's goes to done right away and the full file(s) are there.

**Comment by btmdave** [comment]
In some cases it goes straight to done, but the files are zero bytes (for different previous downloads i killed partially through).

**Comment by feross** [comment]
If you don't specify a path option with `webtorrent --path <path>`, then a temporary path at `/tmp/webtorrent` is used. If you re-run WebTorrent than that previously downloaded data can be reused.

**Comment by feross** [comment]
Can you elaborate on your second comment? Are you saying that if a torrent was previously downloaded successfully that later downloads with `--out <path>` won't actually download anything to the given path?

**Comment by feross** [comment]
Closing this issue – it's so old that the parameter is now named `--out`.
