### ISSUE TITLE
npm error fetch failed

### ISSUE THREAD

**Issue by baratch** [feross/webtorrent#412]
Hi!
When I try to install webtorrent from npm , I have this error with mp4box.js
```javascript
npm ERR! fetch failed https://github.com/jhiesey/mp4box.js.git#nodified
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406
```

**Comment by feross** [comment]
Please run the following and share the output:

```
node -v
npm -v
```

**Comment by baratch** [comment]
1st row
```javascript
npm WARN engine windows-no-runnable@0.0.6: wanted: {"node":"0.6"} (current: {"node":"0.12.0","npm":"2.5.1"})
npm ERR! fetch failed https://github.com/jhiesey/mp4box.js.git#nodified
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 406
```

**Comment by feross** [comment]
Thanks for sharing the version of node you're using. I just tested on node 0.12.0 and confirmed that it doesn't work. If you update to the latest from the 0.12 series (node 0.12.7), then it installs without error! It looks like there's probably a bug in the older version that got fixed.

You can download the latest node release from https://nodejs.org.

**Comment by baratch** [comment]
Thanks a lot, i now upgrade node

**Comment by feross** [comment]
@baratch Cool - let me know if it works for you now!
