### ISSUE TITLE
--airplay flag not working

### ISSUE THREAD

**Issue by markhilton** [feross/webtorrent#413]
Not sure if this is a problem on Beta El Capitan OS X or dependencies, but webtorrent --airplay does not work for me. Seems like webtorrent is streaming magnet link but it does not connect with AppleTV, while --vlc option works great.

**Comment by feross** [comment]
What version is the software on your Apple TV? A recent update may have broken support. Knowing the version would help me debug this.

**Comment by markhilton** [comment]
Apple TV model A1469, software 7.2 (7512) - latest at the moment.

**Comment by feross** [comment]
Thanks for the version information! I'm currently traveling, but I will
test this out on my Apple TV when I get home in mid September.

If anyone else has an Apple TV -- please test if `webtorrent --airplay`
works for you and share your Apple TV version information here as well and
we can get to the bottom of this!

**Comment by feross** [comment]
@markhilton I just tested on an Apple TV with the exact same version info as yours (Apple TV model A1469, software 7.2 (7512)) and El Capitan, and it worked fine.

I expect that the `airplay-js` library wasn't updated to support the latest of Apple TV when you opened this issue.

**Comment by feross** [comment]
Note: this can also be network dependent. Your network might block mdns discovery traffic.
