### ISSUE TITLE
NodeJS install of webtorrent-hybrid broken ?

### ISSUE THREAD

**Issue by Daemon024** [feross/webtorrent#421]
Hi
So the last 3 hours i tried to install the webtorrent-hybrid server, on different clouds machines.
**Tried with my dedicated server with Ubuntu 14.04 -> Errors
Tried with cloud vm Ubuntu 12.04 -> Errors
Tried with cloud vm Debian Wheezy -> Errors
Tried with NodeJS Image from AWS -> Errors**

All comes with this error (with the updated node version from the repo) : 
```
 node-pre-gyp install --fallback-to-build
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.38"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/webtorrent-hybrid/node_modules/wrtc/.node-gyp"
```
**Or** 
```
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (evalmachine.<anonymous>:107:15)
```
Any idea how to fix this ? Cant go further in the dev without working server for seeding.

**Comment by VoR0220** [comment]
Chances are you're using the Node 0.13.3-pre version....which sucks, use a stable version. 

Install nvm and then run

    nvm install v0.12.2 

and rerun the commands and then you should be able to get it to run. Be patient though. It's a monster of a file load.

**Comment by Daemon024** [comment]
Hi
I tried, but i got the same error 

npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build

Seem like this error is with the latest Node version AND the version 0.12.2 …
Find attached the log file

Any idea how to fix this ? 
Cant seed without it, or go further in development….
Thanks

**DEBUGG LOG FILE : **
http://git.io/vGpxc

**Comment by Daemon024** [comment]
So tried this whole afternoun 
The error is persistent, if i try to use 'older' version of node js with nvm, i got bunch of error because most depedency are not available, and if i try 'newest or actual stable' one, i always end up with error from 

node-pre-gyp, which seem to be needed for the wrtc package not installing.

I tried npm install gyp, which work.
It tried then npm install pre-gyp, which dosnt't work
And then tried install wrtc but with no luck
so i'am stuck with this error : 

npm ERR! wrtc@0.0.58 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wrtc@0.0.58 install script 'node-pre-gyp

On all distro (tried Ubuntu 12.04, 14,04, Fedora, differents nodesjs version, compile from repo etc...)
HELP pls

**Comment by gillesdemey** [comment]
Did you check if you have the correct dependencies installed?
https://github.com/js-platform/node-webrtc#debianubuntu

Either way, it sounds like this is an issue with node-wrtc, not WebTorrent.

**Comment by Daemon024** [comment]
No i didn't so here the process i used : 
```bash
apt-get update && apt-get upgrade
apt-get install curl python2.7 git-all pkg-config libncurses5-dev libssl-dev libnss3-dev libexpat-dev gcc g++ make build-essential
curl https://raw.githubusercontent.com/creationix/nvm/v0.11.1/install.sh | bash
source ~/.profile
nvm install v0.12.2
node-gyp --python /path/to/python2.7
npm install webtorrent-hybrid
```
On Ubuntu 14.04 (clean/fresh install) : Error, same as before 
![image](https://cloud.githubusercontent.com/assets/9357072/9700761/cad3062a-540f-11e5-8f68-f63c7d4cc4eb.png)

**Comment by Daemon024** [comment]
Find out that the problem is with node-pre-gyp (gyp) on ARM7 servers (all cloud servers that i'am using).
Tried the same process on a Vmware vm got no issues.
So i need to find a way to build the node-pre-gyp package on arm...
Any ideas ?

**Comment by DiegoRBaquero** [comment]
Did you find a solution??? I have pretty much tried every major version of node and I still can't get it to install on Mac/Linux

**Comment by feross** [comment]
Sorry about this issue, guys. I think we'll just have to wait for a better node.js implementation of webrtc to come along. I'm currently holding out for https://github.com/nickdesaulniers/node-rtc-peer-connection by @nickdesaulniers which has no native dependencies, so it'll have no build issues. It's not finished yet, but it's shaping up nicely so far!
