### ISSUE TITLE
Parse torrent file from XMLHttpRequest

### ISSUE THREAD

**Issue by jakefb** [feross/webtorrent#424]
I want to stream a video in the browser from a .torrent file. To do this I have made an XHR request to return a buffer, which I want to parse with parse-torrent and download with WebTorrent. This is because I want to load the whole torrent file, so I can start streaming for a HTTP WebSeed, without having to wait for WebRTC peers to connect.

I don't know how to do this so help would be greatly appreciated. Here's my code:

    function reqListener () {
      console.log('.torrent file download')

      var videoTorrent =  new Uint8Array(this.response)
      var parsedTorrent =  parseTorrent(videoTorrent)
      client.add(parsedTorrent, onTorrent)
    }

    var oReq = new XMLHttpRequest()

    oReq.addEventListener("load", reqListener)

    oReq.responseType = 'arraybuffer';

    oReq.open('GET', '/torrents/yosemite-hd.torrent', true)

    oReq.send()

    function onTorrent (torrent) {
      ...
    }

**Comment by jakefb** [comment]
I managed to get this working by using [stream-http](https://github.com/jhiesey/stream-http) - thanks @jhiesey

    var parseTorrent = require('parse-torrent')
    var http = require('stream-http')
    var WebTorrent = require('webtorrent')

    var torrentName = 'awakening-new-zealand-4k.torrent'

    http.get('/torrents/' + torrentName, function (res) {
      var data = [] // List of Buffer objects

      res.on("data", function(chunk) {
        data.push(chunk) // Append Buffer object
      })

      res.on("end", function() {
        data = Buffer.concat(data) // Make one large Buffer of it

        var torrentParsed = parseTorrent(data) // Parse the Buffer

        var client = new WebTorrent()

        client.add(torrentParsed, onTorrent)

        function onTorrent (torrent) {
          ...
        }
      })
    })

**Comment by bertofer** [comment]
Hi, i'm trying this code, but i want to send the buffer from inside node.js instead of accessing it with an http-server. I'm getting this when trying to add it to the webtorrent client:

Invalid data: Missing delimiter ":" [0x3a]

From the bencoder,

Any tip?

The torrent i'm generating is like that:

var torrentOpts = {
        name: req.files.file.name, // Get from the front end!!
        createdBy: 'Alberto',
        creationDate: Date.now(),
        private: true,
        announceList: [['localhost:8000']], // IP of my tracker and port.
        urlList: 'localhost:9000/' + req.files.file.name
      }

Thanks!

**Comment by vintikzzz** [comment]
It could be achieved without additional dependencies. The main idea is to convert from ArrayBuffer to Buffer.
This works!
```
            const xhr = new XMLHttpRequest();
            xhr.onreadystatechange = function() {
              if (this.readyState == 4) {
                const ab = new Uint8Array(this.response);
                const buffer = new Buffer(ab.byteLength);
                const view = new Uint8Array(ab);
                for (let i = 0; i < buffer.length; ++i) {
                  buffer[i] = view[i];
                }
                const torrent = parseTorrent(buffer);
              }
            };
            xhr.open('GET', 'http://exmaple-url');
            xhr.responseType = 'arraybuffer';
            xhr.send();

```

**Comment by SilentBot1** [comment]
Hey @vintikzzz, since the original post, the WebTorrent library ([parse-torrent](https://github.com/webtorrent/parse-torrent)) added support for passing through a URL to a `.torrent` file while calling `client.add()`. 

An example of this in action:

```
var WebTorrent = require('webtorrent')
var client = new WebTorrent()

var torrent = client.add("https://webtorrent.io/torrents/sintel.torrent")
```
Note: In a browser the URL must have the header 'Access-Control-Allow-Origin' set while in Node.js, it doesn't mind.

**Comment by jakefb** [comment]
Thanks @vintikzzz and @SilentBot1  :smiley:

Good to know that this is supported in parse-torrent
