### ISSUE TITLE
Can't install webtorrent

### ISSUE THREAD

**Issue by Faraonul** [feross/webtorrent#428]
I started playing with node a couple days ago and stumbled across this webtorrent thing, but I can't manage to make it work. Can you guys please help me?

Output for npm install webtorrent : http://paste.ubuntu.com/12330650/

thanks

**Comment by Jenso** [comment]
Same problem for me.

Using Centos 7

Npm output - http://pastebin.com/aM17Dy10

**Comment by maca134** [comment]
I think the problem is with the videostream dep requiring mp4box which seems to have been taken down...
https://github.com/jhiesey/mp4box

**Comment by maca134** [comment]
Im having the same issue

**Comment by feross** [comment]
You guys are all using node 0.10, which is not supported by WebTorrent.

I think node 0.10 has issues with the git dependency used by the `videostream` package, which WebTorrent requires.

I suggest using node v4 or node v5.
