### ISSUE TITLE
Making webtorrent stream using standalone script

### ISSUE THREAD

**Issue by josaric** [feross/webtorrent#431]
https://github.com/feross/webtorrent/wiki/FAQ

I'm not getting this answer right, do you mean that if nobody seeds a torrent file, I can't upload it?

Can I stream and seed torrent using standalone webtorrent.min.js script?

I'm trying to make small site to stream video, just copying magnet link, do you have any example of that, if do, can you send it to me? Thank you very much! :)

**Comment by feross** [comment]
> **Why does browser downloading not work?**

> It does work! But you can't just paste in any random magnet uri or .torrent file. Is the torrent being seeded by a webrtc-capable client, i.e. webtorrent-hybrid or instant.io?

> In the browser, WebTorrent can only download torrents that are explicitly seeded to web peers via a WebTorrent capable client. Desktop torrent clients need to support WebRTC to peer with web browsers.

With WebTorrent, you can download any torrent from the network as long as there are seeders. This is how regular BitTorrent works too.

The point that the FAQ answer is trying to make is that you can't download any old torrent. There have to be "web peers" seeding it. Peers that support WebRTC and WebTorrent.

**Comment by josaric** [comment]
So, can I be seeder by using your script?

**Comment by feross** [comment]
Yes, you can be a seeder with the WebTorrent script.
