### ISSUE TITLE
Dowload torrent without seed

### ISSUE THREAD

**Issue by 4gnostic** [feross/webtorrent#435]
First my english is bad. 

I want to stream torrent videos in my website. I think i have to seed file before dowload.

I mean how can i stream any torrent files(videos or audios) without seed ? because my internet (up/down) very low. Is this possible ?

**Comment by ArtskydJ** [comment]
Webtorrent in the browser is unable to communicate with torrent clients, except for other webtorrent clients.

If the video has webtorrent clients seeding it, you should be able to "stream" it, but it'll need to buffer for a while if your internet is slow.

**Comment by feross** [comment]
Thanks for the helpful answer @ArtskydJ :+1:
