### ISSUE TITLE
filed download and seed

### ISSUE THREAD

**Issue by zoudf** [feross/webtorrent#437]
Hi,
Today I got error code:

WebSocket connection to 'wss://tracker.webtorrent.io/' failed: Connection closed before receiving a handshake response

How's going on?

**Comment by feross** [comment]
Is this error persistant? Sometimes trackers might not be reachable. If you want to guarantee that your app that depends on WebTorrent always works, you should consider running your own instance of [`bittorrent-tracker`](https://github.com/feross/bittorrent-tracker).

**Comment by zoudf** [comment]
Not persistent error, Sometimes occur.
thank you.
