### ISSUE TITLE
Webtorrent without tracker.

### ISSUE THREAD

**Issue by bachlx-bitmark** [feross/webtorrent#438]
Hi Feross.

I'm using webtorrent, but I don't use bitorrent-tracker, to add a peer to download I use torrent.addPeer(addr). But, I really run on LAN network with "addr" is IP and port of computers.
When two computers in the different LAN network, I don't know what is "addr".
Because a computer has public IP address and private IP address.

Please help me.
Thanks!

**Comment by feross** [comment]
You can usually just use the built-in list of torrents in a .torrent file or magnet link. If your use case is your own private torrents, then you should consider running your own bitorrent-tracker instance to make peer discovery automatic and easy.

That said, if you want to use `torrent.addPeer(addr)`, you need to know an IP address that will let you reach another peer. Usually it's safest to just use the public IP address. But you can try passing in the private IP address as well, especially if you know the peers are on the same network.

Don't worry if the host at the IP address might not be reachable – the torrent client is smart enough to try and give up after a number of consecutive connect failures. Just add both the public and private IPs.

You can get the port that the torrent client is listening on by calling `client.address().port`.

**Comment by bachlx-bitmark** [comment]
Thanks, I will try.

**Comment by feross** [comment]
Great - feel free to ask additional questions if you run into trouble.
