### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by van-nguyen** [feross/webtorrent#454]
HI there, it seems to be trying to do everything in memory and causes very high memory usage with large torrents. i.e. a 10GB torrent will use more than 10GB of memory, is it possible to flush the streams in smaller chunks? Cheers.

**Comment by ngjermundshaug** [comment]
Hi, I believe I have fixed this issue here: https://github.com/feross/webtorrent/pull/447 

Tests won't run properly on my windows machine, so if you could take a look at this it would be great.

**Comment by feross** [comment]
Piece verification is now throttled so the number of pieces that are verified at a time matches the number of cpu cores on the machine.

Released as 0.72.1.
