### ISSUE TITLE
Problem seeding using tcp from the server side

### ISSUE THREAD

**Issue by thehobbit85** [feross/webtorrent#460]
I'm trying to create a simple file seeding using some default trackers but even after the seed has "started" and the callback is being called, when I try to leech the file using the magnet link and uTorrent/Transmission/WebTorrent (Tried all three) the download never starts and it stays stuck on "downloading metadata"

I tried seeding and leeching from a variety of machines (mac, linux and windows) and I just never start downloading.

This is the code I'm running (I'm using webtorrent 0.62.2):

```js
var WebTorrent = require('webtorrent')

var opt = {
  announce: [['udp://tracker.openbittorrent.com:80', 'udp://open.demonii.com:1337', 'udp://tracker.coppersurfer.tk:6969', 'udp://tracker.leechers-paradise.org:6969']]
}

var client = new WebTorrent(opt)
var fileName =  './Screen.png'
client.seed(fileName, opt, function (torrent) {
  console.log(torrent.magnetURI)
})
```

**Comment by eliooses** [comment]
I think what this issue are the same thing of many others:

udp and dht trackers is not compatible with webtorrent peers seeds.

**Comment by thehobbit85** [comment]
Ok, thats good to know....
And how can that be fixed? 
If I run my own tracker (the webtorrent one) can that be solved?

**Comment by eliooses** [comment]
You must keep calm and wait for an update. Are devs works in this, here in /feross/webtorrent/ and other repositories:

https://github.com/jhiesey/webdht

**Comment by hualiwang** [comment]
As I think, webrtc can not talk to tcp and udp protocol.

**Comment by rom1504** [comment]
it is definitely possible to seed in node and download in uTorrent/Transmission/WebTorrent

if that doesn't work, it's a bug. (But I think it does work)

**Comment by devTristan** [comment]
I think you want to be using webtorrent-hybrid if you want compatibility with the bittorrent network

**Comment by hualiwang** [comment]
It will be great if can seed in node and download in utorrent/webtorrent(chrome)
but I tried many times ,never successed. 
but as you said , I will try it again .

**Comment by solderzzc** [comment]
Are you seeding in Nodejs behind NAT?


It will be great if can seed in node and download in

**Comment by hualiwang** [comment]
I seeding in nodejs  in public IP(digitalocean vps)
![webtorrent](https://cloud.githubusercontent.com/assets/16126643/12214306/bacda042-b6c9-11e5-8f5c-055556c1faa2.jpg)

I try it again ,still failed.
 v0.71.3

**Comment by solderzzc** [comment]
I guess your webtorrent command use different tracker other than
Instance.io.

**Comment by DiegoRBaquero** [comment]
@hualiwang You are seeding in TCP/UDP and trying to download in WebRTC. It just won't work.

**Comment by feross** [comment]
The current recommendation is to make sure that you're seeding using [`webtorrent-hybrid`](https://github.com/feross/webtorrent-hybrid), which can seed to browser peers.

 I am going to work on making that work a lot better soon (i.e. it should use Electron), since it's really hard to install right now.
