### ISSUE TITLE
Error trying to acess: client.ratio

### ISSUE THREAD

**Issue by Stiveknx** [feross/webtorrent#463]
According to API, I can access a "global" ratio.

But when I try to access:

``client.ratio``

It fails with:
``TypeError: Cannot read property 'length' of undefined
    at Torrent.Object.defineProperty.get (/home/webtorrentapp/node_modules/webtorrent-hybrid/node_modules/webtorrent/lib/torrent.js:106:42)``

I tryied commenting ``this.pieces.length`` in line:
https://github.com/feross/webtorrent/blob/master/lib/torrent.js#L106

The error goes away.
Apparently is: I created a new torrent. The torrent is added in client.torrents, but no pieces were found / or downloaded yet. So when I call client.ratio, it calls all torrents and count his pieces, but no pieces were downloaded.

**Comment by DiegoRBaquero** [comment]
Solved in 0.63.4 with https://github.com/feross/webtorrent/commit/efa410dc279bff80f5ab6ffcbcc87279e3737908

Not yet published in NPM as feross hasn't been around.
