### ISSUE TITLE
I2P

### ISSUE THREAD

**Issue by aaannndddyyy** [feross/webtorrent#465]
Please support an option for secure anonymous file sharing (slow) via I2P network.
( https://geti2p.net )
libtorrent comes with i2p support and Vuze has a plugin that even bundles the i2p router.
You need not bundle it, but could simply require the user to have it installed and running.

**Comment by TheNain38** [comment]
+1, Yes, it would be cool to be able to use I2P to download content directly in the browser

**Comment by eliooses** [comment]
+1

**Comment by feross** [comment]
Sorry, I think this isn't a top priority for us right now.

WebTorrent's primary focus right now is to make the WebRTC/browser implementation really solid.

I'm not completely ruling out I2P support forever, but it doesn't make sense for me to devote my time to it right now. If someone wants to step up to work on this, and make a proposal for how this would even work, I'm all ears.
