### ISSUE TITLE
Can't fetch peers: ICE (always) failed

### ISSUE THREAD

**Issue by gustavomrfz** [feross/webtorrent#467]
Hi,

I'm making a browser application with webtorrent module and bittorrent-tracker via web socket to sharing audio files and append them to a playlist. File sharing works fine inside a local area network, but the peers aren't fetched when they are behind a NAT. When I analyze traffic with Wireshark and about:webrtc, STUN servers return the remote private and public IP addresses with their UDP ports, but ICE process always fail. Application is using google STUN servers, but this behaviour exists with any server.

I'm using a global announce for tracker in client script. I launch the tracker with bin/cmd.js script. The tracker receive start message from peers, but never start really.  

What could be happening?  Must I set some options in the client script? Somes changes in bittorrent-tracker are needed? 

Thank you in advance.

**Comment by feross** [comment]
Sounds like you have a really restrictive NAT. You can specify a TURN server for these situtations, but the transfer won't be P2P anymore.

```js
var WebTorrent = require('webtorrent')
var client = new WebTorrent({
  rtcConfig: { /* fill this in with your server details */ }
})
```

More info here: http://www.html5rocks.com/en/tutorials/webrtc/basics/
