### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by pdutt111** [feross/webtorrent#468]
npm ERR! not a package /var/folders/w2/qgtvh7v57px6jp37192fg6w40000gn/T/npm-1429-_wC1GVxX/github.com/jhiesey/mp4box.js.git
    npm WARN optional dep failed, continuing node-ssdp@2.6.3
    npm ERR! Error: ENOENT, open '/var/folders/w2/qgtvh7v57px6jp37192fg6w40000gn/T/npm-1429-_wC1GVxX/github.com/jhiesey/mp4box.js.git-unpack/package.json'
    npm ERR! If you need help, you may report this *entire* log,
    npm ERR! including the npm and node versions, at:
    npm ERR!     <http://github.com/npm/npm/issues>
    
    npm ERR! System Darwin 15.0.0
    npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "webtorrent@latest" "--save"
    npm ERR! cwd /Users/pariskshitdutt/WebstormProjects/WoobusRaspberryPi
    npm ERR! node -v v0.10.36
    npm ERR! npm -v 1.4.28
    npm ERR! path /var/folders/w2/qgtvh7v57px6jp37192fg6w40000gn/T/npm-1429-_wC1GVxX/github.com/jhiesey/mp4box.js.git-unpack/package.json
    npm ERR! code ENOENT
    npm ERR! errno 34
    npm ERR! not ok code 0

error while npm installing webtorrent

**Comment by DiegoRBaquero** [comment]
Try using node 0.12

**Comment by feross** [comment]
The version of node that you're using is really old. Try installing the latest version (v4) from https://nodejs.org/
