### ISSUE TITLE
Cannot seed and download from same Node.js process?

### ISSUE THREAD

**Issue by olalonde** [feross/webtorrent#469]
So I have a Node.js file where I start seeding a file with `client1` and create a `client2` that downloads it using a magnet URI. I hardcoded the `torrentPort` for client1 to `20001` so that it doesn't conflict with client2. 

The download doesn't seem to work for some reason. However if I repeat the process but comment out the client1 download part and instead download the file using the `webtorrent` client from another shell session, it downloads correctly.

Is there anything in the code that might explain this? I recall seeing `refusing handshake with self` errors in the logs. Is this a bug related to the fact that both clients share the same node process?

Both clients have different peerIds/nodeIds.

Here's part of the log output:

```bash
Tue, 27 Oct 2015 09:20:27 GMT bittorrent-swarm addPeer 183.17.152.194:20001
Tue, 27 Oct 2015 09:20:27 GMT bittorrent-swarm:peer new Peer 183.17.152.194:20001
Tue, 27 Oct 2015 09:20:27 GMT bittorrent-swarm tcp connect attempt to 183.17.152.194:20001
Tue, 27 Oct 2015 09:20:27 GMT bittorrent-swarm:peer Peer 183.17.152.194:20001 connected
Tue, 27 Oct 2015 09:20:27 GMT bittorrent-swarm:peer new Peer ::ffff:183.17.152.194:51646
Tue, 27 Oct 2015 09:20:27 GMT bittorrent-swarm:peer Peer ::ffff:183.17.152.194:51646 connected
Tue, 27 Oct 2015 09:20:27 GMT bittorrent-swarm _addIncomingPeer ::ffff:183.17.152.194:51646
Tue, 27 Oct 2015 09:20:27 GMT bittorrent-swarm:peer destroy ::ffff:183.17.152.194:51646 (error: refusing to handshake with self)
Tue, 27 Oct 2015 09:20:27 GMT bittorrent-swarm removePeer ::ffff:183.17.152.194:51646
Tue, 27 Oct 2015 09:20:27 GMT bittorrent-swarm:peer destroy 183.17.152.194:20001 (error: undefined)
Tue, 27 Oct 2015 09:20:27 GMT bittorrent-swarm removePeer 183.17.152.194:20001
Tue, 27 Oct 2015 09:20:27 GMT bittorrent-swarm conn 183.17.152.194:20001 closed: will not re-add (max 3 attempts)
```

183.17.152.194 being my IP.

**Comment by olalonde** [comment]
Well, this is not really a priority so closing.

**Comment by feross** [comment]
@olalonde Yeah I think this is due to the `bittorrent-swarm` package using the same listening port for both clients. I think this might have been fixed in the last month or two, but I can't remember.
