### ISSUE TITLE
webtorrent + webrtc + AWS ec2 server seeding issues

### ISSUE THREAD

**Issue by olalonde** [feross/webtorrent#472]
I'm having trouble seeding a file over webrtc from an ec2 machine (webtorrent-hybrid). Are there any specific ports that need to be opened? I've opened `opts.torrentPort` and `opts.dhtPort` in my ec2 security group and both dht + regular bittorrent protocol are working. I can't however seem to download anything from my browser over webrtc which is seeded from that server.

**Comment by DiegoRBaquero** [comment]
I'm having a similar problem on a DO droplet. There's no firewall rules at all.

**Comment by olalonde** [comment]
I also tried disabling firewall rules but not luck. I'm running my app in Docker though which might make things more complex too. I also noticed that when I enable webrtc support, my server CPU usage skyrockets.

**Comment by Chocobozzz** [comment]
@olalonde See https://github.com/feross/webtorrent-hybrid/issues/5

But same here, I can't seed from a Docker image.

**Comment by olalonde** [comment]
Thanks for pointing to this issue, I'm having same issues as you it seems.

**Comment by Chocobozzz** [comment]
Finally doesn't seem to be a Docker issue, I can view videos with the host from a webtorrent server seeding inside Docker.

**Comment by DiegoRBaquero** [comment]
@olalonde have you fixed it? I got a semi-working seeder using xfvb (as fake screen, so no need to install a GUI desktop), electron-spawn (headless electron wrapper) (to make it work as a browser). The problem I have is that the process dies after a few hours (haven't really investigated why).

**Comment by feross** [comment]
It sounds like you guys got this figured out, and the remaining issues are just related to `wrtc` crashing after a while and taking a lot of CPU :(
