### ISSUE TITLE
Select path where download file

### ISSUE THREAD

**Issue by rokity** [feross/webtorrent#473]
Hi

i want to know if there is a way to choose a path where download the torrent.
If there is , can you explain me with some examples.
Thank you

Riccardo

**Comment by gillesdemey** [comment]
If you're using the library, you can specify the path in the `opts`, the default path is `/tmp/webtorrent`.

See https://github.com/feross/webtorrent#clientaddtorrentid-opts-function-ontorrent-torrent-

If you're using the CLI, you can specify the download path using the `-o / --out` option and supply a path.

**Comment by feross** [comment]
Yep, what @gillesdemey said.

```
webtorrent "magnet-link" --out /path/to/folder
```
