### ISSUE TITLE
How to launch external media player to play torrent stream?

### ISSUE THREAD

**Issue by tsoernes** [feross/webtorrent#474]
Is it possible to play the torrent file in an external media player as it is being streamed? How?
```
var WebTorrent = require('webtorrent')

var client = new WebTorrent()
var magnetUri = '...'

client.add(magnetUri, function (torrent) {
  torrent.files.forEach(function (file) {
       // play file with vlc or mpc-hc
  })
})
```
Thanks

**Comment by DiegoRBaquero** [comment]
You can use the command line version for that. https://github.com/feross/webtorrent#as-a-command-line-app

**Comment by tsoernes** [comment]
That won't do, unless it is possible to use command line args from inside a node js module?

**Comment by DiegoRBaquero** [comment]
Why not? If I may ask. And no, at least not for webtorrent.

**Comment by tsoernes** [comment]
I get the magnet link from a web scraper written in nodejs

**Comment by gillesdemey** [comment]
You can use the `torrent.createServer` function to create an HTTP server that serves the torrent's contents.

https://github.com/feross/webtorrent#torrentcreateserveropts

**Comment by DiegoRBaquero** [comment]
Have you looked at https://github.com/mafintosh/playback ? It has WT support

**Comment by tsoernes** [comment]
@gillesdemey Thanks, just what I needed.
@DiegoRBaquero Looks cool but it does not support the formats/codecs I need to play

Solved

**Comment by feross** [comment]
Awesome – glad your issue was solved.

Thanks @gillesdemey and @DiegoRBaquero!
