### ISSUE TITLE
Large torrent -  FATAL ERROR: Out Of Memory

### ISSUE THREAD

**Issue by dragonpiper** [feross/webtorrent#475]
I have 24GB of ram. When trying to start a 2GB+ torrent i get 

FATAL ERROR: node::smalloc::Alloc(v8::Handle<v8::Object>, size_t, v8::ExternalArrayType) Out Of Memory

Is there anyway to fix or avoid this ?

**Comment by DiegoRBaquero** [comment]
Because WebTorrent stores the files in memory too at the moment, it's a limitation of V8 engine.

**Comment by feross** [comment]
@dragonpiper Did you run into this error while using WebTorrent in the **browser**?

**Comment by feross** [comment]
@dragonpiper Without further info, we can't reproduce this issue. I just tried seeding a 4.5GB torrent without issues. Closing.
