### ISSUE TITLE
Someones crashes.

### ISSUE THREAD

**Issue by eliooses** [feross/webtorrent#476]
Hi there!, i´m testing the browser version of webtorrent and in a timelapse of 12 hours aprox. i have 4 crashes.

I attach someones captures if that is for help.

My upload connection is very poor, i presume what that affects the performance because the connection is refused, but in other cases is crash spontaneously.

![sin titulo](https://cloud.githubusercontent.com/assets/5062034/10902967/12a58e40-81e3-11e5-8eb5-5676efb74fe7.png)
![sin titulo2](https://cloud.githubusercontent.com/assets/5062034/10902975/363dfe78-81e3-11e5-8ca4-92d4264bd997.png)
![sin titulo3](https://cloud.githubusercontent.com/assets/5062034/10902976/36454890-81e3-11e5-971f-447cc73483e8.png)
![sin titulo4](https://cloud.githubusercontent.com/assets/5062034/10902977/364bc512-81e3-11e5-9f68-8e2f9e0155cb.png)

**Comment by DiegoRBaquero** [comment]
The issue is the RAM. The message clearly states it.

**Comment by eliooses** [comment]
The first and the second yes, but the third and fourth not. I only report that if this help. The RAM collapse is weird becausa i have 8 GB of RAM and only load Sublime Text and Instantio (an many tabs of GitHub but is not relevant).

**Comment by DiegoRBaquero** [comment]
The time out of the websocket must be and issue of the tracker server I think. Unless you whatever reason you are being blocked? (Which I doubt it).

The RAM issue, I've had it too. I suppose chrome does this to protect a tab from consuming all the RAM. The thing is, I think, that any torrent downloaded content is maintained in RAM until you download it from its blob url.

And nice series btw.

**Comment by eliooses** [comment]
@DiegoRBaquero ! no respondí en español para que todos puedan leer. #lol 

Si, te entiendo perfectamente. Genial, entonces será un tema de Chrome. Te pregunto ya que veo que estas bien activo en el tema. Sirve que reporte este tipo de cosas?

Abrazo.

**Comment by DiegoRBaquero** [comment]
Supongo que sí. A mí me pasa lo mismo cuando intento hacer stream un torrent pesado, aún cuando no hay problemas al hacer seed inicial.

Y sí! Todo reporte ayuda! Así intentamos llegar a soluciones en conjunto, como comunidad.

**Comment by feross** [comment]
If you seed files greater than 2GB in size, you will likely crash Chrome. See https://github.com/feross/webtorrent/issues/319.

**Comment by amilajack** [comment]
Will node crash in the same situation?

**Comment by feross** [comment]
@amilajack No -- in node.js, WebTorrent uses [`fs-chunk-store`](https://www.npmjs.com/package/fs-chunk-store) instead of [`memory-chunk-store`](https://www.npmjs.com/package/memory-chunk-store), so you're not limited by the maximum JS buffer size.

**Comment by amilajack** [comment]
Is it possible to require only the node module, is it possible to import the node version of webtorrent in electron instead of the browser version?

**Comment by feross** [comment]
@amilajack If you do `require('webtorrent')` in Electron, you get the node.js version. But you'll get WebRTC support for free too, because webtorrent detects it in the Electron environment.

If you want the browser version, then you can use the minified script `webtorrent.min.js` via a `<script>` tag.
