### ISSUE TITLE
Idea to get more seeds on the webtorrent network.

### ISSUE THREAD

**Issue by B00tLdr** [feross/webtorrent#478]
Hi guys! I really like your project and have been following it since the beginning.
Now that most of the stuff seems to be working i have some ideas to get people to use the network and close the bridge to the standard protocol.

Most of opensource projects use libtorrent as a backend for their torrenting, especially the new ones that stream media directly like butterproject and popcorntime.

My proposal is that you either fork libtorrent and make it work with webtorrent or get the developer to add the missing bits himself(would probably need an accepted BEP).

It seems that you are making your own client right now for desktops but i do not think that it will get popular unless it really gives people something they miss(eg something like popcorn-time).

Now that the main popcorntime fork is dead there is a huge demand for a new one(especially a open source client) and thats why i propose that you work with the butterproject/libtorrent since i belive they would be very interest in having a lite version of the app as a website that could do most of the things that the native client can do but with some missing features(e.g chromecasting etc) and if people want those features they would have to download the binary(with webtorrent support) instead.

This way the content that can be fetched from the binary also would be well seeded to webtorrent peers and maybe the protocol would get popular enough to be incorporated into other torrent clients.

I hope you understand what i'am propsing and sorry for my bad english.

**Comment by rom1504** [comment]
see https://github.com/feross/webtorrent/issues/369

**Comment by DiegoRBaquero** [comment]
Just commenting on the Popcorn-time idea: Although it could promote the project, @feross wouldn't like to see it involved in illegal activities, much less when the project is still in its alpha/beta stage.

**Comment by jtremback** [comment]
Does @feross have a specific jurisdiction whose laws he does not want to see broken?

**Comment by ericwooley** [comment]
@jtremback It's probably not a legal thing it's a perception thing. Technical projects do not want to mix with pirating, because they don't want that association. Take the project and use it how you will, but don't associate piracy with a particular tech.

**Comment by andreapaiola** [comment]
I'm developing a site, a video streaming hub, a near-infinite video queue.
Sure, the content of the video could be illegal in various countries, but the accountability is not mine.

**Comment by ericwooley** [comment]
@andreapaiola If your content might be illigal, keep it to yourself, github is a place for technical discussion.

**Comment by feross** [comment]
Please don't use WebTorrent for copyright infringement. As others have said, that's not something the WebTorrent developers support or can help you with.

If you support copyright infringement, please go find another open source project to contribute to. That sort of activity is not welcome here.
