### ISSUE TITLE
How to disable seeding ?

### ISSUE THREAD

**Issue by roonie007** [feross/webtorrent#480]
Hey guys , how to disabled Torrent seeding when it starts downloading ? i am using NodeJS

**Comment by DiegoRBaquero** [comment]
You can't. You don't.

**Comment by feross** [comment]
As @DiegoRBaquero says, there's no way to disable seeding.

The best you can do is to call `torrent.destroy()` after the download is complete to remove the torrent from the client and stop seeding.
