### ISSUE TITLE
leveldown for storing data

### ISSUE THREAD

**Issue by calvinmetcalf** [feross/webtorrent#486]
it should be possible to seed and download to a levelup db if the file was broken up and the chunks stored separately.  This could prevent some of the out of memory issues that are being seen.  You could still stream out of it without putting it all in memory.

**Comment by calvinmetcalf** [comment]
looks like it could also be done by subing out an indexeddb based chunk store for the memory one by default

**Comment by DiegoRBaquero** [comment]
Some stores have been created. At the moment I'm working on https://github.com/DiegoRBaquero/lf-chunk-store, it wraps IndexedDB, WebSQL and localStorage, it shows promise

**Comment by feross** [comment]
@calvinmetcalf Yeah, the approach we want to take is the indexeddb chunk store.
