### ISSUE TITLE
HTML only out-of-box working example

### ISSUE THREAD

**Issue by Fastidious** [feross/webtorrent#487]
Would it be possible to have an out-of-box working example, using only HTML (no Node), along the way of `instant.io`, or similar (if it is not possible to have it exactly like it)?

**Comment by blairanderson** [comment]
Instant is open

https://github.com/feross/instant.io

**Comment by Fastidious** [comment]
@blairanderson correct me if I am wrong, doesn't instant.io use Node?

**Comment by raphaelparent** [comment]
You're right, it does run on Node.

**BUT**, if you look in the code, everything that is WebTorrent related is on the client side

**Comment by Fastidious** [comment]
> if you look in the code, everything that is WebTorrent related is on the client side

@raphaelparent that is the thing, I am not a programmer. Yet, I would love to have a full working example (which could be use on a daily bases, like `instant.io`) of `webtorrent` using *only* HTML5 and JS, no Node, or any extras, say to upload a file, serve it via torrent, and allow the download of it (all browser to browser).

**Comment by raphaelparent** [comment]
Ok I get your point now, someone should convert the Jade view to html and make it work with the `.js` file. 

If you know HTML and work you way around the Jade file you should be able to recreate the HTML part and you can use the file `/client/index.js` as the script.

Otherwise someone you know is way around Jade and HTML should be able to do it pretty easily.

**Comment by elad** [comment]
There are working browser-only examples, [browser-seed.js](https://github.com/feross/webtorrent/blob/master/examples/browser-seed.js) and [browser-download.js](https://github.com/feross/webtorrent/blob/master/examples/browser-download.js).

**Comment by Fastidious** [comment]
@elad could you put it all together in a simple HTML page (index.html plus JS)?

**Comment by elad** [comment]
If https://file.pizza/ doesn't do what you want, you'll have to figure this one out yourself I'm afraid...

**Comment by Fastidious** [comment]
@elad sigh... https://file.pizza/ uses Node. It is not the same. Thanks for trying though, appreciated.

**Comment by DiegoRBaquero** [comment]
Have you checked out my client? https://github.com/DiegoRBaquero/BTorrent

It's Jade, CoffeeScript and Sass (HTML, Javascript and CSS). Three simple files.

The compiled version is https://btorrent.xyz, thought the files are minified and rendered (angular).

If you'd liked HTML, JS and CSS (in case you really don't understand Jade/CoffeeScript/CSS) I can compile a non-minified versions.

Cheers

**Comment by Fastidious** [comment]
@DiegoRBaquero that is most excellent, thanks! I have played with it, and already have three issues opened for you. :-) Closing this one here, as you provided what I asked for.

**Comment by feross** [comment]
Let's add some complete HTML examples to the examples/ folder, because I keep getting this request from people.

"On github you provide JS examples, but I couldn't find any HTML examples, that is required."

**Comment by professorhaseeb** [comment]
agreed.

**Comment by feross** [comment]
Here's a PR that adds the example: https://github.com/feross/webtorrent/pull/538
