### ISSUE TITLE
Powerfull But Crashes | I Tested A Simple One Page PHP

### ISSUE THREAD

**Issue by besoeasy** [feross/webtorrent#489]
Hi I Test Your Script But It Crashes Most Of Time 

Using This 
var client = new WebTorrent()

var torrentId = 'magnet:?xt=urn:btih:976674fc52bb8e61499e701033a5a4759b5f0d60'

client.add(torrentId, function (torrent) {
  var file = torrent.files[0]
  file.appendTo('body') // append the file to the DOM
})

Beside I Made This 1 Page PHP Torrent Downloader Without Mysql Needed ( Needs Security Fixes For Now )  
https://github.com/besoeasy/PHP-Torrent-Downloader

**Comment by DiegoRBaquero** [comment]
Could you please provide more information? Browser's log is a start

**Comment by feross** [comment]
Without more info, this issue makes no sense. Closing.
