### ISSUE TITLE
We need to get torrent clients to support web torrents

### ISSUE THREAD

**Issue by Leekao** [feross/webtorrent#490]
If we want web torrents to prosper we need to get the large torrent clients to support it, uTorrent, Transmission and qBitorrent are the main clients (according to life hacker) and they all have forums, let's register to their forums and start promoting this feature.
https://qbforums.shiki.hu/index.php/topic,3970.0.html

**Comment by rom1504** [comment]
duplicated of https://github.com/feross/webtorrent/issues/369

**Comment by feross** [comment]
@Leekao Thanks for opening this issue. I encourage you to tell the developers of your favorite clients to support WebTorrent!
