### ISSUE TITLE
Unify docs with webtorrent-www

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#507]
The WebTorrent API docs live in two places right now:

1. [`README.md`](README.md) in this repo
2. [`server/views/docs.jade`](https://github.com/feross/webtorrent-www/blob/master/server/views/docs.jade) in `webtorrent-www`

Let's unify these so we don't need to keep them manually in sync.

Also, move examples from `examples/` to the website.

**Comment by DiegoRBaquero** [comment]
There's no way to load from external to HTML. What we can do is load the README.md, remove the non-api parts and present it.

**Comment by rom1504** [comment]
What might be possible is the opposite: include webtorrent README.md (or a API.md subset extracted from it) into the jade file, since it's possible to include markdown in jade http://jade-lang.com/reference/includes/

**Comment by feross** [comment]
I'm working on fixing this right now.

**Comment by feross** [comment]
This is done now! Docs now live in [`docs/`](https://github.com/feross/webtorrent/tree/master/docs).
