### ISSUE TITLE
WT can't handle magnets from private trackers, only torrent files

### ISSUE THREAD

**Issue by tsoernes** [feross/webtorrent#511]
If I use WebTorrent in the command line, and pass it the location of a downloaded .torrent file from a private tracker, it functions as expected.

If I pass the same torrent file through parse-torrent to get the magnet URI and then pass this magnet to WebTorrent in the cli, it does not find any peers. 

E.g.
```
webtorrent "C:\Path\to\file.torrent"
```
works, but the output from
```
var parsed = pt(fs.readFileSync('C:\\path\to\file.torrent'))
var uri = parsetorrent.toMagnetURI(parsed)
```
does not work when passed to the WebTorrent CLI. I can't upload the torrent file here, as it contains the login token for the private tracker, but I can send it by email if you need it.

**Comment by feross** [comment]
There's probably a custom field in the .torrent file that the tracker server needs and `parse-torrent` doesn't recognize it so it throws it away.

Can you run the following code on the torrent file?

```js
var path = './test/torrents/pride.torrent'
console.log(Object.keys(bencode.decode(fs.readFileSync(path))))
console.log(Object.keys(bencode.decode(fs.readFileSync(path)).info))
```

You will need to install this package:

```
npm install bencode
```

Then paste the output here.

**Comment by tsoernes** [comment]
Result:
[ 'announce', 'created by', 'creation date', 'info' ]
[ 'files', 'name', 'piece length', 'pieces', 'private', 'source' ]

**Comment by feross** [comment]
`parse-torrent` doesn't recognize the "source" key. I wonder if there's documentation for that anywhere? I've never seen that in any spec.

Do you have a parallel magnet link for the torrent file you're using, from the same source? Could you run this on it?

```js
var magnet = require('magnet-uri')
var uri = 'magnet:?xt...'
console.log(Object.keys(magnet(uri)))
```

You'll need to install this package first:

```
npm install magnet-uri
```

**Comment by tsoernes** [comment]
No, sorry, the tracker does not specify magnets

**Comment by feross** [comment]
Can you send me the .torrent file? Email is in my profile.

**Comment by tsoernes** [comment]
Done!

2015-12-04 4:49 GMT+01:00 Feross Aboukhadijeh <notifications@github.com>:

**Comment by feross** [comment]
My understanding of the way that "private torrents" work is that they just use an http tracker server and put a unique identifier into the announce url (for example: a query param). There's no reason this shouldn't work fine as a magnet uri. The tracker will still be contacted, as before.

The only reason I can think of why this isn't working is that other torrent clients that are using the private .torrent file (with the "private: 1" flag) have disabled the `ut_metadata` extension, so you're not able to fetch the torrent metadata from them.

In any case, I think WebTorrent is producing the correct magnet uri here, so there's nothing else to do.
