### ISSUE TITLE
nodejs download slowly

### ISSUE THREAD

**Issue by hualiwang** [feross/webtorrent#512]
To my experience , browser mode is faster more then  nodejs mode.

I try to  run commandline   "node cmd.js seed sintel.torrent ", the torrent downloaded from https://webtorrent.io/torrents/sintel.torrent 

It just found up to 3 peers ,  with speed 70kb/s , after 5 minutes , two peers disappeared , and time remaining: Infinity years remaining
but I can recover speed by restart the commandline. 

so I open  http://webtorrent.io in chrome  and watch the same movie , I can found over 5 peers and  20 minutes remaining.

what the different between node and browser ? Is that because of  webrtc ?
If some peers has low download speed ,can I   change it to other one?

**Comment by DiegoRBaquero** [comment]
On the browser it's only webrtc peers, on node, it's TCP/uTP peers only. The 3 peers are different from the 5 peers. Sintel is also webseeded but webseed broke in last 2 builds. Pending PR in bittorrent-swarm to fix this.

If you want to use webrtc from CLI, you can use webtorrent-hybrid (Although I would recommend using electron-spawn) See feross/webtorrent-hybrid#5
