### ISSUE TITLE
Seed file in nodejs mode failed.

### ISSUE THREAD

**Issue by hualiwang** [feross/webtorrent#519]
How to seed file in node mode?
I created seed.js like this :

function runSeed (input) {
    client = new WebTorrent()
    function onTorrent (torrent) {
        console.log('Client is seeding:', torrent.infoHash)
        console.log(torrent.magnetURI)
    }
    client.seed(input , onTorrent)
}
runSeed('mp3.mp3')

open terminal and it output:
Client is seeding: 38178900b09f42319e8be46c22566222fdcede55
magnet:?xt=urn:btih:38178900b09f42319e8be46c22566222fdcede55&dn=mp3.mp3&tr=udp%3
A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr
=udp%3A%2F%2Ftracker.publicbt.com%3A80&tr=udp%3A%2F%2Ftracker.webtorrent.io%3A80
&tr=wss%3A%2F%2Ftracker.webtorrent.io

after that I open an other terminal and input : webtorrent download magnet:?xt=urn:btih:38178900b09f42319e8be46c22566222fdcede55

and it only print one line: 
fetching torrent metadata from 0 peers

I have not specified any trackers ,and  webtorrent  will  always use the same trackers ,

But the code doesn't work , Am i doing wrong ?

**Comment by DiegoRBaquero** [comment]
Could you please enable debug and comment the logs? #518 looks the same

**Comment by hualiwang** [comment]
My comment is too long ,so I attached the files:


[log.zip](https://github.com/feross/webtorrent/files/56545/log.zip)

**Comment by DiegoRBaquero** [comment]
Are you currently seeding?

Hop on gitter and PM me, I'll help you :)

**Comment by hualiwang** [comment]
I'm not online , sleeping at  night at that time.
I have opened a vps and now running  webtorrent ,and it still seeding file.
magnet:?xt=urn:btih:38178900b09f42319e8be46c22566222fdcede55
I will email vps account and password to you .

the problem is:
Every things is ok , when I running the seeder and downloader at the same computer,
But can not download from  computer which located behind  NAT

My purpose is seeding files on server , and users can download  all of world  using browser ,

**Comment by DiegoRBaquero** [comment]
Checking this now, will report in a few minutes.

**Comment by hualiwang** [comment]
I can connect to internet and still failed , I don't know why , 
did it  needs NAT traversal service ?

**Comment by DiegoRBaquero** [comment]
Something must be blocking it, NAT or a firewall.
