### ISSUE TITLE
Demo app: torrent.pizza

### ISSUE THREAD

**Issue by berpj** [feross/webtorrent#522]
Hi,

I created https://torrent.pizza (code: https://github.com/berpj/torrent-pizza) using webtorrent. If you find it interesting, could it be added to the readme? :)

**Comment by berpj** [comment]
I can't remember why I did that, indeed it works: https://torrent.pizza/#6a9759bffd5c0af65319979fb7832189f4f3c35d :+1: 

It's currently hosted with AWS (EB). Not the cheapest way, so if needed I'll migrate to an other hosting service.

Does it answer your last question?

So I created a PR: https://github.com/feross/webtorrent/pull/523

**Comment by DiegoRBaquero** [comment]
Ummm no. I mean, are you running the server with webtorrent-hybrid or how are you achieving that node connects to webrtc peers?

**Comment by rom1504** [comment]
@DiegoRBaquero  it just doesn't (https://github.com/berpj/torrent-pizza/blob/master/server/package.json#L15), it just transmits the data by http to the browser

**Comment by DiegoRBaquero** [comment]
I'm scratching my head as to why it would work downloading from webrtc in a node app. Unless the server is ran inside something such as electron.

**Comment by rom1504** [comment]
> why it would work downloading from webrtc in a node app

does it ?

**Comment by DiegoRBaquero** [comment]
I don't really know, I just seeded 2 files from both networks and I'm not uploading form either to TorrentPizza's server :/

**Comment by berpj** [comment]
Yes, I'm not using webrtc here. rom1504 is right.

What file were you seeding? Does it work with a regular torrent client?

**Comment by DiegoRBaquero** [comment]
I was seeding a small mp4 video, from uTorrent and BTorrent (WebRTC client).

Maybe what failed was the discovery as we might not have been using the same trackers and DHT failed

**Comment by rom1504** [comment]
> At the moment streaming to the server and sending to the clients by http seems to be the best / only solution for cross-browser compatibility.

The point of webtorrent is to avoid that though

**Comment by DiegoRBaquero** [comment]
@rom1504 My first thoughts exactly, although this is an interesting project. Similar to joker.org/bitport.io/(another one which I forgot the name) or peerflix -> web (@berpj you are using webtorrent, but it's for videos only)

**Comment by DiegoRBaquero** [comment]
I see you've closed it, so I'm gonna close this and the PR.
