### ISSUE TITLE
Error caused by Filelist type

### ISSUE THREAD

**Issue by gustavomrfz** [feross/webtorrent#526]
When getting a Filelist on Chromium/Firefox works properly, but not in Electron (0.36.0) with same functions and modules version.

```javascript

var webtorrent = require('webtorrent')

this.torrentUpload =  function (){
            files = this.files
            player.startSeeding(files)
}
this.startSeeding = function (files) {

   // If I put files.shift() in here, launches error on the browsers also

    $.each(files,function (i,file) {
             client.seed(file, {dht: false},  onTorrent)  
             // Doesn't launch errors on browsers. 
             // Launches error with Electron
      }
}
```

The error is:

*104 Uncaught (in promise) TypeError: item.path.shift is not a function(…)*

could be found at: 

**create-torrent/index.js**
```javascript
 if (commonPrefix) {
    input.forEach(function (item) {
      if (typeof item === 'string') return
      item.path.shift()
    })
```
I understand that Filelist is not a proper array for shift(), but I belive that It would be fine that Webtorrent could parse files as good in Electron as in Chromium.

**Comment by feross** [comment]
@jhiesey Another issue related to the change we made to `create-torrent` together.

**Comment by feross** [comment]
@gustavomrfz Actually, can you try this again using the latest version of WebTorrent? We may have fixed this issue in the latest version of create-torrent (3.20.2).

**Comment by gustavomrfz** [comment]
@feross I tried again with webtorrent 0.67.1 but the issue still persits.

**Comment by feross** [comment]
@gustavomrfz Can you try again with 0.68.0? There's a chance that it's fixed now.

If it's still not, I'll make a sample Electron app and debug this.

**Comment by gustavomrfz** [comment]
@feross Still not. 

I realize that file objects created by file input forms are not the same type in browser than in Electron. Object that Electron makes doesn't have shift() function even when elements are taken individually from a function as $.each(). I belive the issue comes by that way.

**Comment by feross** [comment]
@gustavomrfz Btw, how have you managed to get drag and drop working in an Eleectron app? The `drag-drop` module doesn't seem to work because of this chromium bug: https://code.google.com/p/chromium/issues/detail?id=412373

**Comment by gustavomrfz** [comment]
@feross I'm not using drag and drop, but "classical" input. Indeed, it didn't work when I tried.

**Comment by feross** [comment]
`drag-drop` actually works just fine. I was doing something silly before

**Comment by feross** [comment]
The issue in `create-torrent` is fixed now, so `webtorrent.seed` works correctly in Electron now!

This is the relevant commit: https://github.com/feross/create-torrent/commit/89eeed32eb3a83ba98d913ae17ad377d4f64bbf7

**Comment by DiegoRBaquero** [comment]
@feross Was having this issue too in Electron! Awesome, closer and closer.

**Comment by gustavomrfz** [comment]
@feross Thanks a lot!

**Comment by feross** [comment]
No problem guys :+1:
