### ISSUE TITLE
browserify issue

### ISSUE THREAD

**Issue by chiggachiggayeah** [feross/webtorrent#529]
when I browserify the basic example from the webtorrent.io I get the error: net.createServer is not a function. It seems to make sense, not being able to make a server on the client, but I thought I'd bring it up since it seems that we are supposed to be able to browserify the npm webtorrent module. Just using the CDN for now.

**Comment by DiegoRBaquero** [comment]
That's something, at least for now, clients cannot do. Would be cool to create an http server from your browser window, but not yet :(

Just like the direct file system access, it's still not available. And who knows if it will ever be.

**Comment by feross** [comment]
@chiggachiggayeah Just to make suer, you got this error when calling `torrent.createServer()`, right? If you got it while calling some other function, then it might be a bug. Please leave a comment if that's the case.

**Comment by chiggachiggayeah** [comment]
Hey sorry for just getting back. The error happens when I try to browserify webtorrent, which, from the repo, I thought was supposed to be possible. Maybe it's not anymore, or I just misunderstood. Anyhow, I get an error in the web console complaining that net.createServer isn't a function in this bit of code:

```
function TCPPool (port, hostname) {
  var self = this

  self.port = port
  self.listening = false
  self.swarms = {} // infoHash (hex) -> Swarm

  debug('new TCPPool (port: %s, hostname: %s)', port, hostname)

  // Save incoming conns so they can be destroyed if server is closed before the conn is
  // passed off to a Swarm.
  self.pendingConns = []

  self.server = net.createServer()
  self.server.on('connection', function (conn) { self._onConnection(conn) })
  self.server.on('error', function (err) { self._onError(err) })
  self.server.on('listening', function () { self._onListening() })
  self.server.listen(self.port, hostname)
}
```

the code that I've browserified is here:

```
var WebTorrent = require('webtorrent');

var client = new WebTorrent();

var torrentId = 'magnet:?xt=urn:btih:6a9759bffd5c0af65319979fb7832189f4f3c35d'

client.add(torrentId, function (torrent) {
  // Torrents can contain many files. Let's use the first.
  var file = torrent.files[0]

  // Display the file by adding it to the DOM. Supports video, audio, image, etc. files
  file.appendTo('body')
})
```

**Comment by feross** [comment]
Yes, browserifying webtorrent should be possible, and works for me. It sounds like your browserify is misbehaving because it's packaging `tcp-pool.js` with the `TCPPool` class. This file is supposed to be skipped by bundlers. See this line:

Are you sure you're not using webpack or something like that? What version of browserify and webtorrent are you using?

**Comment by feross** [comment]
Now that I think about it, I recall there was a browserify issue with resolving the `browser` field correctly in older versions of browserify.

Please make sure you're running the latest version.

```
npm install browserify@latest --save-dev
```

If you have browserify installed globally, beware that that might get used if your PATH is not set correctly in your scripts, so update that too, like this:

```
npm install browserify -g
```

**Comment by chiggachiggayeah** [comment]
Yep. It seems to be working after an uninstall and then installing the latest browserify version. Sorry about that. Should've tried that myself instead of bothering you guys. Thanks though.

**Comment by feross** [comment]
Cool, thanks for letting us know that you got it working!
