### ISSUE TITLE
Increase web seed request size from 16kb

### ISSUE THREAD

**Issue by hualiwang** [feross/webtorrent#534]
Everytime it return 16.5kb data size, I think it is too small .

**Comment by rom1504** [comment]
It's not possible currently, but @DiegoRBaquero is working on it. I think he was pretty close to have it working.

**Comment by DiegoRBaquero** [comment]
At the moment, you can't. I managed to get it up to the piece length, which you can test here: https://rawgit.com/DiegoRBaquero/BMagnet/master/demo/bmagnet.html

I don't really know when I'm going to make the PRs, because I did the changes manually in the node modules and have been sick.

**Comment by feross** [comment]
@DiegoRBaquero Do you mind quickly describing the changes you made? I can go through and make all the changes to the various modules. I have free time at the moment.

**Comment by rom1504** [comment]
I guess https://github.com/DiegoRBaquero/BMagnet/commit/5b9e389d59c31c1963420543bfcbc75a5c4661e8

**Comment by DiegoRBaquero** [comment]
@feross Going to do that now.

**Comment by feross** [comment]
Make the changes or describe them? ;)

**Comment by DiegoRBaquero** [comment]
@feross Make the changes and PR to the respective modules

**Comment by feross** [comment]
nice :+1:

**Comment by DiegoRBaquero** [comment]
@feross Any updates or changes that should be made? Maybe allow the users to selected through the opts the max size?

**Comment by feross** [comment]
This is released as 0.81.0. The web seed request size is now equal to the piece size, which is much better.
