### ISSUE TITLE
"Not allowed to load local resource",why?

### ISSUE THREAD

**Issue by solidkim** [feross/webtorrent#537]
```
<html>
<head><title>Test</title></head>
<body>
<script src="https://cdn.jsdelivr.net/webtorrent/latest/webtorrent.min.js"></script>
<script>
var client = new WebTorrent();

var torrentId = 'magnet:?xt=urn:btih:6A9759BFFD5C0AF65319979FB7832189F4F3C35D';

client.add(torrentId, function (torrent) {

    console.log(torrent);

    var file = torrent.files[0];
    file.appendTo('body');
});
</script>

</html>
```

![image](https://cloud.githubusercontent.com/assets/9121022/12010937/15f01374-aca2-11e5-904d-72e5529fd35f.png)

I got a message "Not allowed to load local resource" on Chrome console.

**Comment by feross** [comment]
This is a bug in Chrome. See: https://code.google.com/p/chromium/issues/detail?id=379206

You can workaround it by running a local server and visiting your site over localhost. You can use this npm module to do it:

```
$ npm install ecstatic -g
$ cd your-project
$ ecstatic
```

**Comment by solidkim** [comment]
Why video at home page , https://webtorrent.io/ , works fine?

**Comment by feross** [comment]
Because `https://webtorrent.io` is not served over `file://`. If you look in your location bar, you'll see that you are loading the site directly from your filesystem, which Chrome doesn't like.

If you install `ecstatic`, then it will run a local server for you, so you can visit your site at `http://localhost:port` so Chrome is happy.

**Comment by solidkim** [comment]
1000x Thanks.

**Comment by feross** [comment]
Cheers!

**Comment by webarthur** [comment]
This happens on ZeroNet too and I don't know why =(

**Comment by webarthur** [comment]
Link: http://127.0.0.1:43110/114Zc7EUqBFTpqWujU7VC1rGEKoyzQrghE/

**Comment by vikrambarnwal** [comment]
Thanks
