### ISSUE TITLE
missing torrent.pause api

### ISSUE THREAD

**Issue by thelordofthetimes** [feross/webtorrent#543]
torrent api missing torrent.pause to pause torrent download/upload progress. now, torrent.destroy() remove torrent from client, remove all torrent downloaded file, it so bad to resume download

**Comment by feross** [comment]
We don't support pausing yet, but this should be easier to support once we have throttling upload/download speed implemented (#163).

Until then, we expose the underlying `swarm.pause()` and `swarm.resume()` functionality as:

```
torrent.pause()
torrent.resume()
```

This will temporarily stop connecting to new peers. Note that this does not pause new incoming connections, nor does it pause the streams of existing connections or their wires.

**Comment by thelordofthetimes** [comment]
sorry for slow response, I think that we wait until throttling is completed to avoid wasted time. I will find other solution for my issues, thank you

**Comment by feross** [comment]
`torrent.pause()` and `torrent.resume()` are already implemented. You're free to use them.

**Comment by thelordofthetimes** [comment]
yes, I know, I watched #547
