### ISSUE TITLE
Examle magnet link is working, others are not

### ISSUE THREAD

**Issue by stoufa88** [feross/webtorrent#557]
I'm using the example for simple client download:

```javascript
var client = new WebTorrent()

var magnetUri = 'magnet:?xt=urn:btih:b65c2bb749589035347180e8b0931899859cfd8e&dn=linuxmint-17.3-cinnamon-64bit.iso&tr=http%3A%2F%2Ftorrents.linuxmint.com%2Fannounce.php&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.webtorrent.io'

client.add(magnetUri,function (torrent) {
  // Got torrent metadata!
  console.log('Client is downloading:', torrent.infoHash)
})
```

this will prints the info hash in the screen and supposed to work properly.

For testing purposes, I tried to stream the video from the movie with this magnet uri:
"magnet:?xt=urn:btih:2be0bb0c947dc30ea3655b1db05670d02860d994&dn=Ronaldo.2015.HDRip.XviD.AC3-EVO&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969"

does not work, neither starts downloading.

**Comment by feross** [comment]
Do not use WebTorrent for copyright infringement.

We don't allow opening issues that discuss downloading copyrighted content. If that's what you're interested in, please don't use WebTorrent.
