### ISSUE TITLE
Remove git dependency for `npm install`

### ISSUE THREAD

**Issue by guigaoliveira** [feross/webtorrent#559]
I do not know very well use the git wanted to know why I have to download it to use webtorrent via npm.

**Comment by feross** [comment]
You're using `npm install webtorrent` and you're getting a message about needing `git`? Did I understand correctly?

**Comment by guigaoliveira** [comment]
This! Thanks! :)

**Comment by feross** [comment]
This is done now. You shouldn't need `git` to install webtorrent anymore!
