### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by guigaoliveira** [feross/webtorrent#561]
file-send.html example is not working for me. How do I solve this problem?
Log: Firefox can not establish a connection to the server wss: //tracker.torrent.xyz/. webtorrent.min.js: 
ICE failed, see about: WebRTC for more details

**Comment by feross** [comment]
What are you trying to do when it fails?

**Comment by guigaoliveira** [comment]
I try to download a torrent and it appears in the console log.

**Comment by guigaoliveira** [comment]
I need bittorrent-hybrid? For me webtorrent just does not work in browser...

**Comment by feross** [comment]
Please see the [FAQ](https://webtorrent.io/faq) where this issue is addressed:


> Why does browser downloading not work? I see no peers!

> It does work! But you can't just use any random magnet uri or .torrent file. The torrent must be seeded by a WebRTC-capable client, i.e. webtorrent-hybrid, instant.io, or Playback.

> In the browser, WebTorrent can only download torrents that are explicitly seeded to web peers via a WebRTC-capable client. Desktop torrent clients need to support WebRTC to connect to web browsers.

**Comment by guigaoliveira** [comment]
I need to download a torrent and video by streaming to the client, you can only using the node? I am unable to use the webtorrent in the browser.

**Comment by feross** [comment]
You can only download torrents in the browser if there are webrtc seeders, or you specify an http url as a "web seed".

You can use `webtorrent-hybrid` to seed content to browsers.

**Comment by guigaoliveira** [comment]
Ok, I can google chrome, but not in firefox, I think it's version, but here says it's the latest ...

**Comment by solidkim** [comment]
Are you brazilian?

**Comment by guigaoliveira** [comment]
Yes :-/

**Comment by solidkim** [comment]
Te mandei um email, não sei se você viu...
