### ISSUE TITLE
Torrent from magnet not adding webseeds

### ISSUE THREAD

**Issue by DiegoRBaquero** [feross/webtorrent#563]
Tested to see if it would work with `magnet:?xt=urn:btih:4d1729d2cde07ff84d4d50f121f005deedc8db74&dn=gimp-2.8.16-x86_64.dmg&tr=udp%3A%2F%2Fexodus.desync.com%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.webtorrent.io&tr=wss%3A%2F%2Ftracker.webtorrent.io&tr=wss%3A%2F%2Ftracker.webtorrent.io&tr=wss%3A%2F%2Ftracker.webtorrent.io&ws=https%3A%2F%2Fwebseed.btorrent.xyz%2Fgimp-2.8.16-x86_64.dmg`

Webseed doesn't get added.

Also, generated magnet URI repeats wss trackers.

Will investigate and PR later.

**Comment by feross** [comment]
Is this a new issue? Or has this never worked for you before?

**Comment by feross** [comment]
If there are no peers, this is actually expected behavior, I believe. With no peers, there's no way for WebTorrent to get the torrent metadata. Without the torrent metadata, it can't verify that the right file data is being downloaded.

You can test this out in Transmission or another torrent client and see that the download never starts there either.

If there's a chance of no seeders, I think going with a .torrent file is the safest bet.

**Comment by feross** [comment]
Can you open a new issue for the repeated trackers and share some code that reproduces it? Or just send a PR? ;) :+1:

**Comment by DiegoRBaquero** [comment]
I feel so stupid. I forgot about that, and the worst Is that I knew that.

**Comment by feross** [comment]
Haha, it's fine :+1:

**Comment by feross** [comment]
I can't reproduce this issue. I even added a test: https://github.com/feross/webtorrent/commit/d573c1fdc047c6d8d0f07fc6224f6d9ab34c755a

**Comment by DiegoRBaquero** [comment]
To exactly reproduce this:

Go to https://btorrent.xyz/
Add ´https://webseed.btorrent.xyz/gimp-2.8.16-x86_64.dmg.torrent´ to the hash/magnet and click download button. (It will download the .torrent)

The magnet uri in share will be:

´´´´
magnet:?xt=urn:btih:4d1729d2cde07ff84d4d50f121f005deedc8db74&dn=gimp-2.8.16-x86_64.dmg&tr=udp%3A%2F%2Fexodus.desync.com%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.webtorrent.io&tr=wss%3A%2F%2Ftracker.webtorrent.io&tr=wss%3A%2F%2Ftracker.webtorrent.io&tr=wss%3A%2F%2Ftracker.webtorrent.io&ws=https%3A%2F%2Fwebseed.btorrent.xyz%2Fgimp-2.8.16-x86_64.dmg
´´´´

2 times BTorrent's tracker and 3 times WebTorrent's

**Comment by feross** [comment]
@DiegoRBaquero This doesn't happen on https://instant.io. I think you must be doing something different on your site. Lmk if you can pinpoint what you're doing differently.

**Comment by DiegoRBaquero** [comment]
@feross Are you talking about the repeated trackers or the webseed adding? (Taking that the metadata is available from webrtc peers)

**Comment by feross** [comment]
@DiegoRBaquero I'm talking about the repeated trackers issue. Doesn't happen on instant.io.

**Comment by DiegoRBaquero** [comment]
@feross Yes, for the opts I add manually both wss trackers in the client.add

So the problem is that, when specifying trackers manually for a http(s) torrent file, repeated trackers will be allowed.

See [torrent.js#L238](https://github.com/feross/webtorrent/blob/master/lib/torrent.js#L238)

This isn't working then: [torrent.js#L258](https://github.com/feross/webtorrent/blob/master/lib/torrent.js#L258) because when encoded to a magnet uri, they should be unique, see [torrent.js#L263](https://github.com/feross/webtorrent/blob/master/lib/torrent.js#L263)

**Comment by feross** [comment]
Moving to issue: https://github.com/feross/webtorrent/issues/571
