### ISSUE TITLE
Uncaught TypeError: r is not a function

### ISSUE THREAD

**Issue by andreapaiola** [feross/webtorrent#564]
In Chrome and Firefox console

Uncaught TypeError: r is not a function
(anonymous function) @ webtorrent.min.js:6
y @ webtorrent.min.js:6

or formatted (beautified javascript)

Uncaught TypeError: r is not a function(anonymous function) 
@ webtorrent.min.js:formatted:11302
y @ webtorrent.min.js:formatted:11395

The error is live here http://andreapaiola.name/niagara/ ( simple code, nothing fancy :) )

Last version without the error: 0.64.0

The latest version and the 0.65.0 have the same error

**Comment by feross** [comment]
Looks like this was caused by a change in `file.appendTo` and `file.renderTo` that made the callbacks no longer optional. You can fix the problem by passing a callback, or wait for a few minutes and I'll publish a new version of `webtorrent.min.js`.

**Comment by feross** [comment]
Released 0.71.4.
