### ISSUE TITLE
Functions are not working

### ISSUE THREAD

**Issue by guigaoliveira** [feross/webtorrent#565]
The functions torrent.timeRemaining, torrent.downloadSpeed (), torrent.uploadSpeed (), are not working for me, all display the result = 0; I put the functions inside the client.download function

**Comment by feross** [comment]
Please share the code you're using, or there's no way to help you.

**Comment by feross** [comment]
Also, note that in the latest version, the function were just changed to getters:

```
torrent.downloadSpeed
torrent.uploadSpeed
```

**Comment by guigaoliveira** [comment]
My code: 
var WebTorrent = require('webtorrent');
var fs = require('fs');

var client = new WebTorrent();
var torrentId =magnet_url; // link
var counter=1;

client.download(torrentId, function (torrent) 
{
  console.log('Torrent magnet link:', torrent.magnetURI);
  console.log(torrent.timeRemaining);
  console.log(torrent.downloadSpeed);
  torrent.files.forEach(function (file) 
  {
    // get mp4 files
    if(file.path.indexOf("mp4") !=-1) 
    {
    var source = file.createReadStream();
    var destination = fs.createWriteStream('docs/'+file.name);
    source.pipe(destination);
    // finish 
    destination.on('finish', function() 
    {
        console.log(file.name)
        if(counter===torrent.files.length)
        {
         client.destroy(function callback (err) {})
          return console.log('finish');
        }
        else
        {
         counter++;
        }
    });
   }
   })
  
 return false;
})

**Comment by guigaoliveira** [comment]
torrent.timeRemaining = infinity
torrent.downloadSpeed = 0

**Comment by Stiveknx** [comment]
Maybe, because there's no peers for that torrent, so the download doesn't start and the time reimaining is not calculated.
Try checking the number of peers:

console.log(torrent.swarm.numPeers)

**Comment by guigaoliveira** [comment]
No, I checked and there are 43 peers. I don't know the cause of this.

**Comment by feross** [comment]
Please read this part of the [FAQ](https://webtorrent.io/faq):

> Why does browser downloading not work? I see no peers!

> It does work! But you can't just use any random magnet uri or .torrent file. The torrent must be seeded by a WebRTC-capable client, i.e. webtorrent-hybrid, instant.io, or Playback.

> In the browser, WebTorrent can only download torrents that are explicitly seeded to web peers via a WebRTC-capable client. Desktop torrent clients need to support WebRTC to connect to web browsers.
