### ISSUE TITLE
client.add() with manual trackers, causes duplicates

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#571]
Reposting issue for @DiegoRBaquero, from https://github.com/feross/webtorrent/issues/563#issuecomment-171127831:

> @feross Yes, for the opts I add manually both wss trackers in the client.add

> So the problem is that, when specifying trackers manually for a http(s) torrent file, repeated trackers will be allowed.

> See [torrent.js#L238](https://github.com/feross/webtorrent/blob/master/lib/torrent.js#L238)

> This isn't working then: [torrent.js#L258](https://github.com/feross/webtorrent/blob/master/lib/torrent.js#L258) because when encoded to a magnet uri, they should be unique, see [torrent.js#L263](https://github.com/feross/webtorrent/blob/master/lib/torrent.js#L263)

**Comment by feross** [comment]
@DiegoRBaquero I can't seem to reproduce this issue still. I even took a look at the BTorrent codebase to see if I could find the cause.

I just committed some additional tests that work fine.

If you could help get to the bottom of this, that would be great!

**Comment by DiegoRBaquero** [comment]
@feross I will look into this issue this weekend, having bad internet connection right now. I'll be home tomorrow and check this

**Comment by DiegoRBaquero** [comment]
The issue in BTorrent was that the announce list was an array of array of string so uniq wasn't really working on array <-> string comparison. Fixed in BTorrent 0.12.1.
