### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by Blixia** [feross/webtorrent#573]
I am getting the following error while I add a torrent to the client:

````
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write ECONNRESET
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)
````
I am not sure where to catch this error or where it is coming from?

Code used:
````
'use strict';

var webTorrent = require('webtorrent');
var fs = require('fs');

var client = new webTorrent();
var magnet = '';

client.add(magnet,function(torrent)
{
    client.on('torrent',function(torrent)
    {
        console.log(torrent.infoHash);
    });

    torrent.on('done',function()
    {
        console.log('done downloading');
        torrent.files.forEach(function(file)
        {
            file.getBuffer(function(err,buffer)
            {
                if(err) throw err;

                fs.appendFile('./downloads/'+file.name,buffer,function(err)
                {
                    if(err) return console.log(err);
                    console.log('appending');
                })
            });
        });
    });

    torrent.on('download', function(chunkSize)
    {
      console.log('chunk size: ' + chunkSize);
      console.log('total downloaded: ' + torrent.downloaded);
      console.log('download speed: ' + torrent.downloadSpeed);
      console.log('progress: ' + torrent.progress);
      console.log('======');
    });

});
```

**Comment by feross** [comment]
@Blixia I added some extra checks to `bittorrent-swarm` so we're more defensive against remote sockets potentially closing without warning (which is the source of this error).

Can you re-install WebTorrent and try it out again? The problem should be gone, but don't hesitate to leave a comment here or open a new issue if you see this again.

**Comment by anurupr** [comment]
I'm receiving this error when using the following snippet

`torrent.on('done', function(){

            const torrentPath = torrent.path;
            console.log('torrent finished downloading located at ',torrentPath);
            console.log("File count",torrent.files.length);
            var list = [];
            torrent.files.forEach(function(file){
                list.push(file.createReadStream());
               console.log(file.name);
            });

            client.seed(list,function(ntorrent){
                const magnetURI = ntorrent.magnetURI;
                console.log("magnetURI",magnetURI);

            });

          });
`

**Comment by feross** [comment]
@anurupr Why are you calling `client.seed` on the same files after they are done? The client will automatically seed the files when the download is complete. No need for this extra code.

```js
torrent.on('done', function () {
  const torrentPath = torrent.path
  console.log('Torrent finished downloading located at ', torrentPath)
  console.log('Torrent file count is ', torrent.files.length)
  console.log('Torrent magnet link is ', torrent.magnetURI)
})
```

**Comment by anurupr** [comment]
@feross I apologize. I was not aware of that. Thanks for the help.

**Comment by feross** [comment]
No problem!
