### ISSUE TITLE
Add support for Bowser

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#576]
A WebRTC browser for iOS. https://github.com/EricssonResearch/bowser

Haven't tested, but heard a report on Twitter that it's not working. 

This might require a change to [`simple-peer`](https://github.com/feross/simple-peer).

**Comment by DiegoRBaquero** [comment]
I just tested Chrome in Mac OS X <-> iPhone 6 Bowser. The connection fails with an undefined error.

This is the log in the Mac, couldn't get the console to be shown in bowser:
````
simple-peer [null] iceConnectionStateChange complete connected +304ms
simple-peer [null] maybeReady pc true channel false +0ms
simple-peer [c00f9f1] on channel open +32ms
simple-peer [c00f9f1] maybeReady pc true channel true +0ms
simple-peer [c00f9f1] connect remote: 192.168.101.110:54326 +2ms
simple-peer [c00f9f1] connect local: 192.168.101.112:62103 +1ms
simple-peer [c00f9f1] connect +0ms
simple-peer [7be628d] on channel close +2s
simple-peer [7be628d] destroy (error: undefined) +0ms
bittorrent-swarm:peer destroy 2d5757303037362d666565366533353461653139 (error: undefined) +1ms
simple-peer [7be628d] destroy (error: null) +1ms
bittorrent-protocol [2a2ddaa8] destroy +3ms
bittorrent-protocol [2a2ddaa8] end +0ms
bittorrent-protocol [2a2ddaa8] got uninterested +0ms
bittorrent-protocol [2a2ddaa8] got choke +1ms
bittorrent-swarm removePeer 2d5757303037362d666565366533353461653139 +0ms
bittorrent-swarm _drain numConns 0 maxConns 55 +1ms
````

Awesome work from @EricssonResearch

**Comment by feross** [comment]
I can't even get [a basic WebRTC data channel demo](https://webrtc.github.io/samples/src/content/datachannel/basic/) to work with Bowser. I don't believe they actually have support. I've never seen it working.
