### ISSUE TITLE
Request: Peer5 like functionality

### ISSUE THREAD

**Issue by zorrobyte** [feross/webtorrent#577]
I'm building a file downloads site on Django, backed by GridFS. I've used Peer5 in the past: https://www.peer5.com/downloader

Using it is as easy as:
!-- peer5 script 
script src="//api.peer5.com/peer5.js?id=z142i5n5qypq4cxr"

 just an a tag with peer5-download attribute 
a href="//storage.googleapis.com/peer5/avg_free_x86_all_2015_5577a8546.exe" peer5-download>Download Sample #2 (150MB)<

Is simple usage such as this something WebTorrent can do? If not, are there any alternatives?

**Comment by DiegoRBaquero** [comment]
This functionality can be built in top of WebTorrent but is not a feature that WebTorrent as a project itself will implement.
