### ISSUE TITLE
Implement WebRTC 1.1 support for MS Edge

### ISSUE THREAD

**Issue by wizzard0** [feross/webtorrent#579]
see the http://caniuse.com/#search=webrtc matrix, it is unlikely that Edge will support WebRTC 1.0 in the future, so for the time being there will be 2 versions of this API.

**Comment by feross** [comment]
@wizzard0 Thanks for opening this. We'll definitely add support for Edge once they support the WebRTC Data Channel, which is what WebTorrent uses to communicate arbitrary data between peers.


From the [Windows blog](https://blogs.windows.com/msedgedev/2015/09/18/ortc-api-is-now-available-in-microsoft-edge/):

> We don’t currently support any of the DataChannel functionality currently defined in the ORTC spec.

We'll probably just need to add support to [`simple-peer`](https://github.com/feross/simple-peer) and everything will hopefully just work :)
