### ISSUE TITLE
Stop/Pause download button on the webtorrent.io website.

### ISSUE THREAD

**Issue by Saheb** [feross/webtorrent#580]
I opened the website and it started with a bang, loved the quickness, but as I couldn't find a way to stop or pause the download, I had to close the tab. 

There should be a way to stop or atleast pause the download, for giving me an option to be on the website without using 129 MB of my data.

**Comment by iamshubh22** [comment]
@Saheb @feross I would like to work upon this.

**Comment by DiegoRBaquero** [comment]
There's no way to completely pause a torrent once started right now. I don't know how it would affect the UX if you had to click or tap a button to start.

I, however, would like to have a much smaller video as the demo. See #530

**Comment by feross** [comment]
If you remove all the "selections" from the file, then it should stop downloading. You have to destroy any `FileStream` objects you might have.

```js
var stream = torrent.files[0].createReadStream() // say I have a stream 
stream.destroy() // i need to destroy it
```

And deselect any ranges I may have selected:

```js
torrent.deselect(start, end, priority)
```
