### ISSUE TITLE
Reseed bittorrent to webtorrent

### ISSUE THREAD

**Issue by KeizerDev** [feross/webtorrent#581]
How can I reseed/port bittorrent torrents to the webtorrent protocol so they will also work here. I've a little collection of videos(similar to http://vodo.net/) I want to port it to the webtorrent protocol so they are playable within your browser. Just a bunch of torrents/magnet links.

Can someone explain me how I can do this and make them work? 

Thanks in advance

**Comment by DiegoRBaquero** [comment]
You would have to seed them using instant.io o btorrent.xyz

The other solution would be to use a webseed.

**Comment by KeizerDev** [comment]
@DiegoRBaquero how can I set up a server similar to instant.io and btorrent.xyz?

**Comment by Edward-Stryfe** [comment]
@DiegoRBaquero same question

**Comment by DiegoRBaquero** [comment]
@KeizerDev You could download the full code of either and host it yourself. Instant.io is a native node http server and btorrent.xyz uses harp
