### ISSUE TITLE
Missing delimiter ":" [0x3a]

### ISSUE THREAD

**Issue by riccardomartinelli** [feross/webtorrent#583]
Hi!
Recently I have download the last  webtorrent.mini.js and now a page that worked is giving this error:
Invalid data: Missing delimiter ":" [0x3a]
My code is very simple. I use only the function client.add("http://mysite/file.torrent", etc).

ps: I'm new on github and i hope to follow the guidelines.

**Comment by DiegoRBaquero** [comment]
Could you please post your full code or the website URL to test?

**Comment by riccardomartinelli** [comment]
This is the page that gives the error: <a href="http://wpdiary.altervista.org/Streaming.html">Link</a>

**Comment by DiegoRBaquero** [comment]
You are using Browserify, right? 

Try to change requiring the minified version and require the NPM module.
