### ISSUE TITLE
Let's make a WebTorrent sticker!

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#586]
Calling everyone with graphical design skills!

We need a logo for [webtorrent.io](https://webtorrent.io), as well as a [hex sticker design](https://github.com/terinjokes/StickerConstructorSpec) for our laptops!

Hex stickers are awesome because you can tile them. Check out what my laptop looks like:

![](https://cloud.githubusercontent.com/assets/121766/12538462/41fe6512-c2da-11e5-8ff9-a83e9262735e.jpg)

After we have a sticker design, I'll print a bunch and send them to anyone who wants one.

**Comment by feross** [comment]
I really like the [Node School international day](http://nodeschool.io/international-day/) sticker:

![c1cdc644-e387-11e4-93a5-36584ed041bd](https://cloud.githubusercontent.com/assets/121766/12538495/0eb2f136-c2db-11e5-8ee9-e1cb72ebbdd7.png)

So I tried to make something based on that:

![webtorrent-heart](https://cloud.githubusercontent.com/assets/121766/12538505/59f48dbc-c2db-11e5-84c2-d7a1fa0e5c35.png)

**Comment by feross** [comment]
This one gets rid of the satellite and uses a rocket instead. And it's connected to the rest of the webtorrent network!

![webtorrent](https://cloud.githubusercontent.com/assets/121766/12538511/7bb35f00-c2db-11e5-95b9-7cf33b275b17.png)

Still looks a bit too similar to the NodeSchool international day sticker.

**Comment by feross** [comment]
There's a bunch of inspirational hex designs on [Hexbin](http://hexb.in/) and [Hexdex](http://nodeschool.io/hexdex). Use to get ideas!

**Comment by jzbz** [comment]
The logo with the rocket looks fantastic.

**Comment by feross** [comment]
Here's another attempt:

![webtorrent-beehive](https://cloud.githubusercontent.com/assets/121766/12538865/4ab7da8e-c2e5-11e5-9876-39b4e9c16de1.png)

**Comment by astro** [comment]
I want some too! Shape is no issue for me.

**Comment by feross** [comment]
![webtorrent-big-text-green](https://cloud.githubusercontent.com/assets/121766/12538963/d1213aaa-c2e7-11e5-81c3-dd2a41d43208.png)

**Comment by alxhotel** [comment]
I would love a sticker for my laptop :)

Idea: a rocket with a heart leaning out the widow; you could imagine it similar to the Github logo

**Comment by feross** [comment]
![webtorrent-big-text-rocket](https://cloud.githubusercontent.com/assets/121766/12542277/2d476992-c321-11e5-94cf-3a7a6d74c448.png)

**Comment by feross** [comment]
Replaced the round window in the rocket with a heart-shaped one.

![webtorrent-big-text-rocket-heart](https://cloud.githubusercontent.com/assets/121766/12542736/421ac660-c327-11e5-951d-5514aa2d3ddb.png)

Finally learned how to use an "erase layer mask", something I've wanted to do for years, but could never adequately describe and find on google.

**Comment by bitanath** [comment]
![webtorrent](https://cloud.githubusercontent.com/assets/7344942/12542773/81d3058a-c34d-11e5-8b49-d2bf47037ccf.png)

An amateurish attempt at an option..

**Comment by feross** [comment]
@bitanath Cool, hadn't considered that circuit boards look kinda like peer-to-peer networks!

**Comment by bitanath** [comment]
![webtorrent](https://cloud.githubusercontent.com/assets/7344942/12542814/1f025068-c34e-11e5-90b2-3adb83b4876e.png)
@feross Just putting it out there... anyway, one with the heart inlay :)

**Comment by tonygoussot** [comment]
Hi Guys, just to say I'm completely fond of that last one with the circuit
board. It looks totally awesome !

**Comment by yciabaud** [comment]
I was thinking about adding some water to represent the bittorrent ecosystem but I am not able to make a design on my own ;)

I like your stickers but in my opinion, the rounded typo is not that great.

Good job!

**Comment by feross** [comment]
Latest iteration, lots more love:

![webtorrent-hearts](https://cloud.githubusercontent.com/assets/121766/12581537/8a71c60a-c437-11e5-9d47-8052534f0075.png)

@yciabaud got a suggested font?

**Comment by feross** [comment]
No rocket version:

![webtorrent-hearts-no](https://cloud.githubusercontent.com/assets/121766/12581716/b9f7095c-c438-11e5-818e-7c013b54e988.png)

**Comment by feross** [comment]
Okay, so I just printed 500 of the last sticker!

Look out for me at conferences and meetups to pick one up for free! If you've contributed to WebTorrent, send a message to my email (on my github profile) and I'll send you one for free!

If you just want to buy one for yourself, here's a link to get one from StickerMule: https://www.stickermule.com/en/marketplace/10200-webtorrent

(I added no markup, so the price is just what StickerMule charges to print the stickers and it goes entirely to them)

![b9f7095c-c438-11e5-818e-7c013b54e988](https://cloud.githubusercontent.com/assets/121766/12633585/37e8fc18-c573-11e5-9942-ab81629b5db2.png)

**Comment by joeshua** [comment]
@feross   at the end of the rocket you can add the heart rather then the smoke

**Comment by feross** [comment]
The WebTorrent stickers just arrived!

![img_9010](https://cloud.githubusercontent.com/assets/121766/12742840/2027e5ca-c93e-11e5-8f1e-f4dbb1173ca4.jpg)

Look out for me at conferences and meetups to pick one up for free! You can also just [buy one for yourself](https://www.stickermule.com/en/marketplace/10200-webtorrent) right now from StickerMule (lowest price, no markup).

If you've contributed to WebTorrent, send a message to my email (on my github profile) with your mailing address and I'll send you one for free!

@fisch0920 @astro @mafintosh @ivantodorovich @bobrenjc93 @substack @gillesdemey @valeriangalliat @josephfrazier @lucaswxp @DiegoRBaquero @maxogden  @whyrusleeping @diasdavid Send me your address and I'll ship 50 to you (free!).

@dcposch @jhiesey @jbenet - I'll just give you some next time I see you (probably next couple of days ;)

**Comment by diasdavid** [comment]
wooooo, free and awesome stickers :D

**Comment by feross** [comment]
Alright, last call – I already packed a bunch of envelopes. If you're a contributor and want your free stickers, send your address now!

**Comment by jbenet** [comment]
I want some! But i'm now in NYC :( -- i'll be back to SF soon.

**Comment by feross** [comment]
@jbenet sounds good! sorry i missed you this time :(

**Comment by ivantodorovich** [comment]
Wow, they look awesome!!

I'd love some, but I live in Argentina, so I don't think it would be possible.

Also, I don't think I deserve them! My contributions (if any) were so small that I don't even remember them :flushed:

**Comment by whyrusleeping** [comment]
@feross sent you my address on IRC :)

**Comment by feross** [comment]
@ivantodorovich that's alright! if you want some stickers, i'm happy to send you some! i can send to argentina!

@whyrusleeping got it!
