### ISSUE TITLE
Seeding a large amount of files from server

### ISSUE THREAD

**Issue by oleib** [feross/webtorrent#587]
Hi, I'm attempting to deploy a server, which serves a large amount of files in which the server initially holds exclusively.
We want those files to be shareable with torrents, using WebTorrent.
The problem is - initially seeding this large amount of files is impossible. It creates a large amount of open files and I/O connections up to the relying machine's (or OS) limit.
Is there any way I can just 'announce' them without constantly 'seeding' them and keeping all these open files and I/O connections (to the DHT and trackers)?
I thought about using web-seeds, where I can initially generate HTTP urls for the torrents, so that 'seeding' can be done lazily only upon request (I'll provide the http server that will serve these files, at least up to a certain amount of external seeders for a torrent).

I'll be glad to get your input on that. Cheers!

**Comment by oleib** [comment]
Hi, exploring this issue a bit further - 
Will it be possible to announce all of my files, i.e. inform the trackers (and preferably the DHT) I have these files without actually seeding them - and be notified when someone requests them (i.e. try to find peers holding this file using a tracker or DHT), and only then start seeding them?

This approach of 'lazy seeding' will solve my issue of opening too many sockets (specifically with the DHT bootstrap nodes)

**Comment by dimatter** [comment]
increase the limit of open sockets on your operating system

**Comment by oleiba** [comment]
(same @oleib user here)
Hi @dimatter , thanks for your reply - The thing is that the amount of files is thousands and growing. Moreover the DHT bootstrapping node refuses to open so many sockets for my server.
I'm looking for a more scalable solution, hence the need of 'lazy seeding'.

**Comment by feross** [comment]
You can definitely go the web seed approach. If you host all the files you need on the server, the you can pass the `urlList` option to [`create-torrent`](https://github.com/feross/create-torrent) to get a .torrent file that references the http url. That might be a simpler approach, since http is pretty easy to scale.

**Comment by oleib** [comment]
@feross thank you so much for your reply. 
I am using magnet links, and actually I tried that approach but with no success. (I used create-torrent@3.10.0)
As far as I came to understand, when I distribute my torrents using magnet links (it is essential for my application) web-seeds still require at least one peer connected to the swarm to provide the metadata.

**Comment by feross** [comment]
@oleib Yes, that is correct. Hopefully, we can improve the performance of WebTorrent enough for your application. There's another issue that it looks like you opened for that: https://github.com/feross/webtorrent/issues/599

**Comment by oleib** [comment]
Yes @feross, that's right - I closed this issue to open a new one better defined. Thank you.
