### ISSUE TITLE
Guidelines for c# server support.

### ISSUE THREAD

**Issue by jsboige** [feross/webtorrent#590]
Hi, I would be interested in implementing a c# websocket tracker to support webtorrent. I am aware of the [node implementation](https://github.com/feross/bittorrent-tracker) .
What would be some guidelines to implement the protocol, given the IHttpHandler approach of [that article](http://www.codeproject.com/Articles/618032/Using-WebSocket-in-NET-4-5-Part-2) and a BitTorrent library as [Monotorrent](https://github.com/mono/monotorrent/tree/master/src)

**Comment by feross** [comment]
Right now, you can emulate the node implementation (`bittorrent-tracker`). Specifically, these are the files to look at:

- https://github.com/feross/bittorrent-tracker/blob/master/lib/server/parse-websocket.js
- https://github.com/feross/bittorrent-tracker/blob/master/server.js#L297-L398

For an actual spec, follow #168.

**Comment by jsboige** [comment]
Thanks a lot for your guidelines. I believe this should be tractable with [Microsoft.WebSockets](https://www.nuget.org/packages/Microsoft.WebSockets/) and Monotorrent providing some of the code you linked.
 
I will look into that probably over the summer, and I'll let you know about it.
