### ISSUE TITLE
Is there a way to resume download in command line app

### ISSUE THREAD

**Issue by hackerkid** [feross/webtorrent#591]
If for some reason I quit the application(while downloading) in  the middleway, is there a way to resume the download from where I have left it earlier?

**Comment by DiegoRBaquero** [comment]
Shouldn't it? Unless you delete /tmp the completed pieces should remain there. iirc

**Comment by hackerkid** [comment]
I didn't notice this. Sorry for the trouble.

**Comment by DiegoRBaquero** [comment]
@hackerkid I'm not saying that that's the way it works for certain. If that doesn't happen, reopen the issue :)

**Comment by hackerkid** [comment]
@DiegoRBaquero It's storing the data in the directory from which it was invoked. And it's resuming from where it's left. I didn't notice it before. Thanks. :smile:
