### ISSUE TITLE
How create instantly stram torrent file ?

### ISSUE THREAD

**Issue by BeetleTN** [feross/webtorrent#594]
Hello
How make Video.js and Webtorrent for stream videos torrent without download like Hola
[https://github.com/hola/player](https://github.com/hola/player)
Thanks

**Comment by DiegoRBaquero** [comment]
I don't understand your question. Can you elaborate?

**Comment by feross** [comment]
Take a look at the quick example here (https://webtorrent.io/intro). It shows you how to stream a video directly into a video tag, without a full download.
