### ISSUE TITLE
Unify webtorrent fixture files into one npm package

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#597]
Right now, sample .torrent files appear haphazardly in the various webtorrent packages for testing purposes. Mainly, Leaves of Grass. Let's just make a single package `webtorrent-fixtures` or something like that and make everything dev-depend on that.

- [x] webtorrent
- [x] parse-torrent
- [x] parse-torrent-file
- [x] bittorrent-tracker
- [x] ut_metadata

**Comment by feross** [comment]
Working on this right now. https://github.com/feross/webtorrent-fixtures

**Comment by rom1504** [comment]
https://github.com/feross/parse-torrent-file/pull/7 should be enough for parse-torrent-file.

**Comment by rom1504** [comment]
I want to do the 2 remaining packages, but waiting for feedback on https://github.com/feross/parse-torrent-file/pull/7 before starting.

**Comment by feross** [comment]
@rom1504 Thanks for offering to complete the other two packages, but I just went ahead and made the changes to prevent confusion. Much appreciated!
