### ISSUE TITLE
Explanation of WebRTC roadmap

### ISSUE THREAD

**Issue by fisch0920** [feross/webtorrent#60]
I'm not clear on how exactly the WebRTC version of webtorrent will interface with the existing browserifiable libraries bittorrent-client/swarm/protocol.

I think progress towards the actual web portion of webtorrent would benefit greatly from a detailed breakdown of the plan to build the webrtc version based on what exists today, including:
* what modules need to be built and their anticipated dependencies
* how the actual peer connection / communication will be handled over webrtc
* the expected browserify process
* will any existing webrtc modules be used for connecting the hybrid bittorrent/webtorrent clients with the webtorrent clients? e.g., [wrtc](https://www.npmjs.org/package/wrtc), [webrtc](https://www.npmjs.org/package/webrtc), or [webrtc.io](https://www.npmjs.org/package/webrtc.io)?

Thanks! :+1:

**Comment by feross** [comment]
We have support for WebRTC peers now, so I'm going to close this issue.
