### ISSUE TITLE
A new peer takes too long to connect to other peers.

### ISSUE THREAD

**Issue by parth1729** [feross/webtorrent#612]
Hi, I am using the bittorrent tracker and Webtorrent both in my application. I am using Webtorrent just to seed a file using "seed" method. Here is the code snippet:

```js
var file = fs.createWriteStream("C:/"+filename);
	console.log(filename);
    var request = needle.get(UrlPath).pipe(file);
	var client=new WebTorrent();
    file.on('finish', function() {
        file.close(createTorrent("C:/"+filename, function (err, torrent) {
            if (!err) {
                client.seed("C:/"+filename);
                fs.writeFile(config.torrentFilePath, torrent);
                res.send(torrent);
            }
   });
});
```

A new peer connects to the other peers after around 10-15 minutes, maybe in the second announce interval. Earlier I was using just the bittorrent tracker and I was seeding the file manually using a torrent client. This approach did not take much time to discover a newly added peer.But, after seeding the file using Webtorrent's "seed" method, I observed this behaviour. I don't know if it has something to do with the client(Utorrent) that I am using to download the file. Could somebody please help me out with this?

**Comment by feross** [comment]
@parth1729 What exactly are you trying to do?

It seems like you're sending back the created `.torrent` file in an http response, right?

You might consider waiting until the client has completed fully seeding the file (creating the `.torrent`, announcing to trackers and the DHT, etc.) before doing that.

Try this:

```js
var file = fs.createWriteStream('C:/' + filename)
console.log(filename)
var request = needle.get(UrlPath).pipe(file)
var client = new WebTorrent()
file.on('finish', function () {
    file.close(function () {
        client.seed('C:/' + filename, function (torrent) {
            fs.writeFile(config.torrentFilePath, torrent.torrentFile)
            res.send(torrent.torrentFile)
        })
    })
})
```

I eliminated the unnecessary call to `createTorrent` since that's already done internally for you in `client.seed`. You can get the generated `.torrent` file with the `.torrentFile` property.

**Comment by parth1729** [comment]
Tried the approach you mentioned, but still no luck. It functions same as before.
Actually, I'm developing an application in which the user will initially be served a torrent file. When the user starts downloading the file, I want to seed the file from one end so that the user can download the file. And yes, I'm sending the torrent file as Http response for the user to download the torrent file.

**Comment by godigex** [comment]
Ditto for this problem. I find that downloading clients can't connect to any seeds/peers for 10~20 minutes, generally after the second or third announce. It behaves the same way with subsequent downloads from additional clients - always after a few announces regardless of how long the client has been seeding. Any ideas about what's going on here?
