### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by andreapaiola** [feross/webtorrent#633]
With WebRTC in Safari it seems feasible, right?

https://news.ycombinator.com/item?id=11142913

**Comment by feross** [comment]
It's great news that Safari seems to be planning support for WebRTC! We'll definitely make sure WebTorrent works in Safari. But it doesn't have support quite yet, so I'm going to close this issue.

**Comment by thangngoc89** [comment]
Hi, a little suprise when I go to webtorrent.io with safari on my ipad. It started to download the file (which is pretty annoying). But hey, webtorrent works on safari now.


![image](https://cloud.githubusercontent.com/assets/3049054/16969684/e668df46-4e40-11e6-8742-8109336f9b6f.png)

**Comment by DiegoRBaquero** [comment]
@thangngoc89 It's just the webseed working through XHR. WebRTC has not yet arrived to Safari, and it will take longer to arrive to mobile Safari.

**Comment by thangngoc89** [comment]
Yeah. My mistake. It's the implementation of BEP19 right?

**Comment by feross** [comment]
@thangngoc89 Yep, that's right. BEP19.

Video playback in Safari is broken at the moment. See issue: https://github.com/jhiesey/videostream/issues/24
