### ISSUE TITLE
There is already a swarm listening on port (error)

### ISSUE THREAD

**Issue by niieani** [feross/webtorrent#635]
I don't have reproduction steps for this. This happened when destroying a running torrent (not sure if that's related to the error or not).

```ts
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: There is already a swarm with info hash 3f19b149f53a50e14fc0b79926a391896eabab6f listening on port 62108
    at node_modules/bittorrent-swarm/lib/tcp-pool.js:100:22
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)
```

**Comment by feross** [comment]
What version of webtorrent? What version of node.js?

This is really odd, because an `'error'` handler is always attached to the swarm. See https://github.com/feross/webtorrent/blob/66e8be7a12c22276bcb94ba81dcc5da3a41ceeda/lib/torrent.js#L216

**Comment by niieani** [comment]
WebTorrent from Git master (cloned 2 days ago) and Node 5.6.
