### ISSUE TITLE
WebTorrent in a LAN setting without Internet connection

### ISSUE THREAD

**Issue by Wasser-Eis** [feross/webtorrent#636]
Out of a software developer perspective:

How can I set up a WebTorrent network in a LAN without Internet connection?
It can be taken for granted that all members of the LAN can exchange signaling information.
Preferably the solution does not need a tracking/bootstrap server.

Probably a related question:
How can I connect a peer to a WebTorrent network without the help of a tracking/bootstrap server.
It can be taken for granted that the peer who wants to connect to the WebTorrent network can exchange information with a peer out of the WebTorrent network.

**Comment by feross** [comment]
Right now there's no way for peers to connect without using a signaling server. Fortunately, you can run one of these easily on your own local network.

The package is called [`bittorrent-tracker`](https://github.com/feross/bittorrent-tracker). Just do:

```
$ bittorrent-tracker --port 8000
HTTP tracker: http://localhost:8000/announce
UDP tracker: udp://localhost:8000
WebSocket tracker: ws://localhost:8000
```

Ensure that the `.torrent` files and magnet links you generate include one of these (or all of these) tracker URLs. You can also force WebTorrent to use your local tracker server by including an `announce` option when you call `client.add()`. Like this:

```js
client.add(torrentId, { announce: [ 'http://localhost:8000/announce', ... ] }
```

That should be it. Enjoy.

**Comment by Wasser-Eis** [comment]
"Right now there's no way for peers to connect without using a signaling server. "
     Go, go, go implement it. I would really appreciate this feature.

**Comment by rom1504** [comment]
have a look at #288 I guess

**Comment by Wasser-Eis** [comment]
I want to connect peers only by using torrent.addPeer(). The signaling data should be exchanged via QR-Codes. I want to put all peers into one single swarm.
Isn't that independent from the DHT feature?

**Comment by rom1504** [comment]
Yes, I bet that's already possible. Did you try it ?

**Comment by Wasser-Eis** [comment]
I tried but maybe there a bug in my code. I'm not an experienced Web developer.
This is my client-side code (I use a socket.io server for assigning different numbers to the peers):
<html>
  <head>
      <meta charset="UTF-8">
      <title>WebTorrent Test</title>
   </head>
   <body>
      <p>First select file then connect peers<p>
      <style>
         #outgoing {
           width: 600px;
           word-wrap: break-word;
         }
      </style>
      <form>
         <textarea id="incoming"></textarea>
         <button type="submit">submit</button>
      </form>
      <pre id="outgoing"></pre>
      <div id="myDiv">
      </div>
   </body>
<script src="webtorrent.min.js"></script>
<script src="simplepeer.min.js"></script>
<script src="https://cdn.socket.io/socket.io-1.2.0.js"></script>
<script src="buffer.js"></script>
<script>
var client = new WebTorrent({dht: false, tracker: false});
var myPeerNumber = -42;
var p;
var theTorrentFile;
var seeded = false;
var appended = false;


function handleFileSelect(evt){
   client.seed(evt.target.files[0], function(torrent){				
      seeded = true;
      theTorrentFile = torrent.torrentFile;
   });
}
   

function isOdd(n) {
   return (n % 2 === 1);
}


var socket = io();
socket.on('number', function(msg){
	document.title = msg;
	myPeerNumber = msg;
	p = new SimplePeer({initiator: isOdd(myPeerNumber), trickle: false});
   
   if(isOdd(myPeerNumber)){
      var myDiv = document.getElementById("myDiv");
      var child = document.createElement('input');
      child.type="file";
      child.id="myFileInput";
      myDiv.appendChild(child);
      document.getElementById('myFileInput').addEventListener('change', handleFileSelect, false);
   }
   
	p.on('signal', function (data){
      document.querySelector('#outgoing').textContent = JSON.stringify(data);
	});

	document.querySelector('form').addEventListener('submit', function (ev) {
      ev.preventDefault();
      p.signal(JSON.parse(document.querySelector('#incoming').value));
	});

	p.on('connect', function (){
		if(seeded){
			p.send(theTorrentFile);
		}
	});

	p.on('data', function (data){
      if(!seeded && !appended){
         client.add(data, function (torrent){
            torrent.files[0].appendTo('body', function (err, elem) {
               if (err) throw err
            });
            torrent.addPeer(p);
            appended = true;
         });
      }
	});
});	
</script>
</html>

**Comment by Wasser-Eis** [comment]
"Yes, I bet that's already possible."
    You are right.

I found the bug.
Now it works. :-)

**Comment by feross** [comment]
Nice!

**Comment by shinp** [comment]
Do you have an offline implementation for wss://tracker.webtorrent.io. I am looking to create an 'offline' tracker (similar to that of bittorrent-tracker) that runs on wss:// protocol to support webrtc (related #325)

**Comment by feross** [comment]
@shinp I don't know what you mean by "offline implementation". The tracker needs to be reachable by the peers. You can, of course, run a tracker that's only accessible on your local network.

Peers can only connect to each other if they can both reach the same tracker.

**Comment by shinp** [comment]
Sorry, I may have communicated this wrong. I am currently using your bittorrent-tracker implementation for local network peer discovery however browser webtorrent does not connect to webtorrent-hybrid and webtorrent-desktop implementations using a localhost bittorrent-tracker. I am assuming in this case the webtorrent-hybrid and webtorrent-desktop uses standard bittorrent peer connections to communicate rather webrtc.

I was wondering if you had the implementation for wss://tracker.webtorrent.io as I would also like webrtc/webtorrent peer discovery as well.

**Comment by Zibri** [comment]
isn't it possible to use DHT in a (big) LAN?
