### ISSUE TITLE
does client.add seed after completion?

### ISSUE THREAD

**Issue by dkobia** [feross/webtorrent#638]
`client.add` does is not seeding after the torrent is done. It does show up as a Peer, but none of the other peers seem to be able to connect to it.

Do I have to do anything special after the torrent is done or should I begin an explicit `client.seed` after the torrent is done? Does DHT need to be set to true?

**Comment by feross** [comment]
`client.add` automatically seeds during and after the download is complete.

I assume you're using WebTorrent in Node.js. WebTorrent currently doesn't support the traditional methods of NAT hole punching (UPnP and NAT-PMP) that most torrent clients support. There's an issue about this here: #195. This might explain why peers outside your local network are unable to connect to your client.

As a workaround, you can set up [Port Forwarding](http://www.howtogeek.com/66214/how-to-forward-ports-on-your-router/) on your router.
