### ISSUE TITLE
Question: How visible are the hash and tracker?

### ISSUE THREAD

**Issue by ndm13** [feross/webtorrent#654]
The meat of the question is this: if someone were to make a website hosting licensed or premium content, how difficult would it be for someone to find a "direct link" to it by retrieving the hash and tracker and sharing an instant.io link to unprivileged users?

Specifically, is this something that is easy to do?  Are there precautions that must be taken when designing such a system, and what would those be?  Are there any deficiencies in the WebTorrent infrastructure that could allow for this information to be compromised?  It doesn't matter nearly as much when dealing with test files, CC-licensed media, and other essentially penalty-free media files, but if DMCA were to get involved, this is important to know and protect against.

**Comment by rom1504** [comment]
See https://github.com/feross/bittorrent-tracker/issues/58

Basically I think if you setup a private tracker, with only private torrents (http://www.bittorrent.org/beps/bep_0027.html), it should be safe enough.

Of course that wouldn't automatically add DRM to files and people could create a public torrent out of these files.

**Comment by ndm13** [comment]
How difficult would it be to obtain the source files if all rendering is done through MediaElement?  My understanding is that using MediaElement decodes the torrent segments as they come in, but I could be wrong.

**Comment by rom1504** [comment]
rendering is separated from downloading. People can always use an other client to download files.
For example you can download youtube files, without doing any rendering.

**Comment by ndm13** [comment]
Files are stored as they are rendered.  With enough obfuscation, authentication, and the use of a private tracker, the ability to obtain a copy through a separate client can be reduced.  What I'm wondering, however, is if files that are streamed into a MediaElement can be saved and redistributed.

**Comment by feross** [comment]
MediaElement supports DRM, so you can protect the content you play in a `<video>` tag.

http://www.html5rocks.com/en/tutorials/eme/basics/

Netflix uses EME, for example.
