### ISSUE TITLE
Memory leak detected in Electron

### ISSUE THREAD

**Issue by solderzzc** [feross/webtorrent#655]
The code is called as in webtorrent-app.
The torrent file contains one large video file with webseed.
The webseed speed is 2+ MB/s.

Memory leak detected in Dev Tool.
By HEAP TIMELINES, there're 257MB Typed Arrays captured.
![screen shot 2016-03-02 at 11 10 51 pm](https://cloud.githubusercontent.com/assets/3085564/13487120/23a70bc2-e0cc-11e5-9127-e9747ea040d3.png)
![screen shot 2016-03-02 at 11 11 53 pm](https://cloud.githubusercontent.com/assets/3085564/13487137/51b8c7f8-e0cc-11e5-8ded-62e7cdd9d352.png)

![screen shot 2016-03-02 at 11 14 03 pm](https://cloud.githubusercontent.com/assets/3085564/13487162/7f812e64-e0cc-11e5-8d2e-00a3afcef75b.png)

* WebTorrent version 0.81.2:
* Electron version:  0.36.8
* Browser name/version (if using WebTorrent in the browser): Electrons

**Comment by solderzzc** [comment]
Another catch may relate with simple-get. The 36% of Shallow Size.
![screen shot 2016-03-02 at 11 27 05 pm](https://cloud.githubusercontent.com/assets/3085564/13487398/7b23f1f6-e0ce-11e5-93d0-ed3b23b53208.png)

**Comment by simbazhang2016** [comment]
This issue was fixed on 0.89.0.

**Comment by solderzzc** [comment]
It was fixed after the huge fine tune.
