### ISSUE TITLE
Can't streaming video?

### ISSUE THREAD

**Issue by itanhduy** [feross/webtorrent#658]
* WebTorrent version: 0.82.0
* Node.js version:4.3.0
* Browser name/version (if using WebTorrent in the browser):Google Chorme 48.0.2564.116 m

I have link torrent: http://owshared.com/data/torrent/94ED169C8B5B3600C77EAB8408F5C3E5E7C7C1D5/Intruders (2015).torrent

And code:
` function createClient() {
    var client = window.client = new WebTorrent();
    client.on('warning', onWarning);
    client.on('error', onError);
    torrent = client.add('http://owshared.com/data/torrent/94ED169C8B5B3600C77EAB8408F5C3E5E7C7C1D5/Intruders (2015).torrent', onTorrent);
}

function onTorrent() {
    for (var i = 0; i < torrent.files.length; i++) {
        if (ifVideo(torrent.files[i].path)) {
            var files = window.files = torrent.files[i];
            files.renderTo('#video', onError);
            files.on('download', onProgress)
            break;
        }
    }
}`

![image](https://cloud.githubusercontent.com/assets/10527554/13519642/fb1469d4-e20b-11e5-8d64-9bac19a84198.png)

And html after renderTo:
`<video id="video" autoplay="" controls="" data-reactid=".0.0.0.0.0.2" src="blob:http%3A//owshared.com/a96319c3-3904-4a36-8a8e-9be3c86faa11"></video>`

And status debug:
`
webtorrent new webtorrent (peerId 2d5757303038312d663365613335393538313563, nodeId a974af88d699ec5491175ba56c21ac67f12d4c44) +0ms
ping:1 

webtorrent.min.js:4 webtorrent new webtorrent (peerId 2d5757303038312d343166346530376635366637, nodeId 740b1b933491180caa4060d6bfc20efaed610706) +13s

webtorrent.min.js:4 webtorrent add +2m

webtorrent.min.js:4 webtorrent:torrent [35366637] new torrent +2ms

webtorrent.min.js:4 bittorrent-swarm new swarm (i 94ed169c8b5b3600c77eab8408f5c3e5e7c7c1d5 p 2d5757303038312d343166346530376635366637) +131ms

webtorrent.min.js:4 webtorrent:torrent [35366637] got metadata +4ms

webtorrent.min.js:4 torrent-discovery setTorrent 94ed169c8b5b3600c77eab8408f5c3e5e7c7c1d5 +2ms

webtorrent.min.js:4 bittorrent-tracker new client 94ed169c8b5b3600c77eab8408f5c3e5e7c7c1d5 +1ms

webtorrent.min.js:4 bittorrent-tracker setInterval 900000 +3ms
webtorrent.min.js:4 bittorrent-tracker send `start` +1ms

webtorrent.min.js:4 webtorrent:torrent [35366637] verifying existing torrent data +4ms

webtorrent.min.js:4 webtorrent:torrent [35366637] done verifying +81ms

webtorrent.min.js:4 webtorrent:torrent [35366637] on store +1ms

webtorrent.min.js:4 webtorrent:torrent [35366637] select 0-1269 (priority 0) +0ms

webtorrent.min.js:4 webtorrent on torrent +2ms

webtorrent.min.js:4 render-media Use `videostream` package for Intruders.2015.720p.BluRay.x264-[YTS.AG].mp4 +2ms

webtorrent.min.js:4 webtorrent:torrent [35366637] select 0-1269 (priority 1) +2ms

webtorrent.min.js:4 webtorrent:torrent [35366637] critical 0-2 +4ms
`

It's not working. Something was wrong?. Please help me.

Thanks & Best Regards.

**Comment by ndm13** [comment]
The torrent you specified doesn't have any WebRTC trackers.  You would have to add those yourself, but only those with the modified torrent would be able to view it.  Another way around this is to implement webtorrent-hybrid instead of standard webtorrent, since webtorrent-hybrid supports UDP seeding.

On another note, it's probably not the best idea to post torrents of copyrighted material when asking for help.  If you're testing, use something you own or something open source.  I'd recommend [the Sintel torrent WebTorrent hosts](https://webtorrent.io/torrents/sintel.torrent) or its [magnet link](magnet:?xt=urn:btih:6a9759bffd5c0af65319979fb7832189f4f3c35d) as they're well-seeded and open-source, or grabbing a bunch of media files and loading them into [BTorrent](http://btorrent.xyz) and using the resulting torrent file/magnet link.

**Comment by itanhduy** [comment]
Thanks @ndm13 ,

I will use https://webtorrent.io/torrents/sintel.torrent for testing.

Sorry about my mistake.

Best Regards.

**Comment by itanhduy** [comment]
Hi @ndm13 ,

Sorry for me reopen this ticket.

I use infoHash for testing: **AC418DB33FA5CEA4FAB11BC58008FE08F291C9BE**

But I get error. You can view images below:

![image](https://cloud.githubusercontent.com/assets/10527554/13546291/42c8c7ae-e2dc-11e5-845c-c6ac0e7d6fa4.png)
![image](https://cloud.githubusercontent.com/assets/10527554/13546294/56c04f48-e2dc-11e5-8f33-fb2224f22e94.png)
![image](https://cloud.githubusercontent.com/assets/10527554/13546301/6a6eca24-e2dc-11e5-91d6-368c1408fd37.png)
![image](https://cloud.githubusercontent.com/assets/10527554/13546307/8ba1a34c-e2dc-11e5-88c8-7e7e2df33183.png)
![image](https://cloud.githubusercontent.com/assets/10527554/13546308/951d470a-e2dc-11e5-99b2-3bd6eacc0660.png)
![image](https://cloud.githubusercontent.com/assets/10527554/13546312/a96b8258-e2dc-11e5-8440-bee8a85a23cf.png)
![image](https://cloud.githubusercontent.com/assets/10527554/13546314/b68adf42-e2dc-11e5-996e-7fdb0f75f03a.png)


Thanks & hope reply from you.
Regards.

**Comment by feross** [comment]
Do not use WebTorrent for copyright infringement.
