### ISSUE TITLE
Ratelimit tracker connection attempts

### ISSUE THREAD

**Issue by dcposch** [feross/webtorrent#659]
* WebTorrent version: 0.82.1
* Node.js version: v4.2.4
* Browser name/version (if using WebTorrent in the browser): Electron 0.36

If a tracker is down, we shouldn't keep trying to connect to it:

![image](https://cloud.githubusercontent.com/assets/169280/13601015/b7d0f9e8-e4e1-11e5-9108-547ecae478da.png)

**Comment by dcposch** [comment]
When a tracker connection fails, we could mark that tracker as down and not try again for say 10 minutes

**Comment by DiegoRBaquero** [comment]
I liked @dcposch 's idea. Will look into it now and PR

**Comment by feross** [comment]
We need to be careful here. If the user's internet connection is down for a minute, we don't want to block tracker connections for 10 minutes.

**Comment by DiegoRBaquero** [comment]
@feross I opened a PR that will increase the time to reconnect on each retry. I removed the variance and set the initital at 15 seconds. Each retry adds 30 seconds.

**Comment by feross** [comment]
@dcposch FYI, this is fixed now.
