### ISSUE TITLE
filesystem paths do not work in the browser

### ISSUE THREAD

**Issue by ajainvivek** [feross/webtorrent#665]
* WebTorrent version: latest 
* Node.js version: 4.0
* Browser name/version (if using WebTorrent in the browser): Chrome/Electron

I am unable to seed the torrent file as it throws me an error "filesystem paths do not work in the browser". Electron as wrapped file system with path attribute after uploading file. Is there any way to get around this problem.

**Comment by feross** [comment]
Works fine for me in Electron. You must be changing what `require('fs')` returns somehow. Are you browserify the script? Or using `webtorrent.min.js`? Don't do that -- just use `require('webtorrent')`.

The error you're seeing comes from this code in `create-torrent`:

```js
    if (typeof fs.stat !== 'function') {
      throw new Error('filesystem paths do not work in the browser')
    }
```

**Comment by ajainvivek** [comment]
I was using webtorrent.min.js. Thanks @feross .

**Comment by feross** [comment]
Glad you got it figured out :)
