### ISSUE TITLE
HTTP trackers

### ISSUE THREAD

**Issue by chrisnharvey** [feross/webtorrent#677]
Hi there,

Amazing project, really enjoying using it!

I was just wondering if this works with standard HTTP trackers, or do I need to use a WebSocket tracker?

I'm currently using my own tracker which is running this PHP package [christeredvartsen/php-bittorrent-tracker](https://github.com/christeredvartsen/php-bittorrent-tracker)

**Comment by feross** [comment]
In environments where TCP/UDP connections are possible (i.e. Node.js, Electron, node-webkit, etc.) HTTP trackers will be used. In the web browser, TCP/UDP connections are not possible for security reasons, the newer tracker protocol that uses WebSocket is required.

**Comment by FrancoisMentec** [comment]
XMLHttpRequest can't do the trick?
