### ISSUE TITLE
Count active peers of webtorrents witouth downloading

### ISSUE THREAD

**Issue by marcu87** [feross/webtorrent#678]
Hello! 

I have a list of webtorrents, and I wan't to display how much peers are available for each webtorrent. 

How can I achieve this using only javascript and witouth start the download of the webtorrents? 

If that's not possible, is there any way to get the "Health" of the webtorrents?

Thanks

**Comment by rom1504** [comment]
Try https://github.com/feross/bittorrent-tracker/blob/master/README.md#multi-scrape

**Comment by marcu87** [comment]
Perfect! That's exactly what I was looking for.

Question: 
I'm including the WebTorrent to my project from the CDN <script src="https://cdn.jsdelivr.net/webtorrent/latest/webtorrent.min.js"></script>

Is the bittorrent-tracker included in the webtorrent.min.js? If that's the case, how can I access the "scrape" method?

**Comment by DiegoRBaquero** [comment]
Scraping is not yet available on WebSocket tracker client. PR pending: https://github.com/feross/bittorrent-tracker/pull/125

**Comment by feross** [comment]
@DiegoRBaquero WebSocket tracker scraping is released now.

@marcu87 You can use the `bittorrent-tracker` package directly to scrape: https://github.com/feross/bittorrent-tracker#multi-scrape This functionality is not yet – and may never be – exposed via the WebTorrent script itself.
