### ISSUE TITLE
webtorrent cli don't seed

### ISSUE THREAD

**Issue by aarondiazr** [feross/webtorrent#679]
Hi, I'm trying to seed a file from command line on ubuntu, but doesn't work. With webtorrent-hybrid up a server in localhost, but when I try to download it via hash or torrent file....shows

> torrent downloaded successfully from 0/0 peers in 0s!

> webtorrent is exiting...

**Comment by feross** [comment]
What version of webtorrent? `webtorrent --version`

What are the exact commands and the order you're running them in?

**Comment by aarondiazr** [comment]
Webtorrent version: 1.0.1

First create a torrent file from command line on "/home/users/videos/"

> webtorrent create "Katy Perry - Roar (Official).mp4" > katy.torrent

After, with webtorrent-hybrid (because I read webtorrent client doesn't share with webrtc peers)

> webtorrent-hybrid seed katy.torrent

After, in a new terminal execute:

> webtorrent seed 2ae1db0fdd903fec610515afaf64e714805eab2f

also... webtorrent-hybrid seed 2ae1db0fdd903fec610515afaf64e714805eab2f

**Comment by DiegoRBaquero** [comment]
There's no webtorrent version 1+.
webtorrent-hyrbrid is not stable at this time.
Don't use WebTorrent for copyright infringement.
