### ISSUE TITLE
Web seed support for multi-file torrents

### ISSUE THREAD

**Issue by dcposch** [feross/webtorrent#684]
Currently, web seeds only work for single file torrents. If we fix that, then WebTorrent will be able to download torrents like this one:

http://www.archive.org/download/alls_well_that_ends_well_2_1603_librivox/alls_well_that_ends_well_2_1603_librivox_archive.torrent

**Comment by feross** [comment]
Confirmed.

**Comment by DiegoRBaquero** [comment]
Is there an spec? I was thinking (for multi-file torrents)... For any given piece being downloaded to a webseed, pass the file that it belongs to the swarm's webconn and append it to the url of the webseed.

**Comment by yciabaud** [comment]
You're right according to the [BEP0019](http://www.bittorrent.org/beps/bep_0019.html) :+1: 

> BitTorrent clients normally use the "name" from the torrent info section to make a folder, then use the "path/file" items from the info section within that folder. For the case of Multi-File torrents, the "url-list" must be a root folder where a client could add the same "name" and "path/file" to create the URL for the request.
> 
> For example:
> ... 8:url-list22:http://mirror.com/pub/ 4:infod5:filesld6:lengthi949e4:pathl10:Readme.txte e4:name7:michael
> 
> A client would use all that to build a url: http://mirror.com/pub/michael/Readme.txt

**Comment by yciabaud** [comment]
Notice the name of the torrent is appended to the root URL too.

**Comment by dcposch** [comment]
PR coming soon

**Comment by feross** [comment]
Merged Daniel's PR (https://github.com/feross/bittorrent-swarm/pull/33) with some fixes (https://github.com/feross/bittorrent-swarm/commit/247c79a1be5029654b03ad022e56124eea481eb0).

Still need to handle requests that span multiple files better.

**Comment by feross** [comment]
As of @dcposch's most recent PR (https://github.com/feross/bittorrent-swarm/pull/34), multi-file web seeding should be working correctly. Please open a new issue if this is not the case.
