### ISSUE TITLE
WebTorrent does not play back some MP4 files

### ISSUE THREAD

**Issue by Wasser-Eis** [feross/webtorrent#685]
* WebTorrent version: 0.86.1
* Node.js version: -
* Browser name/version (if using WebTorrent in the browser): Chrome 49.0.2623.87 m

The quick example of the WebTorrent Documentation on webtorrent.io does not work with some .mp4 files. I have tried it with three different mp4 files. I always got an "Uncaught Error: Unsupported file type "": Cannot append to DOM" error. 
For example the following mp4 file does not get played back:
http://peach.themazzone.com/durian/movies/sintel-2048-surround.mp4
My desktop VLC player can play this mp4 file back without problems.
Please explain.

Additionally:
Where can I download a mp4 file that definitively works with WebTorrent?

**Comment by rom1504** [comment]
have a look at #405

**Comment by feross** [comment]
@Wasser-Eis This mp4 file definitely works: https://webtorrent.io/torrents/sintel-1024-surround.mp4

But the file that you linked to also should work. If I download it, then drop it onto https://instant.io it works just fine. The error message you're getting is weird because it normally shows up for file extension types that cannot be added to the DOM, for example ".exe" or ".avi". But it's an empty string for you.

Are you adding the `sintel-2048-surround.mp4` file directly? Or adding a .torrent file?

**Comment by Wasser-Eis** [comment]
It also does not work with your posted mp4 file.
These are the most relevant parts of my code:

document.getElementById('fileinput').addEventListener('change', function(){
    file2 = this.files[0];
}, false);

client.seed(file2, {name: "Test42"}, function(torrent){});

client.add(magnetURI, function(torrent){
        file = torrent.files[0];
        file.appendTo('body', function (err, elem) {
	         if (err) throw err // file failed to download or display in the DOM
	});
}

"Are you adding the sintel-2048-surround.mp4 file directly? Or adding a .torrent file?"
    I added it directly.

**Comment by feross** [comment]
@Wasser-Eis Both adding the video directly or the .torrent file should work.

What browser are you using?

**Comment by Wasser-Eis** [comment]
I use Google Chrome in the most current version.

**Comment by feross** [comment]
I don't know what to tell you – there's clearly a mistake somewhere in your code. If you send a link to your full code, I can take a quick look.

I recommend using the [Instant.io code](https://github.com/feross/instant.io/blob/master/client/index.js) as a guide.
