### ISSUE TITLE
WebRTC DHT

### ISSUE THREAD

**Issue by Wasser-Eis** [feross/webtorrent#686]
Hello,

what is the current state of the (planned?) WebRTC-based DHT for WebTorrent?
The node.js WebTorrent clients participate only in the normal, non-WebRTC  DHT of the Bittorent network, right?
The Webtorrent browser clients can query this non-WebRTC DHT but do not participate in it, right?
There is neither for the browser nor for the node.js Webtorrent client a WebRTC-based DHT, right?
Sorry, I'm a bit confused at the moment.

**Comment by rom1504** [comment]
Yes that's correct.
There is already an issue open on this topic : https://github.com/feross/webtorrent/issues/288
Let's avoid duplicating issues, you can read and comments on this issue.
