### ISSUE TITLE
Does torrent.addPeer(addr) work in the browser?

### ISSUE THREAD

**Issue by Wasser-Eis** [feross/webtorrent#687]
Does this function work in the browser?
If yes, please give at least one concrete example how to use it in the browser?
When does it work?
How should addr be encoded?

**Comment by feross** [comment]
Yes, but you can only use it for WebRTC peers in the browser.

Normally, you don't need to call `addPeer`. You can rely on WebTorrent to find peers for you based on the tracker servers or DHT. This is just for manually adding a peer to the client.

Docs are updated now: https://github.com/feross/webtorrent/blob/master/docs/api.md#torrentaddpeerpeer
