### ISSUE TITLE
Uncaught TypeError: must start with number, buffer, array or string

### ISSUE THREAD

**Issue by ajainvivek** [feross/webtorrent#691]
The error started appearing recently while seeding and downloading a file. Its not blocking anything as such but can I get to know what I am doing wrong. 

Thanks,

**Comment by rom1504** [comment]
Can you paste the rest of the error ? (The stack trace containing the lines where it happened and all)

**Comment by ajainvivek** [comment]
I am using minified version of webtorrent 

```
c	@	webtorrent.min.js:formatted:1
i	@	webtorrent.min.js:formatted:1
n.binaryToHex	@	webtorrent.min.js:formatted:1
r._onSocketData	@	webtorrent.min.js:formatted:1
r.emit	@	webtorrent.min.js:formatted:1
i	@	webtorrent.min.js:formatted:1
o.push	@	webtorrent.min.js:formatted:1
r._onMessage	@	webtorrent.min.js:formatted:1
```

Hope this trace makes some sense.
﻿

**Comment by feross** [comment]
@ajainvivek 

> parse-torrent build is failing is it do something with that ???

No, that's a false positive.

Can you post the code you wrote?

**Comment by ajainvivek** [comment]
Snippet of code:           

 ```
 return new RSVP.Promise(function (resolve, reject) {
			client.add("magnet:?xt=urn:btih:" + magnetURI, function (torrent) {
				// Got torrent metadata!
				console.log('Client is downloading:', torrent.infoHash)
				callback(torrent);
				resolve(torrent.files);
			});
		});
```

File: https://github.com/ajainvivek/P2PDrop/blob/master/app/services/webtorrent.js
App: http://app.p2pdrop.com/

I am unable to get complete stack trace as the error seems to starts from webtorrent.min.js

**Comment by ajainvivek** [comment]
Any updates @feross ?

**Comment by ajainvivek** [comment]
Issue seems to be not happening after updating webtorrent.min.js. 

Thanks

**Comment by feross** [comment]
@ajainvivek Glad you got it figured out! When your app is ready, you should send a PR, or open an issue to add it to the list of WebTorrent users: https://github.com/feross/webtorrent/blob/master/docs/faq.md#who-is-using-webtorrent-today
