### ISSUE TITLE
bittorrent-swarm methods

### ISSUE THREAD

**Issue by Wasser-Eis** [feross/webtorrent#695]
swarm.on('wire', function(wire) {
    // a relevant wire has appeared, see `bittorrent-protocol` for more info
    wire.on('unchoke', function() {
        // we are now unchoked
    })
    swarm.wires // <- list of all connected wires
});

Do swarm and wire instances offer other methods?
Are there other undocumented functions in the WebTorrent API?
Can I manually choke a peer?
Which of these functions can only be used in node.js and which ones can be used in the browser?

**Comment by feross** [comment]
Yes, there are methods on the `swarm` and `wire` objects. The methods are undocumented because they should probably not be used on most cases, but you're free to try.

The `wire` methods are documented here: https://github.com/feross/bittorrent-protocol

**Comment by feross** [comment]
Some methods like `wire.use` are intended to be used by end users, though.

You can manually choke a peer with `wire.choke()`.
