### ISSUE TITLE
What does a WebTorrent tracking server exactly do?

### ISSUE THREAD

**Issue by Wasser-Eis** [feross/webtorrent#698]
What does a WebTorrent tracking server do exactly?

Edit:
Does a WebTorrent tracking server keeps track of which peer has which fragment of a file?
How to peers within a bittorrent-swarm behave?

**Comment by DiegoRBaquero** [comment]
A WebTorrent tracking (Websocket one) allows browser clients to connect between them using WebRTC. It's the only way they can "find" themselves. DHT is not implementable (for now) in the browser.

**Comment by feross** [comment]
The tracker just helps peers to find each other.

The peer sends a message to the tracker to register its interest in a torrent. The tracker responds with a list of other peers who have previously expressed interest.

Then the peer connects directly to each of the peers it received from the tracker.

Things the tracker does NOT do:

- The tracker does NOT act as a proxy or middle-man between the peers.
- The tracker does NOT relay data between peers.
- The tracker CANNOT see what pieces of the torrent each peer has.
- The tracker CANNOT see the .torrent file o(r any metadata contained within the .torrent file, like the list of file names).

**Comment by jeremy-bruns** [comment]
What about webrtc leaks ?!

**Comment by feross** [comment]
@jeremy-bruns How is that related to this issue?
