### ISSUE TITLE
WebTorrent issue

### ISSUE THREAD

**Issue by NaiTreNo** [feross/webtorrent#699]
Hello, Im trying to download this torrent https://yts.ag/torrent/download/42FDF1AEEE3C641BE8C41BC1FEEDDF87A50CAE12.torrent from : https://instant.io/ , its showing all torrent informations but its stuck in 0% but when I try to download the same torrent from my utorrent program it start downloading perfectly is the problem because the torrent include files ? thanks.

**Comment by DiegoRBaquero** [comment]
WebTorrent in the browser can't connect to TCP/UDP (normal bittorrent clients) peers, only WebRTC peers.

Don't use WebTorrent for copyright content.
