### ISSUE TITLE
Question about WebTorrent

### ISSUE THREAD

**Issue by NaiTreNo** [feross/webtorrent#700]
Hello, Can I use WebTorrent in my website for example putting the code inside PHP file or something? And what's the another method to use WebTorrent except browser? Thanks.

**Comment by DiegoRBaquero** [comment]
WebTorrent won't work in PHP unless you are sending the pure HTML/JS code from PHP (Which really doesn't use PHP for WebTorrent). You can use WebTorrent in Node or electron too.

**Comment by NaiTreNo** [comment]
Can you give me an example please :)
