### ISSUE TITLE
Get Download speed, Upload speed And progress from node

### ISSUE THREAD

**Issue by NaiTreNo** [feross/webtorrent#701]
Hello, I'm trying to make a code that makes me able to download torrent via node inside PHP, I succeeded when I make it run using <?php exec('webtorrent '.$link);?> but now I'm trying to get process details in PHP can that be done? Thanks.

**Comment by feross** [comment]
WebTorrent has two command line flags for getting information about the progress.

```
--on-done [script]      run script after torrent download is done
--on-exit [script]      run script before program exit
```

With these flags, you can make scripts run when the torrent completes. But, honestly, this might be a bit tricky to do out of the box.

You might want to write your own Node.js script which regularly outputs progress to stdout, then read that output from your PHP process.
