### ISSUE TITLE
webtorrent.min.js:7 Uncaught TypeError: Cannot read property 'readUInt8' of undefined

### ISSUE THREAD

**Issue by Wasser-Eis** [feross/webtorrent#717]
* WebTorrent version: v0.90.0 
* Browser name/version (if using WebTorrent in the browser): Google Chrome 49.0.2623.110 m

I once again try to use client.appendTo(....) to get mp4 videos played back in the browser. This worked for this MP4 file: http://www.w3schools.com/html/mov_bbb.mp4 

But if I use the same code with this MP4 file: http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_2160p_30fps_normal.mp4

, I get the following error:
"webtorrent.min.js:7 Uncaught TypeError: Cannot read property 'readUInt8' of undefined"

**Comment by feross** [comment]
Thanks for reporting this, but it actually looks like a bug in `videostream`, or one of it's dependencies.

@jhiesey - can you confirm?

Here's a full stack trace:

```
Uncaught TypeError: Cannot read property 'readUInt8' of undefinedexports.esds.decode
  Box.decodeWithoutHeaders
  Box.decode
  exports.AudioSampleEntry.decode
  Box.decodeWithoutHeaders
  Box.decode
  exports.stsd.decode
  Box.decodeWithoutHeaders
  Box.decode
  Box.decodeWithoutHeaders
  Box.decode
  Box.decodeWithoutHeaders
  Box.decode
  Box.decodeWithoutHeaders
  Box.decode
  Box.decodeWithoutHeaders
  Box.decode
  Box.decodeWithoutHeaders
  (anonymous function)
  Decoder._write
  doWrite
  writeOrBuffer
  Writable.write
  ondata
  EventEmitter.emit
  readableAddChunk
  Readable.push
  (anonymous function)
  (anonymous function)
  Item.run
  drainQueue
```

**Comment by jhiesey** [comment]
@feross: This should fix the exception: https://github.com/jhiesey/mp4-box-encoding/commit/9a9c7c3274e835481f77018beb75c6eb446367bd

However, this file still doesn't work even with that fix, so I'll keep investigating.

**Comment by jhiesey** [comment]
Yeah, chrome MediaSource doesn't seem to like the audio mime type of `audio/mp4; codecs="mp4a.6b"` on the audio track. This could either be a limitation of the browser or a bug in computing the mime type in a dependency of videostream. I'll look at this soon.

**Comment by feross** [comment]
@jhiesey Cool, thanks for digging into this :+1:
