### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by steelbrain** [feross/webtorrent#726]
The releases are nice but looking through commit history isn't the best experience ever, it would be nice to have a changelog for future versions so we can know in one look what's changed/updated

**Comment by feross** [comment]
Agreed. Change logs are nice.

Can someone take a stab at adding a changelog for the past 2-3 releases as a starting point? I'm happy to keep it up to date after that :+1:

**Comment by feross** [comment]
This is done now!

https://github.com/feross/webtorrent/blob/master/CHANGELOG.md
