### ISSUE TITLE
Downloads folder in Windows should be respected

### ISSUE THREAD

**Issue by nkour** [feross/webtorrent#729]
it's not always USER\Downloads, it should ask the OS

**Comment by nkour** [comment]
as a side note, context menu should have open destination folder

**Comment by rom1504** [comment]
this should go in https://github.com/feross/webtorrent-desktop/issues

**Comment by feross** [comment]
@nkour What is your `Downloads` folder called if not `Downloads`? Is this a language issue?

**Comment by feross** [comment]
Moved to: https://github.com/feross/webtorrent-desktop/issues/359
