### ISSUE TITLE
no audio in Dolby AC3 file

### ISSUE THREAD

**Issue by nkour** [feross/webtorrent#730]
Video: MPEG4 Video (H264) 1920x1080 25fps [V: h264 high L4.1, yuv420p, 1920x1080 [default]]
Audio: Dolby AC3 48000Hz stereo 192kbps [A: English [eng] (ac3, 48000 Hz, stereo, 192 kb/s) [default]]

**Comment by rom1504** [comment]
this should go in https://github.com/feross/webtorrent-desktop/issues

**Comment by feross** [comment]
See https://github.com/feross/webtorrent-desktop/issues/350

**Comment by feross** [comment]
**If you want Dolby surround sound (AC3) support in WebTorrent, please star this Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=611517**
