### ISSUE TITLE
Does not work Mac OS X 10.8.2

### ISSUE THREAD

**Issue by motfinger** [feross/webtorrent#731]
* WebTorrent version: mac
* Node.js version:
* Browser name/version (if using WebTorrent in the browser):

Cannot install it.

**Comment by DiegoRBaquero** [comment]
Screenshots? Logs? Also, I think this is intended for the [desktop](https://github.com/feross/webtorrent-desktop) version.

**Comment by feross** [comment]
OS X 10.8 is almost 4 years old, and it's either unsupported by Apple or will be very soon. Unless it's a really easy fix, I can't afford to spend a ton of time to fix this. But if you have more info, feel free to provide it and we'll do what we can if it's easy.
