### ISSUE TITLE
Include simple browser that connect ONLY to webtorrent

### ISSUE THREAD

**Issue by webtrnt** [feross/webtorrent#734]
something like QtWeb, github.com/LOOT/LOOT 's browser.

Advantage
1. So people who disable browser's WebRTC for security can use webtorrent.
2. Split GUI <---> Core will reduce memory usage.

WebTorrent GUI(browser) <===> Webtorrent_core.exe <---> Internet or Proxied Internet

**Comment by feross** [comment]
I don't really understand what this issue is asking for. WebTorrent Desktop already has the UI and torrent engine separated into different processes.
