### ISSUE TITLE
Is Sintel a public domain or Creative Commons film?

### ISSUE THREAD

**Issue by webtrnt** [feross/webtorrent#737]
https://webtorrent.io/
https://webtorrent.io/desktop

As far as I can see, https://webtorrent.io/ is showing COPYRIGHTED movies as screenshot.
I think I should report https://webtorrent.io/ as copyright violation.

> https://github.com/feross/webtorrent/issues/699
> Don't use WebTorrent for copyright content.
>  DiegoRBaquero commented Mar 28, 2016  (Collab)

That's funny... He's actually doing illegal download.

**Comment by webtrnt** [comment]
https://archive.is/kPhDK

**Comment by feross** [comment]
The film "Sintel" was released under a Creative Commons license by the Blender Foundation. It's free to reproduce and distribute.

You can learn more about [Sintel](https://en.wikipedia.org/wiki/Sintel) and [Creative Commons](https://en.wikipedia.org/wiki/Creative_Commons_license) on Wikipedia. Please do your research before making inaccurate claims.

**Comment by feross** [comment]
All the sample films that come bundled with WebTorrent are Creative Commons licensed or public domain.

You can find great public domain and Creative Commons content on the [Internet Archive](https://archive.org/), [Librivox](https://librivox.org/) (audiobooks), and [Bitlove](https://bitlove.org/) (podcasts).
