### ISSUE TITLE
Can't install on 32-bit Windows

### ISSUE THREAD

**Issue by kapitanluffy** [feross/webtorrent#739]
* WebTorrent version: 0.3.3
* Node.js version: n/a

I downloaded the setup file from the website and it fails to install.
Tried running it as administrator too.

Here is the log: https://gist.github.com/kapitanluffy/6f5596a66c68f3fe8fb57314a1bf5783

**Comment by feross** [comment]
Are you using 32 bit Windows?

**Comment by AgoniH** [comment]
Same issue here. Using Windows 7 Ultimate, 32-bit.

**Comment by kapitanluffy** [comment]
@feross yes

**Comment by AgoniH** [comment]
Any idea how to fix it, @feross ? It has been four days...

**Comment by nkittsteiner** [comment]
Is this related to https://github.com/feross/webtorrent-desktop ?? Maybe should be moved over there.

**Comment by Cariocecus** [comment]
Same problem, Windows 10 win32

**Comment by kapitanluffy** [comment]
@nkittsteiner now that you mentioned it, is there a way we can transfer this issue? I already commented in https://github.com/feross/webtorrent-desktop/issues/416 though.

**Comment by feross** [comment]
Let's just move discussion to https://github.com/feross/webtorrent-desktop/issues/416

**Comment by feross** [comment]
If you were having issues installing WebTorrent Desktop on Windows 32 bit, you should know that v0.4.0 (released a few days ago) has support for Windows 32 bit now! Enjoy!

You an grab the latest installer from: https://webtorrent.io/desktop
