### ISSUE TITLE
Missing API documentation for "torrent.on"

### ISSUE THREAD

**Issue by Tercus** [feross/webtorrent#740]
* WebTorrent version: 0.86.2
* Node.js version: 5.8.0

The API documentation does not list all the possible triggers that can be used for "torrent.on". It would be really helpful if there was a complete list of them. These are the ones I found being used in webtorrent-desktop:
```
	torrent.on('warning', function (err) {})
	torrent.on('error', function (err) {})
	torrent.on('infoHash', function () {})
	torrent.on('metadata', function () {})
	torrent.on('ready', function () {})
	torrent.on('done', function () {})
```
After all, they are great for debugging.

**Comment by rom1504** [comment]
a few are there https://github.com/feross/webtorrent/blob/master/docs/api.md#torrentondone-function-- but I guess the other ones might be documented yeah

**Comment by DiegoRBaquero** [comment]
Feel free to throw make a PR :)

**Comment by Tercus** [comment]
I'm new to using github, so I *think* I have done that?
https://github.com/feross/webtorrent/pull/747

I only added minimal info, because I don't really know much about them. But often it helps just knowing that the options are there...

**Comment by feross** [comment]
Done, thanks!
