### ISSUE TITLE
Error in connection establishment: net::ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by douineauromain** [feross/webtorrent#741]
Hello,

* WebTorrent version: 0.90.3
* Node.js version: nwjs 0.12.3
* Browser name/version (if using WebTorrent in the browser): Chromium 41.0.2272.76

I tried on Windows 10 and OSX El Captain but I always have this error :

![image](https://cloud.githubusercontent.com/assets/8361263/14397005/316ab840-fddb-11e5-995c-6d1263bde828.png)

Maybe my NWJS version is too old ? But currently I've problems to update to v0.13 or 0.14
https://github.com/nwjs/nw.js/blob/master/CHANGELOG.md

Thx

**Comment by DiegoRBaquero** [comment]
This was problem of the tracker. It's been fixed. Please open a new issue if it happens again.
