### ISSUE TITLE
 WebSocket connection to 'wss://tracker.fastcast.nz/' failed: Error in connection establishment: net::ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by douineauromain** [feross/webtorrent#743]
Hello,

It's about https://github.com/feross/webtorrent/issues/741
![image](https://cloud.githubusercontent.com/assets/8361263/14406775/cc403f48-feb2-11e5-8d81-174a629d8bb6.png)

I still have the problem :(

**Comment by douineauromain** [comment]
I tried again and I hadn't the error message, but got nothing on instant.io
![image](https://cloud.githubusercontent.com/assets/8361263/14406911/25eac362-feb6-11e5-9f6f-c88f8139bd2c.png)

**Comment by rom1504** [comment]
I believe that tracker was down a little while ago. Can you try again ?

**Comment by douineauromain** [comment]
Currently I have `WebSocket connection to 'wss://tracker.fastcast.nz/' failed: Error in connection establishment: net::ERR_CONNECTION_RESET`

**Comment by DiegoRBaquero** [comment]
Can you load https://tracker.fastcast.nz/stats ?

**Comment by douineauromain** [comment]
Right now I can. So i tried again hadn't the error message but still got nothing on instant.io

**Comment by DiegoRBaquero** [comment]
@douineauromain What do you mean "I still have nothing on instant.io"?

**Comment by douineauromain** [comment]
@DiegoRBaquero I mean I copy the magnet: url returned by the `client.seed` function and paste it in instant.io, and nothing happens 
https://cloud.githubusercontent.com/assets/8361263/14406911/25eac362-feb6-11e5-9f6f-c88f8139bd2c.png

**Comment by DiegoRBaquero** [comment]
Where are you running that `client.seed`? Node?

**Comment by douineauromain** [comment]
Yes you can have all information in my first issue : https://github.com/feross/webtorrent/issues/741

> WebTorrent version: 0.90.3
> Node.js version: nwjs 0.12.3
> Browser name/version (if using WebTorrent in the browser): Chromium 41.0.2272.76

**Comment by DiegoRBaquero** [comment]
Are you using webtorrent-hybrid? webtorrent in node won't connect to webrtc clients.

**Comment by douineauromain** [comment]
No sorry I don't used webtorrent-hybrid but webtorrent.

So I tried with it.

During npm install (on Windows 10) I had 
`MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [D:\Users\Romain\[...]\node_modules\sleep\build\binding.sln]`
```
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
70:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node
-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Users\Romain\[...]\node_modules\sleep
gyp ERR! node -v v5.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:sleep@3.0.1 sleep@3.0.1 install: `node-gyp rebuild`
npm WARN install:sleep@3.0.1 Exit status 1
```

Is this mean all people which will install my software will need to have installed .NET Framework ?

Also I see in log the installation download ElectronJS 
```
> node install.js

Downloading electron-v0.37.5-win32-x64.zip
```

But I'm using NW.JS instead of ElectronJS is this also a problem ?

I tried without installing .NET and got this :
```
Uncaught SyntaxError: D:\Users\Romain[...]\node_modules\webtorrent-hybrid\lib\global.js:17
wrtc.on('error', (err, source) => {
                               ^^
Unexpected token =>
```

**Comment by feross** [comment]
The last error (about `=>`) is due to an ES6 feature sneaking into the code. Just patched `webtorrent-hybrid` to remove it. You could also update node to the very latest version to make it work.

**Comment by feross** [comment]
The npm install error looks like a bug with a `webtorrent-hyrbid` dependency depending on `xvfb`. Just sent a PR to make that an optional dependency: https://github.com/mappum/electron-eval/pull/13 Should make this work for Windows users (unless there are also other issues).

**Comment by feross** [comment]
> No sorry I don't used webtorrent-hybrid but webtorrent.

You're definitely using `webtorrent-hyrbid`. If you switch to `webtorrent` then you shouldn't get any of these compile errors.

**Comment by Zibri** [comment]
I cloned instant.io and run it from my host... I get the same result I get on instant.io
"WebSocket connection to 'wss://tracker.fastcast.nz/' failed: Error in connection establishment: net::ERR_CONNECTION_RESET"

**Comment by DiegoRBaquero** [comment]
@Zibri tracker is down. Can be ignored if you are using other trackers. jakefb is the owner. 

@jakefb Can you bring it back up?

**Comment by jakefb** [comment]
Hi @Zibri and @DiegoRBaquero, sorry about this. I noticed the website is down this morning. It is an issue with the web server which is hosted by a friend of mine. I am waiting to here back from him on the situation. It could just be a server maintenance. I will try get it back online as soon as possible.
