### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by montogeek** [feross/webtorrent#744]
* WebTorrent version: 0.3.3
* Node.js version: 5.3.0 (although I am using nvm)

Hi! Great app, I just watched a movie over the Chromecast, worked flawlessly!

I got this error after hitting Cmd+Q in the app while it was downloading 3 torrents:
![screen shot 2016-04-09 at 23 01 03](https://cloud.githubusercontent.com/assets/1002461/14408019/66aea4ae-fea7-11e5-9261-cb8102b6f073.png)

**Comment by rom1504** [comment]
This is an issue for https://github.com/feross/webtorrent-desktop

**Comment by montogeek** [comment]
Thank you :) https://github.com/feross/webtorrent-desktop/issues/373
