### ISSUE TITLE
Idea - Subtitles/VLC 

### ISSUE THREAD

**Issue by HiMutz** [feross/webtorrent#745]
Subtitle support? 
or allow the client to stream to VLC player perhaps? to work like an ancre

**Comment by rom1504** [comment]
Did you meant to open this on https://github.com/feross/webtorrent-desktop ?
Otherwise https://github.com/feross/webtorrent-cli already supports opening to vlc.

**Comment by HiMutz** [comment]
my bad :( the sleep deprived me didn't realize I was posting on the wrong repo

**Comment by DiegoRBaquero** [comment]
https://github.com/feross/webtorrent-desktop/issues/281
