### ISSUE TITLE
close https://instant.io/ download not work

### ISSUE THREAD

**Issue by asifagaria** [feross/webtorrent#746]
close https://instant.io/ download not work

**Comment by DiegoRBaquero** [comment]
I don't really understand what the issue is?

Can you please provide more information and how to reproduce it

**Comment by asifagaria** [comment]
i mean i upload a file on instant.io and get hash b0e0135a6b594b288deaceb80cf53f1f4101f8d3

it's work perfect when i close instant.io window then shah data not found stop seed

**Comment by DiegoRBaquero** [comment]
If that tab is the only one seeding of course it will stop working because nobody else is seeding that hash.

**Comment by asifagaria** [comment]
ok if the webtorrent cli have seed server

**Comment by DiegoRBaquero** [comment]
Yes, but it seems you want to connect to webrtc peers. Use [webtorrent-hybrid](https://github.com/feross/webtorrent-hybrid) in the CLI: `npm i -g webtorrent-hybrid` :)

**Comment by asifagaria** [comment]
Thanks 1 more question i make a webtorrent seed server web

**Comment by DiegoRBaquero** [comment]
For a web seed you just need a CORS enabled web server and to add the URL into the torrent file.

**Comment by asifagaria** [comment]
thanks and need sum ,ore help how to change webtorrent default trackers like my local trackers

**Comment by DiegoRBaquero** [comment]
You can use `opts.announce` parameter for the client. More info here: https://webtorrent.io/docs
