### ISSUE TITLE
Seeding in Node (linux) eats a lot of CPU

### ISSUE THREAD

**Issue by Tercus** [feross/webtorrent#753]
* WebTorrent version: webtorrent-hybrid 1.0.1 with webtorrent 0.88.3
* Node.js version: 5.10.1
* OS: Linux in a VM

When I try to seed a file from within node to my custom tracker, it takes up quite a bit of CPU power. Even though it is in a VM, I still think this is a bug. It just takes 2 torrents to push CPU usage to 100% in the VM.
The command I use:
`client.seed('./storage/image.jpg')`
It made no difference whether I used optional arguments or provided it with a callback function.

**Comment by DiegoRBaquero** [comment]
Duplicate https://github.com/feross/webtorrent/issues/551

Will be fixed when the bugfix reaches the stable channel.

**Comment by feross** [comment]
Should be fixed in ~8 weeks when Electron will pull in Chrome 51.
