### ISSUE TITLE
Support/Sanity for Safari Browser.

### ISSUE THREAD

**Issue by gauravsaini** [feross/webtorrent#754]
* WebTorrent version: <1.x
* Node.js version: x.x
* Browser name/version (if using WebTorrent in the browser): Safari

Since webrtc is now being supported by safari as well, make sure it works across :+1: 
https://webkit.org/status/#specification-webrtc

**Comment by feross** [comment]
Once Safari actually ships WebRTC support, we'll make sure it works there. For now, this is only in Webkit, and it's also incomplete.
