### ISSUE TITLE
Does not read subtitles.

### ISSUE THREAD

**Issue by GabeRivera** [feross/webtorrent#755]
* WebTorrent version:  0.3.3 (0-a5366c3)
* Node.js version: 5.0.0
* Browser name/version (if using WebTorrent in the browser): 

Unfortunately I've just come to report a bug, not to fix it as I do not know how. Anyways, I noticed that subtitles are not recognized

**Comment by feross** [comment]
This will be fixed in the next version of the app. Will be v0.4.0. Released in the next couple of days.

**Comment by GabeRivera** [comment]
Awesome! Thanks for the reply man, and great work so far. Its a great project!
