### ISSUE TITLE
Why no book support?

### ISSUE THREAD

**Issue by origina** [feross/webtorrent#760]
* WebTorrent version:
* Node.js version:
* Browser name/version (if using WebTorrent in the browser):

I want to be able to download ebooks.

**Comment by rom1504** [comment]
webtorrent can download any file.
If you meant you want book visualization support in webtorrent-desktop, open an issue there https://github.com/feross/webtorrent-desktop/issues with more details.

**Comment by feross** [comment]
Hey @origina! Supporting PDF files in WebTorrent Desktop is a great idea. Will open an issue there for it.
