### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by BocaBoy** [feross/webtorrent#763]
* WebTorrent version: Latest
* Node.js version: ?
* Browser name/version (if using WebTorrent in the browser):

I have no sound in a Windows version. I am using a Windows 10. What do I need to do to fix the issue?

Thank you!

**Comment by rom1504** [comment]
see https://github.com/feross/webtorrent-desktop/pull/424

**Comment by feross** [comment]
**If you want Dolby surround sound (AC3) support in WebTorrent, please star this Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=611517**
