### ISSUE TITLE
why is your js blocking udp trackers & how to download this one

### ISSUE THREAD

**Issue by CodeLyokotEAM** [feross/webtorrent#764]
I can't Download this magnet torrent.
why is your js blocking udp trackers(if you said it is unsecure) ?  & so how to download this one in web torrent?

magnet:?xt=urn:btih:92B4D5EA2D21BC2692A2CB1E5B9FBECD489863EC&dn=Avengers%3A+Age+of+Ultron+%282015%29+1080p+BrRip+x264+-+YIFY&tr=udp%3A%2F%2Ftracker.yify-torrents.com%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Fexodus.desync.com%3A6969&tr=udp%3A%2F%2Ftracker.istole.it%3A80&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2F9.rarbg.com%3A2710&tr=udp%3A%2F%2Fp4p.arenabg.ch%3A1337&tr=udp%3A%2F%2Fp4p.arenabg.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp://tracker.openbittorrent.com:80/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://coppersurfer.tk:6969/announce

**Comment by rom1504** [comment]
Webtorrent cannot download torrent not seeded on the webrtc torrent network. Also, Webtorrent doesn't support copyright infringement.
