### ISSUE TITLE
.add(torrentUrl) erronously adds the local client port

### ISSUE THREAD

**Issue by mrozbarry** [feross/webtorrent#768]
* WebTorrent version: 0.91.0
* Node.js version: 5.8
* Browser name/version (if using WebTorrent in the browser): Chrome/49.0.2623.112 (64-bit)

While testing my app, I am running from http://localhost:3000 .  To test, I added `http://releases.ubuntu.com/16.04/ubuntu-16.04-desktop-amd64.iso.torrent` as the torrent url with no extra options.  After it's added, I get an error saying the torrent `http://releases.ubuntu.com:3000/16.04/ubuntu-16.04-desktop-amd64.iso.torrent` couldn't be added.  Why is port 3000 being added?

**Comment by feross** [comment]
Can you share a complete code example?

**Comment by mrozbarry** [comment]
I'm using webpack-dev-server, which is serving my files on port 3000.  For my webpack config, I added
` target: 'web',
  node: {
    fs: 'empty'
  }` as part of my configuration

```javascript
import WebTorrent from 'webtorrent'

const client = new WebTorrent()
client.on('torrent', function (torrent) {
  console.log('A new torrent has been added:', torrent)
})
client.add('http://releases.ubuntu.com/16.04/ubuntu-16.04-desktop-amd64.iso.torrent')
```

**Comment by mrozbarry** [comment]
@feross I made a much more comprehensive example [here](https://github.com/mrozbarry/webtorrent-webpack-port)

**Comment by mrozbarry** [comment]
@feross your [issue is here](https://github.com/feross/webtorrent/blob/master/lib/torrent.js#L218).  The try/catch isn't doing what you expect it to.  Looks like parseTorrent doesn't throw, even though it looks like it should.

**Comment by feross** [comment]
This is a bug in `http-browserify` which webpack is using. Browserify doesn't have this issue because it's using the superior `stream-http` package.

webpack should switch to use `stream-http`. Issue here: https://github.com/webpack/node-libs-browser/issues/38
