### ISSUE TITLE
Is it possible to add trackers programmatically?

### ISSUE THREAD

**Issue by chrisnharvey** [feross/webtorrent#770]
Hi,

I'm looking for the ability to add trackers to a torrent that is already downloading, is this possible.

I'm looking for something along the lines of:

```
torrent.addTracker('wss://tracker.com')
```

**Comment by feross** [comment]
Sorry -- this is not supported. You have to add trackers upfront:

```js
client.add(torrentId, { announce: ''wss://tracker.com' })
```

What is the use case for this?

**Comment by chrisnharvey** [comment]
I'm creating a private tracker to allow the download of software from my site.
I was thinking that the tracker URL will contain a key to identify a user and their access to the torrent. Which would change every so often to prevent it from being shared. So it would need to delete the old tracker URL and replace it with a new one containing a new key.
I'm probably completely over thinking this so please let me know if you know of a simpler way to achieve this.
Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Feross Aboukhadijeh <notifications@github.com> Date: 24/04/2016  9:43 a.m.  (GMT+00:00) To: feross/webtorrent <webtorrent@noreply.github.com> Cc: Chris Harvey <chris@chrisnharvey.com>, Author <author@noreply.github.com> Subject: Re: [feross/webtorrent] Is it possible to add trackers programmatically? (#770) 
Sorry -- this is not supported. You have to add trackers upfront:

client.add(torrentId, { announce: ''wss://tracker.com' })

What is the use case for this?

**Comment by feross** [comment]
You might consider using the `getAnnounceOpts` property of the `client.add` function. It's documented here: https://github.com/feross/bittorrent-tracker#client

You could use it like this:

```js
var token = 1

client.add(torrentId, {
   // include a token parameter in announce requests to the server
  getAnnounceOpts: function () {
    return {
      token: token
    }
  }
})

// update the token every 10s
setInterval(function () {
  token += 1
}, 10000)
```
