### ISSUE TITLE
Error on including webtorrent.min.js

### ISSUE THREAD

**Issue by Lunik** [feross/webtorrent#771]
* WebTorrent version:
0.91.1
* Node.js version:

* Browser name/version (if using WebTorrent in the browser):
Chrome 49.0.2623.112 (64-bit)

When I include webtorrent.min.js to my html, I get this error in the console:
`Uncaught TypeError: Object prototype may only be an Object or null: undefined     webtorrent.min.js:5`

**Comment by patrick-othmer** [comment]
Same issue here. Looks like build 0.91.1 is bugged. Works without a problem with version 0.91.0.

**Comment by chrisnharvey** [comment]
Exact same issue for me.

**Comment by Tercus** [comment]
For others having issues: In the URL to include the webtorrent.min.js, you can just replace the "/latest/" with the version you want to include. The last version that worked for me was "/0.90.3/".

**Comment by waleeddogar** [comment]
Thank you @Tercus. I just spent hours on figuring out why I was having this issue. @feross please make it clear in the docs and stuff because this can be a huge pain point. I would resolve the issue as well if you have time. Other than that, you have created something awesome. Great job!

**Comment by emschwartz** [comment]
I'm also running into this problem, even using `0.90.3`. I'm using a fork of instant.io that browserifies the dependencies and it was working fine a few days ago, but I've since removed and reinstalled the dependencies. My guess is that it's actually not a problem with webtorrent `0.91.1` but an issue with a dependency of webtorrent that changed and broke between when `0.90.3` and `0.91.1` were bundled.

**Comment by feross** [comment]
I will look into this tomorrow. Sorry for the delay.

**Comment by emschwartz** [comment]
I'm trying to hunt down the issue now.

The function that's complaining is `inherits(IncomingMessage, stream.Readable)` from [`stream-http`](https://github.com/jhiesey/stream-http/blob/master/lib/response.js#L101)

**Comment by feross** [comment]
I've seen that error before, I believe this is the solution: https://github.com/jhiesey/stream-http/pull/41

**Comment by feross** [comment]
Fix published as 0.91.2
