### ISSUE TITLE
Example on website plays audio, but no video.

### ISSUE THREAD

**Issue by Nullifer** [feross/webtorrent#772]
* WebTorrent version: webtorrent.io
* Node.js version: webtorrent.io
* Browser name/version (if using WebTorrent in the browser):
I'm on arch linux using firefox. It works on chromium, but not firefox.

**Comment by Tercus** [comment]
For me, the video does not automatically start. I have to pause and resume once to get it starting. Does that also work for you?

**Comment by Nullifer** [comment]
@Tercus yes it works for the audio but the video doesn't play. When I press pause it shows a picture of the frame I stopped it at.

**Comment by Tercus** [comment]
Just for the off-chance that this is not related to webtorrent, but does this happen to other `<video>` elements too? Maybe you should check out some HTML5 test-sites.

**Comment by Nullifer** [comment]
@Tercus I updated recently and it works now, it must have just been a firefox bug.

**Comment by Tercus** [comment]
@Nullifer great to hear. What version of firefox were you using and to what version did you update to?

**Comment by Nullifer** [comment]
@Tercus I was either using the beta of 46 or the stable of 45 (probably the beta). Now it works in stable of 46.

**Comment by feross** [comment]
Cool -- glad this works for you guys now. I also just pushed some changes to improve autoplay reliability in Firefox. It often didn't work until the play button was clicked manually a few times. Should be better now :)
