### ISSUE TITLE
Error: Offset is out of bounds

### ISSUE THREAD

**Issue by green13** [feross/webtorrent#773]
* WebTorrent version: 0.90.3
* Node.js version: 5.10.0
* Electron: 0.37.6
* OS: windows 8.1

Hello.
I have all files, run WebTorrent (client.add) and get error:
```
fs.js:620 Uncaught Error: Offset is out of bounds
	fs.read @ fs.js:620
	onread  @ C:\Projects\launcher\src\main_app\node_modules\random-access-file\index.js:84
	wrapper @ fs.js:614
```

---

Note:
My server not working, torrent can't download. Screenshot from uTorrent:
![image](https://cloud.githubusercontent.com/assets/4918944/14778439/9c014f68-0adb-11e6-9267-3fa9e33b1f92.png)

**Comment by rom1504** [comment]
Providing the code reproducing that problem should help ;)

**Comment by green13** [comment]
It reproducing with webtorrent-cli:

```
D:\downloads>webtorrent http://example.com/my.torrent 

UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/feross/webtorrent/issues

DEBUG INFO: webtorrent-cli 1.1.3, webtorrent 0.91.1, node v5.11.0, win32 x64, exit 1
fs.js:620
  binding.read(fd, buffer, offset, length, position, req);
          ^

RangeError: Length extends beyond buffer
    at RangeError (native)
    at Object.fs.read (fs.js:620:11)
    at onread (C:\Users\bb_hakimov\AppData\Roaming\npm\node_modules\webtorrent-cli\node_modules\random-access-file\index.js:84:8)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:614:17)
```

For some files i get `RangeError: Length extends beyond buffer` on the same line.

**Comment by rom1504** [comment]
How did you created that torrent ? Do you have an example of such torrent ? (without copyrighted content)

**Comment by green13** [comment]
I think problem not in .torrent. May be problem in file: [LifeRace.zip](https://github.com/feross/webtorrent/files/236117/LifeRace.zip)

```
D:\main_app\resources\app.asar\node_modules\random-access-file\index.js:84 ..\downloads\LifeRace\LifeRace\Saved\Logs\LifeRace.log RangeError: Length extends beyond buffer(…)
onread @ D:\LifeRace Launcher\main_app\resources\app.asar\node_modules\random-access-file\index.js:84
wrapper @ fs.js:614
```

**Comment by rom1504** [comment]
If we can't reproduce your problem, it's harder to fix it ;)

**Comment by green13** [comment]
I understand it and fully agree, but do not know how reproduce error. I attached file from error, but it looks normal.

**Comment by rom1504** [comment]
LifeRace.log is the file contained in your torrent ?

Does that error happen in every torrent for you ? If not it looks like the problem is in that torrent.

**Comment by green13** [comment]
Yes, LifeRace.log contained in my torrent.

Not in every torrent. Yes, it's problem that torrent, but it's not the problem for uTorrent as an example. 

For generate torrent I use [create-torrent](https://github.com/feross/create-torrent).

**Comment by feross** [comment]
@green13 Can you share the code or command line arguments you used to create the torrent?

**Comment by green13** [comment]
```javascript
var fs = require('fs');
var createTorrent = require('create-torrent');
var config = require('./config');
var path = require("path");


function create(folder, name, cb) {
    var opts = {
        name: name,                         // name of the torrent (default = basename of `path`)
        comment: 'no',                      // free-form textual comments of the author
        createdBy: 'SuperApp',              // name and version of program used to create torrent
        private: false,                     // is this a private .torrent? (default = false)
        announceList: config.announceList   // custom trackers (array of arrays of strings) (see [bep12](http://www.bittorrent.org/beps/bep_0012.html))
    };

    createTorrent(folder, opts, function (err, torrent) {
        if (err) {
            throw err;
        }

        var file_name = name + '.torrent';
        fs.writeFileSync(path.join(config.torrentDir, file_name), torrent);

        if (typeof cb === 'function') {
            cb(file_name);
        }
    });
}

module.exports = create;
```

**Comment by feross** [comment]
Sorry -- it's just really hard to solve this issue without a minimal code example that can reliably reproduce it.

If you can produce a minimal test case that exhibits the issue, I'm happy to look at it in a new issue.
