### ISSUE TITLE
please add option to add subtitles.

### ISSUE THREAD

**Issue by eliyahuler** [feross/webtorrent#776]
#feature request
* WebTorrent version:
* Node.js version:
* Browser name/version (if using WebTorrent in the browser):

please add option to add subtitles.
also the option like VLSub (plugin of VLC) that allow to search automaticlly subtitles by the hash of the file or by its own name.
in addition, its will be nice to have option to decide where the movie will be saved.

thank you for all the nice work.

**Comment by nkittsteiner** [comment]
This is related to the [webtorrent-desktop](https://github.com/feross/webtorrent-desktop) or this repo?

**Comment by DiegoRBaquero** [comment]
Yes, duplicated too.
