### ISSUE TITLE
Fix confusion between webtorrent-desktop and webtorrent issues

### ISSUE THREAD

**Issue by rom1504** [feross/webtorrent#777]
Make sure everything direct people to https://github.com/feross/webtorrent-desktop/issues

**Comment by feross** [comment]
I'm not sure the best way to fix this. The WebTorrent Desktop webpage has the right link: https://webtorrent.io/desktop And the links in the app's help menu also go to the right place.

What else can we do?

**Comment by josephfrazier** [comment]
Maybe ISSUE_TEMPLATE.md could have a message at the beginning asking the user whether they mean to create the issue at webtorrent-desktop?

**Comment by nkittsteiner** [comment]
I think many people will look at this repo, searching for the desktop app. But renaming this project could be too extreme. What about rename the desktop app with some catchy name?

**Comment by rom1504** [comment]
Maybe the "Open an issue" link in https://webtorrent.io/desktop should point to https://github.com/feross/webtorrent-desktop/issues

**Comment by rom1504** [comment]
Also the title of the webtorrent-desktop window is "WebTorrent". I agree it looks a bit better than writing "WebTorrent-Desktop" though.

**Comment by feross** [comment]
Added link to issue template as @josephfrazier recommends, and updated url on website as @rom1504 recommends.
