### ISSUE TITLE
Uncaught Error: filesystem paths do not work in the browser

### ISSUE THREAD

**Issue by NgaNguyenDuy** [feross/webtorrent#779]
* WebTorrent version: 0.91.1
* Node.js version: v5.2.0
* Browser name/version (if using WebTorrent in the browser): Chromium 49.0.2623.108 Built on 8.3, running on Debian 8.3 (64-bit)

I got this message when try to seed a file served from localhost via nginx: `http://localhost/a.mp4`. My code:

index.html
```html
<!doctype html>
<html>

  <body>
    <input type="file" name="upload" onchange="handleFiles()" multiple>
  </body>
  <script src="webtorrent.min.js">
  </script>
  <script src="script.js"></script>
</html>
```

script.js
```javascript
var rtcConfig = {iceServers: []};
var client = new WebTorrent({ rtcConfig: rtcConfig });
client.seed("http://localhost/a.mp4", function (torrent) {

        console.log('Web Seeding support ..' + torrent.magnetURI);
    })
```

I have just search in issue and find #665 but i can't any information to solve this. Pls help me.

**Comment by feross** [comment]
HTTP url arguments are not supported to `client.seed`. You should try passing in one of the other supported types.

If you insist on using an http url, then you should download the file first, if it's not too large.

```js
var get = require('simple-get')

var client = new WebTorrent({ rtcConfig: rtcConfig })
get('http://localhost/a.mp4', function (err, res) {
  if (err) return console.error(err.message)
  client.seed(res, {
    name: 'My cool torrent',
    urlList: [ 'http://localhost/a.mp4' ] // add a web seed to the torrent
  }, function (torrent) {
    console.log('magnet link with web seed support: ' + torrent.magnetURI)
  })
})

```
