### ISSUE TITLE
ZeroNet + Webtorrent = Chromium "Not allowed" error

### ISSUE THREAD

**Issue by webarthur** [feross/webtorrent#783]
Blob links...

* localhost/apache: blob:http%3A//localhost/0a375747-bfdd-422e-bb8c-7838cdec7c49
* Webtorrent home: blob:https%3A//webtorrent.io/5368bdd6-53ca-4b03-a85b-fea682968cd6
* ZeroNet on Firefox (works fine!): mediasource:null/c007f211-d859-4edc-b5f4-4a742e96e946
* ZeroNet on Chromium (error) blob:null/84c9da13-bf32-4706-84ed-885b8c444b3d

Console output (on chromium):
> Not allowed to load local resource: blob:null/84c9da13-bf32-4706-84ed-885b8c444b3d

Why? =/

**Comment by feross** [comment]
Sorry -- I couldn't get ZeroNet to run on OS X. This is probably a ZeroNet issue. If you're able to figure it out, I'm happy to accept a PR.

**Comment by ndm13** [comment]
Just came across this while doing local development.  Apparently it's a [long-standing Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=379206) that people run into every few months.  I don't know a workaround, although one StackOverflow user worked around it by passing the data as an array (which obviously won't be feasible for WebTorrent.

**Comment by MuxZeroNet** [comment]
Big thanks to the person who helped me re-report this Chromium bug. The new issue ticket is available at https://bugs.chromium.org/p/chromium/issues/detail?id=686516

Please star to make this issue more urgent and more appealing to Chrome devs.
