### ISSUE TITLE
Doesn't work with tor

### ISSUE THREAD

**Issue by Nullifer** [feross/webtorrent#788]
* WebTorrent version: webtorrent.io
* Node.js version: ?
* Browser name/version (if using WebTorrent in the browser): tor-browser-en 5.5.5-1

Webtorrent doesn't work with tor. I think I read somewhere that tor disables webrtc due to an ip leak regardless of vpn settings.

**Comment by retrohacker** [comment]
Beyond webrtc, the bittorrent protocol has many other challenges that need to be addressed before tor is a viable way of anonymously downloading content through it.

https://blog.torproject.org/blog/bittorrent-over-tor-isnt-good-idea

Namely, bittorrent trackers are doing what they do best: tracking.

I'm assuming this applies to webtorrent.

**Comment by feross** [comment]
@Nullifer That's right. WebRTC is disabled in Tor Browser for privacy reasons right now. But there's [an issue](https://trac.torproject.org/projects/tor/ticket/16221) open considering how support could be re-added. I would chime in there and explain that you want to use WebTorrent over Tor Browser.

If there's enough support -- and examples of WebRTC use cases -- I think the developers will make it a priority.

Issue: https://trac.torproject.org/projects/tor/ticket/16221
