### ISSUE TITLE
file.createReadStream([opts]) yields "Uncaught Error: invalid selection"

### ISSUE THREAD

**Issue by triangle42** [feross/webtorrent#794]
* WebTorrent version: 0.91.4
* Browser name/version (if using WebTorrent in the browser): 50.0.2661.94 m

file.createReadStream([opts]) yields "Uncaught Error: invalid selection".
opts === {start: 0, end: 129241752} works
opts === {start: 1008813135, end: 129241752} yields "Uncaught Error: invalid selection".

Is there a lower limit on the difference between start and end?
If yes, please remove it.

**Comment by DiegoRBaquero** [comment]
See [torrent.js#L758](https://github.com/feross/webtorrent/blob/master/lib/torrent.js#L758)

In your opts start > end, that's why.

**Comment by triangle42** [comment]
That's right. Thank you.

I did not expect that from my program.
