### ISSUE TITLE
Streaming playback?

### ISSUE THREAD

**Issue by ollym** [feross/webtorrent#80]
How will this work exactly? And what are your plans for implementing it?

**Comment by feross** [comment]
Streaming playback is already supported. From the README:

#### `stream = file.createReadStream([opts])`

Create a [readable stream](http://nodejs.org/api/stream.html#stream_class_stream_readable)
to the file. Pieces needed by the stream will be prioritized highly and fetched from the
swarm first.

You can pass `opts` to stream only a slice of a file.

``` js
{
  start: startByte,
  end: endByte
}
```

Both `start` and `end` are inclusive.

**Comment by feross** [comment]
Streaming playback is implemented for VLC, Chromecast, Airplay, the html5 `<video>` tag, etc. by detecting seek events and responding with the correct file data. If those pieces of the torrent haven't been fetched from the network yet, then these pieces are highly prioritized.
