### ISSUE TITLE
How to download only one of the torrents?

### ISSUE THREAD

**Issue by amilajack** [feross/webtorrent#801]
I'm having trouble understanding the documentation. How can I download only one of the torrents?

This is what I have so far:

```javascript
// ....
client.add(magnetURI, function(torrent) {
     for (const file of torrent.files) {
       if (file.path.includes('mp4', 'srt')) {
         // How can I select only one of these?
         file.appendTo('body');
         break;
      }
    }
});
```

* WebTorrent version:
* Node.js version: 5.11.1
* Browser name/version (if using WebTorrent in the browser): Electron

**Comment by feross** [comment]
I assume you're asking about how to download one of the **files** in a torrent.

```js
client.add(magnetURI, function(torrent) {
  for (const file of torrent.files) {
    if (file.path === some_condition) {
      file.appendTo('body')
    }
})
```

**Comment by amilajack** [comment]
Oh I see. So if I want to download only certain files, I have to call  `appendTo` on them?

**Comment by DiegoRBaquero** [comment]
You should deselect the rest of files.

**Comment by feross** [comment]
Right. What @DiegoRBaquero said:

```js
file.deselect()
```

**Comment by amilajack** [comment]
@feross @DiegoRBaquero Thanks a ton! Is there a way to list all the selected torrents (for debugging purposes)?

**Comment by DiegoRBaquero** [comment]
@amilajack You mean files? You could just create an attribute for the file.

**Comment by amilajack** [comment]
Yea sorry for the confusion. I edited my comment. I mean to ask how I could list all the files that are being downloaded from a given torrent? Ideally, I'd like to start a torrent, deselect certain files, and then list all the ones that are still selected.

**Comment by feross** [comment]
The way that selected files are tracked internally (based on byte ranges) would make this information kind of hard to expose, at the moment. I recommend tracking this information manually in your application.
