### ISSUE TITLE
Avoiding that the complete file gets downloaded after call of file.createReadstream([opts])

### ISSUE THREAD

**Issue by triangle42** [feross/webtorrent#803]
* WebTorrent version: 0.91.4

How can I avoid that the WebTorrent client downloads the entire file as fast as possible after I have called file.createReadstream([opts])? I want to configure the maximum amount of data that createReadstream buffers before I read the next chunk of data.

**Comment by feross** [comment]
Right now, there's no way to do this. Eventually, we're going to make the client switch to a rarest-first strategy (#375) once there's sufficient data buffered to satisfy all `file.createReadStream()` calls. But the plan is always going to be to download as fast as possible to make the best use of available network capacity (modulo throttling, once that gets implemented #163).

But in the meantime, you can accomplish what you want by calling createReadStream with `opts`.

You can pass opts to stream only a slice of a file.

```
{
  start: startByte,
  end: endByte
}
```

Both `start` and `end` are inclusive.
