### ISSUE TITLE
Webtorrent in Meteor fails when loaded via NPM. Not via CDN 

### ISSUE THREAD

**Issue by FinnFrotscher** [feross/webtorrent#804]
When I import the `webtorrent` package via `import  WebTorrent  from 'webtorrent'` and try to set up the package with `var client = new WebTorrent()` I get 
 
    tcp-pool.js:22 Uncaught TypeError: net.createServer is not a function
But when I use `$.ajax()` to load the `CDN` hosted version it works. 

This is both `clientside` running `Meteor 1.3`. 

* WebTorrent version: newest NPM version
* Node.js version: Meteor 1.3 is 0.10.43
* Browser name/version (if using WebTorrent in the browser): Chrome, newest

**Add**
When I use `meteor npm` and `import`, and then `console.log(webtorrent)` I get the function back and i also have the required files. `index.js` starts with: 
    
    module.exports = WebTorrent
    //stuff
    function WebTorrent (opts) {
    var self = this
    if (!(self instanceof WebTorrent)) return new WebTorrent(opts)
    EventEmitter.call(self)`
    //asf...

but i cant use it.

**Comment by feross** [comment]
I did some digging and it looks like Meteor doesn't support the "browser" field in `package.json` fully, so it's not properly replacing the needed files with browser versions during the packaging process.

I left a comment on the relevant Meteor issue for you. https://github.com/meteor/meteor/issues/6890 You can follow that issue, or share more information there to help the Meteor devs prioritize the issue.

**Comment by nska02** [comment]
@FinnFrotscher seems like the issue hasn't been fixed yet on Meteor side. Have you found a temporary solution? Did you keep it via CDN? Thanks
