### ISSUE TITLE
[webtorrent-cli] Uncaught exception in nodebmc from JSON.parse()

### ISSUE THREAD

**Issue by thanosme** [feross/webtorrent#805]
Hello I' ve tried downloading a torrent file using the xbmc module and I got this error. I don' t understand the error my self nor did I find another issue like this. If this is a duplicate a will close it.
USER, HOSTNAME and IP are obviously masked.

{ addresses: [ 'IP' ],
  query: [ '_xbmc-jsonrpc-h._tcp.local' ],
  type: 
   [ { name: 'xbmc-jsonrpc-h',
       protocol: 'tcp',
       subtypes: [],
       description: undefined } ],
  txt: [ '' ],
  port: 8080,
  fullname: 'HOSTNAME._xbmc-jsonrpc-h._tcp.local',
  host: 'HOSTNAME.local',
  interfaceIndex: 0,
  networkInterface: 'enp2s0' }

UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/feross/webtorrent/issues

DEBUG INFO: webtorrent-cli 1.2.0, webtorrent 0.93.3, node v5.7.0, linux x64, exit 1
undefined:1

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/home/USER/.nvm/v5.7.0/lib/node_modules/webtorrent-cli/node_modules/nodebmc/device.js:35:31)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (node.js:377:13)
    at process._tickCallback (node.js:401:11)

* WebTorrent version: 1.2.0 (webtorrent 0.93.3)
* Node.js version: v5.7.0
* Browser name/version (if using WebTorrent in the browser):

**Comment by feross** [comment]
Thanks for the report! This is actually a bug in `nodebmc` which `webtorrent-cli` depends on.

They have a call to `JSON.parse()` which they need to wrap in a try-catch block to prevent uncaught exceptions like this one. I sent them a PR: https://github.com/gtuk/nodebmc/pull/1

**Comment by feross** [comment]
PR was merged, now waiting for it get published to npm.

**Comment by feross** [comment]
The fixed version is on npm now. This should be frixed.
