### ISSUE TITLE
Can't seed torrent

### ISSUE THREAD

**Issue by pietrovismara** [feross/webtorrent#813]
* WebTorrent version: 0.93.3
* Node.js version: 5.10.1

I'm having a problem with a webtorrent based client, and a [bittorrent-tracker](https://github.com/feross/bittorrent-tracker#client) tracker.

I have this options for seed:
```
const seedOptions = {
    announceList: [
        [
            `udp://${config.tracker.address}:${config.tracker.port}/announce`, 
             `http://${config.tracker.address}:${config.tracker.port}/announce`,
            `wss://${config.tracker.address}:${config.tracker.port}/announce`
        ]
    ]
};
```

And i seed like this:
```
client.seed(path, seedOptions, (torrent) => {
            // Creating a torrent file
            fs.writeFile(`${torrent.name}.torrent`, torrent.torrentFile, function () {
                console.log("written");
            });
});
```

My tracker answer says: 
```
got start message from ip:port
got complete message from ip:port
```

If i try to load the generated torrent into Transmission or any torrent client, i see no active seeders and download doesn't start.

Am i missing something?

**Comment by feross** [comment]
udp:// and wss:// trackers do not have a `/announce` at the end of the URL. Can you try again after removing that?

Also, can you post the results of these commands:

```
npm install parse-torrent -g
parse-torrent /path/to/your/file.torrent
```

**Comment by pietrovismara** [comment]
I made various test, i think the problem is because i didn't forwarded the ports. 
After forwarding the correct port, seeding is working.
I saw an issue on this project for nat upnp support, do you plan to implement it any soon?

**Comment by joradom** [comment]
a couple of mounths, really I'm learning more about bourbon, neat and suzy, and your theme helped me to get up an easy workflow...

**Comment by feross** [comment]
It's on the list, but there's lots to do.

**Comment by pietrovismara** [comment]
Well, i spent various hours yesterday trying to find a working solution for nodejs, but all existing modules are old and not mantained, and no one could work with my router.
Anyway i'm working on a project which uses Webtorrent as the core feature, so if i will work out some solution on my own, i'll let you know, who knows if i can make a good pull request and help this awesome project.
Closing, thank you for your time.

**Comment by feross** [comment]
@pietrovismara Awesome, sounds good
