### ISSUE TITLE
Don't download a 129MB file automatically

### ISSUE THREAD

**Issue by franciscop** [feross/webtorrent#815]
Please don't auto-download a 129MB file automatically from the website. I'm on mobile and don't want to have my data spent just by visiting the website.

**Comment by rickbeacham** [comment]
Agreed

**Comment by franciscop** [comment]
I propose two alternatives:

- Download a 2-3MB file. However this is not so cool as you cannot see the video itself, but much better than using the user's data plan.
- Detect the device/screen and choose to download only on desktop. However this is probably error-phrone.

**Comment by franciscop** [comment]
Another option:

- Add a "stop" button (or a "start" one) so the visitors can toggle the torrent download at will.

**Comment by feross** [comment]
Thanks -- I feel your pain but this is an issue for `webtorrent-www`.
