### ISSUE TITLE
Get InfoHash before downloading torrent

### ISSUE THREAD

**Issue by HughIsaacs2** [feross/webtorrent#816]
Unless I'm mistaken there doesn't appear to be any way to get the InfoHash of a .Torrent file or Magnet link before downloading the torrent.

I think this would be useful for building WebTorrent applications that sport offline storage.

**Example:** I'm building something that downloads the files and stores them offline in an array using LocalForage and sets the InfoHash as the key of that storage so when a user opens a link to that same torrent it'll just search to see if it's stored offline already and use the offline stored copies instead.

**Comment by feross** [comment]
You can listen to the `'infoHash'` event:

```js
var torrent = client.add(torrentId)
torrent.on('infoHash', function (infoHash) {
  // ...
})
```

Another way to customize the storage location based on the infoHash is to use the `store` option to `client.add`, but you need to follow the [abstract-chunk-store](https://www.npmjs.com/package/abstract-chunk-store) interface:

```js
function Store (chunkLength, opts) {
  console.log(opts.torrent.infoHash)
}
client.add(torrentId, {
  store: Store
})
```

Or, probably the simplest way is to use `parse-torrent` to get the info hash before passing it to WebTorrent in the first place:

```js
var parseTorrent = require('parse-torrent')

var parsed = parseTorrent(torrentId)
console.log(parsed.infoHash)

client.add(torrentId, ...)
```
