### ISSUE TITLE
Seeding a file from HTTP stream?

### ISSUE THREAD

**Issue by quangtrang1111** [feross/webtorrent#817]
I have a video stored in backblaze.com (a cloud store service), and I can get the public link of video through https protocol. So, can I seed directly this video in NodeJS - I mean: the video won't download and store in computer run NodeJS?

Thank you,

**Comment by rom1504** [comment]
Yes you can, is this related to webtorrent ?

**Comment by feross** [comment]
This is unrelated to WebTorrent.
