### ISSUE TITLE
Desktop won't install on ubuntu 16.04

### ISSUE THREAD

**Issue by physiii** [feross/webtorrent#818]
I am not able to install the desktop package - I'm using ubuntu 16.04.

sudo dpkg -i webtorrent-desktop_0.6.1-1_amd64.deb && sudo apt-get install -f
Selecting previously unselected package webtorrent-desktop.
(Reading database ... 190150 files and directories currently installed.)
Preparing to unpack webtorrent-desktop_0.6.1-1_amd64.deb ...
Unpacking webtorrent-desktop (0.6.1-1) ...
Setting up webtorrent-desktop (0.6.1-1) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 112 not upgraded.

**Comment by rom1504** [comment]
What is the error ?

**Comment by physiii** [comment]
It goes through unpacking, setting up, but then say 0 newly installed and I can not find it on my system.

I ended up trying "npm install webtorrent-desktop" which worked - probably should be in the readme

**Comment by feross** [comment]
Cool, glad you got it figured out. We actually don't want to encourage using the version on npm too much since it currently doesn't run the auto-updater. We'll consider publicizing that in the future.
