### ISSUE TITLE
Doesn't start streaming in vlc

### ISSUE THREAD

**Issue by rom1504** [feross/webtorrent#82]
Hello,
As said in https://github.com/feross/webtorrent/issues/81 , npm install webtorrent -g make it possible to  use a webtorrent command.
The interface seems very similar to peerflix one.
So i tried streaming a magnet with the --vlc option, but it only started once the file was *entirely* downloaded, which is not really streaming...
Is this ready to be used yet ? Is that a bug ?

A less important thing, it seems to be behaving like peerflix was before : vlc on top, but it isn't very pratical as said in https://github.com/mafintosh/peerflix/pull/92 , so it would be nice to do the same thing here.

**Comment by feross** [comment]
This issue is fixed now.
