### ISSUE TITLE
Torrent file is too big

### ISSUE THREAD

**Issue by q903068245** [feross/webtorrent#823]
Hi ：
    Tips appears when I try to play a https://webtorrent.io/ Torrent:
Reads as follows

Downloading torrent from 【BT天堂】【BTtiantang.com】[1080p]丘吉尔的秘密.4.31GB.torrent

"丘吉尔的秘密.Churchills.Secret.2016.BD1080P.X264.AAC.English.CHS-ENG.torrent" contains 9 files:

  - 丘吉尔的秘密.Churchills.Secret.2016.BD1080P.X264.AAC.English.CHS-ENG.Mp4Ba.mp4 (4.63 GB)

  - _____padding_file_0_如果您看到此文件，请升级到BitComet(比特彗星)0.85或以上版本____ (300.23 kB)

  - 字幕翻译人员名单.txt (121 B)

  - _____padding_file_1_如果您看到此文件，请升级到BitComet(比特彗星)0.85或以上版本____ (1.05 MB)

  - 更多高清请访问www.mp4ba.com.txt (27 B)

  - _____padding_file_2_如果您看到此文件，请升级到BitComet(比特彗星)0.85或以上版本____ (1.05 MB)

  - 本站唯一域名www.mp4ba.com.txt (50 B)

  - _____padding_file_3_如果您看到此文件，请升级到BitComet(比特彗星)0.85或以上版本____ (1.05 MB)

  - 点击进入高清MP4ba.url (122 B)

Torrent info hash: 278453399cdc55480abcf7bc2f30d6722266d39e [Share link] [Magnet URI] [Download .torrent]

Torrent downlod url
blob:https://instant.io/ab3e50f1-eca9-4155-8f69-7f55b9e09367

**Comment by q903068245** [comment]
i  email  weiqiuwen#live.cn  Thank You

**Comment by feross** [comment]
Do not use WebTorrent for copyright infringement. We cannot assist you.
