### ISSUE TITLE
Can not download torrent file

### ISSUE THREAD

**Issue by v0dy** [feross/webtorrent#825]
I'am trying to download a .torrent from butter.vodo.net API by passing the torrent URL to client.add but i'am getting CORS error, also it seems that neither instant.io nor βTorrent can handle this. Is there any workaround to get it working?

**Comment by DiegoRBaquero** [comment]
The webserver needs to be CORS-Enabled. There's no way to access resources from that domain through XHR from another without it. You could ask the domain owner to add CORS. Or if you want to have it on your own site have this small read: https://medium.com/@diegorbaquero/how-to-create-a-swarm-cdn-for-free-with-webtorrent-bfa09d193f71
