### ISSUE TITLE
Add something about live streaming in the faq

### ISSUE THREAD

**Issue by rom1504** [feross/webtorrent#826]
People [often ask](https://github.com/feross/webtorrent/issues?utf8=%E2%9C%93&q=is%3Aissue+live+streaming+is%3Aclosed+) whether it's possible to do live streaming with webtorrent.
I think it would be useful to add some info about that in the  [faq](https://github.com/feross/webtorrent/blob/master/docs/faq.md).

**Comment by DiegoRBaquero** [comment]
"Although, in theory, it's possible to have P2P live streaming, there isn't yet a complete implementation. Why not start one yourself and share it?"

**Comment by feross** [comment]
@rom1504 Agreed. Can you send a PR?

**Comment by nkittsteiner** [comment]
I'm thinking if it is possible to use only bittorrent-dht for peer discovery and then use a normal WebRTC communication for P2P live streaming. Any of you folks have any idea if this can be achieved?

**Comment by ewwink** [comment]
p2p live streaming is not only "possible", its already exist, it starts 2 years ago from **bem.tv** (https://github.com/streamroot/bemtv) and moved to streamroot, since it become commercial service there are no github development. Two other commercial service is peer5 and viblast.

if anyone looking for start, https://github.com/streamroot/clappr-p2phls-plugin

**Comment by feross** [comment]
I added something to the FAQ about this now.

**Comment by feross** [comment]
https://github.com/feross/webtorrent/commit/2be09cc2fabef37ddba365fb0b014d719fbb8fff

**Comment by BenjaminLawson** [comment]
http://nilejs.com/ Has implemented live streaming using WebTorrent!

**Comment by nkittsteiner** [comment]
Wooow. Looks promising!

**Comment by DiegoRBaquero** [comment]
@BenjaminLawson Wow, they are doing it. I wonder how they stick the video pieces into one stream?
