### ISSUE TITLE
Unable to seed a file via client

### ISSUE THREAD

**Issue by xeoneux** [feross/webtorrent#828]
* WebTorrent version: 0.94.3
* Node.js version: 6.2.1
* Browser name/version (if using WebTorrent in the browser): Electron 1.2.1

Trying the usage example,
```js
// When user drops files on the browser, create a new torrent and start seeding it!
dragDrop('body', function (files) {
  client.seed(files, function (torrent) {
    console.log('Client is seeding:', torrent.infoHash)
  })
})
```
`.../node_modules/webtorrent/lib/torrent.js:851 Uncaught Error: invalid selection` gets thrown

**Comment by xeoneux** [comment]
I rechecked and It happens with all the tiny text files but succeeds for larger files. @feross Any solution?

**Comment by feross** [comment]
Can you share an example of one such text file?

**Comment by xeoneux** [comment]
I tried it again with different files of similar sizes and it worked. Didn't encounter it again! 😄
