### ISSUE TITLE
Using torrentFile (Node.js Buffer) as first parameter for client.add(...)

### ISSUE THREAD

**Issue by triangle42** [feross/webtorrent#835]
* WebTorrent version: v0.94.4
* Node.js version: v4.4.5
* Browser name/version (if using WebTorrent in the browser): Google Chrome 51.0.2704.84 m

I use browserify.
Client.add(torrent_file_from_torrent.torrentFile, options, callbackFunction) throws an 'Invalid torrent identifier' error.

**Comment by DiegoRBaquero** [comment]
Could you please show your full code?

**Comment by feross** [comment]
Closing due to lack of information to reproduce this.
