### ISSUE TITLE
can't download popcorn time torrents

### ISSUE THREAD

**Issue by alioygur** [feross/webtorrent#838]
I am using popcorn time API's for finding movie torrents. (https://api-fetch.website/tv)

but the webtorrent does not downloading those torrents file.

**an example torrent url**

https://api-fetch.website/tv/movie/tt0111161

**an example torrent**

magnet:?xt=urn:btih:AC418DB33FA5CEA4FAB11BC58008FE08F291C9BE&tr=udp://glotorrents.pw:6969/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://torrent.gresille.org:80/announce&tr=udp://tracker.openbittorrent.com:80&tr=udp://tracker.coppersurfer.tk:6969&tr=udp://tracker.leechers-paradise.org:6969&tr=udp://p4p.arenabg.ch:1337&tr=udp://tracker.internetwarriors.net:1337

what is the problem ?

* WebTorrent version: 0.94.4
* Node.js version:
* Browser name/version (if using WebTorrent in the browser): Chromium Version 50.0.2661.102 Ubuntu 16.04 (64-bit)

**Comment by feross** [comment]
Do not use WebTorrent for copyright infringement. We cannot assist you.
