### ISSUE TITLE
Suggestion: add a "privacy" option

### ISSUE THREAD

**Issue by Ayms** [feross/webtorrent#839]
Add a privacy option to implement [torrent-live](https://github.com/Ayms/torrent-live) features

Note: libtorrent has a privacy option that implements one of those features ("do not say to the world what your are looking for")

**Comment by feross** [comment]
I think the `torrent-live` features are interesting, but I don't think they're the most effective to maintain Internet privacy while torrenting. A VPN is a better solution as it works in all situations and doesn't involve guesswork and heuristics.

Also, these types of features would add considerable complexity to the WebTorrent codebase.

**Comment by Ayms** [comment]
>I think the torrent-live features are interesting, but I don't think they're the most effective to maintain Internet privacy while torrenting.

They are: [study](https://gist.github.com/Ayms/79bdfc6ba747fb49503d) but to be optimal for those that are bridging with the bittorrent network they must be combined with the [dynamic blocklist](https://github.com/Ayms/torrent-live#how-is-the-dynamic-blocklist-createdmaintained), and later same kind of dynamic blocklist might apply to webtorrent users but alone torrent-lives privacy features already protect the users quite a lot (or please tell me what does this better... cf below)

> A VPN is a better solution

Certainly not: [Deanonymizing the VPN peers](https://github.com/Ayms/torrent-live#deanonymizing-the-vpn-peers) and what VPNs do you foresee for Webtorrent?

>as it works in all situations and doesn't involve guesswork and heuristics.

No, Torrent-live's features are determinist, not VPNs who indeed involve quite a lot of guesswork

> Also, these types of features would add considerable complexity to the WebTorrent codebase.

A little complexity but no so considerable

Do as you like but I think it's a mistake to elude the problem which will inevitably concern webtorrent users, at least you should let the subject open, as stated above even libtorrent has (surprinsingly) a kind of privacy feature, quite weak compared to what is proposed here
