### ISSUE TITLE
--vlc: command not found

### ISSUE THREAD

**Issue by roccomuso** [feross/webtorrent#842]
* WebTorrent version: 0.95.1
* Node.js version: 6.2.1
* OS: Ubuntu 16.04

I'm trying to launch this command on my webtorrent CLI:

    webtorrent download <magnet_uri> --vlc

to have the stream directly prompted to vlc. But on console I got <code>--vlc: command not found</code>.

Am I doing something wrong? Should I surround the magnet_uri with "quotes"?

**Comment by rom1504** [comment]
The --vlc option only works when streaming, so you shouldn't be using `download`
Just do `webtorrent <magnet_uri> --vlc`

**Comment by roccomuso** [comment]
Alright thanks, my mistake. Shouldn't be worth capture this kind of silly mistakes?

**Comment by feross** [comment]
@roccomuso You need to surround the magnet uri with quotes.

@rom1504 Actually, `webtorrent download <magnet_uri> --vlc` and `webtorrent <magnet_uri> --vlc` are the same.
