### ISSUE TITLE
How to change default video/audio player

### ISSUE THREAD

**Issue by phuchptty** [feross/webtorrent#843]
* WebTorrent version:
* Node.js version:
* Browser name/version (if using WebTorrent in the browser):

Like a title, i want change webtorrent default player. What do i do??
Thanks

**Comment by rom1504** [comment]
Webtorrent doesn't have any default player.
Are you using webtorrent-cli, webtorrent-desktop, instant.io,... ?

**Comment by phuchptty** [comment]
I setup on my client so it is possible

**Comment by phuchptty** [comment]
My client in hostinger.co.uk

**Comment by feross** [comment]
If you want to use a custom player like video.js or jwplayer, then you need to use the `renderTo()` method and pass it the video html element.

See: https://github.com/feross/webtorrent/blob/master/docs/api.md#filerendertoelem-function-callback-err-elem--browser-only

Read the documentation for the video player you're using to make sure that it supports MediaSource -- which is what WebTorrent is using under the hood.

**Comment by Nou4r** [comment]
A test with jwplayer would be awesome.
