### ISSUE TITLE
[question] webtorrent.io torrent-graph lib

### ISSUE THREAD

**Issue by roccomuso** [feross/webtorrent#844]
Are the torrent-graph somewhere available as a repo?

    var TorrentGraph = require('../lib/torrent-graph')

It's really cool, I'd like to reuse it.

**Comment by feross** [comment]
Not available anywhere yet -- but I wanted to publish it to npm. I'll make an issue on the website repo to do that, so I don't forget.

https://github.com/feross/webtorrent-www/issues/63
