### ISSUE TITLE
Add mp4 file bug

### ISSUE THREAD

**Issue by yanshekki** [feross/webtorrent#846]
* WebTorrent version: 0.95.2
* Node.js version:
* Browser name/version (if using WebTorrent in the browser): Chrome

I am using Linux Chrome Version 49.0.2623.87 (64-bit), when I add mp4 file will crush, other file type is no problem. Firefox is no problem.
<img src="https://www.extratown.com/public/2016/06/23/Untitled.jpg">

Use this link https://instant.io/ the problem same.

**Comment by feross** [comment]
@yanshekki How large is the MP4 file? I just tested with a 4.2 GB file on Chrome 52 (64-bit) and had no crash. Try updating Chrome.
