### ISSUE TITLE
Create torrent file from webseed

### ISSUE THREAD

**Issue by sandeep048** [feross/webtorrent#847]
This is more of a general torrent technology related question.
Is it possible to create a torrent file just from a web-seed, without downloading that file locally.

**Comment by DiegoRBaquero** [comment]
Hi @sandeep048. It's impossible. The .torrent contains the hashes of the pieces and the hash of the whole torrent. Wherever the torrent file is created, that machine must have the files. 

I was looking into enabling a way to seed and create .torrent file of web files that are in CORS-enabled served webservers with BTorrent, but I haven't been working on it. Although the process should be straightforward: download with XHR and create .torrent.
