### ISSUE TITLE
ERROR:sctpdataengine

### ISSUE THREAD

**Issue by moooradoooo** [feross/webtorrent#856]
give me a solution plz

![screenshot from 2016-07-08 09-16-22](https://cloud.githubusercontent.com/assets/17552614/16681454/ab9fc56c-44ec-11e6-8651-e1a76affb061.png)

**Comment by feross** [comment]
This report is for webtorrent-hybrid or webtorrent-desktop. Please post to the correct issue tracker in the future.

These are not real errors. They're just harmless warnings that the Chromium WebRTC engine outputs. The Chrome team plans to remove them in a future release.

Specifically, the [sctpdataengine sctpdatamediachannelfailed error](https://bugs.chromium.org/p/webrtc/issues/detail?id=3792) is a known issue with Chromium that doesn't seem to be a big deal.
