### ISSUE TITLE
Is it possible to append data when downloading video data

### ISSUE THREAD

**Issue by harryhaos** [feross/webtorrent#860]
* WebTorrent version: 0.95.2
* Node.js version: v6.2.2
* Browser name/version (if using WebTorrent in the browser): chrome 51/ Firefox 

Hi, I am making up a p2p video service. Normally, Ｉsplit big video data into serveal pieces. Webtorrent works well on single video, but I wonder if there is a way I can directly add data to the end  of downloaded video instead reload video player. I have tried mediasource API, but I don't know how to merge it into webtorrent. Can I deal with downloaded data directly(add or read to that stream)? Or can I choose where to download if the speed of peer is too low? 

Thanks a lot!

**Comment by voxadam** [comment]
You might want to take a look at #826.

**Comment by feross** [comment]
Torrents are immutable. You can build a mutable data store on top of torrents, but that's out of scope for webtorrent.
