### ISSUE TITLE
Wrong example at documentation page

### ISSUE THREAD

**Issue by ranierimazili** [feross/webtorrent#861]
Hi,

at documentation site https://github.com/feross/webtorrent/blob/master/docs/get-started.md we have a section called **Download and save a torrent (in Node.js)** where there's an example code.
This example works well but you're showing messages at console using console.error:

fs.writeFile(file.name, buffer, function (err) {
        console.error('Error saving ' + file.name)
})

But it's downloading successfully.

Probably the best example should be
fs.writeFile(file.name, buffer, function (err) {
    if (err) {    
        console.error('Error saving ' + file.name)
    } else {
        console.log('File saved ' + file.name);
    }
})

As I could see at writeFile documentation (https://nodejs.org/api/fs.html#fs_fs_writefile_file_data_options_callback) the 3rd parameters is for error, it's for a callback function.

This creates confusion with new developers using the library, because it's download successfully and at the console it show error messages.

**Comment by feross** [comment]
thanks, fixed!
