### ISSUE TITLE
Entire blocklist logic being executed when blocklist option is not set

### ISSUE THREAD

**Issue by romaincointepas** [feross/webtorrent#862]
*Came across this while going over the code. It's probably not a big deal but I thought I would report it.*

In https://github.com/feross/webtorrent/blob/master/index.js#L135, the code is still trying to load the IPSet even if `opts.blocklist` is undefined. `self.blocked` is then defined as an empty IPSet.

Because `if (self.client.blocked)` returns `true` in https://github.com/feross/webtorrent/blob/master/lib/torrent.js#L710-L732, the entire block of logic in `addPeer()` related to blocklist is always executed, even if originally `opts.blocklist` was not set.

---

* WebTorrent version: 0.95.2

**Comment by feross** [comment]
Fixed in 0.95.4. Thanks for the report!
