### ISSUE TITLE
Which torrent info should I keep to resume it after app close?

### ISSUE THREAD

**Issue by ranierimazili** [feross/webtorrent#864]
Hello,
I'm using webtorrent-hybrid.
After add a new torrent with client.add, it start to download the content...
If the app closes, how do I resume the downloads that were running when the app was closed?

**Comment by DiegoRBaquero** [comment]
You need to re-add the torrents, that should be enough.

**Comment by feross** [comment]
Yep, what @DiegoRBaquero said.

Although this might become a bit easier if https://github.com/feross/webtorrent/issues/872 gets implemented.
