### ISSUE TITLE
help can't seed

### ISSUE THREAD

**Issue by ninodejong** [feross/webtorrent#865]
[index.zip](https://github.com/feross/webtorrent/files/366816/index.zip)
* WebTorrent version: Newest
* Browser name/version (if using WebTorrent in the browser): Chrome/newest

I'am just learning javascript and i see a lot of potential in webtorrent. 

I cant seed. Can someone give me a example how to seed with webtorrent not using node.js but with the min.js file. 

thanks

**Comment by alxhotel** [comment]
Change the line 10 to:
```
var x = document.getElementById("myFile").files[0]
```
That should make it work.

**Comment by ninodejong** [comment]
thank you it worked!!! you made my day :+1:

**Comment by ninodejong** [comment]
can you maybe explain why this code worked en the previous didnt

**Comment by alxhotel** [comment]
I recommend you to look at http://www.w3schools.com/jsref/prop_fileupload_files.asp and https://github.com/feross/webtorrent/blob/6b7bd3cfb48019a02be50d72c814038f3e1a47c2/index.js#L278
