### ISSUE TITLE
Invalid torrent identifier

### ISSUE THREAD

**Issue by huangfei3095** [feross/webtorrent#866]
when I command line   webtorrent magnet_uri
the system retrive     Error: invalid torrent identifier
Debug Info: webtorrent-cli 1.2.3, web torrent 0.95.2, node v4.4.7, win32 x64, exit 1

* WebTorrent version:
* Node.js version:
* Browser name/version (if using WebTorrent in the browser):

**Comment by DiegoRBaquero** [comment]
What's the exact command you are using? Could you take a screenshot?

**Comment by feross** [comment]
Closing due to lack of details. @huangfei3095 Please comment or open a new issue if you have more details.
