### ISSUE TITLE
WebTorrent works in Firefox with disabled WebRTC

### ISSUE THREAD

**Issue by ComodoHacker** [feross/webtorrent#870]
Could you explain please, how can WebTorrent work in Firefox with media.peerconnection.enabled=false?

* Browser name/version (if using WebTorrent in the browser): Firefox 43.0.1

**Comment by feross** [comment]
Are you testing on https://webtorrent.io? The torrent on the homepage has a web seed (i.e. an http server that's used as fallback when/if there are no peers available).
