### ISSUE TITLE
Webtorrent magnet link - ws(web seed) in browser malfunctioning whereas xs works correctly

### ISSUE THREAD

**Issue by kaszub4u** [feross/webtorrent#875]
Malfunctioning:
magnet:?xt=urn:btih:3757c92282b95261836a7042b65269546ef01102&dn=c2wRzfD.jpg&tr=wss://tracker.btorrent.xyz&tr=wss://tracker.fastcast.nz&tr=wss://tracker.openwebtorrent.com&tr=wss://tracker.webtorrent.io&ws=http://i.imgur.com/c2wRzfD.jpg

where (http://i.imgur.com/c2wRzfD.jpg) example img CORS enabled.

Wheras(xs - works):
if torrent(create-torrent) constructed with --urlList http://i.imgur.com/c2wRzfD.jpg and magnet link xs=http://localhost/c2wRzfD.jpg.torrent.

**Comment by feross** [comment]
If there are no seeders or other peers online, then a magnet link will need an `xs` parameter in addition to a `ws` parameter so the peer has a way to get the .torrent file.

Try adding `&xs=http://localhost/c2wRzfD.jpg.torrent` to the end of your magnet link.
