### ISSUE TITLE
options for don't autoplay

### ISSUE THREAD

**Issue by zh99998** [feross/webtorrent#878]
now webtorrent enforce autoplay on render, could give a options for disable that?

**Comment by yciabaud** [comment]
Hello,

I am afraid there is no such option in appendTo function but you can still create the element on your own and use renderTo function.

Will this be ok for you?

**Comment by zh99998** [comment]
even though a create own element without autoplay, and use renderTo, it will autoplay.
maybe it's caused by this?
https://github.com/feross/render-media/blob/master/index.js#L234

**Comment by feross** [comment]
Use it like this:

```js
file.renderTo(elem, { autoplay: false }, callback)
```

Released as WebTorrent 0.96.0.
