### ISSUE TITLE
webseed without WebRTC

### ISSUE THREAD

**Issue by zh99998** [feross/webtorrent#882]
can webtorrent run without webrtc, in webseed-only (no-p2p) mode?
seems it only need stream api like url blob that can work.

if webtorrent support such environment, how can I check browser can run webtorrent or not?

if not.... then there is a feature request to support this

**Comment by feross** [comment]
If you just want to use web seeds, that's fine. WebTorrent should work for this use case. I don't think it makes sense to have WebTorrent expose a boolean to see if this is supported, as it's supported in most modern browsers.

You can detect support like this:

```js
typeof MediaSource !== 'undefined'
