### ISSUE TITLE
Some question of web seed

### ISSUE THREAD

**Issue by yanshekki** [feross/webtorrent#883]
* WebTorrent version: v0.96.0
* Node.js version:
* Browser name/version (if using WebTorrent in the browser): Chrome

Hi guys,

I study the torrent.addWebSeed(url) that is a callback function, so that will run after than found the peers.

Can I download by url first then find other peers to download?
Can it add more than one url to downloads?

Thank you!

**Comment by feross** [comment]
> Can I download by url first then find other peers to download?

No, WebTorrent is primarily a torrent client. Peers will start being discovered immediately.

> Can it add more than one url to downloads?

Yes, you can have multiple web seeds.
