### ISSUE TITLE
web seed format jpg and mp4

### ISSUE THREAD

**Issue by yanshekki** [feross/webtorrent#885]
* WebTorrent version: v0.96.0
* Node.js version:
* Browser name/version (if using WebTorrent in the browser): Chrome

Hi there,

I have some question of addWebSeed function. The problem is addWebSeed not work at jpg files.

sample:
mp4 is work: https://www.extratown.com/webtorrent/download/public/2016/08/13/sintel.mp4
jpg can not work: https://www.extratown.com/webtorrent/download/public/2016/08/13/IMG_20160229_164424-10.jpg

I checked the network mp4 is 206 HTTP_RANGE, but jpg is 200.

Thank you!

**Comment by feross** [comment]
I just checked out the links you posted and did some investigation. It appears that your server is returning an invalid response for the jpg file.

WebTorrent makes a request with the following header, to indicate the range it wants:

```
range:bytes=4456448-4559885
```

But the server responds with this header, indicating it is returning the wrong bytes:

```
content-range:bytes 0-4559885/4559886
```

But for the .mp4 file, it's working fine:

```
range:bytes=0-262143
content-range:bytes 0-262143/129241752
```

I have no idea why your server (which looks like cloudflare's nginx) would be doing that. But I don't think this is a WebTorrent bug, so I'm going to close this issue. Feel free to continue discussion and do share what you find out if you solve this!

**Comment by yanshekki** [comment]
I am sorry for this is my problem.

The proxy server have cache-control header for some extension, i need to close it.

Thank you for your help.

**Comment by feross** [comment]
Glad you got it figured out!
