### ISSUE TITLE
Error at the end of execution

### ISSUE THREAD

**Issue by sunilrx** [feross/webtorrent#887]
When i run the command  webtorrent-hybrid torrent file, i get an error at the end

UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/feross/webtorrent/issues

DEBUG INFO: webtorrent-cli 1.5.0, webtorrent 0.96.3, node v4.5.0, linux x64, exit 1
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:907:11)
    at WriteWrap.afterWrite (net.js:785:14)

**Comment by Rakesh-phpdeveloper** [comment]
i had the same issue, still the same issue

**Comment by feross** [comment]
@Rakesh-phpdeveloper The issue to follow is https://github.com/feross/webtorrent-hybrid/issues/43
