### ISSUE TITLE
UI Languages

### ISSUE THREAD

**Issue by Azpidatziak** [feross/webtorrent#891]
Hi webtorrent,

It's possible add IU languages in this app? I think it's cool feature if you can use it in your language.
Thanks!!

**Comment by obv-mikhail** [comment]
This is the library. You probably want to post this here https://github.com/feross/webtorrent-desktop .

**Comment by Azpidatziak** [comment]
Yes, OK and thanks!!

**Comment by feross** [comment]
@Azpidatziak Internationalization is something that's being worked on. You can follow along in the `webtorrent-desktop` repo.
