### ISSUE TITLE
Add Subtitles

### ISSUE THREAD

**Issue by Azpidatziak** [feross/webtorrent#892]
Hi webtorrent,

I think that it's will be a great feature, if you can add external subs to playing movie or etc.
Thanks!!

**Comment by DiegoRBaquero** [comment]
This is a webtorrent-desktop feature request.

About this...

@feross words (https://github.com/feross/webtorrent-desktop/pull/722#issuecomment-236326877): 

> we're not going to add this feature to WebTorrent Desktop, because the legality of OpenSubtitles is not clear to us.

> Once there's a plugin system, I suppose you could build this as a plugin. But it's not something that should be a part of WebTorrent Desktop core.

Closing this.
