### ISSUE TITLE
server.destroy() TypeError: callback is not a function

### ISSUE THREAD

**Issue by dcposch** [feross/webtorrent#899]
* WebTorrent version: 0.96.4
* Node/browser version: Electron 1.3.3

### When calling `server.destroy()`:

```
TypeError: callback is not a function
nextTick @ internal/process/next_tick.js:142
(anonymous function) @ init.js:22
Server.server.destroy @ server.js:40
stopServer @ webtorrent.js:311
ipc.on.e @ webtorrent.js:76
emitOne @ events.js:96
emit @ events.js:188
```

### Fix

I think `server.destroy()` should handle the case gracefully where it's called with no arguments.

### Workaround

If you don't want a callback, just call

```
server.destroy(function() {})
```

**Comment by feross** [comment]
0.96.5
