### ISSUE TITLE
Cannot read property 'removeListener' of null

### ISSUE THREAD

**Issue by dcposch** [feross/webtorrent#900]
* WebTorrent version: 0.96.4
* Node and browser versions: all

Here's a common error from the WebTorrent Desktop telemetry: https://github.com/feross/webtorrent-desktop/issues/890

In `lib/server.js`:
```
  server.close = function (cb) {
    closed = true
    torrent = null
    server.removeListener('connection', onConnection)
    server.removeListener('request', onRequest)
    while (pendingReady.length) {
      var onReady = pendingReady.pop()
      torrent.removeListener('ready', onReady)
    }
    _close.call(server, cb)
  }
```

The call to `torrent.removeListener` will always fail, right?

We should set `torrent = null` only at the very end.

@feross

**Comment by feross** [comment]
LOL, how did this even get into `master`? We're testing the server functionality. Maybe we only call destroy() and not close()?

Fix is in 0.96.5
