### ISSUE TITLE
Deprioritize range when connection was closed before the end

### ISSUE THREAD

**Issue by romaincointepas** [feross/webtorrent#905]
Example:
- A client (usually a player) would request the webtorrent http server for range 10000-40000
- The user would then seek before the above request was completed, aborting the request (only 10000-20000 was sent back when the request was aborted)

In that case, is the range 20001-40000 still having priority or, because webtorrent has detected that it's not needed anymore, was deprioritized (aka same priority as before that request)?

**Comment by feross** [comment]
This is a good idea, why did you close this @romaincointepas. Re-opening.

**Comment by romaincointepas** [comment]
@feross It was more of a question, and I (if I remember correctly) found out that the answer was "no" (when http request is canceled, everything that was prioritized because of this request is removed from the priority list).

Can you confirm?

**Comment by feross** [comment]
Actually, you're right. This is already implemented: https://github.com/feross/webtorrent/blob/beda5162c573adbecf5d6777b6821ec451b46639/lib/file.js#L83-L86
