### ISSUE TITLE
React Native support (feature request)

### ISSUE THREAD

**Issue by sigurdsvela** [feross/webtorrent#906]
Has there been any thought to react native support?
I'm fairly new to it, so I don't really know what's required to make it work, or how high effort it is,
but it would be great.

**Comment by DiegoRBaquero** [comment]
Each platform would have to support WebRTC. You can just throw in webtorrent if it does.

**Comment by yciabaud** [comment]
You can try using the [react native webrtc module](https://github.com/oney/react-native-webrtc) and let us know how it does!

**Comment by sigurdsvela** [comment]
Cool, I'll try that. Will report as soon as I'v had the time to check it out.

**Comment by sigurdsvela** [comment]
Ok, so I have at least figured one of the problems,
When trying to import `webtorrent` in react native i get an `Unable to resolve module 'WebTorrent'` error. I tried removing everything in `webtorrent/index.js` and only leave `module.exports = {}`. Which worked. Surprisingly.

So I added in removed and added lines until I was left only with:

```
/* global FileList */

module.exports = {}

var Buffer = require('safe-buffer').Buffer
```

which threw `Unable to resolve module 'safe-buffer'`

Looking in the `safe-buffer/index.js` file, I saw that it was trying to import 'buffer', which is not a dependency of safe-buffer(or anything else, i guess), and therefor actually was not resolvable. Simply installing 'buffer' fixed the issue. (not the original one, just the `Unable to resolve module 'safe-buffer'` one)

So it seems that when react is trying to `module A` that tries to import some `module B` that does not exists, it throws an error saying that it can not fine `module A`.
This seems to be a bug in react native's dev tools, so I'm filing an issue there.

My guess is that one or several of the dependencies of `webtorrent`(or one of it's dependencies and so on) has an unresolvable dependency.

**Comment by yciabaud** [comment]
Oh you webtorrent is a node project, you have to use browserify or the javascript-only package (webtorrent.min.js) to use it in a non-node environment.

**Comment by sigurdsvela** [comment]
Ah, sorry. Should have realised. Thanks!

**Comment by Uthpala** [comment]
Can someone give me a example on how to use webtorrent with react native.
