### ISSUE TITLE
Add some api for web readable streams

### ISSUE THREAD

**Issue by jimmywarting** [feross/webtorrent#907]
Given that it's all about using torrent in the web i think it would make since to support the standard web stream also. 

Not saying we should go and replace the hole node stream and go with web streams instead.
But for a way to get it as a instance of ReadableStream from the api so that it can be consumed by the new [FileSystem api](http://w3c.github.io/filesystem-api/), fetch upcoming streaming upload, to [streamsaver](https://github.com/jimmywarting/StreamSaver.js) and all new stuff that i don't know about yet

**Comment by feross** [comment]
It sounds like a great idea to figure out how to turn node.js streams into W3C streams. I'm surprised there isn't a module for this already. Want to go write it? 😉 

I don't think this belongs in the library itself, though. Node.js streams work well and they're by far the most widely used stream implementation. I'm happy to reconsider this if W3C streams get a ton of adoption.

**Comment by josephfrazier** [comment]
It looks like `node-web-streams` has some conversion functions: https://github.com/gwicke/node-web-streams

**Comment by jimmywarting** [comment]
hmm, interesting. Maybe wish he rather built a conversion api instead of depending on web-stream-polyfill
