### ISSUE TITLE
.mkv file unsuported

### ISSUE THREAD

**Issue by frikit** [feross/webtorrent#913]
* WebTorrent version: 0.15.0(0.96.5)
* Node.js version:
* Browser name/version (if using WebTorrent in the browser):

wont play .mkv file 

magnet:?xt=urn:btih:8134bdf216e6813f30cbb37e122f8f50f2d0b49b&dn=Alice.2O16.D.WEB-DL.1O8Op.mkv.torrent&tr=http%3A%2F%2Fannounce.torrentsmd.eu%3A6969%2Fannounce.php%3Fpasskey%3Dcee1cb126f44777e2ccfd4297d89b0be&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=http%3A%2F%2Fannounce.torrentsmd.me%3A8080%2Fannounce.php%3Fpasskey%3Dcee1cb126f44777e2ccfd4297d89b0be

this file 

//----------------------------------------

media info ;

General
Unique ID                                : 178415192442376885891755185022193784499 
(0x8639842371C3A0519340994C0BBA56B3)
Complete name                            : D:\Downloaduri\Alice.2O16.D.WEB-DL.1O8Op.mkv
Format                                  : Matroska
Format version                          : Version 2
File size                                : 3.89 GiB
Duration                                : 1h 52mn
Overall bit rate mode                    : Variable
Overall bit rate                        : 4 927 Kbps
Encoded date                            : UTC 2016-09-17 01:25:09
Writing application                      : mkvmerge v8.3.0 ('Over the Horizon') 64bit
Writing library                          : libebml v1.3.1 + libmatroska v1.4.2

Video
ID                                      : 1
Format                                  : AVC
Format/Info                              : Advanced Video Codec
Format profile                          : High@L4
Format settings, CABAC                  : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                : V_MPEG4/ISO/AVC
Duration                                : 1h 52mn
Bit rate mode                            : Variable
Bit rate                                : 4 541 Kbps
Maximum bit rate                        : 7 000 Kbps
Width                                    : 1 920 pixels
Height                                  : 1 038 pixels
Display aspect ratio                    : 1.85:1
Frame rate mode                          : Constant
Frame rate                              : 23.976 (24000/1001) fps
Standard                                : Component
Color space                              : YUV
Chroma subsampling                      : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                      : 0.095
Stream size                              : 3.58 GiB (92%)
Default                                  : Yes
Forced                                  : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                      : 2
Format                                  : AC-3
Format/Info                              : Audio Coding 3
Mode extension                          : CM (complete main)
Format settings, Endianness              : Big
Codec ID                                : A_AC3
Duration                                : 1h 52mn
Bit rate mode                            : Constant
Bit rate                                : 384 Kbps
Channel(s)                              : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Frame rate                              : 31.250 fps (1536 spf)
Compression mode                        : Lossy
Stream size                              : 310 MiB (8%)
Language                                : Russian
Default                                  : Yes
Forced                                  : No

**Comment by DiegoRBaquero** [comment]
We don't promote or help with piracy content.
