### ISSUE TITLE
There are many magnet links from one file. why?

### ISSUE THREAD

**Issue by bachlx-bitmark** [feross/webtorrent#924]
Hi.
I checking the downloading file between webtorrent and other client and I received many different magnet links.

File to check: 
https://drive.google.com/file/d/0B59_PYQdzzG6TXppLUZfZzV1a2M/view?usp=sharing

I used `utorrent` on window, `webtorrent` on linux (run via node on terminal)

```
Case 1. Download from utorrent to webtorrent
I create torrent file and get magnet link from file:
magnet:?xt=urn:btih:0750D504A7A76C5A8DD688E39C0BA547175DD5D7&dn=test.txt
I used this magnet link to download by `webtorrent`. It is OK, file is downloaded.
```
```
Case 2.  Download from webtorrent to utorrent
I create torrent file and get magnet link from file:
magnet:?xt=urn:btih:0154fafa408d0590df02ce4f132e193f38e7613a&dn=test.txt
I used this magnet link to download by utorrent. It is OK, file is downloaded.
```
The downloadings of two cases are OK, but I see that magnet links of two cases are different.
`webtorrent` : `magnet:?xt=urn:btih:0154fafa408d0590df02ce4f132e193f38e7613a&dn=test.txt`
`utorrent`     : `magnet:?xt=urn:btih:0750D504A7A76C5A8DD688E39C0BA547175DD5D7&dn=test.txt`

I used `webtorrent-desktop` and create magnet link from this file, but I received other magnet link: 
 `magnet:?xt=urn:btih:2414f135d51fced62d538f3d763bbc7f05df3808&dn=test.txt`

I using:
* WebTorrent version:  0.97.1
* Node.js version: 6.5

**Comment by feross** [comment]
There are a few things that go into calculating the info hash, including the torrent name. You're probably using a different name in each program.
