### ISSUE TITLE
Ignoring input without any warning

### ISSUE THREAD

**Issue by roune** [feross/webtorrent#925]
- WebTorrent version: Last
- Browser name/version (if using WebTorrent in the browser): Chrome 52.0.2743.98 32bits

I am working on using webtorrent within a cordova app but I am having really big troubles when seeding due to the input. I use a plugin named imagePicker, which returns a URI which I convert to a FileEntry and then finnally to a File object. My problem is when I pass this File objects to the client.seed, nothing starts seeding (not even the callback is executed) and I get no warning from the WebTorrent library or Chrome's permissions. If I check later the current torrents, I have nothing.
The client.add part works, at least the callback is called.

**Comment by feross** [comment]
I don't think you can actually create a `File` object, right? The best you can do is create a `Blob` that has the extra properties that `File` has: https://developer.mozilla.org/en-US/docs/Web/API/File

I haven't tried using webtorrent with cordova before. If you figure out the cause of the issue and its webtorrent's fault, please send a PR.
