### ISSUE TITLE
file list /play in order

### ISSUE THREAD

**Issue by FlynnFrank** [feross/webtorrent#929]
* WebTorrent version:
* Node.js version:
* Browser name/version (if using WebTorrent in the browser):

hello,
i have 1 torrent file wich contains 1 movie divided in many small parts .
is it possible to have it playback in order, flowing and that each peer comes in at the same file?
bg

**Comment by DiegoRBaquero** [comment]
This seems like a feature built in top of WebTorrent and not of the lib itself.

**Comment by andymikulski** [comment]
>is it possible to have it playback in order, flowing and that each peer comes in at the same file?

I've solved this outside of WebTorrent - I use ffmpeg to get the movie's duration, and then connecting peers hit an API that gives the `currentTime` of whatever's playing. If you have multiple files, you could include which piece should currently be playing, as well.
