### ISSUE TITLE
Minor documentation error: "except it uses WebRTC instead of TCP/uTP"

### ISSUE THREAD

**Issue by ZaneCEO** [feross/webtorrent#931]
Form [here](https://webtorrent.io/faq):

> The WebTorrent protocol works just like BitTorrent protocol, except it uses WebRTC instead of TCP/uTP as the transport protocol.

Uhmm, I'm not tuo familiar with WebRTC yet, ma AFAIK it's an *application* protocol, not a transfer protocol. It still needs a *transfer* protocol below, be it either TCP, UDP, uTP or something else.

**Comment by feross** [comment]
While you're probably technically correct, we're using WebRTC like a transport protocol. As far as the browser environment is concerned, that's what WebRTC is. The application protocol happens on top of WebRTC.
