### ISSUE TITLE
How to troubleshoot .torrent file not getting downloaded? 

### ISSUE THREAD

**Issue by kauegimenes** [feross/webtorrent#935]
Hello, i am trying to use the browser version of WebTorrent, All worked fine with the sample .torrent in the docs, but if i use for example a yify torrent ( https://yts.ag/torrent/download/423EED0C53F3857F66FCFB7522FB8C3829D1DCF4.torrent ) I am able to get the torrent data, but the player does not start downloading the file.

* WebTorrent version: Last
* Node.js version: Last
* Browser name/version (if using WebTorrent in the browser): Chrome last

**Comment by DiegoRBaquero** [comment]
The torrent surely isn't available in the WebRTC network. And please, do not use WebTorrent for copyright infringement.
