### ISSUE TITLE
Offset Out Of Bounds error 

### ISSUE THREAD

**Issue by antoniomuso** [feross/webtorrent#936]
Hi guys,
I'm receiving this error:
```
0|torrentD | RangeError: offset out of bounds
0|torrentD |     at RangeError (native)
0|torrentD |     at Object.fs.write (fs.js:760:20)
0|torrentD |     at onwrite (/home/pi/Desktop/NodeWithIntellij - Copia/node_modu
                 les/random-access-file/index.js:110:8)
0|torrentD |     at FSReqWrap.wrapper [as oncomplete] (fs.js:747:5)

```

* Code: https://github.com/antoniomuso/WebTorrentRep/blob/master/routes/torrent.js
* WebTorrent version: 0.97.2
* Node.js version: v6.7.0
* Browser name/version (if using WebTorrent in the browser):

**Comment by feross** [comment]
@antoniomuso Was your issue resolved?

**Comment by antoniomuso** [comment]
yes, it was a space problem in hd.
