### ISSUE TITLE
torrent.on('wire', function (wire) {}) not being called on LAN peers

### ISSUE THREAD

**Issue by John-p0pe** [feross/webtorrent#938]
torrent.on('wire', function (wire) {})

The wire event isn't being called when the Peer is on a LAN.  It works fine with external peers. 

It seems that after an external peer is connected first , the lan peer connects and calls the wire event.
If the Lan peer connects first it doesnt call the wire event.

**Comment by feross** [comment]
When you say LAN peer, do you mean another peer on the same computer? Or just on the same network?

**Comment by John-p0pe** [comment]
The same network

**Comment by feross** [comment]
Can you provide the minimal code it takes to reproduce this issue?

**Comment by John-p0pe** [comment]
`client.add(torrentId, function (torrent) {

 torrent.on('wire', function(wire, addr) {
                        console.log("WIRE event from:  " + wire.remoteAddress);
                        console.log("PeerId : " + wire.peerId.toString());                        
}
}`

**Comment by feross** [comment]
> I'm using the browser version of webtorrent if that matters.

Yes, that matters! WebRTC connectivity depends heavily on the network that you're on. The only thing I can recommend is for you to try specifying the `rtcConfig` option to the WebTorrent constructor.

More info:

- https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/setConfiguration
- https://www.html5rocks.com/en/tutorials/webrtc/basics/#toc-rtcpeerconnection
