### ISSUE TITLE
New app using WebTorrent

### ISSUE THREAD

**Issue by codealchemist** [feross/webtorrent#939]
@feross I created a demo app using WebTorrent and used WebTorrent's logo as opengraph image.
Is that ok? I'll remove it needed.

This is it:
https://watchtor.herokuapp.com

**Comment by feross** [comment]
Neat demo app! 👍 

IMO, it's better if you use a unique logo to prevent possible confusion with the WebTorrent Desktop app. Maybe when/if your site gets more popular, you could do that?

Want to send a PR to add this to the list of apps using WebTorrent in `docs/faq.md`?

**Comment by codealchemist** [comment]
Yeah, that's the idea!
Thanks a lot dude!

PR sent :)
#940
