### ISSUE TITLE
Can't play webtorrent video if have more than 1 seed

### ISSUE THREAD

**Issue by boygiandi** [feross/webtorrent#943]
Hello.

I'm trying to build a video site that base on webtorrent. I have a webserver to serve file in case have no seeder. You can test it here : http://animeforce.to/test/

The problem is :
- if only you (computer 1) go to that url, you can watch video, player get video from http server
- Then another computer joined, computer 1 stop playing video, it got stuck :(

So, if only 1 watcher, player work fine, if have 2 watchers, player stop.
Can you please take a look ?

**Comment by feross** [comment]
It looks like your site is hosting copyrighted content. Do not use WebTorrent for copyright infringement. We cannot assist you.
