### ISSUE TITLE
Travis builds stall at `zuul --electron ...`

### ISSUE THREAD

**Issue by josephfrazier** [feross/webtorrent#945]
After Travis runs `zuul --electron -- test/*.js test/browser/*.js`, nothing happens, so the build errors out with:

> No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.

Here are some examples:

* master: https://travis-ci.org/feross/webtorrent/builds/165420271#L1806
* https://github.com/feross/webtorrent/pull/909: https://travis-ci.org/feross/webtorrent/builds/166883157#L1811

I haven't yet been able to reproduce this locally :(

**Comment by feross** [comment]
Yep, I noticed this as well. Unclear what is causing it. Can't reproduce locally.
