### ISSUE TITLE
Seed and download file on the local machine sometimes successfully

### ISSUE THREAD

**Issue by tailiu** [feross/webtorrent#946]
Hi, I am using the Webtorrent API to seed and download files locally. When there are many files being seeded locally and each file is being seeded by one seed(that's why only 0 in torrentSeeds[0] below), some downloaders could block at 'torrent.on('done', callback). In other words, after those downloader calls addPeer(), torrent will not be done forever and there is not any error message. I am really confused why some wait forever, while some can download successfully. Here is the code:

Seeder:
```
var torrent = new WebTorrent({ dht: false, tracker: false })
  torrent.seed(filePath , function (value) {
    callback(filemeta)
  })
```

Downloader:
```
  var client = new WebTorrent({ dht: false, tracker: false })
  var torrent = client.add(torrentSeeds[0].infoHash)

  torrent.addPeer(torrentSeeds[0].ipAddr + ':' + torrentSeeds[0].torrentPort)

  torrent.on('done', function() {
      torrent.files.forEach(function(file){
        var ws = fs.createWriteStream(downloadedFilePath)
        var rs = file.createReadStream()
        rs.pipe(ws)
        rs.on('end', function(){
          callback()
        })
     })
  })

```
* WebTorrent version: 
* Node.js version: v6.5.0

Thanks.

**Comment by feross** [comment]
It looks like you are creating a separate webtorrent client instance for each torrent. That will probably overwhelm your network with DHT traffic. Try using a single webtorrent client across your whole webtorrent process.
