### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by rafaelleru** [feross/webtorrent#951]
I'm trying to load a .torrent file from my desktop in a app make with electron, but when I add the .torrent file to appp y Only have the option to save the file, and I don't know how to fix it. 

Also the dragDrop function give me an error on start that say:

Uncaught TypeError: Cannot read property 'addEventListener' of null

Can anyone hel me?¿

**Comment by feross** [comment]
It sounds like you're using Electron. If you don't set up drop handlers correctly, then the default browser behavior is to just save the file, which is what you're seeing.

I recommend reading the `drag-drop` [docs](https://github.com/feross/drag-drop#drag-drop---) more closely. It looks like you're not passing a real DOM node.

**Comment by rafaelleru** [comment]
Where I can found more help to set up drop handlers? I can't find much help in docs.

**Comment by feross** [comment]
Have you tried the code in the "Creating a new torrent and seed it (in the browser)" example on this page: https://webtorrent.io/intro

**Comment by rafaelleru** [comment]
yes but didn't work. Myn actual code look like:

`dragDrop(document.getElementById("draganddrop"), function(file){
    console.log(file);
    torrentID = file;
    addTorrent(torrentID);
})`

before I pass only 'draganddrop' as object, it's my div to drag files, but never show me other option more that save the file draged, and I want to add the torrent to the client via addTorrent function.

**Comment by feross** [comment]
I'm sorry, I don't understand what you're asking.
