### ISSUE TITLE
TCP/UDP Port Webtorrent Client

### ISSUE THREAD

**Issue by bissybowo** [feross/webtorrent#953]
Hi ! Does anyone know which tcp/udp port we need to open in ufw ? It is the same case when we filter port in window. I only find out that i can filter the client on window/ It's not the best way to make it work. Maybe you can help me figure it out. Thank you for your response.

**Comment by Edward-Stryfe** [comment]
I don't think that this is the place you should be asking this question. The client should operate perfectly well with your trackers and torrents unless you are on a private protected network, or have a firewall. Are you asking which ports you should use for your TCP/UDP trackers in the client?

**Comment by bissybowo** [comment]
Yes the client works perfectly when my firewall is disabled. It's why I hoped, there's a port I can open to make it work. Not the tcp/udp trackers cause they're too many. In fact, torrent client usually asks a open particular tcp port to work. I was hoping this one works like this too. That's all. Thanks you for your reply. I apologize for the delay reponse.

**Comment by feross** [comment]
If you're using webtorrent from the Node.js API you can tell it what port to listen to using the (apparently undocumented) `torrentPort` option to the `WebTorrent` constructor.

If you're using the CLI, this option is exposed as `--port`.

If you're using `webtorrent-hybrid`, note that WebRTC doesn't allow you to pick which ports are used. It has it's own process for trying to get through firewalls.

If you're using WebTorrent Desktop, the port option isn't exposed in Preferences yet.

**Comment by minexew** [comment]
I can confirm this is an issue in WebTorrent Desktop.
+1 to reopenining?

**Comment by feross** [comment]
This issue tracker is for the webtorrent engine. If you want to make a feature request for desktop, do that here: https://github.com/feross/webtorrent-desktop

**Comment by minexew** [comment]
Note to other clueless googlers: the relevant issue is https://github.com/feross/webtorrent-desktop/issues/986
