### ISSUE TITLE
Update Default Tracker List

### ISSUE THREAD

**Issue by Edward-Stryfe** [feross/webtorrent#957]
Ok so I know this is a WT client and all but the two UDP trackers openbittorrent and exodus.desync have been offline and useless for a while. And it's safe to say they probably aren't coming back. So they should be removed from the list of default trackers for sure. 

And if webtorrent.io runs the bittorrent-tracker node server then shouldn't we have a UDP and an HTTP for webtorrent that we can add to make it more mainline then what it is? It'd seem more straight if directly affiliated servers are the trackers that are used by default by the client. 

Coppersurfer.tk has been having some issues as well and loses connections frequently.

**Comment by feross** [comment]
Do you have a list of suggested trackers to include in `create-torrent`?

The webtorrent project doesn't run a tracker, and leaves that up to the community.

**Comment by CraigglesO** [comment]
I'll have mine up soon. If you are willing to put my tracker in the list that would be great! I would like to track statistics and see if it can handle traffic well.

**Comment by CraigglesO** [comment]
Also, with DHT, trackers are slowly losing relevance.

**Comment by feross** [comment]
Please send a PR to `create-torrent` with suggested tracker additions.
