### ISSUE TITLE
Webseeds cached content won't work

### ISSUE THREAD

**Issue by DiegoRBaquero** [feross/webtorrent#958]
- WebTorrent version: 0.97 latest
- Browser name/version (if using WebTorrent in the browser): Chrome

How to reproduce: With cache enabled, reload [this](https://btorrent.xyz/view#https:%2F%2Fpeerify.btorrent.xyz%2Ftorrents%2F6f4efbcf0d0ecbf914938b568ffd3bf9%2Fscaredy-cat.jpg.torrent) page after fully loaded about 5 times, after that, it will start failing. HTTP 206 OK won't work for WebTorrent. **No errors**

I quickly checked if WebTorrent does any equal conditional on 200 status but it does < 200 && >= 300, so I don't really know where the issue is coming from. 

Will investigate later.

![image](https://www.dropbox.com/s/gq97p6y8a12qcq8/Screenshot%202016-10-23%2004.34.32.jpg?dl=1)
![img2](https://www.dropbox.com/s/qujrsusg7x9o7fr/Screenshot%202016-10-23%2004.36.20.jpg?dl=1)

**Comment by DiegoRBaquero** [comment]
Could actually be the root cause of https://github.com/feross/webtorrent/issues/535

I'm going to close that issue as we have more info here.

**Comment by feross** [comment]
@DiegoRBaquero I was just trying to reproduce this, but the link in the issue description isn't working anymore. Also, can you try using a fresh copy of webtorrent, as there was a new version of `videostream` published recently that fixed some bugs?

**Comment by DiegoRBaquero** [comment]
Seems to be working now: https://btorrent.xyz/view#https:%2F%2Fpeerify.btorrent.xyz%2Ftorrents%2Fa6b0510e42c276368570589355a82530%2F5fb.Bogota-_Nocturna.jpg.torrent

Reloading many times won't affect.
