### ISSUE TITLE
Redownload on filesystem

### ISSUE THREAD

**Issue by hanspeter1** [feross/webtorrent#967]
* WebTorrent version: 0.97.2
* Node.js version: 6.5.0 (Electron)
* Browser name/version (if using WebTorrent in the browser): Electron 1.4.5

Every time a client-A add's a magnet-URI, he trying to download the file from other clients also if the file is already on client-A file system (Node.js/Electron).
Is there a way to fix that!

**Comment by hanspeter1** [comment]
OK, i habe to use the "path" option.

**Comment by feross** [comment]
Yep, that's right!
