### ISSUE TITLE
cannot read appendTo from object after passing file by ipc.send message with electron

### ISSUE THREAD

**Issue by rafaelleru** [feross/webtorrent#970]
I try to pass a file by ipc message to play in a DOM with electron, but in the ipc.on method file.appendTo give me an error:

mainWindowUpdater.js:45 Uncaught TypeError: file.appendTo is not a .

I try everithing in my mind but I can make it to work.

Any help?¿

**Comment by feross** [comment]
Looks like you already resolved this, but I'll just mention for future google searchers that you can't use Electron's IPC to send across object instances (with methods). The IPC methods serialize the object with the equivalent of `JSON.stringify()` before sending across.
