### ISSUE TITLE
recompose readStream and play it afer sending via ipc

### ISSUE THREAD

**Issue by rafaelleru** [feross/webtorrent#971]
If I send every data of file as readStream throught ipc message, how I can play this data into client side of electron (the renderer procces reading this data from the live stream). I'm sending data like this:
`readstream = file.createReadStream();
readstream.on('data', function(chunk){
    ipc.send('play', data);
}`

so in the renderer I have a constant flow of data that I don't know how to recompose. Whats the better form for do this?

**Comment by xuset** [comment]
You can use the [render-media](https://github.com/feross/render-media) package to convert the stream into an audio/video element. That's what webtorrent uses for the file.appendTo and file.renderTo methods.

Alternatively, it may just be easier to run webtorrent in the browser side of electron, not the nodejs side, but depending on your use case this may not be an option.

Hope this helps!

**Comment by rafaelleru** [comment]
I just show your response and it's sound good but can you hel me a bit more with the recompose of the stream. I can not find any information about load the incomming chunk into a new stream on the renderer side.

@xuset

**Comment by xuset** [comment]
@rafaelleru I'm not too familiar with streams, but it seems like you'll have to create a [Readable](https://nodejs.org/api/stream.html#stream_class_stream_readable) stream on the render side, and when you receive the ipc data, send the data to the stream with `stream.push(...)`

**Comment by rafaelleru** [comment]
I'm still having problems with this because in the file object creation I can't make the render method to works. I'm trying to set the createReadableStream property to my stream of data, that I receibe from ipc but it gives me an excepcion that says it's undefined. My code looks like:
`ipc.on('addData', (event, data) => {
    stream_data.push(data, 'utf8');
})

ipc.on('toPlay', (event, data) => {
    console.log('toPlay: ' + data[0]);
    var file = {
	name: data[0],
	createReadStream: function(){
	    return stream_data;
	}
    }
    
    render.append(file, 'body', function(err, elem){
	if(err)
	    return console.log('error appending file');

	return console.log(elem);
    });
})`

and vars are initialized in the begining of the jd file. @xuset any help with this¿

**Comment by feross** [comment]
@rafaelleru I think the best way for you to accomplish what you're trying to do is to use `torrent.createServer()` to start an http server in the main process. Then you can just use IPC to send the server URL to the renderer process. Then you can set it as the `src` attribute on the video tag. This solution ensures that seeking is supported, since the tag will make a new HTTP request with the proper range headers, and it's a lot simpler than what you're trying to do right now. This is the approach that we use in WebTorrent Desktop, for what it's worth.
