### ISSUE TITLE
torrent with multifile 

### ISSUE THREAD

**Issue by f1atlux** [feross/webtorrent#977]
webtorrent.js latest
firefox latest

hi there, i've a torrent file which has multiple files. myname.txt, blabla.jpg and stream.mp4 

webtorrent.js is not start streaming on that situation. is there any idea to modify it like "detect that file type" thing?

best.

**Comment by vankasteelj** [comment]
I personnaly do this:

```
           var supported = ['.mp4', '.m4v', '.avi', '.mov', '.mkv', '.wmv'];

            // hide non-video files from selection and set index
            for (var f in torrent.files) {
                torrent.files[f].index = f;
                torrent.files[f].display = supported.indexOf(path.extname(torrent.files[f].name).toLowerCase()) !== -1;
            }
```

I can then easily select files, because I only display those who have `display=true` and I can pick them because there is the "real" index (the one that interrests webtorrent anyway) there. You can then:

```
            var fileIndex = <the actual index you set above, you can also loop to find the biggest .length, it will be 99.99% of the time the video file>;
            for (var f in torrent.files) {
                var file = torrent.files[f];
                if (f === parseInt(fileIndex)) {
                    file.select();
                } else {
                    file.deselect();
                }
            }
```

**Comment by feross** [comment]
@f1atlux You should do something like what @vankasteelj suggests. All the information is the `torrent.files` array for you to determine which files you want to stream.

**Comment by vankasteelj** [comment]
it does have the inconvenient of being heavy to process on v8 with a 100+ file torrent on a slow CPU like an Atom Z

**Comment by feross** [comment]
@vankasteelj Looping through an array one time is not a heavyweight operation. Anyway, what your suggesting would have to be done internally in webtorrent either way, so it makes no performance difference:

```js
var files = torrent.files.filter(function (file) {
  var ext = path.extname(file)
  return ext === '.mp4'
})
console.log(files) // now this array only contains mp4 files
```

**Comment by vankasteelj** [comment]
it's not the looping array that is heavy, it's the 99 occurrences of `file.deselect()` on a 100-file torrent. Because part of the point of streaming a torrent is not to download it entirely if it's, for example, the complete CCC collection in 1 torrent.

**Comment by vankasteelj** [comment]
torrent.deselect() could be a useful api (if you're not internally looping and deselecting each file^^)

**Comment by feross** [comment]
Yeah, there is already an open issue about improving the way we do selections. For now, we only have file.deselect(). You can follow that issue here: #164
