### ISSUE TITLE
not entering client.add() 

### ISSUE THREAD

**Issue by c00kie17** [feross/webtorrent#980]
here is my code:
   ```
 function thefuncntion(file)
          var client = new WebTorrent();
          client.add(file,function(torrent){
              //not entering
           });	
       	   client.on('torrent',function(torrent){
             //not entering
          });	
           var val = client.get(file); //val holds the value of my torrent
           client.on('error', function (err) {
              // entering
            });
 }
```

I didnt know where else to ask this question. Is there anything I am doing wrong ?

**Comment by feross** [comment]
This can happen if the magnet link you pass in has no peers and even the metadata can't be fetched. You should set a timeout to detect when this happens, or just show some torrent stats like number of peers, download speed, etc. to the user.

Also, see this FAQ answer: Why does browser downloading not work? I see no peers!

It does work! But you can't just use any random magnet uri or .torrent file. The torrent must be seeded by a WebRTC-capable client, i.e. WebTorrent Desktop, Vuze, webtorrent-hybrid, Playback, instant.io, or βTorrent.

In the browser, WebTorrent can only download torrents that are explicitly seeded to web peers via a WebRTC-capable client. Desktop torrent clients need to support WebRTC to connect to web browsers.

**Comment by c00kie17** [comment]
Hi ,Thanks for the answer. I am using a .torrent or a magnet link which has more than 50 peers and seeders for my testing. It works perfectly fine if I run webtorrent on a nodejs server, but I encounter this error running it on browser javascript.

**Comment by DiegoRBaquero** [comment]
@c00kie17 in Node, WebTorrent connects to TCP/UDP peers. On the browser it can't, it can only connect to WebRTC peers, I suppose your torrent doesn't have any.

webtorrent-hybrid and WebTorrent Desktop can connect to both type of peers.

**Comment by c00kie17** [comment]
Thanks for the reply, I got what you are trying to say. My mistake should have researched more before asking a question here. Thank you.
