### ISSUE TITLE
FAQ - Where is the source file for https://webtorrent.io/ ?

### ISSUE THREAD

**Issue by brianzelip** [feross/webtorrent#981]
This is a suggestion to add the following question (and answer!) to `/docs/faq.md`:

Where is the source file for the WebTorrent homepage?

**Comment by feross** [comment]
The source is here: https://github.com/feross/webtorrent-www

I appreciate the issue, but I don't think that's a very generally useful FAQ question for people. A small link in the footer would be fine, though.

**Comment by brianzelip** [comment]
Thanks!
