### ISSUE TITLE
Works beautifully with the latest Android phones .. but Apple?

### ISSUE THREAD

**Issue by kopy-kate** [feross/webtorrent#982]
This is obviously not a priority, but I was wondering if anyone's tried streaming a video on http://instant.io using a smartphone.

I've tested it on both a Samsung Galaxy S5 (or S4? can't remember exactly..) as well as an iPhone 6 Plus.

I used Google chrome on both devices. Samsung Galaxy was streaming and seeding it beautifully. iPhone 6 managed to download and seed the torrent, but video play back would simply not initiate. It showed a black screen with a play (>) symbol, but that's about it. Nothing happens when you click on it.

I was wondering whether this is a problem with HTML5 video in general on the iPhones. I tried all browsers I could, firefox, chrome, safari .. but none of them worked on iPhone.

* WebTorrent version:
Instant.io

* Browser name/version (if using WebTorrent in the browser):
Google Chrome

**Comment by jerwarren** [comment]
Safari on iOS doesn't support WebRTC.

It is possible to build a Cordova app that will run on iOS with WebRTC support, so you can still support iOS users, they'll just have to install an app first.

**Comment by feross** [comment]
@jerwarren It sounds like he was using a torrent with an http web seed, which is why he saw download speed on Safari.

@kopy-kate The video playback not working in Safari is an issue with the `videostream` library we depend on. There's an issue about it here: https://github.com/jhiesey/videostream/issues/24
