### ISSUE TITLE
TypeError when seeding Caminandes 2 video on Instant.io

### ISSUE THREAD

**Issue by Chocobozzz** [feross/webtorrent#984]
Hi,

When I want to seed Caminandes 2: Gran Dillama (http://www.caminandes.com/) on Instant.io I have an error and the video never plays on the video html tag:

    bundle.js:2838 Uncaught TypeError: "list" argument must be an Array of Buffers(…)

Steps to reproduce:
  - Download the ZIP video: http://www.caminandes.com/download/02_gran_dillama_1080p.zip
  - Unzip it to get the MP4 video
  - Seed it on Instant.io and open the console to see the TypeError

Media info output: http://pastebin.com/r4MCrsxW

Thanks

**Comment by DiegoRBaquero** [comment]
Could you share the bundle.js part around line 2838?

**Comment by Chocobozzz** [comment]
Sure.

Here the stacktrace: http://pastebin.com/HwF9pzyt

JS bundle part arount line 2838: 

    Buffer.concat = function concat (list, length) {
      if (!isArray(list)) {
        /* line 2838 -> */ throw new TypeError('"list" argument must be an Array of Buffers')
      }

      if (list.length === 0) {
        return Buffer.alloc(0)
      }

      var i
      if (length === undefined) {
        length = 0
        for (i = 0; i < list.length; ++i) {
          length += list[i].length
        }
      }

      var buffer = Buffer.allocUnsafe(length)
      var pos = 0
      for (i = 0; i < list.length; ++i) {
        var buf = list[i]
        if (!Buffer.isBuffer(buf)) {
          throw new TypeError('"list" argument must be an Array of Buffers')
        }
        buf.copy(buffer, pos)
        pos += buf.length
      }
      return buffer
    }

The instant.io js complete bundle: [bundle.txt](https://github.com/feross/webtorrent/files/606960/bundle.txt)

**Comment by feross** [comment]
I figured out the source of the bug. It originates many dependencies deep:

render-media > videostream > mp4-stream

PR to fix it: https://github.com/mafintosh/mp4-stream/pull/15

**Comment by feross** [comment]
WOW, the PR literally got merged and released to npm before I left this comment. Nice, @mafintosh

**Comment by Chocobozzz** [comment]
You're awesome guys, big thanks to all of you  :tada:
