### ISSUE TITLE
Epipe error after seeding the 2 torrent to webtorrent

### ISSUE THREAD

**Issue by Rakesh-phpdeveloper** [feross/webtorrent#985]
* WebTorrent-hybrid version: 1.6.0 (0.97.2)
* Node.js version: v4.6.0
* npm o2.15.9
* express js 4.14.0

I'm trying to add the magnet link to the client.add() to download and seed the torrent
my code 
```js
router.post('/magnet_uri', function(req, res, next) { 
    // magnet link
    var torrentId = req.body.magnet_url;
    client.on('error', function (err) {
        console.log("Client Error : ", err);  // Invalid torrent identifier
    });
    //  adding the magnet link to the client 
    client.add(torrentId,{ path: './seed_torrent/' }, function (torrent) { 
       console.log('torrent start seeding');
        // About torrent info
        var info_torrent = {
           // MagnetURI: torrent.magnetURI,
            TorrentHashInfo: torrent.infoHash,
            TorrentName: torrent.name,
            TorrentPeer: torrent.numPeers,
            TorrentPath: torrent.path
        }
        console.log(info_torrent);
        torrent.on('ready', function() {
            console.log("Torrent is ready to download"+'ready');
        });
        // display the warning details if warning occurs
        torrent.on('warning', function (err) {
            console.log("Torrent Warning : ", err);
        })
  	// on torrent error for display the error message
  	torrent.on('error', function (err) {
            console.log("Torrent Error : ", err);
  			// console.log("error occured, Torrent can't downloaded");
  	})
        // if peer is not found
        // announceType is either 'tracker' or 'dht'
        torrent.on('noPeers', function (announceType) {
            console.log("Torrent NoPeers : ", announceType);
        })
              // if torrent is finished download
  		torrent.on('done', function () {
     		console.log('torrent download finished');
    	})
   })
```

i run the app in command line
i used command
<pre>
DEBUG=alpha-webtorrent:* npm start
</pre>
Where alpha-webtorrent is a expressjs app  folder

I'm sending the magnet link to the nodejs server, so that it add the torrent link and start downloading the file.
while i sent the multiple file to the magnet link simultaneously or one after the another 
first torrent file downloaded successfully and start seeding 
while the second torrent  downloaded successfully after that 
i always face an issue :" 
<pre>
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:907:11)
    at WriteWrap.afterWrite (net.js:785:14)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! alpha-webtorrent@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alpha-webtorrent@0.0.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the alpha-webtorrent package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs alpha-webtorrent
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls alpha-webtorrent
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/alpha-webtorrent/npm-debug.log

</pre> 

I coudn't find the solution for this.
Please help @feross

**Comment by Rakesh-phpdeveloper** [comment]
Is this difficult to answer.................... @feross

**Comment by feross** [comment]
Your `webtorrent-hybrid` version can't be 1.6.0. The latest version is 1.0.5. I would check to ensure that you're actually using the latest version.

**Comment by Rakesh-phpdeveloper** [comment]
webtorrent-hybrid version can't be 1.6.0.  I agree, I solved my issue.
