### ISSUE TITLE
how do you get tcp conn for webRTC

### ISSUE THREAD

**Issue by mjena** [feross/webtorrent#988]
Hi, this is not a bug report but just for my knowledge sack. :)
May I know how do you get the tcp conn object from webRTC for a peer connection?

I saw you are not using datachannel but getting the conn object from webRTC.
Is it through RTCPeerConnection.getStats() or something else?

Thanks in advance! ;)

**Comment by feross** [comment]
There is no way to get the underlying TCP connection for an RTCPeerConnection.
