### ISSUE TITLE
Cannot seed torrent from Desktop to Web Browser (on mobile device and using different network)

### ISSUE THREAD

**Issue by EdwinLuKiet** [feross/webtorrent#990]
I've tried to follow the example given but cannot seed the video from Desktop  to the Chrome Browser on mobile device (using different network). However, instant.io has no problem doing such. Have seen some one mentioned the issue before few days ago and now it has been put down for some reason ? My code is simple as just as such : 

```
var torrentId = 'magnet:?xt=urn:btih:751546eb8e02ff7ea28e8679dee8d1372beb4c77&dn=Test20.mp4&tr=udp%3A%2F%2Fexodus.desync.com%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com'
client.add(torrentId, onTorrent);
function onTorrent (torrent) {
    torrent.files.forEach(function (file) {
        file.appendTo('.log');
    })
}
```

**Comment by DiegoRBaquero** [comment]
If it works on instant.io maybe it's the STUN+TURN config.

**Comment by EdwinLuKiet** [comment]
Yes can it be solved effectively? Instant.io sends its own rtcconfig but it looks quite troublesome.

**Comment by feross** [comment]
If your network has a firewall or you're behind a restrictive NAT then some P2P connections will fail. Setting up a TURN server, or paying a service like Twilio (https://www.twilio.com/stun-turn) is the only way to ensure connectivity in these situations.

For torrents with a lot of peers, even peers who are behind bad firewalls can usually connect to at least a few peers. But if you want to guarantee that one specific peer can always connect to any other specific peer, then you need TURN.

**Comment by EdwinLuKiet** [comment]
thanks for the useful information. However, its noted that normal utorrent has no such issue? Is there any any chance that we can bypass such issue, that would be very good way to look forward to?

**Comment by feross** [comment]
uTorrent uses different techniques than WebRTC to bypass firewalls, namely UPnP and NAT-PMP. With WebRTC we're limited to STUN and TURN. This is what browsers give us.
