### ISSUE TITLE
[CloudFlare]Uncaught ReferenceError: torrentId is not defined

### ISSUE THREAD

**Issue by ziomik** [feross/webtorrent#993]
Sorry for my english...

Code is ok and work to http://plnkr.co
but in my vps browser error: **video.html:26 Uncaught ReferenceError: torrentId is not defined(…)**

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
    </head>
<body>
<script src="https://cdn.jsdelivr.net/webtorrent/latest/webtorrent.min.js"></script>
<script>
var client = new WebTorrent()

// Sintel, a free, Creative Commons movie
var torrentId = 'magnet:?xt=urn:btih:467c457b1ccc8a163c0597953a38a61ee102a219&dn=stri.mp4&tr=udp%3A%2F%2Fexodus.desync.com%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com'

client.add(torrentId, function (torrent) {
  // Torrents can contain many files. Let's use the first.
  var file = torrent.files[0]

  // Display the file by adding it to the DOM.
  // Supports video, audio, image files, and more!
  file.appendTo('body')
})


</script>
</body>
</html>
```

**Comment by ziomik** [comment]
found the problem: **CloudFlare**.
The cache causes problems.

**Comment by ziomik** [comment]
tips to bypass cloudflare?
I tried various rules on "Page Rule" without positive results.

**Comment by feross** [comment]
You can learn about purging your cache here: https://support.cloudflare.com/hc/en-us/articles/200169246-How-do-I-purge-my-cache-

**Comment by ziomik** [comment]
No works..
Html page with CLOUDFLARE(cache purge and cache disable): http://www.ziomik.net/video/video.html
Html page not CLOUDFLARE: http://www.pginternationale.com/video.html

**Comment by feross** [comment]
I would contact cloudflare support and ask for help. This is not a webtorrent issue.
